In [29]:
SA01_A_paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        SA01_A_paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                SA01_A_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            SA01_A_paths.append(tmp)

SA01_A_paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                      '../Dataset/SA01/D05_SA01_R01_2.csv',
                      '../Dataset/SA01/D05_SA01_R02_1.csv',
                      '../Dataset/SA01/D05_SA01_R02_2.csv',
                      '../Dataset/SA01/D05_SA01_R03_1.csv',
                      '../Dataset/SA01/D05_SA01_R03_2.csv',
                      '../Dataset/SA01/D05_SA01_R04_1.csv',
                      '../Dataset/SA01/D05_SA01_R04_2.csv',
                      '../Dataset/SA01/D05_SA01_R05_1.csv',
                      '../Dataset/SA01/D05_SA01_R05_2.csv',
                      '../Dataset/SA01/D06_SA01_R01_1.csv',
                      '../Dataset/SA01/D06_SA01_R01_2.csv',
                      '../Dataset/SA01/D06_SA01_R02_1.csv',
                      '../Dataset/SA01/D06_SA01_R02_2.csv',
                      '../Dataset/SA01/D06_SA01_R03_1.csv',
                      '../Dataset/SA01/D06_SA01_R03_2.csv',
                      '../Dataset/SA01/D06_SA01_R04_1.csv',
                      '../Dataset/SA01/D06_SA01_R04_2.csv',
                      '../Dataset/SA01/D06_SA01_R05_1.csv',
                      '../Dataset/SA01/D06_SA01_R05_2.csv']

SA01_A_paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                         '../Dataset/SA01/D17_SA01_R01_2.csv',
                         '../Dataset/SA01/D17_SA01_R02_1.csv',
                         '../Dataset/SA01/D17_SA01_R02_2.csv',
                         '../Dataset/SA01/D17_SA01_R03_1.csv',
                         '../Dataset/SA01/D17_SA01_R03_2.csv',
                         '../Dataset/SA01/D17_SA01_R04_1.csv',
                         '../Dataset/SA01/D17_SA01_R04_2.csv',
                         '../Dataset/SA01/D17_SA01_R05_1.csv',
                         '../Dataset/SA01/D17_SA01_R05_2.csv']

path_list = []

for path in SA01_A_paths:
    path = path.replace('SA01', 'SA01')
    path_list.append(path)

path_list

['../Dataset/SA01/D01_SA01_R01.csv',
 '../Dataset/SA01/D02_SA01_R01.csv',
 '../Dataset/SA01/D03_SA01_R01.csv',
 '../Dataset/SA01/D04_SA01_R01.csv',
 '../Dataset/SA01/D05_SA01_R01_1.csv',
 '../Dataset/SA01/D05_SA01_R01_2.csv',
 '../Dataset/SA01/D05_SA01_R02_1.csv',
 '../Dataset/SA01/D05_SA01_R02_2.csv',
 '../Dataset/SA01/D05_SA01_R03_1.csv',
 '../Dataset/SA01/D05_SA01_R03_2.csv',
 '../Dataset/SA01/D05_SA01_R04_1.csv',
 '../Dataset/SA01/D05_SA01_R04_2.csv',
 '../Dataset/SA01/D05_SA01_R05_1.csv',
 '../Dataset/SA01/D05_SA01_R05_2.csv',
 '../Dataset/SA01/D06_SA01_R01_1.csv',
 '../Dataset/SA01/D06_SA01_R01_2.csv',
 '../Dataset/SA01/D06_SA01_R02_1.csv',
 '../Dataset/SA01/D06_SA01_R02_2.csv',
 '../Dataset/SA01/D06_SA01_R03_1.csv',
 '../Dataset/SA01/D06_SA01_R03_2.csv',
 '../Dataset/SA01/D06_SA01_R04_1.csv',
 '../Dataset/SA01/D06_SA01_R04_2.csv',
 '../Dataset/SA01/D06_SA01_R05_1.csv',
 '../Dataset/SA01/D06_SA01_R05_2.csv',
 '../Dataset/SA01/D07_SA01_R01.csv',
 '../Dataset/SA01/D07_SA01_R02.csv',
 '../Dataset/SA01/D07_SA01_R03.csv',
 '../Dataset/SA01/D07_SA01_R04.csv',
 '../Dataset/SA01/D07_SA01_R05.csv',
 '../Dataset/SA01/D08_SA01_R01.csv',
 '../Dataset/SA01/D08_SA01_R02.csv',
 '../Dataset/SA01/D08_SA01_R03.csv',
 '../Dataset/SA01/D08_SA01_R04.csv',
 '../Dataset/SA01/D08_SA01_R05.csv',
 '../Dataset/SA01/D09_SA01_R01.csv',
 '../Dataset/SA01/D09_SA01_R02.csv',
 '../Dataset/SA01/D09_SA01_R03.csv',
 '../Dataset/SA01/D09_SA01_R04.csv',
 '../Dataset/SA01/D09_SA01_R05.csv',
 '../Dataset/SA01/D10_SA01_R01.csv',
 '../Dataset/SA01/D10_SA01_R02.csv',
 '../Dataset/SA01/D10_SA01_R03.csv',
 '../Dataset/SA01/D10_SA01_R04.csv',
 '../Dataset/SA01/D10_SA01_R05.csv',
 '../Dataset/SA01/D11_SA01_R01.csv',
 '../Dataset/SA01/D11_SA01_R02.csv',
 '../Dataset/SA01/D11_SA01_R03.csv',
 '../Dataset/SA01/D11_SA01_R04.csv',
 '../Dataset/SA01/D11_SA01_R05.csv',
 '../Dataset/SA01/D12_SA01_R01.csv',
 '../Dataset/SA01/D12_SA01_R02.csv',
 '../Dataset/SA01/D12_SA01_R03.csv',
 '../Dataset/SA01/D12_SA01_R04.csv',
 '../Dataset/SA01/D12_SA01_R05.csv',
 '../Dataset/SA01/D13_SA01_R01.csv',
 '../Dataset/SA01/D13_SA01_R02.csv',
 '../Dataset/SA01/D13_SA01_R03.csv',
 '../Dataset/SA01/D13_SA01_R04.csv',
 '../Dataset/SA01/D13_SA01_R05.csv',
 '../Dataset/SA01/D14_SA01_R01.csv',
 '../Dataset/SA01/D14_SA01_R02.csv',
 '../Dataset/SA01/D14_SA01_R03.csv',
 '../Dataset/SA01/D14_SA01_R04.csv',
 '../Dataset/SA01/D14_SA01_R05.csv',
 '../Dataset/SA01/D15_SA01_R01.csv',
 '../Dataset/SA01/D15_SA01_R02.csv',
 '../Dataset/SA01/D15_SA01_R03.csv',
 '../Dataset/SA01/D15_SA01_R04.csv',
 '../Dataset/SA01/D15_SA01_R05.csv',
 '../Dataset/SA01/D16_SA01_R01.csv',
 '../Dataset/SA01/D16_SA01_R02.csv',
 '../Dataset/SA01/D16_SA01_R03.csv',
 '../Dataset/SA01/D16_SA01_R04.csv',
 '../Dataset/SA01/D16_SA01_R05.csv',
 '../Dataset/SA01/D17_SA01_R01_1.csv',
 '../Dataset/SA01/D17_SA01_R01_2.csv',
 '../Dataset/SA01/D17_SA01_R02_1.csv',
 '../Dataset/SA01/D17_SA01_R02_2.csv',
 '../Dataset/SA01/D17_SA01_R03_1.csv',
 '../Dataset/SA01/D17_SA01_R03_2.csv',
 '../Dataset/SA01/D17_SA01_R04_1.csv',
 '../Dataset/SA01/D17_SA01_R04_2.csv',
 '../Dataset/SA01/D17_SA01_R05_1.csv',
 '../Dataset/SA01/D17_SA01_R05_2.csv',
 '../Dataset/SA01/D18_SA01_R01.csv',
 '../Dataset/SA01/D18_SA01_R02.csv',
 '../Dataset/SA01/D18_SA01_R03.csv',
 '../Dataset/SA01/D18_SA01_R04.csv',
 '../Dataset/SA01/D18_SA01_R05.csv',
 '../Dataset/SA01/D19_SA01_R01.csv',
 '../Dataset/SA01/D19_SA01_R02.csv',
 '../Dataset/SA01/D19_SA01_R03.csv',
 '../Dataset/SA01/D19_SA01_R04.csv',
 '../Dataset/SA01/D19_SA01_R05.csv']

In [39]:
import pandas as pd
import numpy as np
import os

# SA01

In [40]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA01_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA01')
    SA01_A_paths.append(path)

SA01_A_paths

['../Dataset/SA01/D01_SA01_R01.csv',
 '../Dataset/SA01/D02_SA01_R01.csv',
 '../Dataset/SA01/D03_SA01_R01.csv',
 '../Dataset/SA01/D04_SA01_R01.csv',
 '../Dataset/SA01/D05_SA01_R01_1.csv',
 '../Dataset/SA01/D05_SA01_R01_2.csv',
 '../Dataset/SA01/D05_SA01_R02_1.csv',
 '../Dataset/SA01/D05_SA01_R02_2.csv',
 '../Dataset/SA01/D05_SA01_R03_1.csv',
 '../Dataset/SA01/D05_SA01_R03_2.csv',
 '../Dataset/SA01/D05_SA01_R04_1.csv',
 '../Dataset/SA01/D05_SA01_R04_2.csv',
 '../Dataset/SA01/D05_SA01_R05_1.csv',
 '../Dataset/SA01/D05_SA01_R05_2.csv',
 '../Dataset/SA01/D06_SA01_R01_1.csv',
 '../Dataset/SA01/D06_SA01_R01_2.csv',
 '../Dataset/SA01/D06_SA01_R02_1.csv',
 '../Dataset/SA01/D06_SA01_R02_2.csv',
 '../Dataset/SA01/D06_SA01_R03_1.csv',
 '../Dataset/SA01/D06_SA01_R03_2.csv',
 '../Dataset/SA01/D06_SA01_R04_1.csv',
 '../Dataset/SA01/D06_SA01_R04_2.csv',
 '../Dataset/SA01/D06_SA01_R05_1.csv',
 '../Dataset/SA01/D06_SA01_R05_2.csv',
 '../Dataset/SA01/D07_SA01_R01.csv',
 '../Dataset/SA01/D07_SA01_R02.csv',
 '../Dataset/SA01/D07_SA01_R03.csv',
 '../Dataset/SA01/D07_SA01_R04.csv',
 '../Dataset/SA01/D07_SA01_R05.csv',
 '../Dataset/SA01/D08_SA01_R01.csv',
 '../Dataset/SA01/D08_SA01_R02.csv',
 '../Dataset/SA01/D08_SA01_R03.csv',
 '../Dataset/SA01/D08_SA01_R04.csv',
 '../Dataset/SA01/D08_SA01_R05.csv',
 '../Dataset/SA01/D09_SA01_R01.csv',
 '../Dataset/SA01/D09_SA01_R02.csv',
 '../Dataset/SA01/D09_SA01_R03.csv',
 '../Dataset/SA01/D09_SA01_R04.csv',
 '../Dataset/SA01/D09_SA01_R05.csv',
 '../Dataset/SA01/D10_SA01_R01.csv',
 '../Dataset/SA01/D10_SA01_R02.csv',
 '../Dataset/SA01/D10_SA01_R03.csv',
 '../Dataset/SA01/D10_SA01_R04.csv',
 '../Dataset/SA01/D10_SA01_R05.csv',
 '../Dataset/SA01/D11_SA01_R01.csv',
 '../Dataset/SA01/D11_SA01_R02.csv',
 '../Dataset/SA01/D11_SA01_R03.csv',
 '../Dataset/SA01/D11_SA01_R04.csv',
 '../Dataset/SA01/D11_SA01_R05.csv',
 '../Dataset/SA01/D12_SA01_R01.csv',
 '../Dataset/SA01/D12_SA01_R02.csv',
 '../Dataset/SA01/D12_SA01_R03.csv',
 '../Dataset/SA01/D12_SA01_R04.csv',
 '../Dataset/SA01/D12_SA01_R05.csv',
 '../Dataset/SA01/D13_SA01_R01.csv',
 '../Dataset/SA01/D13_SA01_R02.csv',
 '../Dataset/SA01/D13_SA01_R03.csv',
 '../Dataset/SA01/D13_SA01_R04.csv',
 '../Dataset/SA01/D13_SA01_R05.csv',
 '../Dataset/SA01/D14_SA01_R01.csv',
 '../Dataset/SA01/D14_SA01_R02.csv',
 '../Dataset/SA01/D14_SA01_R03.csv',
 '../Dataset/SA01/D14_SA01_R04.csv',
 '../Dataset/SA01/D14_SA01_R05.csv',
 '../Dataset/SA01/D15_SA01_R01.csv',
 '../Dataset/SA01/D15_SA01_R02.csv',
 '../Dataset/SA01/D15_SA01_R03.csv',
 '../Dataset/SA01/D15_SA01_R04.csv',
 '../Dataset/SA01/D15_SA01_R05.csv',
 '../Dataset/SA01/D16_SA01_R01.csv',
 '../Dataset/SA01/D16_SA01_R02.csv',
 '../Dataset/SA01/D16_SA01_R03.csv',
 '../Dataset/SA01/D16_SA01_R04.csv',
 '../Dataset/SA01/D16_SA01_R05.csv',
 '../Dataset/SA01/D17_SA01_R01_1.csv',
 '../Dataset/SA01/D17_SA01_R01_2.csv',
 '../Dataset/SA01/D17_SA01_R02_1.csv',
 '../Dataset/SA01/D17_SA01_R02_2.csv',
 '../Dataset/SA01/D17_SA01_R03_1.csv',
 '../Dataset/SA01/D17_SA01_R03_2.csv',
 '../Dataset/SA01/D17_SA01_R04_1.csv',
 '../Dataset/SA01/D17_SA01_R04_2.csv',
 '../Dataset/SA01/D17_SA01_R05_1.csv',
 '../Dataset/SA01/D17_SA01_R05_2.csv',
 '../Dataset/SA01/D18_SA01_R01.csv',
 '../Dataset/SA01/D18_SA01_R02.csv',
 '../Dataset/SA01/D18_SA01_R03.csv',
 '../Dataset/SA01/D18_SA01_R04.csv',
 '../Dataset/SA01/D18_SA01_R05.csv',
 '../Dataset/SA01/D19_SA01_R01.csv',
 '../Dataset/SA01/D19_SA01_R02.csv',
 '../Dataset/SA01/D19_SA01_R03.csv',
 '../Dataset/SA01/D19_SA01_R04.csv',
 '../Dataset/SA01/D19_SA01_R05.csv']

In [41]:
list = []
final_SA01_A = pd.DataFrame(list)

for path in SA01_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA01_A = final_SA01_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA01_A.shape
target_col = row * [1]
final_SA01_A.loc[:,'target'] = target_col

final_SA01_A

FileNotFoundError: [Errno 2] No such file or directory: '../Dataset/SA01/D05_SA01_R01_1.csv'

# SA02

In [5]:
SA02_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA02/F01_SA02_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA02_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA02_F_paths.append(tmp)
            
print(SA02_F_paths)

['../Dataset/SA02/F01_SA02_R01.csv', '../Dataset/SA02/F01_SA02_R02.csv', '../Dataset/SA02/F01_SA02_R03.csv', '../Dataset/SA02/F01_SA02_R04.csv', '../Dataset/SA02/F01_SA02_R05.csv', '../Dataset/SA02/F02_SA02_R01.csv', '../Dataset/SA02/F02_SA02_R02.csv', '../Dataset/SA02/F02_SA02_R03.csv', '../Dataset/SA02/F02_SA02_R04.csv', '../Dataset/SA02/F02_SA02_R05.csv', '../Dataset/SA02/F03_SA02_R01.csv', '../Dataset/SA02/F03_SA02_R02.csv', '../Dataset/SA02/F03_SA02_R03.csv', '../Dataset/SA02/F03_SA02_R04.csv', '../Dataset/SA02/F03_SA02_R05.csv', '../Dataset/SA02/F04_SA02_R01.csv', '../Dataset/SA02/F04_SA02_R02.csv', '../Dataset/SA02/F04_SA02_R03.csv', '../Dataset/SA02/F04_SA02_R04.csv', '../Dataset/SA02/F04_SA02_R05.csv', '../Dataset/SA02/F05_SA02_R01.csv', '../Dataset/SA02/F05_SA02_R02.csv', '../Dataset/SA02/F05_SA02_R03.csv', '../Dataset/SA02/F05_SA02_R04.csv', '../Dataset/SA02/F05_SA02_R05.csv', '../Dataset/SA02/F06_SA02_R01.csv', '../Dataset/SA02/F06_SA02_R02.csv', '../Dataset/SA02/F06_SA02_R03.csv', '../Dataset/SA02/F06_SA02_R04.csv', '../Dataset/SA02/F06_SA02_R05.csv', '../Dataset/SA02/F07_SA02_R01.csv', '../Dataset/SA02/F07_SA02_R02.csv', '../Dataset/SA02/F07_SA02_R03.csv', '../Dataset/SA02/F07_SA02_R04.csv', '../Dataset/SA02/F07_SA02_R05.csv', '../Dataset/SA02/F08_SA02_R01.csv', '../Dataset/SA02/F08_SA02_R02.csv', '../Dataset/SA02/F08_SA02_R03.csv', '../Dataset/SA02/F08_SA02_R04.csv', '../Dataset/SA02/F08_SA02_R05.csv', '../Dataset/SA02/F09_SA02_R01.csv', '../Dataset/SA02/F09_SA02_R02.csv', '../Dataset/SA02/F09_SA02_R03.csv', '../Dataset/SA02/F09_SA02_R04.csv', '../Dataset/SA02/F09_SA02_R05.csv', '../Dataset/SA02/F10_SA02_R01.csv', '../Dataset/SA02/F10_SA02_R02.csv', '../Dataset/SA02/F10_SA02_R03.csv', '../Dataset/SA02/F10_SA02_R04.csv', '../Dataset/SA02/F10_SA02_R05.csv', '../Dataset/SA02/F11_SA02_R01.csv', '../Dataset/SA02/F11_SA02_R02.csv', '../Dataset/SA02/F11_SA02_R03.csv', '../Dataset/SA02/F11_SA02_R04.csv', '../Dataset/SA02/F11_SA02_R05.csv', '../Dataset/SA02/F12_SA02_R01.csv', '../Dataset/SA02/F12_SA02_R02.csv', '../Dataset/SA02/F12_SA02_R03.csv', '../Dataset/SA02/F12_SA02_R04.csv', '../Dataset/SA02/F12_SA02_R05.csv', '../Dataset/SA02/F13_SA02_R01.csv', '../Dataset/SA02/F13_SA02_R02.csv', '../Dataset/SA02/F13_SA02_R03.csv', '../Dataset/SA02/F13_SA02_R04.csv', '../Dataset/SA02/F13_SA02_R05.csv', '../Dataset/SA02/F14_SA02_R01.csv', '../Dataset/SA02/F14_SA02_R02.csv', '../Dataset/SA02/F14_SA02_R03.csv', '../Dataset/SA02/F14_SA02_R04.csv', '../Dataset/SA02/F14_SA02_R05.csv', '../Dataset/SA02/F15_SA02_R01.csv', '../Dataset/SA02/F15_SA02_R02.csv', '../Dataset/SA02/F15_SA02_R03.csv', '../Dataset/SA02/F15_SA02_R04.csv', '../Dataset/SA02/F15_SA02_R05.csv']

In [6]:
list = []
final_SA02_F = pd.DataFrame(list)

for path in SA02_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA02_F = final_SA02_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA02_F.shape
target_col = row * [1]
final_SA02_F.loc[:,'target'] = target_col

final_SA02_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,219.0,224.0,232.0,240.0,242.0,244.0,251.0,255.0,253.0,254.0,...,173.0,179.0,186.0,186.0,198.0,194.0,200.0,209.0,198.0,1
0,177.0,180.0,182.0,189.0,201.0,217.0,237.0,252.0,260.0,270.0,...,446.0,418.0,364.0,305.0,267.0,252.0,235.0,235.0,239.0,1
0,270.0,276.0,282.0,292.0,297.0,305.0,309.0,308.0,314.0,310.0,...,235.0,205.0,187.0,188.0,196.0,200.0,167.0,112.0,101.0,1
0,214.0,215.0,214.0,213.0,208.0,208.0,207.0,213.0,215.0,218.0,...,106.0,110.0,124.0,137.0,139.0,131.0,121.0,118.0,132.0,1
0,244.0,236.0,222.0,210.0,206.0,203.0,203.0,212.0,212.0,220.0,...,256.0,263.0,254.0,243.0,227.0,191.0,142.0,100.0,74.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,250.0,247.0,247.0,246.0,248.0,246.0,245.0,248.0,246.0,250.0,...,246.0,245.0,245.0,244.0,247.0,248.0,241.0,250.0,246.0,1
0,248.0,250.0,251.0,252.0,251.0,250.0,248.0,251.0,252.0,253.0,...,215.0,216.0,223.0,227.0,230.0,231.0,225.0,220.0,203.0,1
0,268.0,267.0,262.0,261.0,252.0,253.0,248.0,258.0,254.0,261.0,...,173.0,185.0,176.0,145.0,168.0,163.0,159.0,155.0,149.0,1
0,245.0,248.0,246.0,246.0,246.0,247.0,248.0,245.0,249.0,246.0,...,209.0,230.0,241.0,239.0,215.0,200.0,210.0,207.0,175.0,1
0,252.0,247.0,242.0,246.0,244.0,244.0,243.0,242.0,238.0,238.0,...,200.0,189.0,169.0,152.0,146.0,158.0,126.0,97.0,127.0,1

# SA03

In [7]:
SA03_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA03/F01_SA03_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA03_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA03_F_paths.append(tmp)
            
print(SA03_F_paths)

['../Dataset/SA03/F01_SA03_R01.csv', '../Dataset/SA03/F01_SA03_R02.csv', '../Dataset/SA03/F01_SA03_R03.csv', '../Dataset/SA03/F01_SA03_R04.csv', '../Dataset/SA03/F01_SA03_R05.csv', '../Dataset/SA03/F02_SA03_R01.csv', '../Dataset/SA03/F02_SA03_R02.csv', '../Dataset/SA03/F02_SA03_R03.csv', '../Dataset/SA03/F02_SA03_R04.csv', '../Dataset/SA03/F02_SA03_R05.csv', '../Dataset/SA03/F03_SA03_R01.csv', '../Dataset/SA03/F03_SA03_R02.csv', '../Dataset/SA03/F03_SA03_R03.csv', '../Dataset/SA03/F03_SA03_R04.csv', '../Dataset/SA03/F03_SA03_R05.csv', '../Dataset/SA03/F04_SA03_R01.csv', '../Dataset/SA03/F04_SA03_R02.csv', '../Dataset/SA03/F04_SA03_R03.csv', '../Dataset/SA03/F04_SA03_R04.csv', '../Dataset/SA03/F04_SA03_R05.csv', '../Dataset/SA03/F05_SA03_R01.csv', '../Dataset/SA03/F05_SA03_R02.csv', '../Dataset/SA03/F05_SA03_R03.csv', '../Dataset/SA03/F05_SA03_R04.csv', '../Dataset/SA03/F05_SA03_R05.csv', '../Dataset/SA03/F06_SA03_R01.csv', '../Dataset/SA03/F06_SA03_R02.csv', '../Dataset/SA03/F06_SA03_R03.csv', '../Dataset/SA03/F06_SA03_R04.csv', '../Dataset/SA03/F06_SA03_R05.csv', '../Dataset/SA03/F07_SA03_R01.csv', '../Dataset/SA03/F07_SA03_R02.csv', '../Dataset/SA03/F07_SA03_R03.csv', '../Dataset/SA03/F07_SA03_R04.csv', '../Dataset/SA03/F07_SA03_R05.csv', '../Dataset/SA03/F08_SA03_R01.csv', '../Dataset/SA03/F08_SA03_R02.csv', '../Dataset/SA03/F08_SA03_R03.csv', '../Dataset/SA03/F08_SA03_R04.csv', '../Dataset/SA03/F08_SA03_R05.csv', '../Dataset/SA03/F09_SA03_R01.csv', '../Dataset/SA03/F09_SA03_R02.csv', '../Dataset/SA03/F09_SA03_R03.csv', '../Dataset/SA03/F09_SA03_R04.csv', '../Dataset/SA03/F09_SA03_R05.csv', '../Dataset/SA03/F10_SA03_R01.csv', '../Dataset/SA03/F10_SA03_R02.csv', '../Dataset/SA03/F10_SA03_R03.csv', '../Dataset/SA03/F10_SA03_R04.csv', '../Dataset/SA03/F10_SA03_R05.csv', '../Dataset/SA03/F11_SA03_R01.csv', '../Dataset/SA03/F11_SA03_R02.csv', '../Dataset/SA03/F11_SA03_R03.csv', '../Dataset/SA03/F11_SA03_R04.csv', '../Dataset/SA03/F11_SA03_R05.csv', '../Dataset/SA03/F12_SA03_R01.csv', '../Dataset/SA03/F12_SA03_R02.csv', '../Dataset/SA03/F12_SA03_R03.csv', '../Dataset/SA03/F12_SA03_R04.csv', '../Dataset/SA03/F12_SA03_R05.csv', '../Dataset/SA03/F13_SA03_R01.csv', '../Dataset/SA03/F13_SA03_R02.csv', '../Dataset/SA03/F13_SA03_R03.csv', '../Dataset/SA03/F13_SA03_R04.csv', '../Dataset/SA03/F13_SA03_R05.csv', '../Dataset/SA03/F14_SA03_R01.csv', '../Dataset/SA03/F14_SA03_R02.csv', '../Dataset/SA03/F14_SA03_R03.csv', '../Dataset/SA03/F14_SA03_R04.csv', '../Dataset/SA03/F14_SA03_R05.csv', '../Dataset/SA03/F15_SA03_R01.csv', '../Dataset/SA03/F15_SA03_R02.csv', '../Dataset/SA03/F15_SA03_R03.csv', '../Dataset/SA03/F15_SA03_R04.csv', '../Dataset/SA03/F15_SA03_R05.csv']

In [8]:
list = []
final_SA03_F = pd.DataFrame(list)

for path in SA03_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA03_F = final_SA03_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA03_F.shape
target_col = row * [1]
final_SA03_F.loc[:,'target'] = target_col

final_SA03_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,254.0,257.0,262.0,259.0,265.0,264.0,263.0,265.0,265.0,267.0,...,269.0,283.0,276.0,294.0,280.0,287.0,267.0,270.0,259.0,1
0,301.0,304.0,299.0,296.0,290.0,285.0,278.0,276.0,269.0,266.0,...,243.0,257.0,276.0,294.0,300.0,303.0,314.0,309.0,302.0,1
0,226.0,228.0,231.0,235.0,234.0,239.0,244.0,250.0,254.0,259.0,...,213.0,207.0,210.0,208.0,208.0,197.0,199.0,196.0,199.0,1
0,295.0,285.0,283.0,276.0,268.0,261.0,256.0,253.0,248.0,245.0,...,212.0,177.0,97.0,18.0,95.0,147.0,183.0,228.0,270.0,1
0,226.0,227.0,227.0,231.0,242.0,254.0,253.0,272.0,260.0,262.0,...,252.0,251.0,251.0,250.0,247.0,234.0,222.0,198.0,183.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,234.0,232.0,234.0,234.0,230.0,233.0,233.0,233.0,231.0,233.0,...,233.0,231.0,233.0,230.0,229.0,232.0,233.0,231.0,231.0,1
0,263.0,264.0,265.0,263.0,262.0,268.0,267.0,268.0,272.0,270.0,...,220.0,220.0,224.0,220.0,218.0,218.0,211.0,212.0,205.0,1
0,263.0,266.0,265.0,262.0,267.0,267.0,268.0,274.0,277.0,275.0,...,243.0,239.0,240.0,240.0,239.0,239.0,235.0,235.0,228.0,1
0,265.0,269.0,264.0,268.0,265.0,266.0,270.0,266.0,263.0,265.0,...,198.0,190.0,188.0,190.0,187.0,193.0,192.0,195.0,198.0,1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

# SA04

In [9]:
SA04_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA04/F01_SA04_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA04_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA04_F_paths.append(tmp)
            
print(SA04_F_paths)

['../Dataset/SA04/F01_SA04_R01.csv', '../Dataset/SA04/F01_SA04_R02.csv', '../Dataset/SA04/F01_SA04_R03.csv', '../Dataset/SA04/F01_SA04_R04.csv', '../Dataset/SA04/F01_SA04_R05.csv', '../Dataset/SA04/F02_SA04_R01.csv', '../Dataset/SA04/F02_SA04_R02.csv', '../Dataset/SA04/F02_SA04_R03.csv', '../Dataset/SA04/F02_SA04_R04.csv', '../Dataset/SA04/F02_SA04_R05.csv', '../Dataset/SA04/F03_SA04_R01.csv', '../Dataset/SA04/F03_SA04_R02.csv', '../Dataset/SA04/F03_SA04_R03.csv', '../Dataset/SA04/F03_SA04_R04.csv', '../Dataset/SA04/F03_SA04_R05.csv', '../Dataset/SA04/F04_SA04_R01.csv', '../Dataset/SA04/F04_SA04_R02.csv', '../Dataset/SA04/F04_SA04_R03.csv', '../Dataset/SA04/F04_SA04_R04.csv', '../Dataset/SA04/F04_SA04_R05.csv', '../Dataset/SA04/F05_SA04_R01.csv', '../Dataset/SA04/F05_SA04_R02.csv', '../Dataset/SA04/F05_SA04_R03.csv', '../Dataset/SA04/F05_SA04_R04.csv', '../Dataset/SA04/F05_SA04_R05.csv', '../Dataset/SA04/F06_SA04_R01.csv', '../Dataset/SA04/F06_SA04_R02.csv', '../Dataset/SA04/F06_SA04_R03.csv', '../Dataset/SA04/F06_SA04_R04.csv', '../Dataset/SA04/F06_SA04_R05.csv', '../Dataset/SA04/F07_SA04_R01.csv', '../Dataset/SA04/F07_SA04_R02.csv', '../Dataset/SA04/F07_SA04_R03.csv', '../Dataset/SA04/F07_SA04_R04.csv', '../Dataset/SA04/F07_SA04_R05.csv', '../Dataset/SA04/F08_SA04_R01.csv', '../Dataset/SA04/F08_SA04_R02.csv', '../Dataset/SA04/F08_SA04_R03.csv', '../Dataset/SA04/F08_SA04_R04.csv', '../Dataset/SA04/F08_SA04_R05.csv', '../Dataset/SA04/F09_SA04_R01.csv', '../Dataset/SA04/F09_SA04_R02.csv', '../Dataset/SA04/F09_SA04_R03.csv', '../Dataset/SA04/F09_SA04_R04.csv', '../Dataset/SA04/F09_SA04_R05.csv', '../Dataset/SA04/F10_SA04_R01.csv', '../Dataset/SA04/F10_SA04_R02.csv', '../Dataset/SA04/F10_SA04_R03.csv', '../Dataset/SA04/F10_SA04_R04.csv', '../Dataset/SA04/F10_SA04_R05.csv', '../Dataset/SA04/F11_SA04_R01.csv', '../Dataset/SA04/F11_SA04_R02.csv', '../Dataset/SA04/F11_SA04_R03.csv', '../Dataset/SA04/F11_SA04_R04.csv', '../Dataset/SA04/F11_SA04_R05.csv', '../Dataset/SA04/F12_SA04_R01.csv', '../Dataset/SA04/F12_SA04_R02.csv', '../Dataset/SA04/F12_SA04_R03.csv', '../Dataset/SA04/F12_SA04_R04.csv', '../Dataset/SA04/F12_SA04_R05.csv', '../Dataset/SA04/F13_SA04_R01.csv', '../Dataset/SA04/F13_SA04_R02.csv', '../Dataset/SA04/F13_SA04_R03.csv', '../Dataset/SA04/F13_SA04_R04.csv', '../Dataset/SA04/F13_SA04_R05.csv', '../Dataset/SA04/F14_SA04_R01.csv', '../Dataset/SA04/F14_SA04_R02.csv', '../Dataset/SA04/F14_SA04_R03.csv', '../Dataset/SA04/F14_SA04_R04.csv', '../Dataset/SA04/F14_SA04_R05.csv', '../Dataset/SA04/F15_SA04_R01.csv', '../Dataset/SA04/F15_SA04_R02.csv', '../Dataset/SA04/F15_SA04_R03.csv', '../Dataset/SA04/F15_SA04_R04.csv', '../Dataset/SA04/F15_SA04_R05.csv']

In [10]:
list = []
final_SA04_F = pd.DataFrame(list)

for path in SA04_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA04_F = final_SA04_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA04_F.shape
target_col = row * [1]
final_SA04_F.loc[:,'target'] = target_col

final_SA04_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,220.0,219.0,220.0,222.0,217.0,218.0,218.0,220.0,216.0,217.0,...,215.0,204.0,204.0,219.0,253.0,358.0,521.0,654.0,707.0,1
0,256.0,240.0,231.0,228.0,225.0,234.0,241.0,254.0,259.0,276.0,...,117.0,118.0,139.0,169.0,181.0,178.0,142.0,99.0,80.0,1
0,288.0,288.0,281.0,279.0,273.0,265.0,265.0,260.0,252.0,244.0,...,144.0,138.0,137.0,141.0,136.0,135.0,126.0,123.0,124.0,1
0,322.0,308.0,304.0,307.0,305.0,306.0,307.0,308.0,304.0,304.0,...,216.0,213.0,214.0,224.0,228.0,226.0,229.0,231.0,230.0,1
0,254.0,254.0,260.0,267.0,276.0,286.0,292.0,297.0,302.0,300.0,...,141.0,160.0,194.0,227.0,252.0,246.0,231.0,198.0,199.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,279.0,278.0,277.0,279.0,277.0,283.0,277.0,279.0,277.0,280.0,...,276.0,279.0,274.0,274.0,276.0,277.0,277.0,280.0,278.0,1
0,262.0,264.0,268.0,264.0,270.0,270.0,269.0,270.0,268.0,271.0,...,236.0,233.0,226.0,219.0,217.0,216.0,220.0,214.0,202.0,1
0,254.0,259.0,260.0,258.0,254.0,257.0,254.0,254.0,253.0,253.0,...,172.0,166.0,165.0,165.0,167.0,161.0,159.0,159.0,161.0,1
0,251.0,250.0,254.0,257.0,258.0,258.0,257.0,256.0,257.0,257.0,...,199.0,194.0,179.0,173.0,169.0,167.0,174.0,178.0,191.0,1
0,248.0,243.0,247.0,245.0,244.0,243.0,243.0,244.0,244.0,243.0,...,250.0,249.0,253.0,254.0,257.0,245.0,251.0,253.0,252.0,1

# SA05

In [58]:
SA05_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA05/F01_SA05_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA05_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA05_F_paths.append(tmp)
            
print(SA05_F_paths)

['../Dataset/SA05/F01_SA05_R01.csv', '../Dataset/SA05/F01_SA05_R02.csv', '../Dataset/SA05/F01_SA05_R03.csv', '../Dataset/SA05/F01_SA05_R04.csv', '../Dataset/SA05/F01_SA05_R05.csv', '../Dataset/SA05/F02_SA05_R01.csv', '../Dataset/SA05/F02_SA05_R02.csv', '../Dataset/SA05/F02_SA05_R03.csv', '../Dataset/SA05/F02_SA05_R04.csv', '../Dataset/SA05/F02_SA05_R05.csv', '../Dataset/SA05/F03_SA05_R01.csv', '../Dataset/SA05/F03_SA05_R02.csv', '../Dataset/SA05/F03_SA05_R03.csv', '../Dataset/SA05/F03_SA05_R04.csv', '../Dataset/SA05/F03_SA05_R05.csv', '../Dataset/SA05/F04_SA05_R01.csv', '../Dataset/SA05/F04_SA05_R02.csv', '../Dataset/SA05/F04_SA05_R03.csv', '../Dataset/SA05/F04_SA05_R04.csv', '../Dataset/SA05/F04_SA05_R05.csv', '../Dataset/SA05/F05_SA05_R01.csv', '../Dataset/SA05/F05_SA05_R02.csv', '../Dataset/SA05/F05_SA05_R03.csv', '../Dataset/SA05/F05_SA05_R04.csv', '../Dataset/SA05/F05_SA05_R05.csv', '../Dataset/SA05/F06_SA05_R01.csv', '../Dataset/SA05/F06_SA05_R02.csv', '../Dataset/SA05/F06_SA05_R03.csv', '../Dataset/SA05/F06_SA05_R04.csv', '../Dataset/SA05/F06_SA05_R05.csv', '../Dataset/SA05/F07_SA05_R01.csv', '../Dataset/SA05/F07_SA05_R02.csv', '../Dataset/SA05/F07_SA05_R03.csv', '../Dataset/SA05/F07_SA05_R04.csv', '../Dataset/SA05/F07_SA05_R05.csv', '../Dataset/SA05/F08_SA05_R01.csv', '../Dataset/SA05/F08_SA05_R02.csv', '../Dataset/SA05/F08_SA05_R03.csv', '../Dataset/SA05/F08_SA05_R04.csv', '../Dataset/SA05/F08_SA05_R05.csv', '../Dataset/SA05/F09_SA05_R01.csv', '../Dataset/SA05/F09_SA05_R02.csv', '../Dataset/SA05/F09_SA05_R03.csv', '../Dataset/SA05/F09_SA05_R04.csv', '../Dataset/SA05/F09_SA05_R05.csv', '../Dataset/SA05/F10_SA05_R01.csv', '../Dataset/SA05/F10_SA05_R02.csv', '../Dataset/SA05/F10_SA05_R03.csv', '../Dataset/SA05/F10_SA05_R04.csv', '../Dataset/SA05/F10_SA05_R05.csv', '../Dataset/SA05/F11_SA05_R01.csv', '../Dataset/SA05/F11_SA05_R02.csv', '../Dataset/SA05/F11_SA05_R03.csv', '../Dataset/SA05/F11_SA05_R04.csv', '../Dataset/SA05/F11_SA05_R05.csv', '../Dataset/SA05/F12_SA05_R01.csv', '../Dataset/SA05/F12_SA05_R02.csv', '../Dataset/SA05/F12_SA05_R03.csv', '../Dataset/SA05/F12_SA05_R04.csv', '../Dataset/SA05/F12_SA05_R05.csv', '../Dataset/SA05/F13_SA05_R01.csv', '../Dataset/SA05/F13_SA05_R02.csv', '../Dataset/SA05/F13_SA05_R03.csv', '../Dataset/SA05/F13_SA05_R04.csv', '../Dataset/SA05/F13_SA05_R05.csv', '../Dataset/SA05/F14_SA05_R01.csv', '../Dataset/SA05/F14_SA05_R02.csv', '../Dataset/SA05/F14_SA05_R03.csv', '../Dataset/SA05/F14_SA05_R04.csv', '../Dataset/SA05/F14_SA05_R05.csv', '../Dataset/SA05/F15_SA05_R01.csv', '../Dataset/SA05/F15_SA05_R02.csv', '../Dataset/SA05/F15_SA05_R03.csv', '../Dataset/SA05/F15_SA05_R04.csv', '../Dataset/SA05/F15_SA05_R05.csv']

In [59]:
list = []
final_SA05_F = pd.DataFrame(list)

for path in SA05_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA05_F = final_SA05_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA05_F.shape
target_col = row * [1]
final_SA05_F.loc[:,'target'] = target_col

final_SA05_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,271.0,264.0,253.0,250.0,258.0,260.0,279.0,292.0,315.0,329.0,...,237.0,200.0,180.0,173.0,152.0,166.0,170.0,202.0,251.0,1
0,311.0,319.0,324.0,328.0,323.0,330.0,324.0,316.0,310.0,296.0,...,163.0,131.0,91.0,66.0,40.0,56.0,80.0,110.0,115.0,1
0,256.0,253.0,251.0,247.0,246.0,242.0,243.0,242.0,239.0,233.0,...,270.0,283.0,272.0,251.0,220.0,211.0,211.0,198.0,198.0,1
0,249.0,262.0,272.0,283.0,289.0,290.0,294.0,294.0,290.0,281.0,...,178.0,185.0,188.0,187.0,179.0,178.0,172.0,161.0,149.0,1
0,222.0,218.0,208.0,207.0,199.0,198.0,195.0,196.0,196.0,199.0,...,117.0,111.0,119.0,125.0,142.0,157.0,163.0,163.0,144.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,257.0,254.0,254.0,252.0,248.0,251.0,242.0,250.0,241.0,244.0,...,94.0,88.0,107.0,122.0,135.0,104.0,127.0,146.0,152.0,1
0,258.0,258.0,255.0,257.0,257.0,257.0,253.0,258.0,254.0,257.0,...,256.0,257.0,259.0,259.0,259.0,259.0,256.0,259.0,252.0,1
0,248.0,246.0,245.0,247.0,245.0,244.0,247.0,244.0,241.0,243.0,...,257.0,254.0,256.0,253.0,256.0,252.0,251.0,246.0,251.0,1
0,251.0,250.0,251.0,250.0,254.0,249.0,250.0,253.0,252.0,253.0,...,249.0,249.0,247.0,252.0,251.0,249.0,247.0,246.0,246.0,1
0,252.0,248.0,251.0,249.0,243.0,242.0,248.0,244.0,246.0,243.0,...,185.0,181.0,169.0,159.0,140.0,125.0,112.0,106.0,86.0,1

# SA06

In [13]:
SA06_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA06/F01_SA06_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA06_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA06_F_paths.append(tmp)
            
print(SA06_F_paths)

['../Dataset/SA06/F01_SA06_R01.csv', '../Dataset/SA06/F01_SA06_R02.csv', '../Dataset/SA06/F01_SA06_R03.csv', '../Dataset/SA06/F01_SA06_R04.csv', '../Dataset/SA06/F01_SA06_R05.csv', '../Dataset/SA06/F02_SA06_R01.csv', '../Dataset/SA06/F02_SA06_R02.csv', '../Dataset/SA06/F02_SA06_R03.csv', '../Dataset/SA06/F02_SA06_R04.csv', '../Dataset/SA06/F02_SA06_R05.csv', '../Dataset/SA06/F03_SA06_R01.csv', '../Dataset/SA06/F03_SA06_R02.csv', '../Dataset/SA06/F03_SA06_R03.csv', '../Dataset/SA06/F03_SA06_R04.csv', '../Dataset/SA06/F03_SA06_R05.csv', '../Dataset/SA06/F04_SA06_R01.csv', '../Dataset/SA06/F04_SA06_R02.csv', '../Dataset/SA06/F04_SA06_R03.csv', '../Dataset/SA06/F04_SA06_R04.csv', '../Dataset/SA06/F04_SA06_R05.csv', '../Dataset/SA06/F05_SA06_R01.csv', '../Dataset/SA06/F05_SA06_R02.csv', '../Dataset/SA06/F05_SA06_R03.csv', '../Dataset/SA06/F05_SA06_R04.csv', '../Dataset/SA06/F05_SA06_R05.csv', '../Dataset/SA06/F06_SA06_R01.csv', '../Dataset/SA06/F06_SA06_R02.csv', '../Dataset/SA06/F06_SA06_R03.csv', '../Dataset/SA06/F06_SA06_R04.csv', '../Dataset/SA06/F06_SA06_R05.csv', '../Dataset/SA06/F07_SA06_R01.csv', '../Dataset/SA06/F07_SA06_R02.csv', '../Dataset/SA06/F07_SA06_R03.csv', '../Dataset/SA06/F07_SA06_R04.csv', '../Dataset/SA06/F07_SA06_R05.csv', '../Dataset/SA06/F08_SA06_R01.csv', '../Dataset/SA06/F08_SA06_R02.csv', '../Dataset/SA06/F08_SA06_R03.csv', '../Dataset/SA06/F08_SA06_R04.csv', '../Dataset/SA06/F08_SA06_R05.csv', '../Dataset/SA06/F09_SA06_R01.csv', '../Dataset/SA06/F09_SA06_R02.csv', '../Dataset/SA06/F09_SA06_R03.csv', '../Dataset/SA06/F09_SA06_R04.csv', '../Dataset/SA06/F09_SA06_R05.csv', '../Dataset/SA06/F10_SA06_R01.csv', '../Dataset/SA06/F10_SA06_R02.csv', '../Dataset/SA06/F10_SA06_R03.csv', '../Dataset/SA06/F10_SA06_R04.csv', '../Dataset/SA06/F10_SA06_R05.csv', '../Dataset/SA06/F11_SA06_R01.csv', '../Dataset/SA06/F11_SA06_R02.csv', '../Dataset/SA06/F11_SA06_R03.csv', '../Dataset/SA06/F11_SA06_R04.csv', '../Dataset/SA06/F11_SA06_R05.csv', '../Dataset/SA06/F12_SA06_R01.csv', '../Dataset/SA06/F12_SA06_R02.csv', '../Dataset/SA06/F12_SA06_R03.csv', '../Dataset/SA06/F12_SA06_R04.csv', '../Dataset/SA06/F12_SA06_R05.csv', '../Dataset/SA06/F13_SA06_R01.csv', '../Dataset/SA06/F13_SA06_R02.csv', '../Dataset/SA06/F13_SA06_R03.csv', '../Dataset/SA06/F13_SA06_R04.csv', '../Dataset/SA06/F13_SA06_R05.csv', '../Dataset/SA06/F14_SA06_R01.csv', '../Dataset/SA06/F14_SA06_R02.csv', '../Dataset/SA06/F14_SA06_R03.csv', '../Dataset/SA06/F14_SA06_R04.csv', '../Dataset/SA06/F14_SA06_R05.csv', '../Dataset/SA06/F15_SA06_R01.csv', '../Dataset/SA06/F15_SA06_R02.csv', '../Dataset/SA06/F15_SA06_R03.csv', '../Dataset/SA06/F15_SA06_R04.csv', '../Dataset/SA06/F15_SA06_R05.csv']

In [14]:
list = []
final_SA06_F = pd.DataFrame(list)

for path in SA06_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA06_F = final_SA06_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA06_F.shape
target_col = row * [1]
final_SA06_F.loc[:,'target'] = target_col

final_SA06_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,256.0,260.0,268.0,272.0,280.0,288.0,296.0,310.0,318.0,330.0,...,84.0,113.0,133.0,139.0,143.0,127.0,101.0,93.0,79.0,1
0,292.0,292.0,295.0,294.0,289.0,289.0,284.0,271.0,265.0,261.0,...,178.0,163.0,156.0,149.0,137.0,124.0,115.0,114.0,117.0,1
0,223.0,218.0,217.0,215.0,215.0,214.0,213.0,211.0,211.0,210.0,...,71.0,114.0,132.0,144.0,157.0,157.0,155.0,161.0,150.0,1
0,266.0,275.0,280.0,286.0,294.0,294.0,293.0,295.0,292.0,291.0,...,94.0,94.0,99.0,95.0,114.0,124.0,130.0,133.0,135.0,1
0,232.0,232.0,235.0,233.0,232.0,232.0,230.0,226.0,224.0,221.0,...,45.0,36.0,36.0,48.0,60.0,80.0,91.0,111.0,122.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,251.0,253.0,252.0,253.0,252.0,252.0,253.0,246.0,249.0,249.0,...,69.0,66.0,64.0,68.0,73.0,74.0,74.0,67.0,79.0,1
0,249.0,254.0,249.0,248.0,253.0,252.0,251.0,253.0,253.0,250.0,...,159.0,153.0,147.0,141.0,131.0,121.0,105.0,96.0,95.0,1
0,261.0,259.0,258.0,255.0,255.0,255.0,257.0,253.0,258.0,258.0,...,153.0,145.0,143.0,138.0,125.0,119.0,109.0,104.0,95.0,1
0,249.0,249.0,252.0,249.0,252.0,254.0,253.0,256.0,252.0,252.0,...,263.0,260.0,251.0,237.0,221.0,206.0,193.0,184.0,179.0,1
0,246.0,246.0,246.0,248.0,245.0,250.0,251.0,244.0,246.0,246.0,...,167.0,170.0,173.0,175.0,178.0,170.0,166.0,154.0,147.0,1

# SA07

In [15]:
SA07_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA07/F01_SA07_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA07_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA07_F_paths.append(tmp)
            
print(SA07_F_paths)

['../Dataset/SA07/F01_SA07_R01.csv', '../Dataset/SA07/F01_SA07_R02.csv', '../Dataset/SA07/F01_SA07_R03.csv', '../Dataset/SA07/F01_SA07_R04.csv', '../Dataset/SA07/F01_SA07_R05.csv', '../Dataset/SA07/F02_SA07_R01.csv', '../Dataset/SA07/F02_SA07_R02.csv', '../Dataset/SA07/F02_SA07_R03.csv', '../Dataset/SA07/F02_SA07_R04.csv', '../Dataset/SA07/F02_SA07_R05.csv', '../Dataset/SA07/F03_SA07_R01.csv', '../Dataset/SA07/F03_SA07_R02.csv', '../Dataset/SA07/F03_SA07_R03.csv', '../Dataset/SA07/F03_SA07_R04.csv', '../Dataset/SA07/F03_SA07_R05.csv', '../Dataset/SA07/F04_SA07_R01.csv', '../Dataset/SA07/F04_SA07_R02.csv', '../Dataset/SA07/F04_SA07_R03.csv', '../Dataset/SA07/F04_SA07_R04.csv', '../Dataset/SA07/F04_SA07_R05.csv', '../Dataset/SA07/F05_SA07_R01.csv', '../Dataset/SA07/F05_SA07_R02.csv', '../Dataset/SA07/F05_SA07_R03.csv', '../Dataset/SA07/F05_SA07_R04.csv', '../Dataset/SA07/F05_SA07_R05.csv', '../Dataset/SA07/F06_SA07_R01.csv', '../Dataset/SA07/F06_SA07_R02.csv', '../Dataset/SA07/F06_SA07_R03.csv', '../Dataset/SA07/F06_SA07_R04.csv', '../Dataset/SA07/F06_SA07_R05.csv', '../Dataset/SA07/F07_SA07_R01.csv', '../Dataset/SA07/F07_SA07_R02.csv', '../Dataset/SA07/F07_SA07_R03.csv', '../Dataset/SA07/F07_SA07_R04.csv', '../Dataset/SA07/F07_SA07_R05.csv', '../Dataset/SA07/F08_SA07_R01.csv', '../Dataset/SA07/F08_SA07_R02.csv', '../Dataset/SA07/F08_SA07_R03.csv', '../Dataset/SA07/F08_SA07_R04.csv', '../Dataset/SA07/F08_SA07_R05.csv', '../Dataset/SA07/F09_SA07_R01.csv', '../Dataset/SA07/F09_SA07_R02.csv', '../Dataset/SA07/F09_SA07_R03.csv', '../Dataset/SA07/F09_SA07_R04.csv', '../Dataset/SA07/F09_SA07_R05.csv', '../Dataset/SA07/F10_SA07_R01.csv', '../Dataset/SA07/F10_SA07_R02.csv', '../Dataset/SA07/F10_SA07_R03.csv', '../Dataset/SA07/F10_SA07_R04.csv', '../Dataset/SA07/F10_SA07_R05.csv', '../Dataset/SA07/F11_SA07_R01.csv', '../Dataset/SA07/F11_SA07_R02.csv', '../Dataset/SA07/F11_SA07_R03.csv', '../Dataset/SA07/F11_SA07_R04.csv', '../Dataset/SA07/F11_SA07_R05.csv', '../Dataset/SA07/F12_SA07_R01.csv', '../Dataset/SA07/F12_SA07_R02.csv', '../Dataset/SA07/F12_SA07_R03.csv', '../Dataset/SA07/F12_SA07_R04.csv', '../Dataset/SA07/F12_SA07_R05.csv', '../Dataset/SA07/F13_SA07_R01.csv', '../Dataset/SA07/F13_SA07_R02.csv', '../Dataset/SA07/F13_SA07_R03.csv', '../Dataset/SA07/F13_SA07_R04.csv', '../Dataset/SA07/F13_SA07_R05.csv', '../Dataset/SA07/F14_SA07_R01.csv', '../Dataset/SA07/F14_SA07_R02.csv', '../Dataset/SA07/F14_SA07_R03.csv', '../Dataset/SA07/F14_SA07_R04.csv', '../Dataset/SA07/F14_SA07_R05.csv', '../Dataset/SA07/F15_SA07_R01.csv', '../Dataset/SA07/F15_SA07_R02.csv', '../Dataset/SA07/F15_SA07_R03.csv', '../Dataset/SA07/F15_SA07_R04.csv', '../Dataset/SA07/F15_SA07_R05.csv']

In [16]:
list = []
final_SA07_F = pd.DataFrame(list)

for path in SA07_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA07_F = final_SA07_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA07_F.shape
target_col = row * [1]
final_SA07_F.loc[:,'target'] = target_col

final_SA07_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,263.0,271.0,280.0,286.0,293.0,303.0,309.0,309.0,310.0,311.0,...,185.0,173.0,171.0,170.0,174.0,198.0,250.0,338.0,449.0,1
0,308.0,312.0,311.0,315.0,316.0,313.0,313.0,312.0,305.0,299.0,...,115.0,104.0,103.0,94.0,98.0,117.0,151.0,229.0,338.0,1
0,209.0,213.0,216.0,221.0,227.0,230.0,231.0,227.0,232.0,233.0,...,250.0,256.0,254.0,258.0,255.0,255.0,253.0,241.0,230.0,1
0,229.0,229.0,228.0,230.0,224.0,226.0,221.0,222.0,225.0,222.0,...,745.0,659.0,573.0,549.0,566.0,602.0,632.0,626.0,568.0,1
0,276.0,277.0,276.0,271.0,268.0,267.0,260.0,253.0,247.0,242.0,...,618.0,661.0,699.0,709.0,707.0,698.0,684.0,659.0,632.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,271.0,270.0,271.0,271.0,273.0,271.0,269.0,272.0,270.0,271.0,...,165.0,156.0,154.0,152.0,145.0,139.0,143.0,138.0,140.0,1
0,272.0,268.0,269.0,272.0,268.0,268.0,264.0,268.0,270.0,267.0,...,145.0,136.0,133.0,138.0,145.0,136.0,144.0,158.0,164.0,1
0,273.0,273.0,274.0,273.0,272.0,268.0,270.0,274.0,273.0,274.0,...,193.0,181.0,182.0,175.0,171.0,182.0,169.0,181.0,176.0,1
0,263.0,267.0,268.0,259.0,265.0,265.0,265.0,261.0,265.0,264.0,...,888.0,809.0,726.0,678.0,629.0,550.0,477.0,410.0,361.0,1
0,267.0,266.0,267.0,267.0,266.0,269.0,269.0,269.0,270.0,270.0,...,162.0,156.0,141.0,129.0,116.0,104.0,94.0,79.0,75.0,1

# SA08

In [17]:
SA08_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA08/F01_SA08_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA08_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA08_F_paths.append(tmp)
            
print(SA08_F_paths)

['../Dataset/SA08/F01_SA08_R01.csv', '../Dataset/SA08/F01_SA08_R02.csv', '../Dataset/SA08/F01_SA08_R03.csv', '../Dataset/SA08/F01_SA08_R04.csv', '../Dataset/SA08/F01_SA08_R05.csv', '../Dataset/SA08/F02_SA08_R01.csv', '../Dataset/SA08/F02_SA08_R02.csv', '../Dataset/SA08/F02_SA08_R03.csv', '../Dataset/SA08/F02_SA08_R04.csv', '../Dataset/SA08/F02_SA08_R05.csv', '../Dataset/SA08/F03_SA08_R01.csv', '../Dataset/SA08/F03_SA08_R02.csv', '../Dataset/SA08/F03_SA08_R03.csv', '../Dataset/SA08/F03_SA08_R04.csv', '../Dataset/SA08/F03_SA08_R05.csv', '../Dataset/SA08/F04_SA08_R01.csv', '../Dataset/SA08/F04_SA08_R02.csv', '../Dataset/SA08/F04_SA08_R03.csv', '../Dataset/SA08/F04_SA08_R04.csv', '../Dataset/SA08/F04_SA08_R05.csv', '../Dataset/SA08/F05_SA08_R01.csv', '../Dataset/SA08/F05_SA08_R02.csv', '../Dataset/SA08/F05_SA08_R03.csv', '../Dataset/SA08/F05_SA08_R04.csv', '../Dataset/SA08/F05_SA08_R05.csv', '../Dataset/SA08/F06_SA08_R01.csv', '../Dataset/SA08/F06_SA08_R02.csv', '../Dataset/SA08/F06_SA08_R03.csv', '../Dataset/SA08/F06_SA08_R04.csv', '../Dataset/SA08/F06_SA08_R05.csv', '../Dataset/SA08/F07_SA08_R01.csv', '../Dataset/SA08/F07_SA08_R02.csv', '../Dataset/SA08/F07_SA08_R03.csv', '../Dataset/SA08/F07_SA08_R04.csv', '../Dataset/SA08/F07_SA08_R05.csv', '../Dataset/SA08/F08_SA08_R01.csv', '../Dataset/SA08/F08_SA08_R02.csv', '../Dataset/SA08/F08_SA08_R03.csv', '../Dataset/SA08/F08_SA08_R04.csv', '../Dataset/SA08/F08_SA08_R05.csv', '../Dataset/SA08/F09_SA08_R01.csv', '../Dataset/SA08/F09_SA08_R02.csv', '../Dataset/SA08/F09_SA08_R03.csv', '../Dataset/SA08/F09_SA08_R04.csv', '../Dataset/SA08/F09_SA08_R05.csv', '../Dataset/SA08/F10_SA08_R01.csv', '../Dataset/SA08/F10_SA08_R02.csv', '../Dataset/SA08/F10_SA08_R03.csv', '../Dataset/SA08/F10_SA08_R04.csv', '../Dataset/SA08/F10_SA08_R05.csv', '../Dataset/SA08/F11_SA08_R01.csv', '../Dataset/SA08/F11_SA08_R02.csv', '../Dataset/SA08/F11_SA08_R03.csv', '../Dataset/SA08/F11_SA08_R04.csv', '../Dataset/SA08/F11_SA08_R05.csv', '../Dataset/SA08/F12_SA08_R01.csv', '../Dataset/SA08/F12_SA08_R02.csv', '../Dataset/SA08/F12_SA08_R03.csv', '../Dataset/SA08/F12_SA08_R04.csv', '../Dataset/SA08/F12_SA08_R05.csv', '../Dataset/SA08/F13_SA08_R01.csv', '../Dataset/SA08/F13_SA08_R02.csv', '../Dataset/SA08/F13_SA08_R03.csv', '../Dataset/SA08/F13_SA08_R04.csv', '../Dataset/SA08/F13_SA08_R05.csv', '../Dataset/SA08/F14_SA08_R01.csv', '../Dataset/SA08/F14_SA08_R02.csv', '../Dataset/SA08/F14_SA08_R03.csv', '../Dataset/SA08/F14_SA08_R04.csv', '../Dataset/SA08/F14_SA08_R05.csv', '../Dataset/SA08/F15_SA08_R01.csv', '../Dataset/SA08/F15_SA08_R02.csv', '../Dataset/SA08/F15_SA08_R03.csv', '../Dataset/SA08/F15_SA08_R04.csv', '../Dataset/SA08/F15_SA08_R05.csv']

In [57]:
list = []
final_SA08_F = pd.DataFrame(list)

for path in SA08_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA08_F = final_SA08_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA08_F.shape
target_col = row * [1]
final_SA08_F.loc[:,'target'] = target_col

final_SA08_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,290.0,358.0,406.0,463.0,499.0,515.0,521.0,502.0,463.0,422.0,...,105.0,102.0,99.0,94.0,100.0,111.0,118.0,105.0,95.0,1
0,244.0,258.0,271.0,283.0,299.0,313.0,325.0,335.0,342.0,349.0,...,214.0,204.0,208.0,208.0,198.0,198.0,201.0,197.0,200.0,1
0,299.0,283.0,275.0,263.0,257.0,259.0,269.0,278.0,290.0,292.0,...,164.0,168.0,174.0,180.0,186.0,186.0,190.0,193.0,193.0,1
0,204.0,204.0,200.0,198.0,193.0,189.0,185.0,178.0,167.0,159.0,...,170.0,190.0,211.0,226.0,232.0,247.0,255.0,250.0,251.0,1
0,207.0,199.0,190.0,185.0,181.0,173.0,167.0,158.0,158.0,159.0,...,259.0,254.0,224.0,207.0,173.0,167.0,172.0,178.0,188.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,220.0,219.0,220.0,217.0,220.0,214.0,213.0,217.0,220.0,219.0,...,361.0,330.0,330.0,339.0,354.0,326.0,277.0,214.0,128.0,1
0,231.0,229.0,229.0,230.0,233.0,234.0,232.0,232.0,245.0,239.0,...,160.0,159.0,147.0,145.0,164.0,145.0,152.0,153.0,157.0,1
0,230.0,220.0,231.0,230.0,227.0,233.0,230.0,229.0,226.0,224.0,...,156.0,139.0,131.0,126.0,142.0,144.0,160.0,167.0,164.0,1
0,224.0,225.0,229.0,225.0,228.0,221.0,224.0,224.0,225.0,229.0,...,238.0,241.0,235.0,218.0,203.0,180.0,154.0,125.0,99.0,1
0,243.0,243.0,248.0,247.0,248.0,245.0,250.0,249.0,252.0,250.0,...,101.0,98.0,101.0,108.0,120.0,132.0,142.0,164.0,177.0,1

# SA09

In [20]:
SA09_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA09/F01_SA09_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA09_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA09_F_paths.append(tmp)
            
print(SA09_F_paths)

['../Dataset/SA09/F01_SA09_R01.csv', '../Dataset/SA09/F01_SA09_R02.csv', '../Dataset/SA09/F01_SA09_R03.csv', '../Dataset/SA09/F01_SA09_R04.csv', '../Dataset/SA09/F01_SA09_R05.csv', '../Dataset/SA09/F02_SA09_R01.csv', '../Dataset/SA09/F02_SA09_R02.csv', '../Dataset/SA09/F02_SA09_R03.csv', '../Dataset/SA09/F02_SA09_R04.csv', '../Dataset/SA09/F02_SA09_R05.csv', '../Dataset/SA09/F03_SA09_R01.csv', '../Dataset/SA09/F03_SA09_R02.csv', '../Dataset/SA09/F03_SA09_R03.csv', '../Dataset/SA09/F03_SA09_R04.csv', '../Dataset/SA09/F03_SA09_R05.csv', '../Dataset/SA09/F04_SA09_R01.csv', '../Dataset/SA09/F04_SA09_R02.csv', '../Dataset/SA09/F04_SA09_R03.csv', '../Dataset/SA09/F04_SA09_R04.csv', '../Dataset/SA09/F04_SA09_R05.csv', '../Dataset/SA09/F05_SA09_R01.csv', '../Dataset/SA09/F05_SA09_R02.csv', '../Dataset/SA09/F05_SA09_R03.csv', '../Dataset/SA09/F05_SA09_R04.csv', '../Dataset/SA09/F05_SA09_R05.csv', '../Dataset/SA09/F06_SA09_R01.csv', '../Dataset/SA09/F06_SA09_R02.csv', '../Dataset/SA09/F06_SA09_R03.csv', '../Dataset/SA09/F06_SA09_R04.csv', '../Dataset/SA09/F06_SA09_R05.csv', '../Dataset/SA09/F07_SA09_R01.csv', '../Dataset/SA09/F07_SA09_R02.csv', '../Dataset/SA09/F07_SA09_R03.csv', '../Dataset/SA09/F07_SA09_R04.csv', '../Dataset/SA09/F07_SA09_R05.csv', '../Dataset/SA09/F08_SA09_R01.csv', '../Dataset/SA09/F08_SA09_R02.csv', '../Dataset/SA09/F08_SA09_R03.csv', '../Dataset/SA09/F08_SA09_R04.csv', '../Dataset/SA09/F08_SA09_R05.csv', '../Dataset/SA09/F09_SA09_R01.csv', '../Dataset/SA09/F09_SA09_R02.csv', '../Dataset/SA09/F09_SA09_R03.csv', '../Dataset/SA09/F09_SA09_R04.csv', '../Dataset/SA09/F09_SA09_R05.csv', '../Dataset/SA09/F10_SA09_R01.csv', '../Dataset/SA09/F10_SA09_R02.csv', '../Dataset/SA09/F10_SA09_R03.csv', '../Dataset/SA09/F10_SA09_R04.csv', '../Dataset/SA09/F10_SA09_R05.csv', '../Dataset/SA09/F11_SA09_R01.csv', '../Dataset/SA09/F11_SA09_R02.csv', '../Dataset/SA09/F11_SA09_R03.csv', '../Dataset/SA09/F11_SA09_R04.csv', '../Dataset/SA09/F11_SA09_R05.csv', '../Dataset/SA09/F12_SA09_R01.csv', '../Dataset/SA09/F12_SA09_R02.csv', '../Dataset/SA09/F12_SA09_R03.csv', '../Dataset/SA09/F12_SA09_R04.csv', '../Dataset/SA09/F12_SA09_R05.csv', '../Dataset/SA09/F13_SA09_R01.csv', '../Dataset/SA09/F13_SA09_R02.csv', '../Dataset/SA09/F13_SA09_R03.csv', '../Dataset/SA09/F13_SA09_R04.csv', '../Dataset/SA09/F13_SA09_R05.csv', '../Dataset/SA09/F14_SA09_R01.csv', '../Dataset/SA09/F14_SA09_R02.csv', '../Dataset/SA09/F14_SA09_R03.csv', '../Dataset/SA09/F14_SA09_R04.csv', '../Dataset/SA09/F14_SA09_R05.csv', '../Dataset/SA09/F15_SA09_R01.csv', '../Dataset/SA09/F15_SA09_R02.csv', '../Dataset/SA09/F15_SA09_R03.csv', '../Dataset/SA09/F15_SA09_R04.csv', '../Dataset/SA09/F15_SA09_R05.csv']

In [21]:
list = []
final_SA09_F = pd.DataFrame(list)

for path in SA09_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA09_F = final_SA09_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA09_F.shape
target_col = row * [1]
final_SA09_F.loc[:,'target'] = target_col

final_SA09_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,218.0,214.0,205.0,199.0,191.0,184.0,176.0,165.0,162.0,155.0,...,199.0,200.0,205.0,207.0,204.0,196.0,192.0,184.0,184.0,1
0,370.0,380.0,385.0,390.0,383.0,372.0,354.0,340.0,323.0,307.0,...,107.0,121.0,151.0,145.0,129.0,122.0,135.0,127.0,104.0,1
0,351.0,355.0,364.0,372.0,359.0,311.0,299.0,345.0,442.0,487.0,...,150.0,103.0,81.0,77.0,52.0,28.0,30.0,54.0,88.0,1
0,190.0,220.0,250.0,279.0,317.0,344.0,358.0,360.0,399.0,428.0,...,171.0,231.0,272.0,328.0,367.0,353.0,337.0,311.0,271.0,1
0,266.0,245.0,229.0,232.0,232.0,241.0,247.0,262.0,274.0,283.0,...,250.0,220.0,209.0,195.0,223.0,243.0,247.0,215.0,182.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,251.0,250.0,249.0,252.0,248.0,250.0,251.0,250.0,253.0,250.0,...,161.0,169.0,168.0,160.0,150.0,133.0,126.0,114.0,122.0,1
0,246.0,245.0,243.0,245.0,246.0,248.0,249.0,251.0,250.0,250.0,...,265.0,277.0,289.0,282.0,260.0,239.0,220.0,216.0,205.0,1
0,256.0,254.0,254.0,250.0,252.0,248.0,249.0,248.0,246.0,245.0,...,218.0,212.0,212.0,205.0,192.0,185.0,178.0,173.0,164.0,1
0,252.0,249.0,252.0,252.0,249.0,247.0,250.0,248.0,253.0,248.0,...,197.0,196.0,185.0,183.0,174.0,175.0,172.0,166.0,167.0,1
0,255.0,252.0,257.0,257.0,258.0,258.0,253.0,259.0,257.0,260.0,...,148.0,137.0,128.0,125.0,125.0,123.0,119.0,108.0,100.0,1

# SA10

In [22]:
SA10_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA10/F01_SA10_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA10_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA10_F_paths.append(tmp)
            
print(SA10_F_paths)

['../Dataset/SA10/F01_SA10_R01.csv', '../Dataset/SA10/F01_SA10_R02.csv', '../Dataset/SA10/F01_SA10_R03.csv', '../Dataset/SA10/F01_SA10_R04.csv', '../Dataset/SA10/F01_SA10_R05.csv', '../Dataset/SA10/F02_SA10_R01.csv', '../Dataset/SA10/F02_SA10_R02.csv', '../Dataset/SA10/F02_SA10_R03.csv', '../Dataset/SA10/F02_SA10_R04.csv', '../Dataset/SA10/F02_SA10_R05.csv', '../Dataset/SA10/F03_SA10_R01.csv', '../Dataset/SA10/F03_SA10_R02.csv', '../Dataset/SA10/F03_SA10_R03.csv', '../Dataset/SA10/F03_SA10_R04.csv', '../Dataset/SA10/F03_SA10_R05.csv', '../Dataset/SA10/F04_SA10_R01.csv', '../Dataset/SA10/F04_SA10_R02.csv', '../Dataset/SA10/F04_SA10_R03.csv', '../Dataset/SA10/F04_SA10_R04.csv', '../Dataset/SA10/F04_SA10_R05.csv', '../Dataset/SA10/F05_SA10_R01.csv', '../Dataset/SA10/F05_SA10_R02.csv', '../Dataset/SA10/F05_SA10_R03.csv', '../Dataset/SA10/F05_SA10_R04.csv', '../Dataset/SA10/F05_SA10_R05.csv', '../Dataset/SA10/F06_SA10_R01.csv', '../Dataset/SA10/F06_SA10_R02.csv', '../Dataset/SA10/F06_SA10_R03.csv', '../Dataset/SA10/F06_SA10_R04.csv', '../Dataset/SA10/F06_SA10_R05.csv', '../Dataset/SA10/F07_SA10_R01.csv', '../Dataset/SA10/F07_SA10_R02.csv', '../Dataset/SA10/F07_SA10_R03.csv', '../Dataset/SA10/F07_SA10_R04.csv', '../Dataset/SA10/F07_SA10_R05.csv', '../Dataset/SA10/F08_SA10_R01.csv', '../Dataset/SA10/F08_SA10_R02.csv', '../Dataset/SA10/F08_SA10_R03.csv', '../Dataset/SA10/F08_SA10_R04.csv', '../Dataset/SA10/F08_SA10_R05.csv', '../Dataset/SA10/F09_SA10_R01.csv', '../Dataset/SA10/F09_SA10_R02.csv', '../Dataset/SA10/F09_SA10_R03.csv', '../Dataset/SA10/F09_SA10_R04.csv', '../Dataset/SA10/F09_SA10_R05.csv', '../Dataset/SA10/F10_SA10_R01.csv', '../Dataset/SA10/F10_SA10_R02.csv', '../Dataset/SA10/F10_SA10_R03.csv', '../Dataset/SA10/F10_SA10_R04.csv', '../Dataset/SA10/F10_SA10_R05.csv', '../Dataset/SA10/F11_SA10_R01.csv', '../Dataset/SA10/F11_SA10_R02.csv', '../Dataset/SA10/F11_SA10_R03.csv', '../Dataset/SA10/F11_SA10_R04.csv', '../Dataset/SA10/F11_SA10_R05.csv', '../Dataset/SA10/F12_SA10_R01.csv', '../Dataset/SA10/F12_SA10_R02.csv', '../Dataset/SA10/F12_SA10_R03.csv', '../Dataset/SA10/F12_SA10_R04.csv', '../Dataset/SA10/F12_SA10_R05.csv', '../Dataset/SA10/F13_SA10_R01.csv', '../Dataset/SA10/F13_SA10_R02.csv', '../Dataset/SA10/F13_SA10_R03.csv', '../Dataset/SA10/F13_SA10_R04.csv', '../Dataset/SA10/F13_SA10_R05.csv', '../Dataset/SA10/F14_SA10_R01.csv', '../Dataset/SA10/F14_SA10_R02.csv', '../Dataset/SA10/F14_SA10_R03.csv', '../Dataset/SA10/F14_SA10_R04.csv', '../Dataset/SA10/F14_SA10_R05.csv', '../Dataset/SA10/F15_SA10_R01.csv', '../Dataset/SA10/F15_SA10_R02.csv', '../Dataset/SA10/F15_SA10_R03.csv', '../Dataset/SA10/F15_SA10_R04.csv', '../Dataset/SA10/F15_SA10_R05.csv']

In [23]:
list = []
final_SA10_F = pd.DataFrame(list)

for path in SA10_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA10_F = final_SA10_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA10_F.shape
target_col = row * [1]
final_SA10_F.loc[:,'target'] = target_col

final_SA10_F

ParserError: Error tokenizing data. C error: Expected 9 fields in line 1030, saw 21

# SA11

In [24]:
SA11_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA11/F01_SA11_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA11_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA11_F_paths.append(tmp)
            
print(SA11_F_paths)

['../Dataset/SA11/F01_SA11_R01.csv', '../Dataset/SA11/F01_SA11_R02.csv', '../Dataset/SA11/F01_SA11_R03.csv', '../Dataset/SA11/F01_SA11_R04.csv', '../Dataset/SA11/F01_SA11_R05.csv', '../Dataset/SA11/F02_SA11_R01.csv', '../Dataset/SA11/F02_SA11_R02.csv', '../Dataset/SA11/F02_SA11_R03.csv', '../Dataset/SA11/F02_SA11_R04.csv', '../Dataset/SA11/F02_SA11_R05.csv', '../Dataset/SA11/F03_SA11_R01.csv', '../Dataset/SA11/F03_SA11_R02.csv', '../Dataset/SA11/F03_SA11_R03.csv', '../Dataset/SA11/F03_SA11_R04.csv', '../Dataset/SA11/F03_SA11_R05.csv', '../Dataset/SA11/F04_SA11_R01.csv', '../Dataset/SA11/F04_SA11_R02.csv', '../Dataset/SA11/F04_SA11_R03.csv', '../Dataset/SA11/F04_SA11_R04.csv', '../Dataset/SA11/F04_SA11_R05.csv', '../Dataset/SA11/F05_SA11_R01.csv', '../Dataset/SA11/F05_SA11_R02.csv', '../Dataset/SA11/F05_SA11_R03.csv', '../Dataset/SA11/F05_SA11_R04.csv', '../Dataset/SA11/F05_SA11_R05.csv', '../Dataset/SA11/F06_SA11_R01.csv', '../Dataset/SA11/F06_SA11_R02.csv', '../Dataset/SA11/F06_SA11_R03.csv', '../Dataset/SA11/F06_SA11_R04.csv', '../Dataset/SA11/F06_SA11_R05.csv', '../Dataset/SA11/F07_SA11_R01.csv', '../Dataset/SA11/F07_SA11_R02.csv', '../Dataset/SA11/F07_SA11_R03.csv', '../Dataset/SA11/F07_SA11_R04.csv', '../Dataset/SA11/F07_SA11_R05.csv', '../Dataset/SA11/F08_SA11_R01.csv', '../Dataset/SA11/F08_SA11_R02.csv', '../Dataset/SA11/F08_SA11_R03.csv', '../Dataset/SA11/F08_SA11_R04.csv', '../Dataset/SA11/F08_SA11_R05.csv', '../Dataset/SA11/F09_SA11_R01.csv', '../Dataset/SA11/F09_SA11_R02.csv', '../Dataset/SA11/F09_SA11_R03.csv', '../Dataset/SA11/F09_SA11_R04.csv', '../Dataset/SA11/F09_SA11_R05.csv', '../Dataset/SA11/F10_SA11_R01.csv', '../Dataset/SA11/F10_SA11_R02.csv', '../Dataset/SA11/F10_SA11_R03.csv', '../Dataset/SA11/F10_SA11_R04.csv', '../Dataset/SA11/F10_SA11_R05.csv', '../Dataset/SA11/F11_SA11_R01.csv', '../Dataset/SA11/F11_SA11_R02.csv', '../Dataset/SA11/F11_SA11_R03.csv', '../Dataset/SA11/F11_SA11_R04.csv', '../Dataset/SA11/F11_SA11_R05.csv', '../Dataset/SA11/F12_SA11_R01.csv', '../Dataset/SA11/F12_SA11_R02.csv', '../Dataset/SA11/F12_SA11_R03.csv', '../Dataset/SA11/F12_SA11_R04.csv', '../Dataset/SA11/F12_SA11_R05.csv', '../Dataset/SA11/F13_SA11_R01.csv', '../Dataset/SA11/F13_SA11_R02.csv', '../Dataset/SA11/F13_SA11_R03.csv', '../Dataset/SA11/F13_SA11_R04.csv', '../Dataset/SA11/F13_SA11_R05.csv', '../Dataset/SA11/F14_SA11_R01.csv', '../Dataset/SA11/F14_SA11_R02.csv', '../Dataset/SA11/F14_SA11_R03.csv', '../Dataset/SA11/F14_SA11_R04.csv', '../Dataset/SA11/F14_SA11_R05.csv', '../Dataset/SA11/F15_SA11_R01.csv', '../Dataset/SA11/F15_SA11_R02.csv', '../Dataset/SA11/F15_SA11_R03.csv', '../Dataset/SA11/F15_SA11_R04.csv', '../Dataset/SA11/F15_SA11_R05.csv']

In [25]:
list = []
final_SA11_F = pd.DataFrame(list)

for path in SA11_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA11_F = final_SA11_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA11_F.shape
target_col = row * [1]
final_SA11_F.loc[:,'target'] = target_col

final_SA11_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,160.0,170.0,174.0,184.0,186.0,189.0,188.0,189.0,194.0,192.0,...,98.0,97.0,83.0,70.0,79.0,73.0,69.0,54.0,50.0,1
0,294.0,305.0,310.0,321.0,328.0,344.0,353.0,361.0,377.0,384.0,...,120.0,124.0,131.0,134.0,142.0,141.0,139.0,131.0,126.0,1
0,159.0,161.0,159.0,166.0,179.0,178.0,190.0,194.0,207.0,221.0,...,117.0,119.0,121.0,112.0,107.0,98.0,85.0,77.0,70.0,1
0,205.0,198.0,195.0,190.0,191.0,189.0,194.0,204.0,214.0,227.0,...,104.0,115.0,111.0,98.0,81.0,74.0,89.0,103.0,119.0,1
0,407.0,418.0,422.0,418.0,408.0,391.0,372.0,367.0,361.0,355.0,...,127.0,116.0,94.0,76.0,57.0,45.0,55.0,59.0,77.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,259.0,264.0,260.0,256.0,268.0,255.0,263.0,258.0,254.0,257.0,...,76.0,67.0,70.0,72.0,75.0,73.0,66.0,50.0,55.0,1
0,282.0,285.0,291.0,294.0,297.0,302.0,296.0,297.0,302.0,303.0,...,79.0,78.0,80.0,82.0,84.0,86.0,75.0,75.0,74.0,1
0,258.0,259.0,250.0,257.0,258.0,259.0,258.0,258.0,258.0,258.0,...,269.0,261.0,265.0,265.0,263.0,264.0,260.0,258.0,264.0,1
0,257.0,260.0,263.0,261.0,269.0,262.0,263.0,267.0,264.0,267.0,...,141.0,146.0,147.0,140.0,143.0,152.0,151.0,134.0,127.0,1
0,275.0,270.0,266.0,269.0,267.0,289.0,254.0,262.0,261.0,254.0,...,104.0,95.0,79.0,75.0,72.0,83.0,90.0,98.0,93.0,1

# SA12

In [26]:
SA12_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA12/F01_SA12_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA12_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA12_F_paths.append(tmp)
            
print(SA12_F_paths)

['../Dataset/SA12/F01_SA12_R01.csv', '../Dataset/SA12/F01_SA12_R02.csv', '../Dataset/SA12/F01_SA12_R03.csv', '../Dataset/SA12/F01_SA12_R04.csv', '../Dataset/SA12/F01_SA12_R05.csv', '../Dataset/SA12/F02_SA12_R01.csv', '../Dataset/SA12/F02_SA12_R02.csv', '../Dataset/SA12/F02_SA12_R03.csv', '../Dataset/SA12/F02_SA12_R04.csv', '../Dataset/SA12/F02_SA12_R05.csv', '../Dataset/SA12/F03_SA12_R01.csv', '../Dataset/SA12/F03_SA12_R02.csv', '../Dataset/SA12/F03_SA12_R03.csv', '../Dataset/SA12/F03_SA12_R04.csv', '../Dataset/SA12/F03_SA12_R05.csv', '../Dataset/SA12/F04_SA12_R01.csv', '../Dataset/SA12/F04_SA12_R02.csv', '../Dataset/SA12/F04_SA12_R03.csv', '../Dataset/SA12/F04_SA12_R04.csv', '../Dataset/SA12/F04_SA12_R05.csv', '../Dataset/SA12/F05_SA12_R01.csv', '../Dataset/SA12/F05_SA12_R02.csv', '../Dataset/SA12/F05_SA12_R03.csv', '../Dataset/SA12/F05_SA12_R04.csv', '../Dataset/SA12/F05_SA12_R05.csv', '../Dataset/SA12/F06_SA12_R01.csv', '../Dataset/SA12/F06_SA12_R02.csv', '../Dataset/SA12/F06_SA12_R03.csv', '../Dataset/SA12/F06_SA12_R04.csv', '../Dataset/SA12/F06_SA12_R05.csv', '../Dataset/SA12/F07_SA12_R01.csv', '../Dataset/SA12/F07_SA12_R02.csv', '../Dataset/SA12/F07_SA12_R03.csv', '../Dataset/SA12/F07_SA12_R04.csv', '../Dataset/SA12/F07_SA12_R05.csv', '../Dataset/SA12/F08_SA12_R01.csv', '../Dataset/SA12/F08_SA12_R02.csv', '../Dataset/SA12/F08_SA12_R03.csv', '../Dataset/SA12/F08_SA12_R04.csv', '../Dataset/SA12/F08_SA12_R05.csv', '../Dataset/SA12/F09_SA12_R01.csv', '../Dataset/SA12/F09_SA12_R02.csv', '../Dataset/SA12/F09_SA12_R03.csv', '../Dataset/SA12/F09_SA12_R04.csv', '../Dataset/SA12/F09_SA12_R05.csv', '../Dataset/SA12/F10_SA12_R01.csv', '../Dataset/SA12/F10_SA12_R02.csv', '../Dataset/SA12/F10_SA12_R03.csv', '../Dataset/SA12/F10_SA12_R04.csv', '../Dataset/SA12/F10_SA12_R05.csv', '../Dataset/SA12/F11_SA12_R01.csv', '../Dataset/SA12/F11_SA12_R02.csv', '../Dataset/SA12/F11_SA12_R03.csv', '../Dataset/SA12/F11_SA12_R04.csv', '../Dataset/SA12/F11_SA12_R05.csv', '../Dataset/SA12/F12_SA12_R01.csv', '../Dataset/SA12/F12_SA12_R02.csv', '../Dataset/SA12/F12_SA12_R03.csv', '../Dataset/SA12/F12_SA12_R04.csv', '../Dataset/SA12/F12_SA12_R05.csv', '../Dataset/SA12/F13_SA12_R01.csv', '../Dataset/SA12/F13_SA12_R02.csv', '../Dataset/SA12/F13_SA12_R03.csv', '../Dataset/SA12/F13_SA12_R04.csv', '../Dataset/SA12/F13_SA12_R05.csv', '../Dataset/SA12/F14_SA12_R01.csv', '../Dataset/SA12/F14_SA12_R02.csv', '../Dataset/SA12/F14_SA12_R03.csv', '../Dataset/SA12/F14_SA12_R04.csv', '../Dataset/SA12/F14_SA12_R05.csv', '../Dataset/SA12/F15_SA12_R01.csv', '../Dataset/SA12/F15_SA12_R02.csv', '../Dataset/SA12/F15_SA12_R03.csv', '../Dataset/SA12/F15_SA12_R04.csv', '../Dataset/SA12/F15_SA12_R05.csv']

In [27]:
list = []
final_SA12_F = pd.DataFrame(list)

for path in SA12_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA12_F = final_SA12_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA12_F.shape
target_col = row * [1]
final_SA12_F.loc[:,'target'] = target_col

final_SA12_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,215.0,206.0,200.0,196.0,186.0,188.0,181.0,179.0,180.0,177.0,...,223.0,218.0,207.0,200.0,201.0,201.0,204.0,211.0,204.0,1
0,235.0,224.0,214.0,207.0,203.0,197.0,190.0,190.0,192.0,190.0,...,238.0,222.0,176.0,101.0,117.0,137.0,155.0,183.0,211.0,1
0,211.0,211.0,209.0,210.0,209.0,208.0,208.0,209.0,210.0,213.0,...,1104.0,1048.0,933.0,754.0,612.0,536.0,470.0,435.0,406.0,1
0,222.0,220.0,220.0,220.0,225.0,229.0,236.0,240.0,249.0,249.0,...,347.0,480.0,686.0,892.0,1047.0,1157.0,1312.0,1460.0,1477.0,1
0,243.0,261.0,273.0,291.0,298.0,301.0,296.0,290.0,283.0,273.0,...,146.0,131.0,121.0,101.0,91.0,83.0,68.0,64.0,59.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,242.0,245.0,245.0,248.0,246.0,247.0,248.0,241.0,249.0,251.0,...,185.0,151.0,126.0,109.0,91.0,83.0,69.0,60.0,56.0,1
0,243.0,239.0,242.0,249.0,241.0,244.0,246.0,245.0,242.0,246.0,...,229.0,221.0,213.0,201.0,197.0,192.0,196.0,200.0,204.0,1
0,252.0,253.0,251.0,253.0,253.0,253.0,253.0,255.0,254.0,250.0,...,152.0,147.0,145.0,151.0,152.0,156.0,159.0,154.0,158.0,1
0,244.0,244.0,243.0,245.0,246.0,245.0,247.0,249.0,244.0,249.0,...,173.0,169.0,164.0,161.0,157.0,156.0,160.0,155.0,151.0,1
0,247.0,250.0,247.0,247.0,251.0,250.0,249.0,245.0,244.0,239.0,...,194.0,167.0,150.0,127.0,121.0,102.0,98.0,93.0,80.0,1

# SA13

In [28]:
SA13_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA13/F01_SA13_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA13_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA13_F_paths.append(tmp)
            
print(SA13_F_paths)

['../Dataset/SA13/F01_SA13_R01.csv', '../Dataset/SA13/F01_SA13_R02.csv', '../Dataset/SA13/F01_SA13_R03.csv', '../Dataset/SA13/F01_SA13_R04.csv', '../Dataset/SA13/F01_SA13_R05.csv', '../Dataset/SA13/F02_SA13_R01.csv', '../Dataset/SA13/F02_SA13_R02.csv', '../Dataset/SA13/F02_SA13_R03.csv', '../Dataset/SA13/F02_SA13_R04.csv', '../Dataset/SA13/F02_SA13_R05.csv', '../Dataset/SA13/F03_SA13_R01.csv', '../Dataset/SA13/F03_SA13_R02.csv', '../Dataset/SA13/F03_SA13_R03.csv', '../Dataset/SA13/F03_SA13_R04.csv', '../Dataset/SA13/F03_SA13_R05.csv', '../Dataset/SA13/F04_SA13_R01.csv', '../Dataset/SA13/F04_SA13_R02.csv', '../Dataset/SA13/F04_SA13_R03.csv', '../Dataset/SA13/F04_SA13_R04.csv', '../Dataset/SA13/F04_SA13_R05.csv', '../Dataset/SA13/F05_SA13_R01.csv', '../Dataset/SA13/F05_SA13_R02.csv', '../Dataset/SA13/F05_SA13_R03.csv', '../Dataset/SA13/F05_SA13_R04.csv', '../Dataset/SA13/F05_SA13_R05.csv', '../Dataset/SA13/F06_SA13_R01.csv', '../Dataset/SA13/F06_SA13_R02.csv', '../Dataset/SA13/F06_SA13_R03.csv', '../Dataset/SA13/F06_SA13_R04.csv', '../Dataset/SA13/F06_SA13_R05.csv', '../Dataset/SA13/F07_SA13_R01.csv', '../Dataset/SA13/F07_SA13_R02.csv', '../Dataset/SA13/F07_SA13_R03.csv', '../Dataset/SA13/F07_SA13_R04.csv', '../Dataset/SA13/F07_SA13_R05.csv', '../Dataset/SA13/F08_SA13_R01.csv', '../Dataset/SA13/F08_SA13_R02.csv', '../Dataset/SA13/F08_SA13_R03.csv', '../Dataset/SA13/F08_SA13_R04.csv', '../Dataset/SA13/F08_SA13_R05.csv', '../Dataset/SA13/F09_SA13_R01.csv', '../Dataset/SA13/F09_SA13_R02.csv', '../Dataset/SA13/F09_SA13_R03.csv', '../Dataset/SA13/F09_SA13_R04.csv', '../Dataset/SA13/F09_SA13_R05.csv', '../Dataset/SA13/F10_SA13_R01.csv', '../Dataset/SA13/F10_SA13_R02.csv', '../Dataset/SA13/F10_SA13_R03.csv', '../Dataset/SA13/F10_SA13_R04.csv', '../Dataset/SA13/F10_SA13_R05.csv', '../Dataset/SA13/F11_SA13_R01.csv', '../Dataset/SA13/F11_SA13_R02.csv', '../Dataset/SA13/F11_SA13_R03.csv', '../Dataset/SA13/F11_SA13_R04.csv', '../Dataset/SA13/F11_SA13_R05.csv', '../Dataset/SA13/F12_SA13_R01.csv', '../Dataset/SA13/F12_SA13_R02.csv', '../Dataset/SA13/F12_SA13_R03.csv', '../Dataset/SA13/F12_SA13_R04.csv', '../Dataset/SA13/F12_SA13_R05.csv', '../Dataset/SA13/F13_SA13_R01.csv', '../Dataset/SA13/F13_SA13_R02.csv', '../Dataset/SA13/F13_SA13_R03.csv', '../Dataset/SA13/F13_SA13_R04.csv', '../Dataset/SA13/F13_SA13_R05.csv', '../Dataset/SA13/F14_SA13_R01.csv', '../Dataset/SA13/F14_SA13_R02.csv', '../Dataset/SA13/F14_SA13_R03.csv', '../Dataset/SA13/F14_SA13_R04.csv', '../Dataset/SA13/F14_SA13_R05.csv', '../Dataset/SA13/F15_SA13_R01.csv', '../Dataset/SA13/F15_SA13_R02.csv', '../Dataset/SA13/F15_SA13_R03.csv', '../Dataset/SA13/F15_SA13_R04.csv', '../Dataset/SA13/F15_SA13_R05.csv']

In [29]:
list = []
final_SA13_F = pd.DataFrame(list)

for path in SA13_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA13_F = final_SA13_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA13_F.shape
target_col = row * [1]
final_SA13_F.loc[:,'target'] = target_col

final_SA13_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,242.0,241.0,240.0,235.0,231.0,231.0,229.0,228.0,225.0,222.0,...,194.0,198.0,200.0,205.0,234.0,266.0,303.0,322.0,341.0,1
0,257.0,249.0,242.0,233.0,226.0,216.0,209.0,204.0,200.0,195.0,...,224.0,224.0,221.0,221.0,222.0,210.0,216.0,205.0,195.0,1
0,250.0,251.0,245.0,245.0,239.0,240.0,238.0,244.0,245.0,247.0,...,184.0,171.0,184.0,199.0,201.0,191.0,188.0,202.0,212.0,1
0,315.0,317.0,316.0,307.0,303.0,289.0,280.0,263.0,257.0,244.0,...,178.0,183.0,191.0,195.0,198.0,200.0,198.0,200.0,197.0,1
0,212.0,220.0,227.0,231.0,239.0,241.0,245.0,246.0,240.0,232.0,...,211.0,218.0,220.0,222.0,217.0,211.0,205.0,198.0,200.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,237.0,239.0,235.0,235.0,234.0,233.0,237.0,233.0,235.0,233.0,...,227.0,223.0,229.0,224.0,225.0,225.0,222.0,222.0,219.0,1
0,224.0,224.0,227.0,225.0,224.0,223.0,221.0,221.0,221.0,221.0,...,101.0,93.0,127.0,186.0,277.0,483.0,787.0,1008.0,1260.0,1
0,231.0,228.0,233.0,230.0,233.0,231.0,229.0,228.0,231.0,228.0,...,217.0,218.0,221.0,224.0,223.0,223.0,221.0,225.0,225.0,1
0,231.0,233.0,230.0,231.0,233.0,233.0,230.0,231.0,233.0,230.0,...,225.0,225.0,227.0,223.0,226.0,228.0,227.0,226.0,224.0,1
0,237.0,235.0,240.0,239.0,236.0,239.0,240.0,236.0,237.0,242.0,...,212.0,213.0,214.0,214.0,215.0,220.0,216.0,222.0,223.0,1

# SA14

In [30]:
SA14_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA14/F01_SA14_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA14_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA14_F_paths.append(tmp)
            
print(SA14_F_paths)

['../Dataset/SA14/F01_SA14_R01.csv', '../Dataset/SA14/F01_SA14_R02.csv', '../Dataset/SA14/F01_SA14_R03.csv', '../Dataset/SA14/F01_SA14_R04.csv', '../Dataset/SA14/F01_SA14_R05.csv', '../Dataset/SA14/F02_SA14_R01.csv', '../Dataset/SA14/F02_SA14_R02.csv', '../Dataset/SA14/F02_SA14_R03.csv', '../Dataset/SA14/F02_SA14_R04.csv', '../Dataset/SA14/F02_SA14_R05.csv', '../Dataset/SA14/F03_SA14_R01.csv', '../Dataset/SA14/F03_SA14_R02.csv', '../Dataset/SA14/F03_SA14_R03.csv', '../Dataset/SA14/F03_SA14_R04.csv', '../Dataset/SA14/F03_SA14_R05.csv', '../Dataset/SA14/F04_SA14_R01.csv', '../Dataset/SA14/F04_SA14_R02.csv', '../Dataset/SA14/F04_SA14_R03.csv', '../Dataset/SA14/F04_SA14_R04.csv', '../Dataset/SA14/F04_SA14_R05.csv', '../Dataset/SA14/F05_SA14_R01.csv', '../Dataset/SA14/F05_SA14_R02.csv', '../Dataset/SA14/F05_SA14_R03.csv', '../Dataset/SA14/F05_SA14_R04.csv', '../Dataset/SA14/F05_SA14_R05.csv', '../Dataset/SA14/F06_SA14_R01.csv', '../Dataset/SA14/F06_SA14_R02.csv', '../Dataset/SA14/F06_SA14_R03.csv', '../Dataset/SA14/F06_SA14_R04.csv', '../Dataset/SA14/F06_SA14_R05.csv', '../Dataset/SA14/F07_SA14_R01.csv', '../Dataset/SA14/F07_SA14_R02.csv', '../Dataset/SA14/F07_SA14_R03.csv', '../Dataset/SA14/F07_SA14_R04.csv', '../Dataset/SA14/F07_SA14_R05.csv', '../Dataset/SA14/F08_SA14_R01.csv', '../Dataset/SA14/F08_SA14_R02.csv', '../Dataset/SA14/F08_SA14_R03.csv', '../Dataset/SA14/F08_SA14_R04.csv', '../Dataset/SA14/F08_SA14_R05.csv', '../Dataset/SA14/F09_SA14_R01.csv', '../Dataset/SA14/F09_SA14_R02.csv', '../Dataset/SA14/F09_SA14_R03.csv', '../Dataset/SA14/F09_SA14_R04.csv', '../Dataset/SA14/F09_SA14_R05.csv', '../Dataset/SA14/F10_SA14_R01.csv', '../Dataset/SA14/F10_SA14_R02.csv', '../Dataset/SA14/F10_SA14_R03.csv', '../Dataset/SA14/F10_SA14_R04.csv', '../Dataset/SA14/F10_SA14_R05.csv', '../Dataset/SA14/F11_SA14_R01.csv', '../Dataset/SA14/F11_SA14_R02.csv', '../Dataset/SA14/F11_SA14_R03.csv', '../Dataset/SA14/F11_SA14_R04.csv', '../Dataset/SA14/F11_SA14_R05.csv', '../Dataset/SA14/F12_SA14_R01.csv', '../Dataset/SA14/F12_SA14_R02.csv', '../Dataset/SA14/F12_SA14_R03.csv', '../Dataset/SA14/F12_SA14_R04.csv', '../Dataset/SA14/F12_SA14_R05.csv', '../Dataset/SA14/F13_SA14_R01.csv', '../Dataset/SA14/F13_SA14_R02.csv', '../Dataset/SA14/F13_SA14_R03.csv', '../Dataset/SA14/F13_SA14_R04.csv', '../Dataset/SA14/F13_SA14_R05.csv', '../Dataset/SA14/F14_SA14_R01.csv', '../Dataset/SA14/F14_SA14_R02.csv', '../Dataset/SA14/F14_SA14_R03.csv', '../Dataset/SA14/F14_SA14_R04.csv', '../Dataset/SA14/F14_SA14_R05.csv', '../Dataset/SA14/F15_SA14_R01.csv', '../Dataset/SA14/F15_SA14_R02.csv', '../Dataset/SA14/F15_SA14_R03.csv', '../Dataset/SA14/F15_SA14_R04.csv', '../Dataset/SA14/F15_SA14_R05.csv']

In [31]:
list = []
final_SA14_F = pd.DataFrame(list)

for path in SA14_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA14_F = final_SA14_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA14_F.shape
target_col = row * [1]
final_SA14_F.loc[:,'target'] = target_col

final_SA14_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,371.0,360.0,355.0,356.0,357.0,353.0,344.0,333.0,322.0,303.0,...,101.0,91.0,96.0,117.0,134.0,164.0,193.0,211.0,223.0,1
0,267.0,261.0,263.0,262.0,264.0,259.0,259.0,256.0,253.0,248.0,...,265.0,263.0,267.0,272.0,279.0,285.0,295.0,297.0,303.0,1
0,254.0,247.0,242.0,238.0,231.0,230.0,226.0,222.0,217.0,218.0,...,232.0,220.0,216.0,214.0,222.0,218.0,214.0,208.0,188.0,1
0,396.0,387.0,372.0,354.0,341.0,322.0,298.0,281.0,271.0,266.0,...,118.0,117.0,135.0,138.0,143.0,136.0,142.0,143.0,140.0,1
0,383.0,397.0,405.0,402.0,394.0,388.0,381.0,358.0,332.0,307.0,...,148.0,148.0,143.0,132.0,128.0,115.0,101.0,79.0,67.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,271.0,270.0,268.0,270.0,273.0,266.0,270.0,268.0,261.0,273.0,...,239.0,321.0,277.0,373.0,267.0,182.0,184.0,176.0,161.0,1
0,277.0,274.0,274.0,275.0,271.0,283.0,277.0,276.0,271.0,274.0,...,226.0,219.0,223.0,224.0,227.0,231.0,235.0,241.0,247.0,1
0,252.0,251.0,253.0,252.0,250.0,253.0,252.0,253.0,253.0,251.0,...,251.0,252.0,252.0,251.0,253.0,249.0,254.0,252.0,253.0,1
0,275.0,271.0,274.0,276.0,275.0,274.0,276.0,279.0,276.0,276.0,...,276.0,277.0,275.0,273.0,270.0,266.0,274.0,272.0,273.0,1
0,272.0,276.0,273.0,276.0,270.0,275.0,272.0,273.0,271.0,272.0,...,281.0,279.0,273.0,275.0,276.0,273.0,271.0,270.0,272.0,1

# SA15

In [32]:
SA15_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA15/F01_SA15_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA15_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA15_F_paths.append(tmp)
            
print(SA15_F_paths)

['../Dataset/SA15/F01_SA15_R01.csv', '../Dataset/SA15/F01_SA15_R02.csv', '../Dataset/SA15/F01_SA15_R03.csv', '../Dataset/SA15/F01_SA15_R04.csv', '../Dataset/SA15/F01_SA15_R05.csv', '../Dataset/SA15/F02_SA15_R01.csv', '../Dataset/SA15/F02_SA15_R02.csv', '../Dataset/SA15/F02_SA15_R03.csv', '../Dataset/SA15/F02_SA15_R04.csv', '../Dataset/SA15/F02_SA15_R05.csv', '../Dataset/SA15/F03_SA15_R01.csv', '../Dataset/SA15/F03_SA15_R02.csv', '../Dataset/SA15/F03_SA15_R03.csv', '../Dataset/SA15/F03_SA15_R04.csv', '../Dataset/SA15/F03_SA15_R05.csv', '../Dataset/SA15/F04_SA15_R01.csv', '../Dataset/SA15/F04_SA15_R02.csv', '../Dataset/SA15/F04_SA15_R03.csv', '../Dataset/SA15/F04_SA15_R04.csv', '../Dataset/SA15/F04_SA15_R05.csv', '../Dataset/SA15/F05_SA15_R01.csv', '../Dataset/SA15/F05_SA15_R02.csv', '../Dataset/SA15/F05_SA15_R03.csv', '../Dataset/SA15/F05_SA15_R04.csv', '../Dataset/SA15/F05_SA15_R05.csv', '../Dataset/SA15/F06_SA15_R01.csv', '../Dataset/SA15/F06_SA15_R02.csv', '../Dataset/SA15/F06_SA15_R03.csv', '../Dataset/SA15/F06_SA15_R04.csv', '../Dataset/SA15/F06_SA15_R05.csv', '../Dataset/SA15/F07_SA15_R01.csv', '../Dataset/SA15/F07_SA15_R02.csv', '../Dataset/SA15/F07_SA15_R03.csv', '../Dataset/SA15/F07_SA15_R04.csv', '../Dataset/SA15/F07_SA15_R05.csv', '../Dataset/SA15/F08_SA15_R01.csv', '../Dataset/SA15/F08_SA15_R02.csv', '../Dataset/SA15/F08_SA15_R03.csv', '../Dataset/SA15/F08_SA15_R04.csv', '../Dataset/SA15/F08_SA15_R05.csv', '../Dataset/SA15/F09_SA15_R01.csv', '../Dataset/SA15/F09_SA15_R02.csv', '../Dataset/SA15/F09_SA15_R03.csv', '../Dataset/SA15/F09_SA15_R04.csv', '../Dataset/SA15/F09_SA15_R05.csv', '../Dataset/SA15/F10_SA15_R01.csv', '../Dataset/SA15/F10_SA15_R02.csv', '../Dataset/SA15/F10_SA15_R03.csv', '../Dataset/SA15/F10_SA15_R04.csv', '../Dataset/SA15/F10_SA15_R05.csv', '../Dataset/SA15/F11_SA15_R01.csv', '../Dataset/SA15/F11_SA15_R02.csv', '../Dataset/SA15/F11_SA15_R03.csv', '../Dataset/SA15/F11_SA15_R04.csv', '../Dataset/SA15/F11_SA15_R05.csv', '../Dataset/SA15/F12_SA15_R01.csv', '../Dataset/SA15/F12_SA15_R02.csv', '../Dataset/SA15/F12_SA15_R03.csv', '../Dataset/SA15/F12_SA15_R04.csv', '../Dataset/SA15/F12_SA15_R05.csv', '../Dataset/SA15/F13_SA15_R01.csv', '../Dataset/SA15/F13_SA15_R02.csv', '../Dataset/SA15/F13_SA15_R03.csv', '../Dataset/SA15/F13_SA15_R04.csv', '../Dataset/SA15/F13_SA15_R05.csv', '../Dataset/SA15/F14_SA15_R01.csv', '../Dataset/SA15/F14_SA15_R02.csv', '../Dataset/SA15/F14_SA15_R03.csv', '../Dataset/SA15/F14_SA15_R04.csv', '../Dataset/SA15/F14_SA15_R05.csv', '../Dataset/SA15/F15_SA15_R01.csv', '../Dataset/SA15/F15_SA15_R02.csv', '../Dataset/SA15/F15_SA15_R03.csv', '../Dataset/SA15/F15_SA15_R04.csv', '../Dataset/SA15/F15_SA15_R05.csv']

In [33]:
list = []
final_SA15_F = pd.DataFrame(list)

for path in SA15_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA15_F = final_SA15_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA15_F.shape
target_col = row * [1]
final_SA15_F.loc[:,'target'] = target_col

final_SA15_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,224.0,226.0,231.0,232.0,243.0,247.0,261.0,259.0,264.0,266.0,...,189.0,153.0,84.0,24.0,26.0,68.0,111.0,135.0,185.0,1
0,245.0,243.0,237.0,241.0,246.0,243.0,245.0,245.0,246.0,252.0,...,250.0,262.0,276.0,290.0,293.0,291.0,282.0,266.0,251.0,1
0,286.0,276.0,270.0,261.0,260.0,257.0,256.0,249.0,244.0,242.0,...,193.0,195.0,214.0,230.0,240.0,246.0,251.0,248.0,237.0,1
0,250.0,258.0,259.0,268.0,270.0,274.0,268.0,280.0,283.0,288.0,...,270.0,249.0,231.0,226.0,227.0,216.0,209.0,196.0,198.0,1
0,210.0,212.0,214.0,216.0,218.0,224.0,228.0,227.0,227.0,231.0,...,155.0,139.0,151.0,166.0,176.0,194.0,204.0,203.0,210.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,269.0,269.0,270.0,269.0,270.0,269.0,268.0,270.0,270.0,270.0,...,125.0,140.0,173.0,224.0,255.0,268.0,292.0,298.0,292.0,1
0,268.0,266.0,266.0,267.0,267.0,265.0,267.0,267.0,270.0,269.0,...,166.0,170.0,178.0,186.0,193.0,212.0,210.0,220.0,231.0,1
0,265.0,268.0,265.0,266.0,267.0,270.0,264.0,265.0,266.0,268.0,...,264.0,264.0,266.0,268.0,268.0,261.0,269.0,269.0,264.0,1
0,266.0,264.0,265.0,264.0,262.0,262.0,265.0,264.0,266.0,267.0,...,178.0,177.0,165.0,161.0,151.0,168.0,154.0,150.0,133.0,1
0,268.0,268.0,271.0,268.0,270.0,272.0,272.0,271.0,271.0,267.0,...,175.0,167.0,174.0,168.0,181.0,183.0,193.0,237.0,219.0,1

# SA16

In [34]:
SA16_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA16/F01_SA16_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA16_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA16_F_paths.append(tmp)
            
print(SA16_F_paths)

['../Dataset/SA16/F01_SA16_R01.csv', '../Dataset/SA16/F01_SA16_R02.csv', '../Dataset/SA16/F01_SA16_R03.csv', '../Dataset/SA16/F01_SA16_R04.csv', '../Dataset/SA16/F01_SA16_R05.csv', '../Dataset/SA16/F02_SA16_R01.csv', '../Dataset/SA16/F02_SA16_R02.csv', '../Dataset/SA16/F02_SA16_R03.csv', '../Dataset/SA16/F02_SA16_R04.csv', '../Dataset/SA16/F02_SA16_R05.csv', '../Dataset/SA16/F03_SA16_R01.csv', '../Dataset/SA16/F03_SA16_R02.csv', '../Dataset/SA16/F03_SA16_R03.csv', '../Dataset/SA16/F03_SA16_R04.csv', '../Dataset/SA16/F03_SA16_R05.csv', '../Dataset/SA16/F04_SA16_R01.csv', '../Dataset/SA16/F04_SA16_R02.csv', '../Dataset/SA16/F04_SA16_R03.csv', '../Dataset/SA16/F04_SA16_R04.csv', '../Dataset/SA16/F04_SA16_R05.csv', '../Dataset/SA16/F05_SA16_R01.csv', '../Dataset/SA16/F05_SA16_R02.csv', '../Dataset/SA16/F05_SA16_R03.csv', '../Dataset/SA16/F05_SA16_R04.csv', '../Dataset/SA16/F05_SA16_R05.csv', '../Dataset/SA16/F06_SA16_R01.csv', '../Dataset/SA16/F06_SA16_R02.csv', '../Dataset/SA16/F06_SA16_R03.csv', '../Dataset/SA16/F06_SA16_R04.csv', '../Dataset/SA16/F06_SA16_R05.csv', '../Dataset/SA16/F07_SA16_R01.csv', '../Dataset/SA16/F07_SA16_R02.csv', '../Dataset/SA16/F07_SA16_R03.csv', '../Dataset/SA16/F07_SA16_R04.csv', '../Dataset/SA16/F07_SA16_R05.csv', '../Dataset/SA16/F08_SA16_R01.csv', '../Dataset/SA16/F08_SA16_R02.csv', '../Dataset/SA16/F08_SA16_R03.csv', '../Dataset/SA16/F08_SA16_R04.csv', '../Dataset/SA16/F08_SA16_R05.csv', '../Dataset/SA16/F09_SA16_R01.csv', '../Dataset/SA16/F09_SA16_R02.csv', '../Dataset/SA16/F09_SA16_R03.csv', '../Dataset/SA16/F09_SA16_R04.csv', '../Dataset/SA16/F09_SA16_R05.csv', '../Dataset/SA16/F10_SA16_R01.csv', '../Dataset/SA16/F10_SA16_R02.csv', '../Dataset/SA16/F10_SA16_R03.csv', '../Dataset/SA16/F10_SA16_R04.csv', '../Dataset/SA16/F10_SA16_R05.csv', '../Dataset/SA16/F11_SA16_R01.csv', '../Dataset/SA16/F11_SA16_R02.csv', '../Dataset/SA16/F11_SA16_R03.csv', '../Dataset/SA16/F11_SA16_R04.csv', '../Dataset/SA16/F11_SA16_R05.csv', '../Dataset/SA16/F12_SA16_R01.csv', '../Dataset/SA16/F12_SA16_R02.csv', '../Dataset/SA16/F12_SA16_R03.csv', '../Dataset/SA16/F12_SA16_R04.csv', '../Dataset/SA16/F12_SA16_R05.csv', '../Dataset/SA16/F13_SA16_R01.csv', '../Dataset/SA16/F13_SA16_R02.csv', '../Dataset/SA16/F13_SA16_R03.csv', '../Dataset/SA16/F13_SA16_R04.csv', '../Dataset/SA16/F13_SA16_R05.csv', '../Dataset/SA16/F14_SA16_R01.csv', '../Dataset/SA16/F14_SA16_R02.csv', '../Dataset/SA16/F14_SA16_R03.csv', '../Dataset/SA16/F14_SA16_R04.csv', '../Dataset/SA16/F14_SA16_R05.csv', '../Dataset/SA16/F15_SA16_R01.csv', '../Dataset/SA16/F15_SA16_R02.csv', '../Dataset/SA16/F15_SA16_R03.csv', '../Dataset/SA16/F15_SA16_R04.csv', '../Dataset/SA16/F15_SA16_R05.csv']

In [35]:
list = []
final_SA16_F = pd.DataFrame(list)

for path in SA16_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA16_F = final_SA16_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA16_F.shape
target_col = row * [1]
final_SA16_F.loc[:,'target'] = target_col

final_SA16_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,328.0,336.0,345.0,357.0,359.0,360.0,354.0,343.0,333.0,317.0,...,209.0,219.0,232.0,265.0,298.0,317.0,352.0,355.0,326.0,1
0,265.0,256.0,248.0,242.0,231.0,223.0,214.0,214.0,206.0,200.0,...,208.0,201.0,204.0,195.0,188.0,164.0,165.0,143.0,143.0,1
0,310.0,303.0,305.0,293.0,286.0,278.0,269.0,264.0,257.0,250.0,...,192.0,189.0,185.0,185.0,189.0,193.0,199.0,199.0,199.0,1
0,276.0,276.0,267.0,264.0,258.0,255.0,246.0,244.0,234.0,234.0,...,30.0,69.0,74.0,119.0,156.0,173.0,178.0,180.0,170.0,1
0,336.0,337.0,340.0,341.0,336.0,333.0,323.0,318.0,313.0,298.0,...,47.0,38.0,30.0,33.0,67.0,106.0,143.0,172.0,194.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,270.0,270.0,267.0,265.0,264.0,263.0,256.0,254.0,255.0,245.0,...,228.0,222.0,219.0,215.0,214.0,214.0,206.0,200.0,199.0,1
0,255.0,259.0,291.0,262.0,253.0,253.0,256.0,244.0,253.0,250.0,...,215.0,210.0,206.0,204.0,197.0,204.0,209.0,206.0,204.0,1
0,256.0,256.0,258.0,254.0,255.0,253.0,255.0,254.0,255.0,255.0,...,213.0,214.0,212.0,213.0,211.0,213.0,208.0,205.0,198.0,1
0,247.0,248.0,250.0,242.0,246.0,245.0,245.0,252.0,253.0,254.0,...,93.0,111.0,134.0,154.0,170.0,198.0,234.0,261.0,307.0,1
0,256.0,265.0,252.0,255.0,251.0,250.0,246.0,247.0,250.0,250.0,...,234.0,234.0,240.0,250.0,262.0,259.0,253.0,251.0,251.0,1

# SA17

In [36]:
SA17_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA17/F01_SA17_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA17_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA17_F_paths.append(tmp)
            
print(SA17_F_paths)

['../Dataset/SA17/F01_SA17_R01.csv', '../Dataset/SA17/F01_SA17_R02.csv', '../Dataset/SA17/F01_SA17_R03.csv', '../Dataset/SA17/F01_SA17_R04.csv', '../Dataset/SA17/F01_SA17_R05.csv', '../Dataset/SA17/F02_SA17_R01.csv', '../Dataset/SA17/F02_SA17_R02.csv', '../Dataset/SA17/F02_SA17_R03.csv', '../Dataset/SA17/F02_SA17_R04.csv', '../Dataset/SA17/F02_SA17_R05.csv', '../Dataset/SA17/F03_SA17_R01.csv', '../Dataset/SA17/F03_SA17_R02.csv', '../Dataset/SA17/F03_SA17_R03.csv', '../Dataset/SA17/F03_SA17_R04.csv', '../Dataset/SA17/F03_SA17_R05.csv', '../Dataset/SA17/F04_SA17_R01.csv', '../Dataset/SA17/F04_SA17_R02.csv', '../Dataset/SA17/F04_SA17_R03.csv', '../Dataset/SA17/F04_SA17_R04.csv', '../Dataset/SA17/F04_SA17_R05.csv', '../Dataset/SA17/F05_SA17_R01.csv', '../Dataset/SA17/F05_SA17_R02.csv', '../Dataset/SA17/F05_SA17_R03.csv', '../Dataset/SA17/F05_SA17_R04.csv', '../Dataset/SA17/F05_SA17_R05.csv', '../Dataset/SA17/F06_SA17_R01.csv', '../Dataset/SA17/F06_SA17_R02.csv', '../Dataset/SA17/F06_SA17_R03.csv', '../Dataset/SA17/F06_SA17_R04.csv', '../Dataset/SA17/F06_SA17_R05.csv', '../Dataset/SA17/F07_SA17_R01.csv', '../Dataset/SA17/F07_SA17_R02.csv', '../Dataset/SA17/F07_SA17_R03.csv', '../Dataset/SA17/F07_SA17_R04.csv', '../Dataset/SA17/F07_SA17_R05.csv', '../Dataset/SA17/F08_SA17_R01.csv', '../Dataset/SA17/F08_SA17_R02.csv', '../Dataset/SA17/F08_SA17_R03.csv', '../Dataset/SA17/F08_SA17_R04.csv', '../Dataset/SA17/F08_SA17_R05.csv', '../Dataset/SA17/F09_SA17_R01.csv', '../Dataset/SA17/F09_SA17_R02.csv', '../Dataset/SA17/F09_SA17_R03.csv', '../Dataset/SA17/F09_SA17_R04.csv', '../Dataset/SA17/F09_SA17_R05.csv', '../Dataset/SA17/F10_SA17_R01.csv', '../Dataset/SA17/F10_SA17_R02.csv', '../Dataset/SA17/F10_SA17_R03.csv', '../Dataset/SA17/F10_SA17_R04.csv', '../Dataset/SA17/F10_SA17_R05.csv', '../Dataset/SA17/F11_SA17_R01.csv', '../Dataset/SA17/F11_SA17_R02.csv', '../Dataset/SA17/F11_SA17_R03.csv', '../Dataset/SA17/F11_SA17_R04.csv', '../Dataset/SA17/F11_SA17_R05.csv', '../Dataset/SA17/F12_SA17_R01.csv', '../Dataset/SA17/F12_SA17_R02.csv', '../Dataset/SA17/F12_SA17_R03.csv', '../Dataset/SA17/F12_SA17_R04.csv', '../Dataset/SA17/F12_SA17_R05.csv', '../Dataset/SA17/F13_SA17_R01.csv', '../Dataset/SA17/F13_SA17_R02.csv', '../Dataset/SA17/F13_SA17_R03.csv', '../Dataset/SA17/F13_SA17_R04.csv', '../Dataset/SA17/F13_SA17_R05.csv', '../Dataset/SA17/F14_SA17_R01.csv', '../Dataset/SA17/F14_SA17_R02.csv', '../Dataset/SA17/F14_SA17_R03.csv', '../Dataset/SA17/F14_SA17_R04.csv', '../Dataset/SA17/F14_SA17_R05.csv', '../Dataset/SA17/F15_SA17_R01.csv', '../Dataset/SA17/F15_SA17_R02.csv', '../Dataset/SA17/F15_SA17_R03.csv', '../Dataset/SA17/F15_SA17_R04.csv', '../Dataset/SA17/F15_SA17_R05.csv']

In [37]:
list = []
final_SA17_F = pd.DataFrame(list)

for path in SA17_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA17_F = final_SA17_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA17_F.shape
target_col = row * [1]
final_SA17_F.loc[:,'target'] = target_col

final_SA17_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,279.0,272.0,265.0,265.0,265.0,270.0,274.0,285.0,302.0,315.0,...,191.0,203.0,216.0,244.0,255.0,251.0,233.0,209.0,197.0,1
0,347.0,357.0,365.0,366.0,366.0,362.0,345.0,329.0,306.0,294.0,...,242.0,247.0,255.0,256.0,192.0,179.0,210.0,228.0,264.0,1
0,248.0,242.0,241.0,234.0,230.0,230.0,230.0,232.0,236.0,233.0,...,192.0,193.0,202.0,211.0,196.0,184.0,188.0,215.0,251.0,1
0,244.0,241.0,236.0,237.0,237.0,236.0,237.0,247.0,245.0,243.0,...,199.0,132.0,134.0,150.0,145.0,122.0,123.0,155.0,196.0,1
0,255.0,249.0,248.0,243.0,238.0,245.0,250.0,250.0,250.0,252.0,...,92.0,101.0,136.0,161.0,155.0,133.0,87.0,62.0,69.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,258.0,255.0,259.0,259.0,260.0,253.0,255.0,253.0,253.0,249.0,...,191.0,183.0,179.0,175.0,169.0,164.0,159.0,155.0,153.0,1
0,249.0,248.0,249.0,255.0,258.0,258.0,261.0,262.0,262.0,264.0,...,218.0,219.0,222.0,213.0,207.0,222.0,194.0,186.0,161.0,1
0,263.0,263.0,258.0,260.0,257.0,255.0,259.0,256.0,253.0,258.0,...,199.0,214.0,215.0,236.0,247.0,252.0,247.0,238.0,227.0,1
0,261.0,258.0,261.0,257.0,256.0,260.0,258.0,262.0,257.0,262.0,...,249.0,249.0,243.0,247.0,247.0,247.0,247.0,249.0,243.0,1
0,261.0,260.0,260.0,262.0,259.0,261.0,262.0,260.0,258.0,257.0,...,228.0,220.0,201.0,181.0,159.0,140.0,137.0,133.0,132.0,1

# SA18

In [38]:
SA18_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA18/F01_SA18_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA18_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA18_F_paths.append(tmp)
            
print(SA18_F_paths)

['../Dataset/SA18/F01_SA18_R01.csv', '../Dataset/SA18/F01_SA18_R02.csv', '../Dataset/SA18/F01_SA18_R03.csv', '../Dataset/SA18/F01_SA18_R04.csv', '../Dataset/SA18/F01_SA18_R05.csv', '../Dataset/SA18/F02_SA18_R01.csv', '../Dataset/SA18/F02_SA18_R02.csv', '../Dataset/SA18/F02_SA18_R03.csv', '../Dataset/SA18/F02_SA18_R04.csv', '../Dataset/SA18/F02_SA18_R05.csv', '../Dataset/SA18/F03_SA18_R01.csv', '../Dataset/SA18/F03_SA18_R02.csv', '../Dataset/SA18/F03_SA18_R03.csv', '../Dataset/SA18/F03_SA18_R04.csv', '../Dataset/SA18/F03_SA18_R05.csv', '../Dataset/SA18/F04_SA18_R01.csv', '../Dataset/SA18/F04_SA18_R02.csv', '../Dataset/SA18/F04_SA18_R03.csv', '../Dataset/SA18/F04_SA18_R04.csv', '../Dataset/SA18/F04_SA18_R05.csv', '../Dataset/SA18/F05_SA18_R01.csv', '../Dataset/SA18/F05_SA18_R02.csv', '../Dataset/SA18/F05_SA18_R03.csv', '../Dataset/SA18/F05_SA18_R04.csv', '../Dataset/SA18/F05_SA18_R05.csv', '../Dataset/SA18/F06_SA18_R01.csv', '../Dataset/SA18/F06_SA18_R02.csv', '../Dataset/SA18/F06_SA18_R03.csv', '../Dataset/SA18/F06_SA18_R04.csv', '../Dataset/SA18/F06_SA18_R05.csv', '../Dataset/SA18/F07_SA18_R01.csv', '../Dataset/SA18/F07_SA18_R02.csv', '../Dataset/SA18/F07_SA18_R03.csv', '../Dataset/SA18/F07_SA18_R04.csv', '../Dataset/SA18/F07_SA18_R05.csv', '../Dataset/SA18/F08_SA18_R01.csv', '../Dataset/SA18/F08_SA18_R02.csv', '../Dataset/SA18/F08_SA18_R03.csv', '../Dataset/SA18/F08_SA18_R04.csv', '../Dataset/SA18/F08_SA18_R05.csv', '../Dataset/SA18/F09_SA18_R01.csv', '../Dataset/SA18/F09_SA18_R02.csv', '../Dataset/SA18/F09_SA18_R03.csv', '../Dataset/SA18/F09_SA18_R04.csv', '../Dataset/SA18/F09_SA18_R05.csv', '../Dataset/SA18/F10_SA18_R01.csv', '../Dataset/SA18/F10_SA18_R02.csv', '../Dataset/SA18/F10_SA18_R03.csv', '../Dataset/SA18/F10_SA18_R04.csv', '../Dataset/SA18/F10_SA18_R05.csv', '../Dataset/SA18/F11_SA18_R01.csv', '../Dataset/SA18/F11_SA18_R02.csv', '../Dataset/SA18/F11_SA18_R03.csv', '../Dataset/SA18/F11_SA18_R04.csv', '../Dataset/SA18/F11_SA18_R05.csv', '../Dataset/SA18/F12_SA18_R01.csv', '../Dataset/SA18/F12_SA18_R02.csv', '../Dataset/SA18/F12_SA18_R03.csv', '../Dataset/SA18/F12_SA18_R04.csv', '../Dataset/SA18/F12_SA18_R05.csv', '../Dataset/SA18/F13_SA18_R01.csv', '../Dataset/SA18/F13_SA18_R02.csv', '../Dataset/SA18/F13_SA18_R03.csv', '../Dataset/SA18/F13_SA18_R04.csv', '../Dataset/SA18/F13_SA18_R05.csv', '../Dataset/SA18/F14_SA18_R01.csv', '../Dataset/SA18/F14_SA18_R02.csv', '../Dataset/SA18/F14_SA18_R03.csv', '../Dataset/SA18/F14_SA18_R04.csv', '../Dataset/SA18/F14_SA18_R05.csv', '../Dataset/SA18/F15_SA18_R01.csv', '../Dataset/SA18/F15_SA18_R02.csv', '../Dataset/SA18/F15_SA18_R03.csv', '../Dataset/SA18/F15_SA18_R04.csv', '../Dataset/SA18/F15_SA18_R05.csv']

In [39]:
list = []
final_SA18_F = pd.DataFrame(list)

for path in SA18_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA18_F = final_SA18_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA18_F.shape
target_col = row * [1]
final_SA18_F.loc[:,'target'] = target_col

final_SA18_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,240.0,236.0,235.0,237.0,242.0,240.0,238.0,239.0,242.0,244.0,...,124.0,142.0,156.0,172.0,188.0,197.0,202.0,192.0,174.0,1
0,200.0,204.0,209.0,223.0,234.0,241.0,243.0,248.0,247.0,242.0,...,175.0,192.0,198.0,209.0,206.0,186.0,153.0,105.0,76.0,1
0,226.0,224.0,226.0,227.0,228.0,229.0,232.0,233.0,238.0,239.0,...,168.0,149.0,138.0,145.0,152.0,147.0,152.0,154.0,150.0,1
0,253.0,254.0,253.0,252.0,254.0,251.0,251.0,250.0,251.0,246.0,...,234.0,242.0,252.0,271.0,303.0,326.0,333.0,338.0,303.0,1
0,200.0,204.0,219.0,223.0,231.0,230.0,227.0,226.0,222.0,220.0,...,110.0,71.0,38.0,39.0,75.0,112.0,135.0,159.0,160.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,259.0,259.0,259.0,256.0,260.0,260.0,260.0,262.0,258.0,260.0,...,165.0,163.0,165.0,161.0,158.0,146.0,131.0,116.0,109.0,1
0,256.0,257.0,255.0,254.0,258.0,253.0,256.0,258.0,255.0,259.0,...,153.0,147.0,147.0,147.0,161.0,173.0,181.0,183.0,180.0,1
0,255.0,261.0,260.0,260.0,258.0,257.0,256.0,258.0,254.0,255.0,...,237.0,230.0,219.0,198.0,175.0,169.0,158.0,150.0,138.0,1
0,257.0,257.0,258.0,260.0,258.0,259.0,258.0,261.0,259.0,261.0,...,137.0,148.0,151.0,159.0,163.0,168.0,162.0,146.0,126.0,1
0,254.0,252.0,257.0,257.0,254.0,256.0,255.0,259.0,258.0,255.0,...,219.0,219.0,202.0,188.0,173.0,161.0,160.0,159.0,156.0,1

# SA19

In [40]:
SA19_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA19/F01_SA19_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA19_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA19_F_paths.append(tmp)
            
print(SA19_F_paths)

['../Dataset/SA19/F01_SA19_R01.csv', '../Dataset/SA19/F01_SA19_R02.csv', '../Dataset/SA19/F01_SA19_R03.csv', '../Dataset/SA19/F01_SA19_R04.csv', '../Dataset/SA19/F01_SA19_R05.csv', '../Dataset/SA19/F02_SA19_R01.csv', '../Dataset/SA19/F02_SA19_R02.csv', '../Dataset/SA19/F02_SA19_R03.csv', '../Dataset/SA19/F02_SA19_R04.csv', '../Dataset/SA19/F02_SA19_R05.csv', '../Dataset/SA19/F03_SA19_R01.csv', '../Dataset/SA19/F03_SA19_R02.csv', '../Dataset/SA19/F03_SA19_R03.csv', '../Dataset/SA19/F03_SA19_R04.csv', '../Dataset/SA19/F03_SA19_R05.csv', '../Dataset/SA19/F04_SA19_R01.csv', '../Dataset/SA19/F04_SA19_R02.csv', '../Dataset/SA19/F04_SA19_R03.csv', '../Dataset/SA19/F04_SA19_R04.csv', '../Dataset/SA19/F04_SA19_R05.csv', '../Dataset/SA19/F05_SA19_R01.csv', '../Dataset/SA19/F05_SA19_R02.csv', '../Dataset/SA19/F05_SA19_R03.csv', '../Dataset/SA19/F05_SA19_R04.csv', '../Dataset/SA19/F05_SA19_R05.csv', '../Dataset/SA19/F06_SA19_R01.csv', '../Dataset/SA19/F06_SA19_R02.csv', '../Dataset/SA19/F06_SA19_R03.csv', '../Dataset/SA19/F06_SA19_R04.csv', '../Dataset/SA19/F06_SA19_R05.csv', '../Dataset/SA19/F07_SA19_R01.csv', '../Dataset/SA19/F07_SA19_R02.csv', '../Dataset/SA19/F07_SA19_R03.csv', '../Dataset/SA19/F07_SA19_R04.csv', '../Dataset/SA19/F07_SA19_R05.csv', '../Dataset/SA19/F08_SA19_R01.csv', '../Dataset/SA19/F08_SA19_R02.csv', '../Dataset/SA19/F08_SA19_R03.csv', '../Dataset/SA19/F08_SA19_R04.csv', '../Dataset/SA19/F08_SA19_R05.csv', '../Dataset/SA19/F09_SA19_R01.csv', '../Dataset/SA19/F09_SA19_R02.csv', '../Dataset/SA19/F09_SA19_R03.csv', '../Dataset/SA19/F09_SA19_R04.csv', '../Dataset/SA19/F09_SA19_R05.csv', '../Dataset/SA19/F10_SA19_R01.csv', '../Dataset/SA19/F10_SA19_R02.csv', '../Dataset/SA19/F10_SA19_R03.csv', '../Dataset/SA19/F10_SA19_R04.csv', '../Dataset/SA19/F10_SA19_R05.csv', '../Dataset/SA19/F11_SA19_R01.csv', '../Dataset/SA19/F11_SA19_R02.csv', '../Dataset/SA19/F11_SA19_R03.csv', '../Dataset/SA19/F11_SA19_R04.csv', '../Dataset/SA19/F11_SA19_R05.csv', '../Dataset/SA19/F12_SA19_R01.csv', '../Dataset/SA19/F12_SA19_R02.csv', '../Dataset/SA19/F12_SA19_R03.csv', '../Dataset/SA19/F12_SA19_R04.csv', '../Dataset/SA19/F12_SA19_R05.csv', '../Dataset/SA19/F13_SA19_R01.csv', '../Dataset/SA19/F13_SA19_R02.csv', '../Dataset/SA19/F13_SA19_R03.csv', '../Dataset/SA19/F13_SA19_R04.csv', '../Dataset/SA19/F13_SA19_R05.csv', '../Dataset/SA19/F14_SA19_R01.csv', '../Dataset/SA19/F14_SA19_R02.csv', '../Dataset/SA19/F14_SA19_R03.csv', '../Dataset/SA19/F14_SA19_R04.csv', '../Dataset/SA19/F14_SA19_R05.csv', '../Dataset/SA19/F15_SA19_R01.csv', '../Dataset/SA19/F15_SA19_R02.csv', '../Dataset/SA19/F15_SA19_R03.csv', '../Dataset/SA19/F15_SA19_R04.csv', '../Dataset/SA19/F15_SA19_R05.csv']

In [41]:
list = []
final_SA19_F = pd.DataFrame(list)

for path in SA19_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA19_F = final_SA19_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA19_F.shape
target_col = row * [1]
final_SA19_F.loc[:,'target'] = target_col

final_SA19_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,376.0,398.0,401.0,405.0,401.0,399.0,391.0,384.0,360.0,341.0,...,227.0,249.0,255.0,264.0,271.0,282.0,298.0,308.0,305.0,1
0,306.0,310.0,305.0,304.0,306.0,314.0,321.0,323.0,322.0,315.0,...,183.0,197.0,208.0,217.0,216.0,206.0,204.0,182.0,180.0,1
0,256.0,254.0,256.0,253.0,251.0,246.0,246.0,243.0,240.0,233.0,...,204.0,210.0,209.0,213.0,211.0,213.0,217.0,216.0,217.0,1
0,277.0,282.0,282.0,289.0,291.0,293.0,296.0,296.0,295.0,295.0,...,283.0,283.0,296.0,324.0,313.0,290.0,270.0,242.0,212.0,1
0,323.0,336.0,339.0,341.0,328.0,321.0,310.0,296.0,292.0,290.0,...,131.0,136.0,133.0,125.0,122.0,130.0,157.0,182.0,190.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,256.0,258.0,256.0,255.0,255.0,258.0,254.0,257.0,254.0,259.0,...,206.0,214.0,212.0,209.0,201.0,193.0,182.0,168.0,147.0,1
0,254.0,259.0,258.0,260.0,259.0,261.0,258.0,256.0,257.0,256.0,...,189.0,186.0,179.0,167.0,159.0,150.0,149.0,150.0,156.0,1
0,256.0,257.0,257.0,257.0,257.0,255.0,255.0,256.0,253.0,255.0,...,181.0,178.0,162.0,163.0,154.0,150.0,148.0,154.0,157.0,1
0,251.0,254.0,253.0,255.0,253.0,254.0,255.0,259.0,253.0,253.0,...,82.0,81.0,74.0,75.0,76.0,74.0,68.0,59.0,67.0,1
0,253.0,254.0,254.0,253.0,253.0,254.0,254.0,258.0,257.0,256.0,...,191.0,180.0,190.0,157.0,149.0,139.0,134.0,125.0,124.0,1

# SA20

In [42]:
SA20_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA20/F01_SA20_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA20_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA20_F_paths.append(tmp)
            
print(SA20_F_paths)

['../Dataset/SA20/F01_SA20_R01.csv', '../Dataset/SA20/F01_SA20_R02.csv', '../Dataset/SA20/F01_SA20_R03.csv', '../Dataset/SA20/F01_SA20_R04.csv', '../Dataset/SA20/F01_SA20_R05.csv', '../Dataset/SA20/F02_SA20_R01.csv', '../Dataset/SA20/F02_SA20_R02.csv', '../Dataset/SA20/F02_SA20_R03.csv', '../Dataset/SA20/F02_SA20_R04.csv', '../Dataset/SA20/F02_SA20_R05.csv', '../Dataset/SA20/F03_SA20_R01.csv', '../Dataset/SA20/F03_SA20_R02.csv', '../Dataset/SA20/F03_SA20_R03.csv', '../Dataset/SA20/F03_SA20_R04.csv', '../Dataset/SA20/F03_SA20_R05.csv', '../Dataset/SA20/F04_SA20_R01.csv', '../Dataset/SA20/F04_SA20_R02.csv', '../Dataset/SA20/F04_SA20_R03.csv', '../Dataset/SA20/F04_SA20_R04.csv', '../Dataset/SA20/F04_SA20_R05.csv', '../Dataset/SA20/F05_SA20_R01.csv', '../Dataset/SA20/F05_SA20_R02.csv', '../Dataset/SA20/F05_SA20_R03.csv', '../Dataset/SA20/F05_SA20_R04.csv', '../Dataset/SA20/F05_SA20_R05.csv', '../Dataset/SA20/F06_SA20_R01.csv', '../Dataset/SA20/F06_SA20_R02.csv', '../Dataset/SA20/F06_SA20_R03.csv', '../Dataset/SA20/F06_SA20_R04.csv', '../Dataset/SA20/F06_SA20_R05.csv', '../Dataset/SA20/F07_SA20_R01.csv', '../Dataset/SA20/F07_SA20_R02.csv', '../Dataset/SA20/F07_SA20_R03.csv', '../Dataset/SA20/F07_SA20_R04.csv', '../Dataset/SA20/F07_SA20_R05.csv', '../Dataset/SA20/F08_SA20_R01.csv', '../Dataset/SA20/F08_SA20_R02.csv', '../Dataset/SA20/F08_SA20_R03.csv', '../Dataset/SA20/F08_SA20_R04.csv', '../Dataset/SA20/F08_SA20_R05.csv', '../Dataset/SA20/F09_SA20_R01.csv', '../Dataset/SA20/F09_SA20_R02.csv', '../Dataset/SA20/F09_SA20_R03.csv', '../Dataset/SA20/F09_SA20_R04.csv', '../Dataset/SA20/F09_SA20_R05.csv', '../Dataset/SA20/F10_SA20_R01.csv', '../Dataset/SA20/F10_SA20_R02.csv', '../Dataset/SA20/F10_SA20_R03.csv', '../Dataset/SA20/F10_SA20_R04.csv', '../Dataset/SA20/F10_SA20_R05.csv', '../Dataset/SA20/F11_SA20_R01.csv', '../Dataset/SA20/F11_SA20_R02.csv', '../Dataset/SA20/F11_SA20_R03.csv', '../Dataset/SA20/F11_SA20_R04.csv', '../Dataset/SA20/F11_SA20_R05.csv', '../Dataset/SA20/F12_SA20_R01.csv', '../Dataset/SA20/F12_SA20_R02.csv', '../Dataset/SA20/F12_SA20_R03.csv', '../Dataset/SA20/F12_SA20_R04.csv', '../Dataset/SA20/F12_SA20_R05.csv', '../Dataset/SA20/F13_SA20_R01.csv', '../Dataset/SA20/F13_SA20_R02.csv', '../Dataset/SA20/F13_SA20_R03.csv', '../Dataset/SA20/F13_SA20_R04.csv', '../Dataset/SA20/F13_SA20_R05.csv', '../Dataset/SA20/F14_SA20_R01.csv', '../Dataset/SA20/F14_SA20_R02.csv', '../Dataset/SA20/F14_SA20_R03.csv', '../Dataset/SA20/F14_SA20_R04.csv', '../Dataset/SA20/F14_SA20_R05.csv', '../Dataset/SA20/F15_SA20_R01.csv', '../Dataset/SA20/F15_SA20_R02.csv', '../Dataset/SA20/F15_SA20_R03.csv', '../Dataset/SA20/F15_SA20_R04.csv', '../Dataset/SA20/F15_SA20_R05.csv']

In [43]:
list = []
final_SA20_F = pd.DataFrame(list)

for path in SA20_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA20_F = final_SA20_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA20_F.shape
target_col = row * [1]
final_SA20_F.loc[:,'target'] = target_col

final_SA20_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,271.0,257.0,245.0,233.0,230.0,229.0,220.0,203.0,226.0,224.0,...,230.0,220.0,206.0,189.0,174.0,169.0,160.0,135.0,98.0,1
0,224.0,224.0,222.0,220.0,219.0,220.0,217.0,214.0,210.0,216.0,...,162.0,164.0,154.0,140.0,129.0,133.0,138.0,151.0,167.0,1
0,224.0,224.0,222.0,220.0,219.0,220.0,217.0,214.0,210.0,216.0,...,162.0,164.0,154.0,140.0,129.0,133.0,138.0,151.0,167.0,1
0,302.0,285.0,269.0,256.0,247.0,245.0,243.0,249.0,255.0,261.0,...,103.0,103.0,100.0,99.0,99.0,107.0,108.0,116.0,118.0,1
0,388.0,362.0,331.0,301.0,277.0,258.0,240.0,232.0,230.0,242.0,...,57.0,76.0,98.0,138.0,139.0,168.0,178.0,193.0,204.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,254.0,255.0,256.0,256.0,255.0,256.0,256.0,257.0,258.0,258.0,...,156.0,158.0,169.0,183.0,196.0,198.0,200.0,188.0,178.0,1
0,254.0,254.0,254.0,254.0,256.0,250.0,254.0,255.0,252.0,251.0,...,99.0,91.0,83.0,73.0,60.0,56.0,56.0,64.0,78.0,1
0,247.0,247.0,244.0,240.0,242.0,240.0,242.0,244.0,240.0,240.0,...,176.0,186.0,221.0,249.0,260.0,261.0,265.0,265.0,248.0,1
0,252.0,251.0,252.0,250.0,253.0,251.0,250.0,249.0,252.0,250.0,...,159.0,171.0,180.0,191.0,201.0,212.0,228.0,253.0,267.0,1
0,253.0,253.0,256.0,257.0,256.0,254.0,258.0,252.0,255.0,254.0,...,196.0,188.0,186.0,185.0,186.0,180.0,183.0,180.0,178.0,1

# SA21

In [44]:
SA21_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA21/F01_SA21_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA21_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA21_F_paths.append(tmp)
            
print(SA21_F_paths)

['../Dataset/SA21/F01_SA21_R01.csv', '../Dataset/SA21/F01_SA21_R02.csv', '../Dataset/SA21/F01_SA21_R03.csv', '../Dataset/SA21/F01_SA21_R04.csv', '../Dataset/SA21/F01_SA21_R05.csv', '../Dataset/SA21/F02_SA21_R01.csv', '../Dataset/SA21/F02_SA21_R02.csv', '../Dataset/SA21/F02_SA21_R03.csv', '../Dataset/SA21/F02_SA21_R04.csv', '../Dataset/SA21/F02_SA21_R05.csv', '../Dataset/SA21/F03_SA21_R01.csv', '../Dataset/SA21/F03_SA21_R02.csv', '../Dataset/SA21/F03_SA21_R03.csv', '../Dataset/SA21/F03_SA21_R04.csv', '../Dataset/SA21/F03_SA21_R05.csv', '../Dataset/SA21/F04_SA21_R01.csv', '../Dataset/SA21/F04_SA21_R02.csv', '../Dataset/SA21/F04_SA21_R03.csv', '../Dataset/SA21/F04_SA21_R04.csv', '../Dataset/SA21/F04_SA21_R05.csv', '../Dataset/SA21/F05_SA21_R01.csv', '../Dataset/SA21/F05_SA21_R02.csv', '../Dataset/SA21/F05_SA21_R03.csv', '../Dataset/SA21/F05_SA21_R04.csv', '../Dataset/SA21/F05_SA21_R05.csv', '../Dataset/SA21/F06_SA21_R01.csv', '../Dataset/SA21/F06_SA21_R02.csv', '../Dataset/SA21/F06_SA21_R03.csv', '../Dataset/SA21/F06_SA21_R04.csv', '../Dataset/SA21/F06_SA21_R05.csv', '../Dataset/SA21/F07_SA21_R01.csv', '../Dataset/SA21/F07_SA21_R02.csv', '../Dataset/SA21/F07_SA21_R03.csv', '../Dataset/SA21/F07_SA21_R04.csv', '../Dataset/SA21/F07_SA21_R05.csv', '../Dataset/SA21/F08_SA21_R01.csv', '../Dataset/SA21/F08_SA21_R02.csv', '../Dataset/SA21/F08_SA21_R03.csv', '../Dataset/SA21/F08_SA21_R04.csv', '../Dataset/SA21/F08_SA21_R05.csv', '../Dataset/SA21/F09_SA21_R01.csv', '../Dataset/SA21/F09_SA21_R02.csv', '../Dataset/SA21/F09_SA21_R03.csv', '../Dataset/SA21/F09_SA21_R04.csv', '../Dataset/SA21/F09_SA21_R05.csv', '../Dataset/SA21/F10_SA21_R01.csv', '../Dataset/SA21/F10_SA21_R02.csv', '../Dataset/SA21/F10_SA21_R03.csv', '../Dataset/SA21/F10_SA21_R04.csv', '../Dataset/SA21/F10_SA21_R05.csv', '../Dataset/SA21/F11_SA21_R01.csv', '../Dataset/SA21/F11_SA21_R02.csv', '../Dataset/SA21/F11_SA21_R03.csv', '../Dataset/SA21/F11_SA21_R04.csv', '../Dataset/SA21/F11_SA21_R05.csv', '../Dataset/SA21/F12_SA21_R01.csv', '../Dataset/SA21/F12_SA21_R02.csv', '../Dataset/SA21/F12_SA21_R03.csv', '../Dataset/SA21/F12_SA21_R04.csv', '../Dataset/SA21/F12_SA21_R05.csv', '../Dataset/SA21/F13_SA21_R01.csv', '../Dataset/SA21/F13_SA21_R02.csv', '../Dataset/SA21/F13_SA21_R03.csv', '../Dataset/SA21/F13_SA21_R04.csv', '../Dataset/SA21/F13_SA21_R05.csv', '../Dataset/SA21/F14_SA21_R01.csv', '../Dataset/SA21/F14_SA21_R02.csv', '../Dataset/SA21/F14_SA21_R03.csv', '../Dataset/SA21/F14_SA21_R04.csv', '../Dataset/SA21/F14_SA21_R05.csv', '../Dataset/SA21/F15_SA21_R01.csv', '../Dataset/SA21/F15_SA21_R02.csv', '../Dataset/SA21/F15_SA21_R03.csv', '../Dataset/SA21/F15_SA21_R04.csv', '../Dataset/SA21/F15_SA21_R05.csv']

In [45]:
list = []
final_SA21_F = pd.DataFrame(list)

for path in SA21_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA21_F = final_SA21_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA21_F.shape
target_col = row * [1]
final_SA21_F.loc[:,'target'] = target_col

final_SA21_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,262.0,268.0,274.0,279.0,285.0,283.0,289.0,289.0,286.0,282.0,...,287.0,336.0,392.0,428.0,490.0,516.0,545.0,593.0,649.0,1
0,192.0,194.0,193.0,203.0,205.0,213.0,220.0,227.0,230.0,232.0,...,216.0,281.0,322.0,284.0,236.0,238.0,157.0,79.0,83.0,1
0,329.0,316.0,304.0,294.0,282.0,278.0,279.0,272.0,278.0,284.0,...,74.0,117.0,147.0,173.0,185.0,169.0,144.0,117.0,103.0,1
0,423.0,444.0,450.0,450.0,444.0,435.0,429.0,424.0,406.0,384.0,...,129.0,120.0,114.0,125.0,131.0,134.0,128.0,116.0,112.0,1
0,268.0,259.0,253.0,251.0,248.0,251.0,252.0,253.0,251.0,239.0,...,191.0,172.0,159.0,159.0,127.0,105.0,85.0,67.0,58.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,254.0,253.0,257.0,257.0,257.0,255.0,261.0,262.0,260.0,259.0,...,194.0,203.0,198.0,205.0,215.0,232.0,249.0,272.0,298.0,1
0,250.0,253.0,254.0,253.0,253.0,249.0,249.0,247.0,248.0,250.0,...,166.0,153.0,172.0,175.0,174.0,163.0,187.0,193.0,181.0,1
0,256.0,252.0,253.0,256.0,254.0,256.0,258.0,256.0,259.0,257.0,...,256.0,255.0,249.0,251.0,256.0,273.0,257.0,259.0,259.0,1
0,265.0,262.0,262.0,261.0,259.0,259.0,261.0,258.0,257.0,255.0,...,442.0,471.0,477.0,474.0,472.0,472.0,469.0,461.0,446.0,1
0,254.0,253.0,250.0,252.0,252.0,250.0,254.0,253.0,254.0,254.0,...,241.0,247.0,259.0,257.0,265.0,276.0,289.0,296.0,294.0,1

# SA22

In [46]:
SA22_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA22/F01_SA22_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA22_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA22_F_paths.append(tmp)
            
print(SA22_F_paths)

['../Dataset/SA22/F01_SA22_R01.csv', '../Dataset/SA22/F01_SA22_R02.csv', '../Dataset/SA22/F01_SA22_R03.csv', '../Dataset/SA22/F01_SA22_R04.csv', '../Dataset/SA22/F01_SA22_R05.csv', '../Dataset/SA22/F02_SA22_R01.csv', '../Dataset/SA22/F02_SA22_R02.csv', '../Dataset/SA22/F02_SA22_R03.csv', '../Dataset/SA22/F02_SA22_R04.csv', '../Dataset/SA22/F02_SA22_R05.csv', '../Dataset/SA22/F03_SA22_R01.csv', '../Dataset/SA22/F03_SA22_R02.csv', '../Dataset/SA22/F03_SA22_R03.csv', '../Dataset/SA22/F03_SA22_R04.csv', '../Dataset/SA22/F03_SA22_R05.csv', '../Dataset/SA22/F04_SA22_R01.csv', '../Dataset/SA22/F04_SA22_R02.csv', '../Dataset/SA22/F04_SA22_R03.csv', '../Dataset/SA22/F04_SA22_R04.csv', '../Dataset/SA22/F04_SA22_R05.csv', '../Dataset/SA22/F05_SA22_R01.csv', '../Dataset/SA22/F05_SA22_R02.csv', '../Dataset/SA22/F05_SA22_R03.csv', '../Dataset/SA22/F05_SA22_R04.csv', '../Dataset/SA22/F05_SA22_R05.csv', '../Dataset/SA22/F06_SA22_R01.csv', '../Dataset/SA22/F06_SA22_R02.csv', '../Dataset/SA22/F06_SA22_R03.csv', '../Dataset/SA22/F06_SA22_R04.csv', '../Dataset/SA22/F06_SA22_R05.csv', '../Dataset/SA22/F07_SA22_R01.csv', '../Dataset/SA22/F07_SA22_R02.csv', '../Dataset/SA22/F07_SA22_R03.csv', '../Dataset/SA22/F07_SA22_R04.csv', '../Dataset/SA22/F07_SA22_R05.csv', '../Dataset/SA22/F08_SA22_R01.csv', '../Dataset/SA22/F08_SA22_R02.csv', '../Dataset/SA22/F08_SA22_R03.csv', '../Dataset/SA22/F08_SA22_R04.csv', '../Dataset/SA22/F08_SA22_R05.csv', '../Dataset/SA22/F09_SA22_R01.csv', '../Dataset/SA22/F09_SA22_R02.csv', '../Dataset/SA22/F09_SA22_R03.csv', '../Dataset/SA22/F09_SA22_R04.csv', '../Dataset/SA22/F09_SA22_R05.csv', '../Dataset/SA22/F10_SA22_R01.csv', '../Dataset/SA22/F10_SA22_R02.csv', '../Dataset/SA22/F10_SA22_R03.csv', '../Dataset/SA22/F10_SA22_R04.csv', '../Dataset/SA22/F10_SA22_R05.csv', '../Dataset/SA22/F11_SA22_R01.csv', '../Dataset/SA22/F11_SA22_R02.csv', '../Dataset/SA22/F11_SA22_R03.csv', '../Dataset/SA22/F11_SA22_R04.csv', '../Dataset/SA22/F11_SA22_R05.csv', '../Dataset/SA22/F12_SA22_R01.csv', '../Dataset/SA22/F12_SA22_R02.csv', '../Dataset/SA22/F12_SA22_R03.csv', '../Dataset/SA22/F12_SA22_R04.csv', '../Dataset/SA22/F12_SA22_R05.csv', '../Dataset/SA22/F13_SA22_R01.csv', '../Dataset/SA22/F13_SA22_R02.csv', '../Dataset/SA22/F13_SA22_R03.csv', '../Dataset/SA22/F13_SA22_R04.csv', '../Dataset/SA22/F13_SA22_R05.csv', '../Dataset/SA22/F14_SA22_R01.csv', '../Dataset/SA22/F14_SA22_R02.csv', '../Dataset/SA22/F14_SA22_R03.csv', '../Dataset/SA22/F14_SA22_R04.csv', '../Dataset/SA22/F14_SA22_R05.csv', '../Dataset/SA22/F15_SA22_R01.csv', '../Dataset/SA22/F15_SA22_R02.csv', '../Dataset/SA22/F15_SA22_R03.csv', '../Dataset/SA22/F15_SA22_R04.csv', '../Dataset/SA22/F15_SA22_R05.csv']

In [47]:
list = []
final_SA22_F = pd.DataFrame(list)

for path in SA22_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA22_F = final_SA22_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA22_F.shape
target_col = row * [1]
final_SA22_F.loc[:,'target'] = target_col

final_SA22_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,185.0,179.0,177.0,174.0,174.0,173.0,174.0,177.0,176.0,181.0,...,158.0,146.0,124.0,104.0,105.0,139.0,220.0,319.0,444.0,1
0,277.0,282.0,287.0,285.0,286.0,287.0,277.0,265.0,264.0,251.0,...,130.0,133.0,134.0,125.0,105.0,98.0,104.0,99.0,87.0,1
0,252.0,252.0,254.0,251.0,255.0,254.0,260.0,254.0,256.0,255.0,...,134.0,125.0,118.0,114.0,122.0,129.0,161.0,170.0,194.0,1
0,369.0,383.0,396.0,405.0,412.0,414.0,413.0,404.0,400.0,390.0,...,116.0,106.0,93.0,72.0,56.0,35.0,32.0,58.0,76.0,1
0,392.0,399.0,405.0,405.0,403.0,403.0,391.0,383.0,373.0,363.0,...,150.0,166.0,177.0,174.0,172.0,163.0,152.0,141.0,137.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,261.0,260.0,260.0,264.0,262.0,258.0,257.0,260.0,259.0,257.0,...,182.0,178.0,179.0,176.0,173.0,180.0,177.0,174.0,172.0,1
0,253.0,254.0,256.0,255.0,258.0,255.0,256.0,254.0,251.0,254.0,...,257.0,256.0,258.0,254.0,255.0,255.0,254.0,253.0,252.0,1
0,249.0,249.0,251.0,251.0,250.0,250.0,250.0,248.0,249.0,250.0,...,134.0,132.0,124.0,120.0,105.0,100.0,88.0,81.0,77.0,1
0,255.0,254.0,250.0,249.0,247.0,255.0,248.0,243.0,259.0,253.0,...,223.0,223.0,223.0,222.0,224.0,224.0,227.0,233.0,232.0,1
0,258.0,256.0,256.0,253.0,254.0,252.0,253.0,251.0,253.0,253.0,...,188.0,203.0,218.0,232.0,245.0,254.0,258.0,258.0,253.0,1

# SA 23

In [48]:
SA23_F_paths = []

for i in range(1, 16):
    root, file = os.path.split("../Dataset/SA23/F01_SA23_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA23_F_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        for j in range(1, 6):
            file_new = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file_new)
            SA23_F_paths.append(tmp)
            
print(SA23_F_paths)

['../Dataset/SA23/F01_SA23_R01.csv', '../Dataset/SA23/F01_SA23_R02.csv', '../Dataset/SA23/F01_SA23_R03.csv', '../Dataset/SA23/F01_SA23_R04.csv', '../Dataset/SA23/F01_SA23_R05.csv', '../Dataset/SA23/F02_SA23_R01.csv', '../Dataset/SA23/F02_SA23_R02.csv', '../Dataset/SA23/F02_SA23_R03.csv', '../Dataset/SA23/F02_SA23_R04.csv', '../Dataset/SA23/F02_SA23_R05.csv', '../Dataset/SA23/F03_SA23_R01.csv', '../Dataset/SA23/F03_SA23_R02.csv', '../Dataset/SA23/F03_SA23_R03.csv', '../Dataset/SA23/F03_SA23_R04.csv', '../Dataset/SA23/F03_SA23_R05.csv', '../Dataset/SA23/F04_SA23_R01.csv', '../Dataset/SA23/F04_SA23_R02.csv', '../Dataset/SA23/F04_SA23_R03.csv', '../Dataset/SA23/F04_SA23_R04.csv', '../Dataset/SA23/F04_SA23_R05.csv', '../Dataset/SA23/F05_SA23_R01.csv', '../Dataset/SA23/F05_SA23_R02.csv', '../Dataset/SA23/F05_SA23_R03.csv', '../Dataset/SA23/F05_SA23_R04.csv', '../Dataset/SA23/F05_SA23_R05.csv', '../Dataset/SA23/F06_SA23_R01.csv', '../Dataset/SA23/F06_SA23_R02.csv', '../Dataset/SA23/F06_SA23_R03.csv', '../Dataset/SA23/F06_SA23_R04.csv', '../Dataset/SA23/F06_SA23_R05.csv', '../Dataset/SA23/F07_SA23_R01.csv', '../Dataset/SA23/F07_SA23_R02.csv', '../Dataset/SA23/F07_SA23_R03.csv', '../Dataset/SA23/F07_SA23_R04.csv', '../Dataset/SA23/F07_SA23_R05.csv', '../Dataset/SA23/F08_SA23_R01.csv', '../Dataset/SA23/F08_SA23_R02.csv', '../Dataset/SA23/F08_SA23_R03.csv', '../Dataset/SA23/F08_SA23_R04.csv', '../Dataset/SA23/F08_SA23_R05.csv', '../Dataset/SA23/F09_SA23_R01.csv', '../Dataset/SA23/F09_SA23_R02.csv', '../Dataset/SA23/F09_SA23_R03.csv', '../Dataset/SA23/F09_SA23_R04.csv', '../Dataset/SA23/F09_SA23_R05.csv', '../Dataset/SA23/F10_SA23_R01.csv', '../Dataset/SA23/F10_SA23_R02.csv', '../Dataset/SA23/F10_SA23_R03.csv', '../Dataset/SA23/F10_SA23_R04.csv', '../Dataset/SA23/F10_SA23_R05.csv', '../Dataset/SA23/F11_SA23_R01.csv', '../Dataset/SA23/F11_SA23_R02.csv', '../Dataset/SA23/F11_SA23_R03.csv', '../Dataset/SA23/F11_SA23_R04.csv', '../Dataset/SA23/F11_SA23_R05.csv', '../Dataset/SA23/F12_SA23_R01.csv', '../Dataset/SA23/F12_SA23_R02.csv', '../Dataset/SA23/F12_SA23_R03.csv', '../Dataset/SA23/F12_SA23_R04.csv', '../Dataset/SA23/F12_SA23_R05.csv', '../Dataset/SA23/F13_SA23_R01.csv', '../Dataset/SA23/F13_SA23_R02.csv', '../Dataset/SA23/F13_SA23_R03.csv', '../Dataset/SA23/F13_SA23_R04.csv', '../Dataset/SA23/F13_SA23_R05.csv', '../Dataset/SA23/F14_SA23_R01.csv', '../Dataset/SA23/F14_SA23_R02.csv', '../Dataset/SA23/F14_SA23_R03.csv', '../Dataset/SA23/F14_SA23_R04.csv', '../Dataset/SA23/F14_SA23_R05.csv', '../Dataset/SA23/F15_SA23_R01.csv', '../Dataset/SA23/F15_SA23_R02.csv', '../Dataset/SA23/F15_SA23_R03.csv', '../Dataset/SA23/F15_SA23_R04.csv', '../Dataset/SA23/F15_SA23_R05.csv']

In [49]:
list = []
final_SA23_F = pd.DataFrame(list)

for path in SA23_F_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape
    for col in range(cols):
        for row in range(rows):
            if data[col][row] < 0:
                data[col][row] *= -1
    max_value1 = data[1000:][0].max()
    max_value2 = data[1000:][1].max()
    max_value3 = data[1000:][2].max()
    
    max_idx1 = data[ data[0] == max_value1 ].index[0]
    max_idx2 = data[ data[1] == max_value2 ].index[0]
    max_idx3 = data[ data[2] == max_value3 ].index[0]
    min_idx = min(max_idx1, max_idx2, max_idx3)
    sliced_df = data[min_idx - 200 : min_idx - 40]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA23_F = final_SA23_F.append(list_C_nine)


# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA23_F.shape
target_col = row * [1]
final_SA23_F.loc[:,'target'] = target_col

final_SA23_F

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,216.0,218.0,218.0,221.0,220.0,222.0,223.0,224.0,224.0,220.0,...,931.0,920.0,902.0,864.0,813.0,745.0,678.0,620.0,567.0,1
0,228.0,228.0,227.0,230.0,229.0,234.0,236.0,239.0,243.0,241.0,...,193.0,182.0,172.0,164.0,162.0,160.0,154.0,149.0,145.0,1
0,237.0,233.0,237.0,237.0,235.0,236.0,235.0,235.0,234.0,241.0,...,308.0,266.0,235.0,215.0,202.0,194.0,199.0,194.0,198.0,1
0,240.0,245.0,247.0,246.0,247.0,245.0,244.0,242.0,242.0,245.0,...,208.0,194.0,181.0,173.0,169.0,167.0,168.0,165.0,162.0,1
0,272.0,265.0,259.0,250.0,245.0,241.0,241.0,234.0,227.0,222.0,...,295.0,270.0,240.0,225.0,214.0,209.0,221.0,220.0,219.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,256.0,254.0,255.0,257.0,256.0,258.0,254.0,253.0,253.0,256.0,...,220.0,205.0,179.0,170.0,160.0,142.0,144.0,143.0,142.0,1
0,255.0,259.0,257.0,257.0,257.0,256.0,258.0,254.0,259.0,256.0,...,257.0,257.0,259.0,256.0,257.0,255.0,257.0,255.0,257.0,1
0,251.0,255.0,255.0,256.0,253.0,253.0,254.0,254.0,256.0,253.0,...,258.0,256.0,258.0,257.0,257.0,252.0,251.0,249.0,249.0,1
0,251.0,252.0,253.0,248.0,250.0,251.0,248.0,253.0,253.0,252.0,...,220.0,211.0,211.0,209.0,212.0,231.0,249.0,270.0,286.0,1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

# Fall 데이터 붙이기

In [65]:
file_list = [final_SA01_F, final_SA02_F, final_SA03_F, final_SA04_F, final_SA05_F,
             final_SA06_F, final_SA07_F, final_SA08_F, final_SA09_F,
             final_SA11_F, final_SA12_F, final_SA13_F, final_SA14_F, final_SA15_F,
             final_SA16_F, final_SA17_F, final_SA18_F, final_SA19_F, final_SA20_F,
             final_SA21_F, final_SA22_F, final_SA23_F]

result = pd.concat(file_list)
result.to_csv('SA_Fall.csv', index=False)

# SE01

In [44]:
SE01_A_paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SE01/D01_SE01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        SE01_A_paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                SE01_A_paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            SE01_A_paths.append(tmp)

SE01_A_paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                      '../Dataset/SA01/D05_SA01_R01_2.csv',
                      '../Dataset/SA01/D05_SA01_R02_1.csv',
                      '../Dataset/SA01/D05_SA01_R02_2.csv',
                      '../Dataset/SA01/D05_SA01_R03_1.csv',
                      '../Dataset/SA01/D05_SA01_R03_2.csv',
                      '../Dataset/SA01/D05_SA01_R04_1.csv',
                      '../Dataset/SA01/D05_SA01_R04_2.csv',
                      '../Dataset/SA01/D05_SA01_R05_1.csv',
                      '../Dataset/SA01/D05_SA01_R05_2.csv',
                      '../Dataset/SA01/D06_SA01_R01_1.csv',
                      '../Dataset/SA01/D06_SA01_R01_2.csv',
                      '../Dataset/SA01/D06_SA01_R02_1.csv',
                      '../Dataset/SA01/D06_SA01_R02_2.csv',
                      '../Dataset/SA01/D06_SA01_R03_1.csv',
                      '../Dataset/SA01/D06_SA01_R03_2.csv',
                      '../Dataset/SA01/D06_SA01_R04_1.csv',
                      '../Dataset/SA01/D06_SA01_R04_2.csv',
                      '../Dataset/SA01/D06_SA01_R05_1.csv',
                      '../Dataset/SA01/D06_SA01_R05_2.csv']

SE01_A_paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                         '../Dataset/SA01/D17_SA01_R01_2.csv',
                         '../Dataset/SA01/D17_SA01_R02_1.csv',
                         '../Dataset/SA01/D17_SA01_R02_2.csv',
                         '../Dataset/SA01/D17_SA01_R03_1.csv',
                         '../Dataset/SA01/D17_SA01_R03_2.csv',
                         '../Dataset/SA01/D17_SA01_R04_1.csv',
                         '../Dataset/SA01/D17_SA01_R04_2.csv',
                         '../Dataset/SA01/D17_SA01_R05_1.csv',
                         '../Dataset/SA01/D17_SA01_R05_2.csv']

path_list = []

for path in SE01_A_paths:
    path = path.replace('SE01', 'SE01')
    path_list.append(path)

path_list

['../Dataset/SE01/D01_SE01_R01.csv',
 '../Dataset/SE01/D02_SE01_R01.csv',
 '../Dataset/SE01/D03_SE01_R01.csv',
 '../Dataset/SE01/D04_SE01_R01.csv',
 '../Dataset/SA01/D05_SA01_R01_1.csv',
 '../Dataset/SA01/D05_SA01_R01_2.csv',
 '../Dataset/SA01/D05_SA01_R02_1.csv',
 '../Dataset/SA01/D05_SA01_R02_2.csv',
 '../Dataset/SA01/D05_SA01_R03_1.csv',
 '../Dataset/SA01/D05_SA01_R03_2.csv',
 '../Dataset/SA01/D05_SA01_R04_1.csv',
 '../Dataset/SA01/D05_SA01_R04_2.csv',
 '../Dataset/SA01/D05_SA01_R05_1.csv',
 '../Dataset/SA01/D05_SA01_R05_2.csv',
 '../Dataset/SA01/D06_SA01_R01_1.csv',
 '../Dataset/SA01/D06_SA01_R01_2.csv',
 '../Dataset/SA01/D06_SA01_R02_1.csv',
 '../Dataset/SA01/D06_SA01_R02_2.csv',
 '../Dataset/SA01/D06_SA01_R03_1.csv',
 '../Dataset/SA01/D06_SA01_R03_2.csv',
 '../Dataset/SA01/D06_SA01_R04_1.csv',
 '../Dataset/SA01/D06_SA01_R04_2.csv',
 '../Dataset/SA01/D06_SA01_R05_1.csv',
 '../Dataset/SA01/D06_SA01_R05_2.csv',
 '../Dataset/SE01/D07_SE01_R01.csv',
 '../Dataset/SE01/D07_SE01_R02.csv',
 '../Dataset/SE01/D07_SE01_R03.csv',
 '../Dataset/SE01/D07_SE01_R04.csv',
 '../Dataset/SE01/D07_SE01_R05.csv',
 '../Dataset/SE01/D08_SE01_R01.csv',
 '../Dataset/SE01/D08_SE01_R02.csv',
 '../Dataset/SE01/D08_SE01_R03.csv',
 '../Dataset/SE01/D08_SE01_R04.csv',
 '../Dataset/SE01/D08_SE01_R05.csv',
 '../Dataset/SE01/D09_SE01_R01.csv',
 '../Dataset/SE01/D09_SE01_R02.csv',
 '../Dataset/SE01/D09_SE01_R03.csv',
 '../Dataset/SE01/D09_SE01_R04.csv',
 '../Dataset/SE01/D09_SE01_R05.csv',
 '../Dataset/SE01/D10_SE01_R01.csv',
 '../Dataset/SE01/D10_SE01_R02.csv',
 '../Dataset/SE01/D10_SE01_R03.csv',
 '../Dataset/SE01/D10_SE01_R04.csv',
 '../Dataset/SE01/D10_SE01_R05.csv',
 '../Dataset/SE01/D11_SE01_R01.csv',
 '../Dataset/SE01/D11_SE01_R02.csv',
 '../Dataset/SE01/D11_SE01_R03.csv',
 '../Dataset/SE01/D11_SE01_R04.csv',
 '../Dataset/SE01/D11_SE01_R05.csv',
 '../Dataset/SE01/D12_SE01_R01.csv',
 '../Dataset/SE01/D12_SE01_R02.csv',
 '../Dataset/SE01/D12_SE01_R03.csv',
 '../Dataset/SE01/D12_SE01_R04.csv',
 '../Dataset/SE01/D12_SE01_R05.csv',
 '../Dataset/SE01/D13_SE01_R01.csv',
 '../Dataset/SE01/D13_SE01_R02.csv',
 '../Dataset/SE01/D13_SE01_R03.csv',
 '../Dataset/SE01/D13_SE01_R04.csv',
 '../Dataset/SE01/D13_SE01_R05.csv',
 '../Dataset/SE01/D14_SE01_R01.csv',
 '../Dataset/SE01/D14_SE01_R02.csv',
 '../Dataset/SE01/D14_SE01_R03.csv',
 '../Dataset/SE01/D14_SE01_R04.csv',
 '../Dataset/SE01/D14_SE01_R05.csv',
 '../Dataset/SA01/D17_SA01_R01_1.csv',
 '../Dataset/SA01/D17_SA01_R01_2.csv',
 '../Dataset/SA01/D17_SA01_R02_1.csv',
 '../Dataset/SA01/D17_SA01_R02_2.csv',
 '../Dataset/SA01/D17_SA01_R03_1.csv',
 '../Dataset/SA01/D17_SA01_R03_2.csv',
 '../Dataset/SA01/D17_SA01_R04_1.csv',
 '../Dataset/SA01/D17_SA01_R04_2.csv',
 '../Dataset/SA01/D17_SA01_R05_1.csv',
 '../Dataset/SA01/D17_SA01_R05_2.csv',
 '../Dataset/SE01/D16_SE01_R01.csv',
 '../Dataset/SE01/D16_SE01_R02.csv',
 '../Dataset/SE01/D16_SE01_R03.csv',
 '../Dataset/SE01/D16_SE01_R04.csv',
 '../Dataset/SE01/D16_SE01_R05.csv',
 '../Dataset/SE01/D17_SE01_R01.csv',
 '../Dataset/SE01/D17_SE01_R02.csv',
 '../Dataset/SE01/D17_SE01_R03.csv',
 '../Dataset/SE01/D17_SE01_R04.csv',
 '../Dataset/SE01/D17_SE01_R05.csv']

In [ ]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA01_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA01')
    SA01_A_paths.append(path)

SA01_A_paths