In [148]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA01_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA01')
    SA01_A_paths.append(path)

SA01_A_paths

['../Dataset/SA01/D01_SA01_R01.csv',
 '../Dataset/SA01/D02_SA01_R01.csv',
 '../Dataset/SA01/D03_SA01_R01.csv',
 '../Dataset/SA01/D04_SA01_R01.csv',
 '../Dataset/SA01/D05_SA01_R01_1.csv',
 '../Dataset/SA01/D05_SA01_R01_2.csv',
 '../Dataset/SA01/D05_SA01_R02_1.csv',
 '../Dataset/SA01/D05_SA01_R02_2.csv',
 '../Dataset/SA01/D05_SA01_R03_1.csv',
 '../Dataset/SA01/D05_SA01_R03_2.csv',
 '../Dataset/SA01/D05_SA01_R04_1.csv',
 '../Dataset/SA01/D05_SA01_R04_2.csv',
 '../Dataset/SA01/D05_SA01_R05_1.csv',
 '../Dataset/SA01/D05_SA01_R05_2.csv',
 '../Dataset/SA01/D06_SA01_R01_1.csv',
 '../Dataset/SA01/D06_SA01_R01_2.csv',
 '../Dataset/SA01/D06_SA01_R02_1.csv',
 '../Dataset/SA01/D06_SA01_R02_2.csv',
 '../Dataset/SA01/D06_SA01_R03_1.csv',
 '../Dataset/SA01/D06_SA01_R03_2.csv',
 '../Dataset/SA01/D06_SA01_R04_1.csv',
 '../Dataset/SA01/D06_SA01_R04_2.csv',
 '../Dataset/SA01/D06_SA01_R05_1.csv',
 '../Dataset/SA01/D06_SA01_R05_2.csv',
 '../Dataset/SA01/D07_SA01_R01.csv',
 '../Dataset/SA01/D07_SA01_R02.csv',
 '../Dataset/SA01/D07_SA01_R03.csv',
 '../Dataset/SA01/D07_SA01_R04.csv',
 '../Dataset/SA01/D07_SA01_R05.csv',
 '../Dataset/SA01/D08_SA01_R01.csv',
 '../Dataset/SA01/D08_SA01_R02.csv',
 '../Dataset/SA01/D08_SA01_R03.csv',
 '../Dataset/SA01/D08_SA01_R04.csv',
 '../Dataset/SA01/D08_SA01_R05.csv',
 '../Dataset/SA01/D09_SA01_R01.csv',
 '../Dataset/SA01/D09_SA01_R02.csv',
 '../Dataset/SA01/D09_SA01_R03.csv',
 '../Dataset/SA01/D09_SA01_R04.csv',
 '../Dataset/SA01/D09_SA01_R05.csv',
 '../Dataset/SA01/D10_SA01_R01.csv',
 '../Dataset/SA01/D10_SA01_R02.csv',
 '../Dataset/SA01/D10_SA01_R03.csv',
 '../Dataset/SA01/D10_SA01_R04.csv',
 '../Dataset/SA01/D10_SA01_R05.csv',
 '../Dataset/SA01/D11_SA01_R01.csv',
 '../Dataset/SA01/D11_SA01_R02.csv',
 '../Dataset/SA01/D11_SA01_R03.csv',
 '../Dataset/SA01/D11_SA01_R04.csv',
 '../Dataset/SA01/D11_SA01_R05.csv',
 '../Dataset/SA01/D12_SA01_R01.csv',
 '../Dataset/SA01/D12_SA01_R02.csv',
 '../Dataset/SA01/D12_SA01_R03.csv',
 '../Dataset/SA01/D12_SA01_R04.csv',
 '../Dataset/SA01/D12_SA01_R05.csv',
 '../Dataset/SA01/D13_SA01_R01.csv',
 '../Dataset/SA01/D13_SA01_R02.csv',
 '../Dataset/SA01/D13_SA01_R03.csv',
 '../Dataset/SA01/D13_SA01_R04.csv',
 '../Dataset/SA01/D13_SA01_R05.csv',
 '../Dataset/SA01/D14_SA01_R01.csv',
 '../Dataset/SA01/D14_SA01_R02.csv',
 '../Dataset/SA01/D14_SA01_R03.csv',
 '../Dataset/SA01/D14_SA01_R04.csv',
 '../Dataset/SA01/D14_SA01_R05.csv',
 '../Dataset/SA01/D15_SA01_R01.csv',
 '../Dataset/SA01/D15_SA01_R02.csv',
 '../Dataset/SA01/D15_SA01_R03.csv',
 '../Dataset/SA01/D15_SA01_R04.csv',
 '../Dataset/SA01/D15_SA01_R05.csv',
 '../Dataset/SA01/D16_SA01_R01.csv',
 '../Dataset/SA01/D16_SA01_R02.csv',
 '../Dataset/SA01/D16_SA01_R03.csv',
 '../Dataset/SA01/D16_SA01_R04.csv',
 '../Dataset/SA01/D16_SA01_R05.csv',
 '../Dataset/SA01/D17_SA01_R01_1.csv',
 '../Dataset/SA01/D17_SA01_R01_2.csv',
 '../Dataset/SA01/D17_SA01_R02_1.csv',
 '../Dataset/SA01/D17_SA01_R02_2.csv',
 '../Dataset/SA01/D17_SA01_R03_1.csv',
 '../Dataset/SA01/D17_SA01_R03_2.csv',
 '../Dataset/SA01/D17_SA01_R04_1.csv',
 '../Dataset/SA01/D17_SA01_R04_2.csv',
 '../Dataset/SA01/D17_SA01_R05_1.csv',
 '../Dataset/SA01/D17_SA01_R05_2.csv',
 '../Dataset/SA01/D18_SA01_R01.csv',
 '../Dataset/SA01/D18_SA01_R02.csv',
 '../Dataset/SA01/D18_SA01_R03.csv',
 '../Dataset/SA01/D18_SA01_R04.csv',
 '../Dataset/SA01/D18_SA01_R05.csv',
 '../Dataset/SA01/D19_SA01_R01.csv',
 '../Dataset/SA01/D19_SA01_R02.csv',
 '../Dataset/SA01/D19_SA01_R03.csv',
 '../Dataset/SA01/D19_SA01_R04.csv',
 '../Dataset/SA01/D19_SA01_R05.csv']

In [149]:
import pandas as pd
import numpy as np
import os

# SA01

In [150]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA01_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA01')
    SA01_A_paths.append(path)

SA01_A_paths

['../Dataset/SA01/D01_SA01_R01.csv',
 '../Dataset/SA01/D02_SA01_R01.csv',
 '../Dataset/SA01/D03_SA01_R01.csv',
 '../Dataset/SA01/D04_SA01_R01.csv',
 '../Dataset/SA01/D05_SA01_R01_1.csv',
 '../Dataset/SA01/D05_SA01_R01_2.csv',
 '../Dataset/SA01/D05_SA01_R02_1.csv',
 '../Dataset/SA01/D05_SA01_R02_2.csv',
 '../Dataset/SA01/D05_SA01_R03_1.csv',
 '../Dataset/SA01/D05_SA01_R03_2.csv',
 '../Dataset/SA01/D05_SA01_R04_1.csv',
 '../Dataset/SA01/D05_SA01_R04_2.csv',
 '../Dataset/SA01/D05_SA01_R05_1.csv',
 '../Dataset/SA01/D05_SA01_R05_2.csv',
 '../Dataset/SA01/D06_SA01_R01_1.csv',
 '../Dataset/SA01/D06_SA01_R01_2.csv',
 '../Dataset/SA01/D06_SA01_R02_1.csv',
 '../Dataset/SA01/D06_SA01_R02_2.csv',
 '../Dataset/SA01/D06_SA01_R03_1.csv',
 '../Dataset/SA01/D06_SA01_R03_2.csv',
 '../Dataset/SA01/D06_SA01_R04_1.csv',
 '../Dataset/SA01/D06_SA01_R04_2.csv',
 '../Dataset/SA01/D06_SA01_R05_1.csv',
 '../Dataset/SA01/D06_SA01_R05_2.csv',
 '../Dataset/SA01/D07_SA01_R01.csv',
 '../Dataset/SA01/D07_SA01_R02.csv',
 '../Dataset/SA01/D07_SA01_R03.csv',
 '../Dataset/SA01/D07_SA01_R04.csv',
 '../Dataset/SA01/D07_SA01_R05.csv',
 '../Dataset/SA01/D08_SA01_R01.csv',
 '../Dataset/SA01/D08_SA01_R02.csv',
 '../Dataset/SA01/D08_SA01_R03.csv',
 '../Dataset/SA01/D08_SA01_R04.csv',
 '../Dataset/SA01/D08_SA01_R05.csv',
 '../Dataset/SA01/D09_SA01_R01.csv',
 '../Dataset/SA01/D09_SA01_R02.csv',
 '../Dataset/SA01/D09_SA01_R03.csv',
 '../Dataset/SA01/D09_SA01_R04.csv',
 '../Dataset/SA01/D09_SA01_R05.csv',
 '../Dataset/SA01/D10_SA01_R01.csv',
 '../Dataset/SA01/D10_SA01_R02.csv',
 '../Dataset/SA01/D10_SA01_R03.csv',
 '../Dataset/SA01/D10_SA01_R04.csv',
 '../Dataset/SA01/D10_SA01_R05.csv',
 '../Dataset/SA01/D11_SA01_R01.csv',
 '../Dataset/SA01/D11_SA01_R02.csv',
 '../Dataset/SA01/D11_SA01_R03.csv',
 '../Dataset/SA01/D11_SA01_R04.csv',
 '../Dataset/SA01/D11_SA01_R05.csv',
 '../Dataset/SA01/D12_SA01_R01.csv',
 '../Dataset/SA01/D12_SA01_R02.csv',
 '../Dataset/SA01/D12_SA01_R03.csv',
 '../Dataset/SA01/D12_SA01_R04.csv',
 '../Dataset/SA01/D12_SA01_R05.csv',
 '../Dataset/SA01/D13_SA01_R01.csv',
 '../Dataset/SA01/D13_SA01_R02.csv',
 '../Dataset/SA01/D13_SA01_R03.csv',
 '../Dataset/SA01/D13_SA01_R04.csv',
 '../Dataset/SA01/D13_SA01_R05.csv',
 '../Dataset/SA01/D14_SA01_R01.csv',
 '../Dataset/SA01/D14_SA01_R02.csv',
 '../Dataset/SA01/D14_SA01_R03.csv',
 '../Dataset/SA01/D14_SA01_R04.csv',
 '../Dataset/SA01/D14_SA01_R05.csv',
 '../Dataset/SA01/D15_SA01_R01.csv',
 '../Dataset/SA01/D15_SA01_R02.csv',
 '../Dataset/SA01/D15_SA01_R03.csv',
 '../Dataset/SA01/D15_SA01_R04.csv',
 '../Dataset/SA01/D15_SA01_R05.csv',
 '../Dataset/SA01/D16_SA01_R01.csv',
 '../Dataset/SA01/D16_SA01_R02.csv',
 '../Dataset/SA01/D16_SA01_R03.csv',
 '../Dataset/SA01/D16_SA01_R04.csv',
 '../Dataset/SA01/D16_SA01_R05.csv',
 '../Dataset/SA01/D17_SA01_R01_1.csv',
 '../Dataset/SA01/D17_SA01_R01_2.csv',
 '../Dataset/SA01/D17_SA01_R02_1.csv',
 '../Dataset/SA01/D17_SA01_R02_2.csv',
 '../Dataset/SA01/D17_SA01_R03_1.csv',
 '../Dataset/SA01/D17_SA01_R03_2.csv',
 '../Dataset/SA01/D17_SA01_R04_1.csv',
 '../Dataset/SA01/D17_SA01_R04_2.csv',
 '../Dataset/SA01/D17_SA01_R05_1.csv',
 '../Dataset/SA01/D17_SA01_R05_2.csv',
 '../Dataset/SA01/D18_SA01_R01.csv',
 '../Dataset/SA01/D18_SA01_R02.csv',
 '../Dataset/SA01/D18_SA01_R03.csv',
 '../Dataset/SA01/D18_SA01_R04.csv',
 '../Dataset/SA01/D18_SA01_R05.csv',
 '../Dataset/SA01/D19_SA01_R01.csv',
 '../Dataset/SA01/D19_SA01_R02.csv',
 '../Dataset/SA01/D19_SA01_R03.csv',
 '../Dataset/SA01/D19_SA01_R04.csv',
 '../Dataset/SA01/D19_SA01_R05.csv']

In [151]:
list = []
final_SA01_A = pd.DataFrame(list)

for path in SA01_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA01_A = final_SA01_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA01_A.shape
target_col = row * [0]
final_SA01_A.loc[:,'target'] = target_col

final_SA01_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,205.0,196.0,194.0,196.0,202.0,236.0,250.0,277.0,318.0,344.0,...,248.0,249.0,249.0,252.0,248.0,243.0,236.0,236.0,232.0,0
0,267.0,260.0,258.0,253.0,255.0,262.0,278.0,286.0,294.0,299.0,...,358.0,337.0,319.0,299.0,272.0,263.0,251.0,241.0,221.0,0
0,110.0,100.0,83.0,75.0,67.0,66.0,69.0,110.0,169.0,224.0,...,112.0,103.0,99.0,93.0,95.0,100.0,129.0,200.0,267.0,0
0,435.0,429.0,436.0,435.0,433.0,437.0,425.0,402.0,378.0,345.0,...,195.0,198.0,184.0,163.0,151.0,172.0,198.0,197.0,191.0,0
0,342.0,340.0,338.0,335.0,331.0,329.0,325.0,318.0,307.0,307.0,...,319.0,316.0,308.0,304.0,300.0,296.0,293.0,293.0,297.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,263.0,263.0,266.0,269.0,264.0,260.0,262.0,260.0,264.0,261.0,...,262.0,263.0,261.0,262.0,262.0,263.0,261.0,261.0,265.0,0
0,263.0,262.0,264.0,264.0,266.0,264.0,266.0,265.0,263.0,261.0,...,261.0,267.0,263.0,265.0,264.0,264.0,264.0,264.0,265.0,0
0,268.0,264.0,264.0,267.0,259.0,265.0,267.0,261.0,261.0,265.0,...,265.0,269.0,266.0,273.0,267.0,267.0,265.0,265.0,265.0,0
0,263.0,262.0,265.0,265.0,263.0,259.0,263.0,268.0,264.0,265.0,...,264.0,262.0,264.0,260.0,264.0,268.0,264.0,264.0,265.0,0
0,266.0,264.0,266.0,265.0,265.0,262.0,263.0,266.0,266.0,266.0,...,265.0,266.0,267.0,267.0,264.0,263.0,266.0,262.0,266.0,0

# SA02

In [152]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA02_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA02')
    SA02_A_paths.append(path)

SA02_A_paths

['../Dataset/SA02/D01_SA02_R01.csv',
 '../Dataset/SA02/D02_SA02_R01.csv',
 '../Dataset/SA02/D03_SA02_R01.csv',
 '../Dataset/SA02/D04_SA02_R01.csv',
 '../Dataset/SA02/D05_SA02_R01_1.csv',
 '../Dataset/SA02/D05_SA02_R01_2.csv',
 '../Dataset/SA02/D05_SA02_R02_1.csv',
 '../Dataset/SA02/D05_SA02_R02_2.csv',
 '../Dataset/SA02/D05_SA02_R03_1.csv',
 '../Dataset/SA02/D05_SA02_R03_2.csv',
 '../Dataset/SA02/D05_SA02_R04_1.csv',
 '../Dataset/SA02/D05_SA02_R04_2.csv',
 '../Dataset/SA02/D05_SA02_R05_1.csv',
 '../Dataset/SA02/D05_SA02_R05_2.csv',
 '../Dataset/SA02/D06_SA02_R01_1.csv',
 '../Dataset/SA02/D06_SA02_R01_2.csv',
 '../Dataset/SA02/D06_SA02_R02_1.csv',
 '../Dataset/SA02/D06_SA02_R02_2.csv',
 '../Dataset/SA02/D06_SA02_R03_1.csv',
 '../Dataset/SA02/D06_SA02_R03_2.csv',
 '../Dataset/SA02/D06_SA02_R04_1.csv',
 '../Dataset/SA02/D06_SA02_R04_2.csv',
 '../Dataset/SA02/D06_SA02_R05_1.csv',
 '../Dataset/SA02/D06_SA02_R05_2.csv',
 '../Dataset/SA02/D07_SA02_R01.csv',
 '../Dataset/SA02/D07_SA02_R02.csv',
 '../Dataset/SA02/D07_SA02_R03.csv',
 '../Dataset/SA02/D07_SA02_R04.csv',
 '../Dataset/SA02/D07_SA02_R05.csv',
 '../Dataset/SA02/D08_SA02_R01.csv',
 '../Dataset/SA02/D08_SA02_R02.csv',
 '../Dataset/SA02/D08_SA02_R03.csv',
 '../Dataset/SA02/D08_SA02_R04.csv',
 '../Dataset/SA02/D08_SA02_R05.csv',
 '../Dataset/SA02/D09_SA02_R01.csv',
 '../Dataset/SA02/D09_SA02_R02.csv',
 '../Dataset/SA02/D09_SA02_R03.csv',
 '../Dataset/SA02/D09_SA02_R04.csv',
 '../Dataset/SA02/D09_SA02_R05.csv',
 '../Dataset/SA02/D10_SA02_R01.csv',
 '../Dataset/SA02/D10_SA02_R02.csv',
 '../Dataset/SA02/D10_SA02_R03.csv',
 '../Dataset/SA02/D10_SA02_R04.csv',
 '../Dataset/SA02/D10_SA02_R05.csv',
 '../Dataset/SA02/D11_SA02_R01.csv',
 '../Dataset/SA02/D11_SA02_R02.csv',
 '../Dataset/SA02/D11_SA02_R03.csv',
 '../Dataset/SA02/D11_SA02_R04.csv',
 '../Dataset/SA02/D11_SA02_R05.csv',
 '../Dataset/SA02/D12_SA02_R01.csv',
 '../Dataset/SA02/D12_SA02_R02.csv',
 '../Dataset/SA02/D12_SA02_R03.csv',
 '../Dataset/SA02/D12_SA02_R04.csv',
 '../Dataset/SA02/D12_SA02_R05.csv',
 '../Dataset/SA02/D13_SA02_R01.csv',
 '../Dataset/SA02/D13_SA02_R02.csv',
 '../Dataset/SA02/D13_SA02_R03.csv',
 '../Dataset/SA02/D13_SA02_R04.csv',
 '../Dataset/SA02/D13_SA02_R05.csv',
 '../Dataset/SA02/D14_SA02_R01.csv',
 '../Dataset/SA02/D14_SA02_R02.csv',
 '../Dataset/SA02/D14_SA02_R03.csv',
 '../Dataset/SA02/D14_SA02_R04.csv',
 '../Dataset/SA02/D14_SA02_R05.csv',
 '../Dataset/SA02/D15_SA02_R01.csv',
 '../Dataset/SA02/D15_SA02_R02.csv',
 '../Dataset/SA02/D15_SA02_R03.csv',
 '../Dataset/SA02/D15_SA02_R04.csv',
 '../Dataset/SA02/D15_SA02_R05.csv',
 '../Dataset/SA02/D16_SA02_R01.csv',
 '../Dataset/SA02/D16_SA02_R02.csv',
 '../Dataset/SA02/D16_SA02_R03.csv',
 '../Dataset/SA02/D16_SA02_R04.csv',
 '../Dataset/SA02/D16_SA02_R05.csv',
 '../Dataset/SA02/D17_SA02_R01_1.csv',
 '../Dataset/SA02/D17_SA02_R01_2.csv',
 '../Dataset/SA02/D17_SA02_R02_1.csv',
 '../Dataset/SA02/D17_SA02_R02_2.csv',
 '../Dataset/SA02/D17_SA02_R03_1.csv',
 '../Dataset/SA02/D17_SA02_R03_2.csv',
 '../Dataset/SA02/D17_SA02_R04_1.csv',
 '../Dataset/SA02/D17_SA02_R04_2.csv',
 '../Dataset/SA02/D17_SA02_R05_1.csv',
 '../Dataset/SA02/D17_SA02_R05_2.csv',
 '../Dataset/SA02/D18_SA02_R01.csv',
 '../Dataset/SA02/D18_SA02_R02.csv',
 '../Dataset/SA02/D18_SA02_R03.csv',
 '../Dataset/SA02/D18_SA02_R04.csv',
 '../Dataset/SA02/D18_SA02_R05.csv',
 '../Dataset/SA02/D19_SA02_R01.csv',
 '../Dataset/SA02/D19_SA02_R02.csv',
 '../Dataset/SA02/D19_SA02_R03.csv',
 '../Dataset/SA02/D19_SA02_R04.csv',
 '../Dataset/SA02/D19_SA02_R05.csv']

In [153]:
list = []
final_SA02_A = pd.DataFrame(list)

for path in SA02_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA02_A = final_SA02_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA02_A.shape
target_col = row * [0]
final_SA02_A.loc[:,'target'] = target_col

final_SA02_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,257.0,257.0,258.0,255.0,251.0,250.0,251.0,248.0,247.0,248.0,...,242.0,241.0,238.0,238.0,236.0,237.0,233.0,234.0,239.0,0
0,250.0,254.0,254.0,251.0,253.0,253.0,253.0,255.0,250.0,249.0,...,265.0,265.0,262.0,261.0,259.0,260.0,253.0,251.0,252.0,0
0,554.0,556.0,550.0,537.0,547.0,550.0,576.0,600.0,626.0,642.0,...,582.0,599.0,589.0,536.0,413.0,277.0,260.0,329.0,398.0,0
0,528.0,509.0,472.0,445.0,441.0,450.0,440.0,428.0,413.0,391.0,...,709.0,744.0,767.0,780.0,772.0,739.0,677.0,599.0,530.0,0
0,248.0,249.0,247.0,255.0,256.0,256.0,254.0,254.0,254.0,244.0,...,192.0,188.0,187.0,185.0,182.0,182.0,184.0,190.0,190.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,251.0,249.0,248.0,252.0,247.0,252.0,248.0,245.0,248.0,249.0,...,248.0,247.0,244.0,248.0,248.0,248.0,250.0,249.0,251.0,0
0,245.0,243.0,247.0,247.0,248.0,249.0,251.0,247.0,248.0,253.0,...,245.0,249.0,250.0,247.0,245.0,247.0,249.0,251.0,248.0,0
0,250.0,250.0,247.0,247.0,250.0,248.0,252.0,251.0,251.0,248.0,...,249.0,246.0,251.0,247.0,247.0,249.0,250.0,249.0,246.0,0
0,251.0,246.0,247.0,252.0,249.0,255.0,249.0,250.0,250.0,248.0,...,251.0,246.0,249.0,246.0,245.0,246.0,246.0,247.0,248.0,0
0,250.0,251.0,251.0,250.0,241.0,248.0,249.0,249.0,250.0,247.0,...,247.0,251.0,244.0,247.0,248.0,246.0,249.0,250.0,250.0,0

# SA03

In [154]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA03_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA03')
    SA03_A_paths.append(path)

SA03_A_paths

['../Dataset/SA03/D01_SA03_R01.csv',
 '../Dataset/SA03/D02_SA03_R01.csv',
 '../Dataset/SA03/D03_SA03_R01.csv',
 '../Dataset/SA03/D04_SA03_R01.csv',
 '../Dataset/SA03/D05_SA03_R01_1.csv',
 '../Dataset/SA03/D05_SA03_R01_2.csv',
 '../Dataset/SA03/D05_SA03_R02_1.csv',
 '../Dataset/SA03/D05_SA03_R02_2.csv',
 '../Dataset/SA03/D05_SA03_R03_1.csv',
 '../Dataset/SA03/D05_SA03_R03_2.csv',
 '../Dataset/SA03/D05_SA03_R04_1.csv',
 '../Dataset/SA03/D05_SA03_R04_2.csv',
 '../Dataset/SA03/D05_SA03_R05_1.csv',
 '../Dataset/SA03/D05_SA03_R05_2.csv',
 '../Dataset/SA03/D06_SA03_R01_1.csv',
 '../Dataset/SA03/D06_SA03_R01_2.csv',
 '../Dataset/SA03/D06_SA03_R02_1.csv',
 '../Dataset/SA03/D06_SA03_R02_2.csv',
 '../Dataset/SA03/D06_SA03_R03_1.csv',
 '../Dataset/SA03/D06_SA03_R03_2.csv',
 '../Dataset/SA03/D06_SA03_R04_1.csv',
 '../Dataset/SA03/D06_SA03_R04_2.csv',
 '../Dataset/SA03/D06_SA03_R05_1.csv',
 '../Dataset/SA03/D06_SA03_R05_2.csv',
 '../Dataset/SA03/D07_SA03_R01.csv',
 '../Dataset/SA03/D07_SA03_R02.csv',
 '../Dataset/SA03/D07_SA03_R03.csv',
 '../Dataset/SA03/D07_SA03_R04.csv',
 '../Dataset/SA03/D07_SA03_R05.csv',
 '../Dataset/SA03/D08_SA03_R01.csv',
 '../Dataset/SA03/D08_SA03_R02.csv',
 '../Dataset/SA03/D08_SA03_R03.csv',
 '../Dataset/SA03/D08_SA03_R04.csv',
 '../Dataset/SA03/D08_SA03_R05.csv',
 '../Dataset/SA03/D09_SA03_R01.csv',
 '../Dataset/SA03/D09_SA03_R02.csv',
 '../Dataset/SA03/D09_SA03_R03.csv',
 '../Dataset/SA03/D09_SA03_R04.csv',
 '../Dataset/SA03/D09_SA03_R05.csv',
 '../Dataset/SA03/D10_SA03_R01.csv',
 '../Dataset/SA03/D10_SA03_R02.csv',
 '../Dataset/SA03/D10_SA03_R03.csv',
 '../Dataset/SA03/D10_SA03_R04.csv',
 '../Dataset/SA03/D10_SA03_R05.csv',
 '../Dataset/SA03/D11_SA03_R01.csv',
 '../Dataset/SA03/D11_SA03_R02.csv',
 '../Dataset/SA03/D11_SA03_R03.csv',
 '../Dataset/SA03/D11_SA03_R04.csv',
 '../Dataset/SA03/D11_SA03_R05.csv',
 '../Dataset/SA03/D12_SA03_R01.csv',
 '../Dataset/SA03/D12_SA03_R02.csv',
 '../Dataset/SA03/D12_SA03_R03.csv',
 '../Dataset/SA03/D12_SA03_R04.csv',
 '../Dataset/SA03/D12_SA03_R05.csv',
 '../Dataset/SA03/D13_SA03_R01.csv',
 '../Dataset/SA03/D13_SA03_R02.csv',
 '../Dataset/SA03/D13_SA03_R03.csv',
 '../Dataset/SA03/D13_SA03_R04.csv',
 '../Dataset/SA03/D13_SA03_R05.csv',
 '../Dataset/SA03/D14_SA03_R01.csv',
 '../Dataset/SA03/D14_SA03_R02.csv',
 '../Dataset/SA03/D14_SA03_R03.csv',
 '../Dataset/SA03/D14_SA03_R04.csv',
 '../Dataset/SA03/D14_SA03_R05.csv',
 '../Dataset/SA03/D15_SA03_R01.csv',
 '../Dataset/SA03/D15_SA03_R02.csv',
 '../Dataset/SA03/D15_SA03_R03.csv',
 '../Dataset/SA03/D15_SA03_R04.csv',
 '../Dataset/SA03/D15_SA03_R05.csv',
 '../Dataset/SA03/D16_SA03_R01.csv',
 '../Dataset/SA03/D16_SA03_R02.csv',
 '../Dataset/SA03/D16_SA03_R03.csv',
 '../Dataset/SA03/D16_SA03_R04.csv',
 '../Dataset/SA03/D16_SA03_R05.csv',
 '../Dataset/SA03/D17_SA03_R01_1.csv',
 '../Dataset/SA03/D17_SA03_R01_2.csv',
 '../Dataset/SA03/D17_SA03_R02_1.csv',
 '../Dataset/SA03/D17_SA03_R02_2.csv',
 '../Dataset/SA03/D17_SA03_R03_1.csv',
 '../Dataset/SA03/D17_SA03_R03_2.csv',
 '../Dataset/SA03/D17_SA03_R04_1.csv',
 '../Dataset/SA03/D17_SA03_R04_2.csv',
 '../Dataset/SA03/D17_SA03_R05_1.csv',
 '../Dataset/SA03/D17_SA03_R05_2.csv',
 '../Dataset/SA03/D18_SA03_R01.csv',
 '../Dataset/SA03/D18_SA03_R02.csv',
 '../Dataset/SA03/D18_SA03_R03.csv',
 '../Dataset/SA03/D18_SA03_R04.csv',
 '../Dataset/SA03/D18_SA03_R05.csv',
 '../Dataset/SA03/D19_SA03_R01.csv',
 '../Dataset/SA03/D19_SA03_R02.csv',
 '../Dataset/SA03/D19_SA03_R03.csv',
 '../Dataset/SA03/D19_SA03_R04.csv',
 '../Dataset/SA03/D19_SA03_R05.csv']

In [155]:
list = []
final_SA03_A = pd.DataFrame(list)

for path in SA03_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA03_A = final_SA03_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA03_A.shape
target_col = row * [0]
final_SA03_A.loc[:,'target'] = target_col

final_SA03_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,273.0,273.0,272.0,275.0,274.0,276.0,273.0,272.0,273.0,274.0,...,274.0,273.0,274.0,276.0,274.0,275.0,270.0,273.0,275.0,0
0,270.0,269.0,269.0,272.0,274.0,271.0,270.0,269.0,270.0,271.0,...,268.0,269.0,268.0,267.0,268.0,270.0,267.0,266.0,270.0,0
0,271.0,272.0,271.0,270.0,268.0,272.0,271.0,274.0,274.0,274.0,...,272.0,271.0,274.0,273.0,272.0,273.0,270.0,271.0,273.0,0
0,269.0,270.0,269.0,267.0,270.0,268.0,268.0,271.0,271.0,270.0,...,332.0,337.0,339.0,332.0,329.0,322.0,308.0,301.0,285.0,0
0,267.0,270.0,269.0,267.0,269.0,271.0,270.0,270.0,267.0,269.0,...,245.0,239.0,239.0,233.0,228.0,222.0,220.0,221.0,219.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,271.0,276.0,273.0,272.0,273.0,274.0,272.0,272.0,275.0,271.0,...,275.0,275.0,274.0,275.0,273.0,276.0,276.0,273.0,275.0,0
0,273.0,271.0,273.0,272.0,274.0,271.0,273.0,272.0,272.0,272.0,...,274.0,276.0,273.0,271.0,274.0,273.0,271.0,272.0,271.0,0
0,274.0,272.0,272.0,273.0,273.0,275.0,271.0,272.0,272.0,273.0,...,269.0,274.0,271.0,273.0,274.0,272.0,272.0,275.0,276.0,0
0,270.0,274.0,275.0,274.0,274.0,272.0,271.0,270.0,271.0,272.0,...,272.0,270.0,274.0,271.0,271.0,271.0,271.0,271.0,273.0,0
0,273.0,271.0,271.0,270.0,272.0,272.0,270.0,272.0,269.0,274.0,...,273.0,276.0,278.0,276.0,276.0,273.0,274.0,276.0,272.0,0

# SA04

In [156]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA04_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA04')
    SA04_A_paths.append(path)

SA04_A_paths

['../Dataset/SA04/D01_SA04_R01.csv',
 '../Dataset/SA04/D02_SA04_R01.csv',
 '../Dataset/SA04/D03_SA04_R01.csv',
 '../Dataset/SA04/D04_SA04_R01.csv',
 '../Dataset/SA04/D05_SA04_R01_1.csv',
 '../Dataset/SA04/D05_SA04_R01_2.csv',
 '../Dataset/SA04/D05_SA04_R02_1.csv',
 '../Dataset/SA04/D05_SA04_R02_2.csv',
 '../Dataset/SA04/D05_SA04_R03_1.csv',
 '../Dataset/SA04/D05_SA04_R03_2.csv',
 '../Dataset/SA04/D05_SA04_R04_1.csv',
 '../Dataset/SA04/D05_SA04_R04_2.csv',
 '../Dataset/SA04/D05_SA04_R05_1.csv',
 '../Dataset/SA04/D05_SA04_R05_2.csv',
 '../Dataset/SA04/D06_SA04_R01_1.csv',
 '../Dataset/SA04/D06_SA04_R01_2.csv',
 '../Dataset/SA04/D06_SA04_R02_1.csv',
 '../Dataset/SA04/D06_SA04_R02_2.csv',
 '../Dataset/SA04/D06_SA04_R03_1.csv',
 '../Dataset/SA04/D06_SA04_R03_2.csv',
 '../Dataset/SA04/D06_SA04_R04_1.csv',
 '../Dataset/SA04/D06_SA04_R04_2.csv',
 '../Dataset/SA04/D06_SA04_R05_1.csv',
 '../Dataset/SA04/D06_SA04_R05_2.csv',
 '../Dataset/SA04/D07_SA04_R01.csv',
 '../Dataset/SA04/D07_SA04_R02.csv',
 '../Dataset/SA04/D07_SA04_R03.csv',
 '../Dataset/SA04/D07_SA04_R04.csv',
 '../Dataset/SA04/D07_SA04_R05.csv',
 '../Dataset/SA04/D08_SA04_R01.csv',
 '../Dataset/SA04/D08_SA04_R02.csv',
 '../Dataset/SA04/D08_SA04_R03.csv',
 '../Dataset/SA04/D08_SA04_R04.csv',
 '../Dataset/SA04/D08_SA04_R05.csv',
 '../Dataset/SA04/D09_SA04_R01.csv',
 '../Dataset/SA04/D09_SA04_R02.csv',
 '../Dataset/SA04/D09_SA04_R03.csv',
 '../Dataset/SA04/D09_SA04_R04.csv',
 '../Dataset/SA04/D09_SA04_R05.csv',
 '../Dataset/SA04/D10_SA04_R01.csv',
 '../Dataset/SA04/D10_SA04_R02.csv',
 '../Dataset/SA04/D10_SA04_R03.csv',
 '../Dataset/SA04/D10_SA04_R04.csv',
 '../Dataset/SA04/D10_SA04_R05.csv',
 '../Dataset/SA04/D11_SA04_R01.csv',
 '../Dataset/SA04/D11_SA04_R02.csv',
 '../Dataset/SA04/D11_SA04_R03.csv',
 '../Dataset/SA04/D11_SA04_R04.csv',
 '../Dataset/SA04/D11_SA04_R05.csv',
 '../Dataset/SA04/D12_SA04_R01.csv',
 '../Dataset/SA04/D12_SA04_R02.csv',
 '../Dataset/SA04/D12_SA04_R03.csv',
 '../Dataset/SA04/D12_SA04_R04.csv',
 '../Dataset/SA04/D12_SA04_R05.csv',
 '../Dataset/SA04/D13_SA04_R01.csv',
 '../Dataset/SA04/D13_SA04_R02.csv',
 '../Dataset/SA04/D13_SA04_R03.csv',
 '../Dataset/SA04/D13_SA04_R04.csv',
 '../Dataset/SA04/D13_SA04_R05.csv',
 '../Dataset/SA04/D14_SA04_R01.csv',
 '../Dataset/SA04/D14_SA04_R02.csv',
 '../Dataset/SA04/D14_SA04_R03.csv',
 '../Dataset/SA04/D14_SA04_R04.csv',
 '../Dataset/SA04/D14_SA04_R05.csv',
 '../Dataset/SA04/D15_SA04_R01.csv',
 '../Dataset/SA04/D15_SA04_R02.csv',
 '../Dataset/SA04/D15_SA04_R03.csv',
 '../Dataset/SA04/D15_SA04_R04.csv',
 '../Dataset/SA04/D15_SA04_R05.csv',
 '../Dataset/SA04/D16_SA04_R01.csv',
 '../Dataset/SA04/D16_SA04_R02.csv',
 '../Dataset/SA04/D16_SA04_R03.csv',
 '../Dataset/SA04/D16_SA04_R04.csv',
 '../Dataset/SA04/D16_SA04_R05.csv',
 '../Dataset/SA04/D17_SA04_R01_1.csv',
 '../Dataset/SA04/D17_SA04_R01_2.csv',
 '../Dataset/SA04/D17_SA04_R02_1.csv',
 '../Dataset/SA04/D17_SA04_R02_2.csv',
 '../Dataset/SA04/D17_SA04_R03_1.csv',
 '../Dataset/SA04/D17_SA04_R03_2.csv',
 '../Dataset/SA04/D17_SA04_R04_1.csv',
 '../Dataset/SA04/D17_SA04_R04_2.csv',
 '../Dataset/SA04/D17_SA04_R05_1.csv',
 '../Dataset/SA04/D17_SA04_R05_2.csv',
 '../Dataset/SA04/D18_SA04_R01.csv',
 '../Dataset/SA04/D18_SA04_R02.csv',
 '../Dataset/SA04/D18_SA04_R03.csv',
 '../Dataset/SA04/D18_SA04_R04.csv',
 '../Dataset/SA04/D18_SA04_R05.csv',
 '../Dataset/SA04/D19_SA04_R01.csv',
 '../Dataset/SA04/D19_SA04_R02.csv',
 '../Dataset/SA04/D19_SA04_R03.csv',
 '../Dataset/SA04/D19_SA04_R04.csv',
 '../Dataset/SA04/D19_SA04_R05.csv']

In [157]:
list = []
final_SA04_A = pd.DataFrame(list)

for path in SA04_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA04_A = final_SA04_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA04_A.shape
target_col = row * [0]
final_SA04_A.loc[:,'target'] = target_col

final_SA04_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,258.0,261.0,259.0,260.0,262.0,264.0,266.0,267.0,268.0,274.0,...,293.0,290.0,291.0,288.0,274.0,276.0,273.0,276.0,273.0,0
0,266.0,264.0,267.0,267.0,267.0,268.0,266.0,263.0,264.0,263.0,...,277.0,280.0,277.0,276.0,272.0,266.0,256.0,256.0,247.0,0
0,256.0,256.0,251.0,252.0,251.0,257.0,260.0,261.0,259.0,263.0,...,359.0,341.0,323.0,297.0,296.0,289.0,282.0,282.0,278.0,0
0,255.0,253.0,251.0,251.0,246.0,248.0,246.0,246.0,243.0,243.0,...,89.0,100.0,106.0,103.0,81.0,64.0,66.0,87.0,113.0,0
0,250.0,246.0,247.0,247.0,244.0,242.0,243.0,245.0,244.0,244.0,...,253.0,252.0,249.0,246.0,251.0,250.0,253.0,259.0,264.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,268.0,266.0,264.0,268.0,267.0,266.0,263.0,265.0,264.0,264.0,...,268.0,269.0,268.0,268.0,268.0,270.0,271.0,268.0,269.0,0
0,278.0,273.0,271.0,271.0,271.0,274.0,272.0,272.0,271.0,272.0,...,269.0,270.0,271.0,272.0,272.0,270.0,269.0,268.0,268.0,0
0,262.0,261.0,268.0,266.0,266.0,263.0,266.0,264.0,266.0,263.0,...,267.0,265.0,267.0,266.0,265.0,266.0,262.0,267.0,265.0,0
0,264.0,261.0,263.0,264.0,273.0,261.0,260.0,260.0,264.0,262.0,...,259.0,258.0,259.0,261.0,259.0,261.0,262.0,260.0,259.0,0
0,263.0,261.0,260.0,261.0,259.0,258.0,260.0,263.0,265.0,268.0,...,262.0,262.0,260.0,259.0,259.0,256.0,256.0,250.0,254.0,0

# SA05

In [158]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA05_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA05')
    SA05_A_paths.append(path)

SA05_A_paths

['../Dataset/SA05/D01_SA05_R01.csv',
 '../Dataset/SA05/D02_SA05_R01.csv',
 '../Dataset/SA05/D03_SA05_R01.csv',
 '../Dataset/SA05/D04_SA05_R01.csv',
 '../Dataset/SA05/D05_SA05_R01_1.csv',
 '../Dataset/SA05/D05_SA05_R01_2.csv',
 '../Dataset/SA05/D05_SA05_R02_1.csv',
 '../Dataset/SA05/D05_SA05_R02_2.csv',
 '../Dataset/SA05/D05_SA05_R03_1.csv',
 '../Dataset/SA05/D05_SA05_R03_2.csv',
 '../Dataset/SA05/D05_SA05_R04_1.csv',
 '../Dataset/SA05/D05_SA05_R04_2.csv',
 '../Dataset/SA05/D05_SA05_R05_1.csv',
 '../Dataset/SA05/D05_SA05_R05_2.csv',
 '../Dataset/SA05/D06_SA05_R01_1.csv',
 '../Dataset/SA05/D06_SA05_R01_2.csv',
 '../Dataset/SA05/D06_SA05_R02_1.csv',
 '../Dataset/SA05/D06_SA05_R02_2.csv',
 '../Dataset/SA05/D06_SA05_R03_1.csv',
 '../Dataset/SA05/D06_SA05_R03_2.csv',
 '../Dataset/SA05/D06_SA05_R04_1.csv',
 '../Dataset/SA05/D06_SA05_R04_2.csv',
 '../Dataset/SA05/D06_SA05_R05_1.csv',
 '../Dataset/SA05/D06_SA05_R05_2.csv',
 '../Dataset/SA05/D07_SA05_R01.csv',
 '../Dataset/SA05/D07_SA05_R02.csv',
 '../Dataset/SA05/D07_SA05_R03.csv',
 '../Dataset/SA05/D07_SA05_R04.csv',
 '../Dataset/SA05/D07_SA05_R05.csv',
 '../Dataset/SA05/D08_SA05_R01.csv',
 '../Dataset/SA05/D08_SA05_R02.csv',
 '../Dataset/SA05/D08_SA05_R03.csv',
 '../Dataset/SA05/D08_SA05_R04.csv',
 '../Dataset/SA05/D08_SA05_R05.csv',
 '../Dataset/SA05/D09_SA05_R01.csv',
 '../Dataset/SA05/D09_SA05_R02.csv',
 '../Dataset/SA05/D09_SA05_R03.csv',
 '../Dataset/SA05/D09_SA05_R04.csv',
 '../Dataset/SA05/D09_SA05_R05.csv',
 '../Dataset/SA05/D10_SA05_R01.csv',
 '../Dataset/SA05/D10_SA05_R02.csv',
 '../Dataset/SA05/D10_SA05_R03.csv',
 '../Dataset/SA05/D10_SA05_R04.csv',
 '../Dataset/SA05/D10_SA05_R05.csv',
 '../Dataset/SA05/D11_SA05_R01.csv',
 '../Dataset/SA05/D11_SA05_R02.csv',
 '../Dataset/SA05/D11_SA05_R03.csv',
 '../Dataset/SA05/D11_SA05_R04.csv',
 '../Dataset/SA05/D11_SA05_R05.csv',
 '../Dataset/SA05/D12_SA05_R01.csv',
 '../Dataset/SA05/D12_SA05_R02.csv',
 '../Dataset/SA05/D12_SA05_R03.csv',
 '../Dataset/SA05/D12_SA05_R04.csv',
 '../Dataset/SA05/D12_SA05_R05.csv',
 '../Dataset/SA05/D13_SA05_R01.csv',
 '../Dataset/SA05/D13_SA05_R02.csv',
 '../Dataset/SA05/D13_SA05_R03.csv',
 '../Dataset/SA05/D13_SA05_R04.csv',
 '../Dataset/SA05/D13_SA05_R05.csv',
 '../Dataset/SA05/D14_SA05_R01.csv',
 '../Dataset/SA05/D14_SA05_R02.csv',
 '../Dataset/SA05/D14_SA05_R03.csv',
 '../Dataset/SA05/D14_SA05_R04.csv',
 '../Dataset/SA05/D14_SA05_R05.csv',
 '../Dataset/SA05/D15_SA05_R01.csv',
 '../Dataset/SA05/D15_SA05_R02.csv',
 '../Dataset/SA05/D15_SA05_R03.csv',
 '../Dataset/SA05/D15_SA05_R04.csv',
 '../Dataset/SA05/D15_SA05_R05.csv',
 '../Dataset/SA05/D16_SA05_R01.csv',
 '../Dataset/SA05/D16_SA05_R02.csv',
 '../Dataset/SA05/D16_SA05_R03.csv',
 '../Dataset/SA05/D16_SA05_R04.csv',
 '../Dataset/SA05/D16_SA05_R05.csv',
 '../Dataset/SA05/D17_SA05_R01_1.csv',
 '../Dataset/SA05/D17_SA05_R01_2.csv',
 '../Dataset/SA05/D17_SA05_R02_1.csv',
 '../Dataset/SA05/D17_SA05_R02_2.csv',
 '../Dataset/SA05/D17_SA05_R03_1.csv',
 '../Dataset/SA05/D17_SA05_R03_2.csv',
 '../Dataset/SA05/D17_SA05_R04_1.csv',
 '../Dataset/SA05/D17_SA05_R04_2.csv',
 '../Dataset/SA05/D17_SA05_R05_1.csv',
 '../Dataset/SA05/D17_SA05_R05_2.csv',
 '../Dataset/SA05/D18_SA05_R01.csv',
 '../Dataset/SA05/D18_SA05_R02.csv',
 '../Dataset/SA05/D18_SA05_R03.csv',
 '../Dataset/SA05/D18_SA05_R04.csv',
 '../Dataset/SA05/D18_SA05_R05.csv',
 '../Dataset/SA05/D19_SA05_R01.csv',
 '../Dataset/SA05/D19_SA05_R02.csv',
 '../Dataset/SA05/D19_SA05_R03.csv',
 '../Dataset/SA05/D19_SA05_R04.csv',
 '../Dataset/SA05/D19_SA05_R05.csv']

In [159]:
list = []
final_SA05_A = pd.DataFrame(list)

for path in SA05_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA05_A = final_SA05_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA05_A.shape
target_col = row * [0]
final_SA05_A.loc[:,'target'] = target_col

final_SA05_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,252.0,247.0,249.0,249.0,245.0,245.0,250.0,248.0,244.0,242.0,...,241.0,240.0,234.0,236.0,234.0,229.0,228.0,227.0,221.0,0
0,240.0,240.0,241.0,248.0,242.0,242.0,249.0,250.0,249.0,248.0,...,294.0,303.0,310.0,320.0,338.0,359.0,374.0,397.0,404.0,0
0,143.0,349.0,493.0,480.0,350.0,404.0,484.0,503.0,535.0,588.0,...,106.0,95.0,82.0,56.0,46.0,53.0,64.0,83.0,92.0,0
0,237.0,237.0,238.0,237.0,235.0,228.0,234.0,226.0,226.0,222.0,...,236.0,245.0,260.0,271.0,278.0,296.0,309.0,320.0,335.0,0
0,220.0,221.0,219.0,223.0,225.0,230.0,238.0,243.0,249.0,260.0,...,241.0,240.0,241.0,245.0,251.0,255.0,260.0,261.0,266.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,250.0,251.0,247.0,251.0,248.0,245.0,247.0,245.0,249.0,246.0,...,245.0,247.0,249.0,243.0,249.0,246.0,250.0,249.0,248.0,0
0,250.0,249.0,248.0,249.0,250.0,249.0,253.0,248.0,249.0,251.0,...,249.0,251.0,247.0,248.0,246.0,250.0,246.0,249.0,251.0,0
0,249.0,247.0,244.0,245.0,248.0,245.0,249.0,251.0,249.0,249.0,...,249.0,250.0,248.0,248.0,248.0,248.0,244.0,245.0,247.0,0
0,247.0,248.0,245.0,245.0,250.0,251.0,246.0,246.0,247.0,242.0,...,249.0,254.0,250.0,255.0,252.0,251.0,250.0,248.0,247.0,0
0,246.0,248.0,252.0,248.0,247.0,243.0,248.0,249.0,253.0,248.0,...,243.0,247.0,245.0,248.0,246.0,247.0,248.0,248.0,248.0,0

# SA06

In [160]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA06_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA06')
    SA06_A_paths.append(path)

SA06_A_paths

['../Dataset/SA06/D01_SA06_R01.csv',
 '../Dataset/SA06/D02_SA06_R01.csv',
 '../Dataset/SA06/D03_SA06_R01.csv',
 '../Dataset/SA06/D04_SA06_R01.csv',
 '../Dataset/SA06/D05_SA06_R01_1.csv',
 '../Dataset/SA06/D05_SA06_R01_2.csv',
 '../Dataset/SA06/D05_SA06_R02_1.csv',
 '../Dataset/SA06/D05_SA06_R02_2.csv',
 '../Dataset/SA06/D05_SA06_R03_1.csv',
 '../Dataset/SA06/D05_SA06_R03_2.csv',
 '../Dataset/SA06/D05_SA06_R04_1.csv',
 '../Dataset/SA06/D05_SA06_R04_2.csv',
 '../Dataset/SA06/D05_SA06_R05_1.csv',
 '../Dataset/SA06/D05_SA06_R05_2.csv',
 '../Dataset/SA06/D06_SA06_R01_1.csv',
 '../Dataset/SA06/D06_SA06_R01_2.csv',
 '../Dataset/SA06/D06_SA06_R02_1.csv',
 '../Dataset/SA06/D06_SA06_R02_2.csv',
 '../Dataset/SA06/D06_SA06_R03_1.csv',
 '../Dataset/SA06/D06_SA06_R03_2.csv',
 '../Dataset/SA06/D06_SA06_R04_1.csv',
 '../Dataset/SA06/D06_SA06_R04_2.csv',
 '../Dataset/SA06/D06_SA06_R05_1.csv',
 '../Dataset/SA06/D06_SA06_R05_2.csv',
 '../Dataset/SA06/D07_SA06_R01.csv',
 '../Dataset/SA06/D07_SA06_R02.csv',
 '../Dataset/SA06/D07_SA06_R03.csv',
 '../Dataset/SA06/D07_SA06_R04.csv',
 '../Dataset/SA06/D07_SA06_R05.csv',
 '../Dataset/SA06/D08_SA06_R01.csv',
 '../Dataset/SA06/D08_SA06_R02.csv',
 '../Dataset/SA06/D08_SA06_R03.csv',
 '../Dataset/SA06/D08_SA06_R04.csv',
 '../Dataset/SA06/D08_SA06_R05.csv',
 '../Dataset/SA06/D09_SA06_R01.csv',
 '../Dataset/SA06/D09_SA06_R02.csv',
 '../Dataset/SA06/D09_SA06_R03.csv',
 '../Dataset/SA06/D09_SA06_R04.csv',
 '../Dataset/SA06/D09_SA06_R05.csv',
 '../Dataset/SA06/D10_SA06_R01.csv',
 '../Dataset/SA06/D10_SA06_R02.csv',
 '../Dataset/SA06/D10_SA06_R03.csv',
 '../Dataset/SA06/D10_SA06_R04.csv',
 '../Dataset/SA06/D10_SA06_R05.csv',
 '../Dataset/SA06/D11_SA06_R01.csv',
 '../Dataset/SA06/D11_SA06_R02.csv',
 '../Dataset/SA06/D11_SA06_R03.csv',
 '../Dataset/SA06/D11_SA06_R04.csv',
 '../Dataset/SA06/D11_SA06_R05.csv',
 '../Dataset/SA06/D12_SA06_R01.csv',
 '../Dataset/SA06/D12_SA06_R02.csv',
 '../Dataset/SA06/D12_SA06_R03.csv',
 '../Dataset/SA06/D12_SA06_R04.csv',
 '../Dataset/SA06/D12_SA06_R05.csv',
 '../Dataset/SA06/D13_SA06_R01.csv',
 '../Dataset/SA06/D13_SA06_R02.csv',
 '../Dataset/SA06/D13_SA06_R03.csv',
 '../Dataset/SA06/D13_SA06_R04.csv',
 '../Dataset/SA06/D13_SA06_R05.csv',
 '../Dataset/SA06/D14_SA06_R01.csv',
 '../Dataset/SA06/D14_SA06_R02.csv',
 '../Dataset/SA06/D14_SA06_R03.csv',
 '../Dataset/SA06/D14_SA06_R04.csv',
 '../Dataset/SA06/D14_SA06_R05.csv',
 '../Dataset/SA06/D15_SA06_R01.csv',
 '../Dataset/SA06/D15_SA06_R02.csv',
 '../Dataset/SA06/D15_SA06_R03.csv',
 '../Dataset/SA06/D15_SA06_R04.csv',
 '../Dataset/SA06/D15_SA06_R05.csv',
 '../Dataset/SA06/D16_SA06_R01.csv',
 '../Dataset/SA06/D16_SA06_R02.csv',
 '../Dataset/SA06/D16_SA06_R03.csv',
 '../Dataset/SA06/D16_SA06_R04.csv',
 '../Dataset/SA06/D16_SA06_R05.csv',
 '../Dataset/SA06/D17_SA06_R01_1.csv',
 '../Dataset/SA06/D17_SA06_R01_2.csv',
 '../Dataset/SA06/D17_SA06_R02_1.csv',
 '../Dataset/SA06/D17_SA06_R02_2.csv',
 '../Dataset/SA06/D17_SA06_R03_1.csv',
 '../Dataset/SA06/D17_SA06_R03_2.csv',
 '../Dataset/SA06/D17_SA06_R04_1.csv',
 '../Dataset/SA06/D17_SA06_R04_2.csv',
 '../Dataset/SA06/D17_SA06_R05_1.csv',
 '../Dataset/SA06/D17_SA06_R05_2.csv',
 '../Dataset/SA06/D18_SA06_R01.csv',
 '../Dataset/SA06/D18_SA06_R02.csv',
 '../Dataset/SA06/D18_SA06_R03.csv',
 '../Dataset/SA06/D18_SA06_R04.csv',
 '../Dataset/SA06/D18_SA06_R05.csv',
 '../Dataset/SA06/D19_SA06_R01.csv',
 '../Dataset/SA06/D19_SA06_R02.csv',
 '../Dataset/SA06/D19_SA06_R03.csv',
 '../Dataset/SA06/D19_SA06_R04.csv',
 '../Dataset/SA06/D19_SA06_R05.csv']

In [205]:
list = []
final_SA06_A = pd.DataFrame(list)

for path in SA06_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SA06_A = final_SA06_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA06_A.shape
target_col = row * [0]
final_SA06_A.loc[:,'target'] = target_col

final_SA06_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,248.0,246.0,249.0,248.0,251.0,255.0,255.0,258.0,261.0,261.0,...,249.0,249.0,251.0,250.0,253.0,251.0,253.0,252.0,255.0,0
0,277.0,277.0,277.0,277.0,275.0,276.0,277.0,278.0,282.0,280.0,...,294.0,302.0,306.0,321.0,323.0,325.0,324.0,315.0,308.0,0
0,210.0,208.0,214.0,221.0,225.0,233.0,239.0,250.0,255.0,262.0,...,378.0,379.0,367.0,362.0,355.0,353.0,351.0,352.0,346.0,0
0,255.0,263.0,258.0,262.0,261.0,263.0,262.0,262.0,258.0,263.0,...,237.0,239.0,234.0,233.0,234.0,231.0,236.0,236.0,232.0,0
0,246.0,245.0,250.0,249.0,248.0,247.0,252.0,248.0,251.0,248.0,...,235.0,234.0,236.0,241.0,241.0,249.0,253.0,257.0,262.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,249.0,247.0,249.0,252.0,254.0,247.0,256.0,259.0,258.0,256.0,...,254.0,253.0,253.0,254.0,254.0,254.0,252.0,254.0,254.0,0
0,250.0,254.0,252.0,250.0,249.0,254.0,255.0,251.0,250.0,247.0,...,250.0,250.0,253.0,248.0,253.0,255.0,246.0,255.0,253.0,0
0,249.0,251.0,248.0,254.0,250.0,248.0,251.0,253.0,252.0,250.0,...,254.0,254.0,253.0,256.0,253.0,248.0,251.0,255.0,253.0,0
0,258.0,255.0,256.0,259.0,252.0,260.0,257.0,252.0,254.0,254.0,...,256.0,257.0,255.0,259.0,255.0,261.0,255.0,256.0,254.0,0
0,253.0,255.0,256.0,254.0,257.0,254.0,255.0,256.0,257.0,255.0,...,255.0,255.0,252.0,254.0,258.0,253.0,252.0,251.0,253.0,0

# SA07

In [206]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA07_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA07')
    SA07_A_paths.append(path)

SA07_A_paths

['../Dataset/SA07/D01_SA07_R01.csv',
 '../Dataset/SA07/D02_SA07_R01.csv',
 '../Dataset/SA07/D03_SA07_R01.csv',
 '../Dataset/SA07/D04_SA07_R01.csv',
 '../Dataset/SA07/D05_SA07_R01_1.csv',
 '../Dataset/SA07/D05_SA07_R01_2.csv',
 '../Dataset/SA07/D05_SA07_R02_1.csv',
 '../Dataset/SA07/D05_SA07_R02_2.csv',
 '../Dataset/SA07/D05_SA07_R03_1.csv',
 '../Dataset/SA07/D05_SA07_R03_2.csv',
 '../Dataset/SA07/D05_SA07_R04_1.csv',
 '../Dataset/SA07/D05_SA07_R04_2.csv',
 '../Dataset/SA07/D05_SA07_R05_1.csv',
 '../Dataset/SA07/D05_SA07_R05_2.csv',
 '../Dataset/SA07/D06_SA07_R01_1.csv',
 '../Dataset/SA07/D06_SA07_R01_2.csv',
 '../Dataset/SA07/D06_SA07_R02_1.csv',
 '../Dataset/SA07/D06_SA07_R02_2.csv',
 '../Dataset/SA07/D06_SA07_R03_1.csv',
 '../Dataset/SA07/D06_SA07_R03_2.csv',
 '../Dataset/SA07/D06_SA07_R04_1.csv',
 '../Dataset/SA07/D06_SA07_R04_2.csv',
 '../Dataset/SA07/D06_SA07_R05_1.csv',
 '../Dataset/SA07/D06_SA07_R05_2.csv',
 '../Dataset/SA07/D07_SA07_R01.csv',
 '../Dataset/SA07/D07_SA07_R02.csv',
 '../Dataset/SA07/D07_SA07_R03.csv',
 '../Dataset/SA07/D07_SA07_R04.csv',
 '../Dataset/SA07/D07_SA07_R05.csv',
 '../Dataset/SA07/D08_SA07_R01.csv',
 '../Dataset/SA07/D08_SA07_R02.csv',
 '../Dataset/SA07/D08_SA07_R03.csv',
 '../Dataset/SA07/D08_SA07_R04.csv',
 '../Dataset/SA07/D08_SA07_R05.csv',
 '../Dataset/SA07/D09_SA07_R01.csv',
 '../Dataset/SA07/D09_SA07_R02.csv',
 '../Dataset/SA07/D09_SA07_R03.csv',
 '../Dataset/SA07/D09_SA07_R04.csv',
 '../Dataset/SA07/D09_SA07_R05.csv',
 '../Dataset/SA07/D10_SA07_R01.csv',
 '../Dataset/SA07/D10_SA07_R02.csv',
 '../Dataset/SA07/D10_SA07_R03.csv',
 '../Dataset/SA07/D10_SA07_R04.csv',
 '../Dataset/SA07/D10_SA07_R05.csv',
 '../Dataset/SA07/D11_SA07_R01.csv',
 '../Dataset/SA07/D11_SA07_R02.csv',
 '../Dataset/SA07/D11_SA07_R03.csv',
 '../Dataset/SA07/D11_SA07_R04.csv',
 '../Dataset/SA07/D11_SA07_R05.csv',
 '../Dataset/SA07/D12_SA07_R01.csv',
 '../Dataset/SA07/D12_SA07_R02.csv',
 '../Dataset/SA07/D12_SA07_R03.csv',
 '../Dataset/SA07/D12_SA07_R04.csv',
 '../Dataset/SA07/D12_SA07_R05.csv',
 '../Dataset/SA07/D13_SA07_R01.csv',
 '../Dataset/SA07/D13_SA07_R02.csv',
 '../Dataset/SA07/D13_SA07_R03.csv',
 '../Dataset/SA07/D13_SA07_R04.csv',
 '../Dataset/SA07/D13_SA07_R05.csv',
 '../Dataset/SA07/D14_SA07_R01.csv',
 '../Dataset/SA07/D14_SA07_R02.csv',
 '../Dataset/SA07/D14_SA07_R03.csv',
 '../Dataset/SA07/D14_SA07_R04.csv',
 '../Dataset/SA07/D14_SA07_R05.csv',
 '../Dataset/SA07/D15_SA07_R01.csv',
 '../Dataset/SA07/D15_SA07_R02.csv',
 '../Dataset/SA07/D15_SA07_R03.csv',
 '../Dataset/SA07/D15_SA07_R04.csv',
 '../Dataset/SA07/D15_SA07_R05.csv',
 '../Dataset/SA07/D16_SA07_R01.csv',
 '../Dataset/SA07/D16_SA07_R02.csv',
 '../Dataset/SA07/D16_SA07_R03.csv',
 '../Dataset/SA07/D16_SA07_R04.csv',
 '../Dataset/SA07/D16_SA07_R05.csv',
 '../Dataset/SA07/D17_SA07_R01_1.csv',
 '../Dataset/SA07/D17_SA07_R01_2.csv',
 '../Dataset/SA07/D17_SA07_R02_1.csv',
 '../Dataset/SA07/D17_SA07_R02_2.csv',
 '../Dataset/SA07/D17_SA07_R03_1.csv',
 '../Dataset/SA07/D17_SA07_R03_2.csv',
 '../Dataset/SA07/D17_SA07_R04_1.csv',
 '../Dataset/SA07/D17_SA07_R04_2.csv',
 '../Dataset/SA07/D17_SA07_R05_1.csv',
 '../Dataset/SA07/D17_SA07_R05_2.csv',
 '../Dataset/SA07/D18_SA07_R01.csv',
 '../Dataset/SA07/D18_SA07_R02.csv',
 '../Dataset/SA07/D18_SA07_R03.csv',
 '../Dataset/SA07/D18_SA07_R04.csv',
 '../Dataset/SA07/D18_SA07_R05.csv',
 '../Dataset/SA07/D19_SA07_R01.csv',
 '../Dataset/SA07/D19_SA07_R02.csv',
 '../Dataset/SA07/D19_SA07_R03.csv',
 '../Dataset/SA07/D19_SA07_R04.csv',
 '../Dataset/SA07/D19_SA07_R05.csv']

In [207]:
list = []
final_SA07_A = pd.DataFrame(list)

for path in SA07_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA07_A = final_SA07_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA07_A.shape
target_col = row * [0]
final_SA07_A.loc[:,'target'] = target_col

final_SA07_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,391.0,400.0,410.0,401.0,396.0,391.0,374.0,360.0,344.0,330.0,...,255.0,264.0,277.0,283.0,287.0,288.0,293.0,291.0,289.0,0
0,292.0,298.0,297.0,298.0,295.0,296.0,287.0,281.0,275.0,266.0,...,361.0,373.0,387.0,398.0,405.0,412.0,417.0,414.0,409.0,0
0,251.0,257.0,252.0,249.0,251.0,244.0,243.0,238.0,233.0,227.0,...,340.0,319.0,308.0,304.0,300.0,307.0,306.0,315.0,314.0,0
0,289.0,274.0,258.0,251.0,243.0,241.0,238.0,243.0,247.0,248.0,...,73.0,95.0,109.0,110.0,136.0,160.0,183.0,201.0,196.0,0
0,270.0,266.0,270.0,272.0,272.0,273.0,277.0,276.0,271.0,273.0,...,318.0,319.0,304.0,306.0,303.0,298.0,299.0,292.0,284.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,263.0,261.0,263.0,256.0,263.0,261.0,263.0,255.0,260.0,261.0,...,261.0,262.0,258.0,260.0,259.0,260.0,259.0,264.0,262.0,0
0,268.0,264.0,267.0,260.0,265.0,265.0,263.0,261.0,260.0,257.0,...,258.0,259.0,256.0,260.0,265.0,261.0,264.0,263.0,263.0,0
0,259.0,258.0,262.0,262.0,263.0,259.0,259.0,261.0,262.0,261.0,...,261.0,262.0,264.0,263.0,264.0,263.0,259.0,265.0,262.0,0
0,263.0,267.0,266.0,265.0,260.0,258.0,261.0,261.0,260.0,261.0,...,260.0,263.0,261.0,262.0,259.0,261.0,265.0,257.0,261.0,0
0,256.0,257.0,262.0,264.0,269.0,262.0,270.0,269.0,270.0,270.0,...,259.0,260.0,262.0,258.0,257.0,257.0,264.0,259.0,261.0,0

# SA08

In [208]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA08_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA08')
    SA08_A_paths.append(path)

SA08_A_paths

['../Dataset/SA08/D01_SA08_R01.csv',
 '../Dataset/SA08/D02_SA08_R01.csv',
 '../Dataset/SA08/D03_SA08_R01.csv',
 '../Dataset/SA08/D04_SA08_R01.csv',
 '../Dataset/SA08/D05_SA08_R01_1.csv',
 '../Dataset/SA08/D05_SA08_R01_2.csv',
 '../Dataset/SA08/D05_SA08_R02_1.csv',
 '../Dataset/SA08/D05_SA08_R02_2.csv',
 '../Dataset/SA08/D05_SA08_R03_1.csv',
 '../Dataset/SA08/D05_SA08_R03_2.csv',
 '../Dataset/SA08/D05_SA08_R04_1.csv',
 '../Dataset/SA08/D05_SA08_R04_2.csv',
 '../Dataset/SA08/D05_SA08_R05_1.csv',
 '../Dataset/SA08/D05_SA08_R05_2.csv',
 '../Dataset/SA08/D06_SA08_R01_1.csv',
 '../Dataset/SA08/D06_SA08_R01_2.csv',
 '../Dataset/SA08/D06_SA08_R02_1.csv',
 '../Dataset/SA08/D06_SA08_R02_2.csv',
 '../Dataset/SA08/D06_SA08_R03_1.csv',
 '../Dataset/SA08/D06_SA08_R03_2.csv',
 '../Dataset/SA08/D06_SA08_R04_1.csv',
 '../Dataset/SA08/D06_SA08_R04_2.csv',
 '../Dataset/SA08/D06_SA08_R05_1.csv',
 '../Dataset/SA08/D06_SA08_R05_2.csv',
 '../Dataset/SA08/D07_SA08_R01.csv',
 '../Dataset/SA08/D07_SA08_R02.csv',
 '../Dataset/SA08/D07_SA08_R03.csv',
 '../Dataset/SA08/D07_SA08_R04.csv',
 '../Dataset/SA08/D07_SA08_R05.csv',
 '../Dataset/SA08/D08_SA08_R01.csv',
 '../Dataset/SA08/D08_SA08_R02.csv',
 '../Dataset/SA08/D08_SA08_R03.csv',
 '../Dataset/SA08/D08_SA08_R04.csv',
 '../Dataset/SA08/D08_SA08_R05.csv',
 '../Dataset/SA08/D09_SA08_R01.csv',
 '../Dataset/SA08/D09_SA08_R02.csv',
 '../Dataset/SA08/D09_SA08_R03.csv',
 '../Dataset/SA08/D09_SA08_R04.csv',
 '../Dataset/SA08/D09_SA08_R05.csv',
 '../Dataset/SA08/D10_SA08_R01.csv',
 '../Dataset/SA08/D10_SA08_R02.csv',
 '../Dataset/SA08/D10_SA08_R03.csv',
 '../Dataset/SA08/D10_SA08_R04.csv',
 '../Dataset/SA08/D10_SA08_R05.csv',
 '../Dataset/SA08/D11_SA08_R01.csv',
 '../Dataset/SA08/D11_SA08_R02.csv',
 '../Dataset/SA08/D11_SA08_R03.csv',
 '../Dataset/SA08/D11_SA08_R04.csv',
 '../Dataset/SA08/D11_SA08_R05.csv',
 '../Dataset/SA08/D12_SA08_R01.csv',
 '../Dataset/SA08/D12_SA08_R02.csv',
 '../Dataset/SA08/D12_SA08_R03.csv',
 '../Dataset/SA08/D12_SA08_R04.csv',
 '../Dataset/SA08/D12_SA08_R05.csv',
 '../Dataset/SA08/D13_SA08_R01.csv',
 '../Dataset/SA08/D13_SA08_R02.csv',
 '../Dataset/SA08/D13_SA08_R03.csv',
 '../Dataset/SA08/D13_SA08_R04.csv',
 '../Dataset/SA08/D13_SA08_R05.csv',
 '../Dataset/SA08/D14_SA08_R01.csv',
 '../Dataset/SA08/D14_SA08_R02.csv',
 '../Dataset/SA08/D14_SA08_R03.csv',
 '../Dataset/SA08/D14_SA08_R04.csv',
 '../Dataset/SA08/D14_SA08_R05.csv',
 '../Dataset/SA08/D15_SA08_R01.csv',
 '../Dataset/SA08/D15_SA08_R02.csv',
 '../Dataset/SA08/D15_SA08_R03.csv',
 '../Dataset/SA08/D15_SA08_R04.csv',
 '../Dataset/SA08/D15_SA08_R05.csv',
 '../Dataset/SA08/D16_SA08_R01.csv',
 '../Dataset/SA08/D16_SA08_R02.csv',
 '../Dataset/SA08/D16_SA08_R03.csv',
 '../Dataset/SA08/D16_SA08_R04.csv',
 '../Dataset/SA08/D16_SA08_R05.csv',
 '../Dataset/SA08/D17_SA08_R01_1.csv',
 '../Dataset/SA08/D17_SA08_R01_2.csv',
 '../Dataset/SA08/D17_SA08_R02_1.csv',
 '../Dataset/SA08/D17_SA08_R02_2.csv',
 '../Dataset/SA08/D17_SA08_R03_1.csv',
 '../Dataset/SA08/D17_SA08_R03_2.csv',
 '../Dataset/SA08/D17_SA08_R04_1.csv',
 '../Dataset/SA08/D17_SA08_R04_2.csv',
 '../Dataset/SA08/D17_SA08_R05_1.csv',
 '../Dataset/SA08/D17_SA08_R05_2.csv',
 '../Dataset/SA08/D18_SA08_R01.csv',
 '../Dataset/SA08/D18_SA08_R02.csv',
 '../Dataset/SA08/D18_SA08_R03.csv',
 '../Dataset/SA08/D18_SA08_R04.csv',
 '../Dataset/SA08/D18_SA08_R05.csv',
 '../Dataset/SA08/D19_SA08_R01.csv',
 '../Dataset/SA08/D19_SA08_R02.csv',
 '../Dataset/SA08/D19_SA08_R03.csv',
 '../Dataset/SA08/D19_SA08_R04.csv',
 '../Dataset/SA08/D19_SA08_R05.csv']

In [209]:
list = []
final_SA08_A = pd.DataFrame(list)

for path in SA08_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA08_A = final_SA08_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA08_A.shape
target_col = row * [0]
final_SA08_A.loc[:,'target'] = target_col

final_SA08_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,240.0,246.0,255.0,264.0,270.0,272.0,281.0,282.0,285.0,281.0,...,259.0,258.0,261.0,261.0,258.0,253.0,253.0,246.0,243.0,0
0,336.0,337.0,331.0,317.0,305.0,296.0,273.0,258.0,245.0,235.0,...,158.0,159.0,154.0,152.0,157.0,153.0,154.0,161.0,158.0,0
0,241.0,242.0,239.0,239.0,241.0,240.0,238.0,236.0,236.0,239.0,...,243.0,237.0,243.0,242.0,242.0,242.0,247.0,243.0,241.0,0
0,237.0,236.0,238.0,236.0,236.0,235.0,237.0,235.0,231.0,228.0,...,162.0,182.0,205.0,224.0,242.0,256.0,278.0,279.0,292.0,0
0,252.0,249.0,251.0,251.0,255.0,253.0,253.0,248.0,246.0,248.0,...,240.0,242.0,239.0,241.0,242.0,237.0,237.0,239.0,241.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,245.0,243.0,248.0,246.0,244.0,246.0,246.0,246.0,247.0,245.0,...,244.0,245.0,245.0,239.0,246.0,241.0,247.0,246.0,245.0,0
0,245.0,245.0,245.0,247.0,243.0,245.0,245.0,247.0,244.0,245.0,...,246.0,245.0,246.0,245.0,243.0,246.0,243.0,244.0,245.0,0
0,245.0,245.0,246.0,247.0,245.0,247.0,248.0,247.0,244.0,247.0,...,243.0,247.0,249.0,246.0,247.0,248.0,245.0,245.0,248.0,0
0,244.0,244.0,246.0,245.0,247.0,246.0,248.0,244.0,246.0,244.0,...,245.0,243.0,243.0,249.0,245.0,246.0,246.0,246.0,247.0,0
0,248.0,247.0,246.0,246.0,246.0,248.0,245.0,244.0,245.0,243.0,...,245.0,245.0,247.0,245.0,246.0,240.0,249.0,245.0,244.0,0

# SA09

In [210]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA09_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA09')
    SA09_A_paths.append(path)

SA09_A_paths

['../Dataset/SA09/D01_SA09_R01.csv',
 '../Dataset/SA09/D02_SA09_R01.csv',
 '../Dataset/SA09/D03_SA09_R01.csv',
 '../Dataset/SA09/D04_SA09_R01.csv',
 '../Dataset/SA09/D05_SA09_R01_1.csv',
 '../Dataset/SA09/D05_SA09_R01_2.csv',
 '../Dataset/SA09/D05_SA09_R02_1.csv',
 '../Dataset/SA09/D05_SA09_R02_2.csv',
 '../Dataset/SA09/D05_SA09_R03_1.csv',
 '../Dataset/SA09/D05_SA09_R03_2.csv',
 '../Dataset/SA09/D05_SA09_R04_1.csv',
 '../Dataset/SA09/D05_SA09_R04_2.csv',
 '../Dataset/SA09/D05_SA09_R05_1.csv',
 '../Dataset/SA09/D05_SA09_R05_2.csv',
 '../Dataset/SA09/D06_SA09_R01_1.csv',
 '../Dataset/SA09/D06_SA09_R01_2.csv',
 '../Dataset/SA09/D06_SA09_R02_1.csv',
 '../Dataset/SA09/D06_SA09_R02_2.csv',
 '../Dataset/SA09/D06_SA09_R03_1.csv',
 '../Dataset/SA09/D06_SA09_R03_2.csv',
 '../Dataset/SA09/D06_SA09_R04_1.csv',
 '../Dataset/SA09/D06_SA09_R04_2.csv',
 '../Dataset/SA09/D06_SA09_R05_1.csv',
 '../Dataset/SA09/D06_SA09_R05_2.csv',
 '../Dataset/SA09/D07_SA09_R01.csv',
 '../Dataset/SA09/D07_SA09_R02.csv',
 '../Dataset/SA09/D07_SA09_R03.csv',
 '../Dataset/SA09/D07_SA09_R04.csv',
 '../Dataset/SA09/D07_SA09_R05.csv',
 '../Dataset/SA09/D08_SA09_R01.csv',
 '../Dataset/SA09/D08_SA09_R02.csv',
 '../Dataset/SA09/D08_SA09_R03.csv',
 '../Dataset/SA09/D08_SA09_R04.csv',
 '../Dataset/SA09/D08_SA09_R05.csv',
 '../Dataset/SA09/D09_SA09_R01.csv',
 '../Dataset/SA09/D09_SA09_R02.csv',
 '../Dataset/SA09/D09_SA09_R03.csv',
 '../Dataset/SA09/D09_SA09_R04.csv',
 '../Dataset/SA09/D09_SA09_R05.csv',
 '../Dataset/SA09/D10_SA09_R01.csv',
 '../Dataset/SA09/D10_SA09_R02.csv',
 '../Dataset/SA09/D10_SA09_R03.csv',
 '../Dataset/SA09/D10_SA09_R04.csv',
 '../Dataset/SA09/D10_SA09_R05.csv',
 '../Dataset/SA09/D11_SA09_R01.csv',
 '../Dataset/SA09/D11_SA09_R02.csv',
 '../Dataset/SA09/D11_SA09_R03.csv',
 '../Dataset/SA09/D11_SA09_R04.csv',
 '../Dataset/SA09/D11_SA09_R05.csv',
 '../Dataset/SA09/D12_SA09_R01.csv',
 '../Dataset/SA09/D12_SA09_R02.csv',
 '../Dataset/SA09/D12_SA09_R03.csv',
 '../Dataset/SA09/D12_SA09_R04.csv',
 '../Dataset/SA09/D12_SA09_R05.csv',
 '../Dataset/SA09/D13_SA09_R01.csv',
 '../Dataset/SA09/D13_SA09_R02.csv',
 '../Dataset/SA09/D13_SA09_R03.csv',
 '../Dataset/SA09/D13_SA09_R04.csv',
 '../Dataset/SA09/D13_SA09_R05.csv',
 '../Dataset/SA09/D14_SA09_R01.csv',
 '../Dataset/SA09/D14_SA09_R02.csv',
 '../Dataset/SA09/D14_SA09_R03.csv',
 '../Dataset/SA09/D14_SA09_R04.csv',
 '../Dataset/SA09/D14_SA09_R05.csv',
 '../Dataset/SA09/D15_SA09_R01.csv',
 '../Dataset/SA09/D15_SA09_R02.csv',
 '../Dataset/SA09/D15_SA09_R03.csv',
 '../Dataset/SA09/D15_SA09_R04.csv',
 '../Dataset/SA09/D15_SA09_R05.csv',
 '../Dataset/SA09/D16_SA09_R01.csv',
 '../Dataset/SA09/D16_SA09_R02.csv',
 '../Dataset/SA09/D16_SA09_R03.csv',
 '../Dataset/SA09/D16_SA09_R04.csv',
 '../Dataset/SA09/D16_SA09_R05.csv',
 '../Dataset/SA09/D17_SA09_R01_1.csv',
 '../Dataset/SA09/D17_SA09_R01_2.csv',
 '../Dataset/SA09/D17_SA09_R02_1.csv',
 '../Dataset/SA09/D17_SA09_R02_2.csv',
 '../Dataset/SA09/D17_SA09_R03_1.csv',
 '../Dataset/SA09/D17_SA09_R03_2.csv',
 '../Dataset/SA09/D17_SA09_R04_1.csv',
 '../Dataset/SA09/D17_SA09_R04_2.csv',
 '../Dataset/SA09/D17_SA09_R05_1.csv',
 '../Dataset/SA09/D17_SA09_R05_2.csv',
 '../Dataset/SA09/D18_SA09_R01.csv',
 '../Dataset/SA09/D18_SA09_R02.csv',
 '../Dataset/SA09/D18_SA09_R03.csv',
 '../Dataset/SA09/D18_SA09_R04.csv',
 '../Dataset/SA09/D18_SA09_R05.csv',
 '../Dataset/SA09/D19_SA09_R01.csv',
 '../Dataset/SA09/D19_SA09_R02.csv',
 '../Dataset/SA09/D19_SA09_R03.csv',
 '../Dataset/SA09/D19_SA09_R04.csv',
 '../Dataset/SA09/D19_SA09_R05.csv']

In [211]:
list = []
final_SA09_A = pd.DataFrame(list)

for path in SA09_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA09_A = final_SA09_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA09_A.shape
target_col = row * [0]
final_SA09_A.loc[:,'target'] = target_col

final_SA09_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,277.0,277.0,274.0,270.0,266.0,263.0,258.0,256.0,254.0,256.0,...,262.0,261.0,260.0,256.0,253.0,254.0,252.0,252.0,254.0,0
0,322.0,316.0,302.0,290.0,274.0,261.0,256.0,253.0,263.0,266.0,...,219.0,214.0,209.0,199.0,196.0,188.0,184.0,180.0,178.0,0
0,251.0,248.0,254.0,252.0,248.0,250.0,253.0,253.0,252.0,256.0,...,257.0,257.0,256.0,260.0,258.0,258.0,258.0,259.0,259.0,0
0,247.0,251.0,251.0,252.0,254.0,252.0,254.0,253.0,250.0,253.0,...,282.0,288.0,298.0,311.0,311.0,305.0,295.0,281.0,263.0,0
0,258.0,260.0,266.0,270.0,277.0,286.0,287.0,295.0,292.0,293.0,...,217.0,219.0,223.0,222.0,221.0,220.0,217.0,217.0,216.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,254.0,251.0,251.0,253.0,252.0,252.0,252.0,252.0,253.0,255.0,...,253.0,255.0,252.0,251.0,252.0,255.0,252.0,255.0,255.0,0
0,256.0,248.0,251.0,252.0,251.0,256.0,253.0,253.0,251.0,249.0,...,250.0,249.0,245.0,250.0,251.0,251.0,254.0,256.0,254.0,0
0,250.0,253.0,252.0,255.0,253.0,251.0,250.0,248.0,252.0,251.0,...,254.0,251.0,250.0,250.0,249.0,250.0,253.0,253.0,253.0,0
0,251.0,252.0,253.0,250.0,250.0,249.0,250.0,253.0,252.0,253.0,...,255.0,255.0,253.0,251.0,252.0,253.0,253.0,253.0,254.0,0
0,252.0,251.0,250.0,251.0,255.0,252.0,253.0,252.0,253.0,253.0,...,252.0,250.0,254.0,253.0,255.0,249.0,251.0,251.0,252.0,0

# SA10

In [212]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA10_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA10')
    SA10_A_paths.append(path)

SA10_A_paths

['../Dataset/SA10/D01_SA10_R01.csv',
 '../Dataset/SA10/D02_SA10_R01.csv',
 '../Dataset/SA10/D03_SA10_R01.csv',
 '../Dataset/SA10/D04_SA10_R01.csv',
 '../Dataset/SA10/D05_SA10_R01_1.csv',
 '../Dataset/SA10/D05_SA10_R01_2.csv',
 '../Dataset/SA10/D05_SA10_R02_1.csv',
 '../Dataset/SA10/D05_SA10_R02_2.csv',
 '../Dataset/SA10/D05_SA10_R03_1.csv',
 '../Dataset/SA10/D05_SA10_R03_2.csv',
 '../Dataset/SA10/D05_SA10_R04_1.csv',
 '../Dataset/SA10/D05_SA10_R04_2.csv',
 '../Dataset/SA10/D05_SA10_R05_1.csv',
 '../Dataset/SA10/D05_SA10_R05_2.csv',
 '../Dataset/SA10/D06_SA10_R01_1.csv',
 '../Dataset/SA10/D06_SA10_R01_2.csv',
 '../Dataset/SA10/D06_SA10_R02_1.csv',
 '../Dataset/SA10/D06_SA10_R02_2.csv',
 '../Dataset/SA10/D06_SA10_R03_1.csv',
 '../Dataset/SA10/D06_SA10_R03_2.csv',
 '../Dataset/SA10/D06_SA10_R04_1.csv',
 '../Dataset/SA10/D06_SA10_R04_2.csv',
 '../Dataset/SA10/D06_SA10_R05_1.csv',
 '../Dataset/SA10/D06_SA10_R05_2.csv',
 '../Dataset/SA10/D07_SA10_R01.csv',
 '../Dataset/SA10/D07_SA10_R02.csv',
 '../Dataset/SA10/D07_SA10_R03.csv',
 '../Dataset/SA10/D07_SA10_R04.csv',
 '../Dataset/SA10/D07_SA10_R05.csv',
 '../Dataset/SA10/D08_SA10_R01.csv',
 '../Dataset/SA10/D08_SA10_R02.csv',
 '../Dataset/SA10/D08_SA10_R03.csv',
 '../Dataset/SA10/D08_SA10_R04.csv',
 '../Dataset/SA10/D08_SA10_R05.csv',
 '../Dataset/SA10/D09_SA10_R01.csv',
 '../Dataset/SA10/D09_SA10_R02.csv',
 '../Dataset/SA10/D09_SA10_R03.csv',
 '../Dataset/SA10/D09_SA10_R04.csv',
 '../Dataset/SA10/D09_SA10_R05.csv',
 '../Dataset/SA10/D10_SA10_R01.csv',
 '../Dataset/SA10/D10_SA10_R02.csv',
 '../Dataset/SA10/D10_SA10_R03.csv',
 '../Dataset/SA10/D10_SA10_R04.csv',
 '../Dataset/SA10/D10_SA10_R05.csv',
 '../Dataset/SA10/D11_SA10_R01.csv',
 '../Dataset/SA10/D11_SA10_R02.csv',
 '../Dataset/SA10/D11_SA10_R03.csv',
 '../Dataset/SA10/D11_SA10_R04.csv',
 '../Dataset/SA10/D11_SA10_R05.csv',
 '../Dataset/SA10/D12_SA10_R01.csv',
 '../Dataset/SA10/D12_SA10_R02.csv',
 '../Dataset/SA10/D12_SA10_R03.csv',
 '../Dataset/SA10/D12_SA10_R04.csv',
 '../Dataset/SA10/D12_SA10_R05.csv',
 '../Dataset/SA10/D13_SA10_R01.csv',
 '../Dataset/SA10/D13_SA10_R02.csv',
 '../Dataset/SA10/D13_SA10_R03.csv',
 '../Dataset/SA10/D13_SA10_R04.csv',
 '../Dataset/SA10/D13_SA10_R05.csv',
 '../Dataset/SA10/D14_SA10_R01.csv',
 '../Dataset/SA10/D14_SA10_R02.csv',
 '../Dataset/SA10/D14_SA10_R03.csv',
 '../Dataset/SA10/D14_SA10_R04.csv',
 '../Dataset/SA10/D14_SA10_R05.csv',
 '../Dataset/SA10/D15_SA10_R01.csv',
 '../Dataset/SA10/D15_SA10_R02.csv',
 '../Dataset/SA10/D15_SA10_R03.csv',
 '../Dataset/SA10/D15_SA10_R04.csv',
 '../Dataset/SA10/D15_SA10_R05.csv',
 '../Dataset/SA10/D16_SA10_R01.csv',
 '../Dataset/SA10/D16_SA10_R02.csv',
 '../Dataset/SA10/D16_SA10_R03.csv',
 '../Dataset/SA10/D16_SA10_R04.csv',
 '../Dataset/SA10/D16_SA10_R05.csv',
 '../Dataset/SA10/D17_SA10_R01_1.csv',
 '../Dataset/SA10/D17_SA10_R01_2.csv',
 '../Dataset/SA10/D17_SA10_R02_1.csv',
 '../Dataset/SA10/D17_SA10_R02_2.csv',
 '../Dataset/SA10/D17_SA10_R03_1.csv',
 '../Dataset/SA10/D17_SA10_R03_2.csv',
 '../Dataset/SA10/D17_SA10_R04_1.csv',
 '../Dataset/SA10/D17_SA10_R04_2.csv',
 '../Dataset/SA10/D17_SA10_R05_1.csv',
 '../Dataset/SA10/D17_SA10_R05_2.csv',
 '../Dataset/SA10/D18_SA10_R01.csv',
 '../Dataset/SA10/D18_SA10_R02.csv',
 '../Dataset/SA10/D18_SA10_R03.csv',
 '../Dataset/SA10/D18_SA10_R04.csv',
 '../Dataset/SA10/D18_SA10_R05.csv',
 '../Dataset/SA10/D19_SA10_R01.csv',
 '../Dataset/SA10/D19_SA10_R02.csv',
 '../Dataset/SA10/D19_SA10_R03.csv',
 '../Dataset/SA10/D19_SA10_R04.csv',
 '../Dataset/SA10/D19_SA10_R05.csv']

In [213]:
list = []
final_SA10_A = pd.DataFrame(list)

for path in SA10_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA10_A = final_SA10_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA10_A.shape
target_col = row * [0]
final_SA10_A.loc[:,'target'] = target_col

final_SA10_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,287.0,286.0,287.0,284.0,285.0,282.0,277.0,275.0,274.0,265.0,...,254.0,249.0,249.0,248.0,250.0,244.0,246.0,247.0,247.0,0
0,256.0,253.0,253.0,255.0,256.0,252.0,254.0,254.0,255.0,256.0,...,244.0,244.0,249.0,249.0,251.0,252.0,260.0,255.0,255.0,0
0,253.0,257.0,255.0,256.0,256.0,251.0,254.0,254.0,254.0,252.0,...,322.0,309.0,300.0,289.0,277.0,268.0,259.0,251.0,239.0,0
0,232.0,224.0,221.0,220.0,212.0,205.0,197.0,188.0,180.0,166.0,...,129.0,98.0,101.0,148.0,210.0,265.0,293.0,300.0,272.0,0
0,272.0,273.0,275.0,276.0,278.0,281.0,285.0,291.0,294.0,299.0,...,324.0,331.0,331.0,325.0,319.0,316.0,312.0,305.0,295.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,255.0,253.0,253.0,255.0,250.0,250.0,251.0,251.0,252.0,252.0,...,252.0,255.0,253.0,254.0,256.0,264.0,254.0,255.0,256.0,0
0,250.0,256.0,252.0,256.0,252.0,250.0,252.0,254.0,256.0,252.0,...,254.0,256.0,254.0,255.0,257.0,256.0,255.0,256.0,254.0,0
0,254.0,255.0,253.0,253.0,256.0,247.0,253.0,252.0,254.0,257.0,...,257.0,258.0,258.0,259.0,260.0,255.0,261.0,261.0,260.0,0
0,253.0,251.0,256.0,255.0,256.0,251.0,252.0,254.0,256.0,257.0,...,253.0,257.0,258.0,257.0,260.0,259.0,264.0,263.0,265.0,0
0,252.0,255.0,253.0,253.0,254.0,254.0,254.0,252.0,252.0,254.0,...,258.0,256.0,255.0,258.0,257.0,256.0,257.0,252.0,253.0,0

# SA11

In [214]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA11_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA11')
    SA11_A_paths.append(path)

SA11_A_paths

['../Dataset/SA11/D01_SA11_R01.csv',
 '../Dataset/SA11/D02_SA11_R01.csv',
 '../Dataset/SA11/D03_SA11_R01.csv',
 '../Dataset/SA11/D04_SA11_R01.csv',
 '../Dataset/SA11/D05_SA11_R01_1.csv',
 '../Dataset/SA11/D05_SA11_R01_2.csv',
 '../Dataset/SA11/D05_SA11_R02_1.csv',
 '../Dataset/SA11/D05_SA11_R02_2.csv',
 '../Dataset/SA11/D05_SA11_R03_1.csv',
 '../Dataset/SA11/D05_SA11_R03_2.csv',
 '../Dataset/SA11/D05_SA11_R04_1.csv',
 '../Dataset/SA11/D05_SA11_R04_2.csv',
 '../Dataset/SA11/D05_SA11_R05_1.csv',
 '../Dataset/SA11/D05_SA11_R05_2.csv',
 '../Dataset/SA11/D06_SA11_R01_1.csv',
 '../Dataset/SA11/D06_SA11_R01_2.csv',
 '../Dataset/SA11/D06_SA11_R02_1.csv',
 '../Dataset/SA11/D06_SA11_R02_2.csv',
 '../Dataset/SA11/D06_SA11_R03_1.csv',
 '../Dataset/SA11/D06_SA11_R03_2.csv',
 '../Dataset/SA11/D06_SA11_R04_1.csv',
 '../Dataset/SA11/D06_SA11_R04_2.csv',
 '../Dataset/SA11/D06_SA11_R05_1.csv',
 '../Dataset/SA11/D06_SA11_R05_2.csv',
 '../Dataset/SA11/D07_SA11_R01.csv',
 '../Dataset/SA11/D07_SA11_R02.csv',
 '../Dataset/SA11/D07_SA11_R03.csv',
 '../Dataset/SA11/D07_SA11_R04.csv',
 '../Dataset/SA11/D07_SA11_R05.csv',
 '../Dataset/SA11/D08_SA11_R01.csv',
 '../Dataset/SA11/D08_SA11_R02.csv',
 '../Dataset/SA11/D08_SA11_R03.csv',
 '../Dataset/SA11/D08_SA11_R04.csv',
 '../Dataset/SA11/D08_SA11_R05.csv',
 '../Dataset/SA11/D09_SA11_R01.csv',
 '../Dataset/SA11/D09_SA11_R02.csv',
 '../Dataset/SA11/D09_SA11_R03.csv',
 '../Dataset/SA11/D09_SA11_R04.csv',
 '../Dataset/SA11/D09_SA11_R05.csv',
 '../Dataset/SA11/D10_SA11_R01.csv',
 '../Dataset/SA11/D10_SA11_R02.csv',
 '../Dataset/SA11/D10_SA11_R03.csv',
 '../Dataset/SA11/D10_SA11_R04.csv',
 '../Dataset/SA11/D10_SA11_R05.csv',
 '../Dataset/SA11/D11_SA11_R01.csv',
 '../Dataset/SA11/D11_SA11_R02.csv',
 '../Dataset/SA11/D11_SA11_R03.csv',
 '../Dataset/SA11/D11_SA11_R04.csv',
 '../Dataset/SA11/D11_SA11_R05.csv',
 '../Dataset/SA11/D12_SA11_R01.csv',
 '../Dataset/SA11/D12_SA11_R02.csv',
 '../Dataset/SA11/D12_SA11_R03.csv',
 '../Dataset/SA11/D12_SA11_R04.csv',
 '../Dataset/SA11/D12_SA11_R05.csv',
 '../Dataset/SA11/D13_SA11_R01.csv',
 '../Dataset/SA11/D13_SA11_R02.csv',
 '../Dataset/SA11/D13_SA11_R03.csv',
 '../Dataset/SA11/D13_SA11_R04.csv',
 '../Dataset/SA11/D13_SA11_R05.csv',
 '../Dataset/SA11/D14_SA11_R01.csv',
 '../Dataset/SA11/D14_SA11_R02.csv',
 '../Dataset/SA11/D14_SA11_R03.csv',
 '../Dataset/SA11/D14_SA11_R04.csv',
 '../Dataset/SA11/D14_SA11_R05.csv',
 '../Dataset/SA11/D15_SA11_R01.csv',
 '../Dataset/SA11/D15_SA11_R02.csv',
 '../Dataset/SA11/D15_SA11_R03.csv',
 '../Dataset/SA11/D15_SA11_R04.csv',
 '../Dataset/SA11/D15_SA11_R05.csv',
 '../Dataset/SA11/D16_SA11_R01.csv',
 '../Dataset/SA11/D16_SA11_R02.csv',
 '../Dataset/SA11/D16_SA11_R03.csv',
 '../Dataset/SA11/D16_SA11_R04.csv',
 '../Dataset/SA11/D16_SA11_R05.csv',
 '../Dataset/SA11/D17_SA11_R01_1.csv',
 '../Dataset/SA11/D17_SA11_R01_2.csv',
 '../Dataset/SA11/D17_SA11_R02_1.csv',
 '../Dataset/SA11/D17_SA11_R02_2.csv',
 '../Dataset/SA11/D17_SA11_R03_1.csv',
 '../Dataset/SA11/D17_SA11_R03_2.csv',
 '../Dataset/SA11/D17_SA11_R04_1.csv',
 '../Dataset/SA11/D17_SA11_R04_2.csv',
 '../Dataset/SA11/D17_SA11_R05_1.csv',
 '../Dataset/SA11/D17_SA11_R05_2.csv',
 '../Dataset/SA11/D18_SA11_R01.csv',
 '../Dataset/SA11/D18_SA11_R02.csv',
 '../Dataset/SA11/D18_SA11_R03.csv',
 '../Dataset/SA11/D18_SA11_R04.csv',
 '../Dataset/SA11/D18_SA11_R05.csv',
 '../Dataset/SA11/D19_SA11_R01.csv',
 '../Dataset/SA11/D19_SA11_R02.csv',
 '../Dataset/SA11/D19_SA11_R03.csv',
 '../Dataset/SA11/D19_SA11_R04.csv',
 '../Dataset/SA11/D19_SA11_R05.csv']

In [215]:
list = []
final_SA11_A = pd.DataFrame(list)

for path in SA11_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA11_A = final_SA11_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA11_A.shape
target_col = row * [0]
final_SA11_A.loc[:,'target'] = target_col

final_SA11_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,228.0,228.0,220.0,217.0,221.0,218.0,225.0,224.0,228.0,231.0,...,238.0,244.0,256.0,259.0,265.0,278.0,278.0,281.0,285.0,0
0,247.0,250.0,249.0,250.0,247.0,246.0,247.0,249.0,248.0,255.0,...,263.0,257.0,255.0,250.0,250.0,248.0,247.0,248.0,249.0,0
0,246.0,248.0,245.0,248.0,253.0,247.0,249.0,248.0,251.0,250.0,...,267.0,263.0,260.0,259.0,252.0,258.0,255.0,254.0,244.0,0
0,249.0,252.0,245.0,247.0,247.0,251.0,242.0,245.0,244.0,244.0,...,207.0,208.0,213.0,219.0,221.0,227.0,225.0,228.0,231.0,0
0,222.0,230.0,229.0,235.0,236.0,243.0,241.0,243.0,248.0,249.0,...,222.0,230.0,236.0,247.0,253.0,256.0,264.0,272.0,277.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,249.0,251.0,250.0,252.0,251.0,249.0,250.0,247.0,249.0,255.0,...,264.0,260.0,263.0,262.0,265.0,267.0,271.0,268.0,269.0,0
0,249.0,246.0,251.0,253.0,251.0,245.0,252.0,251.0,251.0,250.0,...,250.0,252.0,252.0,249.0,252.0,252.0,251.0,251.0,253.0,0
0,250.0,251.0,252.0,250.0,252.0,252.0,249.0,252.0,252.0,253.0,...,248.0,252.0,251.0,251.0,251.0,249.0,249.0,250.0,249.0,0
0,250.0,249.0,252.0,253.0,250.0,247.0,254.0,251.0,253.0,250.0,...,258.0,254.0,249.0,253.0,255.0,255.0,253.0,255.0,253.0,0
0,250.0,251.0,248.0,251.0,254.0,246.0,252.0,251.0,258.0,252.0,...,253.0,252.0,252.0,251.0,248.0,249.0,251.0,252.0,249.0,0

# SA12

In [216]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA12_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA12')
    SA12_A_paths.append(path)

SA12_A_paths

['../Dataset/SA12/D01_SA12_R01.csv',
 '../Dataset/SA12/D02_SA12_R01.csv',
 '../Dataset/SA12/D03_SA12_R01.csv',
 '../Dataset/SA12/D04_SA12_R01.csv',
 '../Dataset/SA12/D05_SA12_R01_1.csv',
 '../Dataset/SA12/D05_SA12_R01_2.csv',
 '../Dataset/SA12/D05_SA12_R02_1.csv',
 '../Dataset/SA12/D05_SA12_R02_2.csv',
 '../Dataset/SA12/D05_SA12_R03_1.csv',
 '../Dataset/SA12/D05_SA12_R03_2.csv',
 '../Dataset/SA12/D05_SA12_R04_1.csv',
 '../Dataset/SA12/D05_SA12_R04_2.csv',
 '../Dataset/SA12/D05_SA12_R05_1.csv',
 '../Dataset/SA12/D05_SA12_R05_2.csv',
 '../Dataset/SA12/D06_SA12_R01_1.csv',
 '../Dataset/SA12/D06_SA12_R01_2.csv',
 '../Dataset/SA12/D06_SA12_R02_1.csv',
 '../Dataset/SA12/D06_SA12_R02_2.csv',
 '../Dataset/SA12/D06_SA12_R03_1.csv',
 '../Dataset/SA12/D06_SA12_R03_2.csv',
 '../Dataset/SA12/D06_SA12_R04_1.csv',
 '../Dataset/SA12/D06_SA12_R04_2.csv',
 '../Dataset/SA12/D06_SA12_R05_1.csv',
 '../Dataset/SA12/D06_SA12_R05_2.csv',
 '../Dataset/SA12/D07_SA12_R01.csv',
 '../Dataset/SA12/D07_SA12_R02.csv',
 '../Dataset/SA12/D07_SA12_R03.csv',
 '../Dataset/SA12/D07_SA12_R04.csv',
 '../Dataset/SA12/D07_SA12_R05.csv',
 '../Dataset/SA12/D08_SA12_R01.csv',
 '../Dataset/SA12/D08_SA12_R02.csv',
 '../Dataset/SA12/D08_SA12_R03.csv',
 '../Dataset/SA12/D08_SA12_R04.csv',
 '../Dataset/SA12/D08_SA12_R05.csv',
 '../Dataset/SA12/D09_SA12_R01.csv',
 '../Dataset/SA12/D09_SA12_R02.csv',
 '../Dataset/SA12/D09_SA12_R03.csv',
 '../Dataset/SA12/D09_SA12_R04.csv',
 '../Dataset/SA12/D09_SA12_R05.csv',
 '../Dataset/SA12/D10_SA12_R01.csv',
 '../Dataset/SA12/D10_SA12_R02.csv',
 '../Dataset/SA12/D10_SA12_R03.csv',
 '../Dataset/SA12/D10_SA12_R04.csv',
 '../Dataset/SA12/D10_SA12_R05.csv',
 '../Dataset/SA12/D11_SA12_R01.csv',
 '../Dataset/SA12/D11_SA12_R02.csv',
 '../Dataset/SA12/D11_SA12_R03.csv',
 '../Dataset/SA12/D11_SA12_R04.csv',
 '../Dataset/SA12/D11_SA12_R05.csv',
 '../Dataset/SA12/D12_SA12_R01.csv',
 '../Dataset/SA12/D12_SA12_R02.csv',
 '../Dataset/SA12/D12_SA12_R03.csv',
 '../Dataset/SA12/D12_SA12_R04.csv',
 '../Dataset/SA12/D12_SA12_R05.csv',
 '../Dataset/SA12/D13_SA12_R01.csv',
 '../Dataset/SA12/D13_SA12_R02.csv',
 '../Dataset/SA12/D13_SA12_R03.csv',
 '../Dataset/SA12/D13_SA12_R04.csv',
 '../Dataset/SA12/D13_SA12_R05.csv',
 '../Dataset/SA12/D14_SA12_R01.csv',
 '../Dataset/SA12/D14_SA12_R02.csv',
 '../Dataset/SA12/D14_SA12_R03.csv',
 '../Dataset/SA12/D14_SA12_R04.csv',
 '../Dataset/SA12/D14_SA12_R05.csv',
 '../Dataset/SA12/D15_SA12_R01.csv',
 '../Dataset/SA12/D15_SA12_R02.csv',
 '../Dataset/SA12/D15_SA12_R03.csv',
 '../Dataset/SA12/D15_SA12_R04.csv',
 '../Dataset/SA12/D15_SA12_R05.csv',
 '../Dataset/SA12/D16_SA12_R01.csv',
 '../Dataset/SA12/D16_SA12_R02.csv',
 '../Dataset/SA12/D16_SA12_R03.csv',
 '../Dataset/SA12/D16_SA12_R04.csv',
 '../Dataset/SA12/D16_SA12_R05.csv',
 '../Dataset/SA12/D17_SA12_R01_1.csv',
 '../Dataset/SA12/D17_SA12_R01_2.csv',
 '../Dataset/SA12/D17_SA12_R02_1.csv',
 '../Dataset/SA12/D17_SA12_R02_2.csv',
 '../Dataset/SA12/D17_SA12_R03_1.csv',
 '../Dataset/SA12/D17_SA12_R03_2.csv',
 '../Dataset/SA12/D17_SA12_R04_1.csv',
 '../Dataset/SA12/D17_SA12_R04_2.csv',
 '../Dataset/SA12/D17_SA12_R05_1.csv',
 '../Dataset/SA12/D17_SA12_R05_2.csv',
 '../Dataset/SA12/D18_SA12_R01.csv',
 '../Dataset/SA12/D18_SA12_R02.csv',
 '../Dataset/SA12/D18_SA12_R03.csv',
 '../Dataset/SA12/D18_SA12_R04.csv',
 '../Dataset/SA12/D18_SA12_R05.csv',
 '../Dataset/SA12/D19_SA12_R01.csv',
 '../Dataset/SA12/D19_SA12_R02.csv',
 '../Dataset/SA12/D19_SA12_R03.csv',
 '../Dataset/SA12/D19_SA12_R04.csv',
 '../Dataset/SA12/D19_SA12_R05.csv']

In [217]:
list = []
final_SA12_A = pd.DataFrame(list)

for path in SA12_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA12_A = final_SA12_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA12_A.shape
target_col = row * [0]
final_SA12_A.loc[:,'target'] = target_col

final_SA12_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,246.0,246.0,247.0,249.0,244.0,241.0,249.0,245.0,249.0,248.0,...,247.0,246.0,245.0,249.0,248.0,245.0,246.0,248.0,249.0,0
0,210.0,203.0,198.0,201.0,203.0,202.0,198.0,198.0,198.0,205.0,...,230.0,233.0,226.0,232.0,227.0,230.0,227.0,225.0,228.0,0
0,359.0,384.0,413.0,441.0,462.0,477.0,494.0,497.0,493.0,487.0,...,534.0,515.0,453.0,370.0,313.0,294.0,319.0,359.0,409.0,0
0,292.0,401.0,496.0,522.0,498.0,477.0,505.0,548.0,536.0,477.0,...,387.0,409.0,600.0,718.0,735.0,686.0,728.0,801.0,817.0,0
0,274.0,275.0,277.0,273.0,275.0,278.0,285.0,290.0,297.0,309.0,...,230.0,228.0,233.0,233.0,236.0,241.0,242.0,242.0,244.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,251.0,250.0,249.0,244.0,249.0,244.0,248.0,244.0,249.0,247.0,...,246.0,251.0,250.0,244.0,247.0,248.0,252.0,252.0,251.0,0
0,251.0,248.0,248.0,244.0,249.0,242.0,252.0,249.0,249.0,246.0,...,250.0,247.0,248.0,247.0,243.0,248.0,245.0,248.0,244.0,0
0,248.0,247.0,251.0,251.0,251.0,247.0,251.0,247.0,247.0,252.0,...,248.0,249.0,249.0,246.0,251.0,247.0,249.0,249.0,250.0,0
0,250.0,251.0,252.0,251.0,248.0,250.0,250.0,245.0,254.0,251.0,...,249.0,246.0,253.0,251.0,252.0,249.0,252.0,251.0,250.0,0
0,253.0,251.0,251.0,249.0,251.0,248.0,246.0,246.0,252.0,247.0,...,250.0,254.0,253.0,253.0,252.0,252.0,253.0,250.0,248.0,0

# SA13

In [218]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA13_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA13')
    SA13_A_paths.append(path)

SA13_A_paths

['../Dataset/SA13/D01_SA13_R01.csv',
 '../Dataset/SA13/D02_SA13_R01.csv',
 '../Dataset/SA13/D03_SA13_R01.csv',
 '../Dataset/SA13/D04_SA13_R01.csv',
 '../Dataset/SA13/D05_SA13_R01_1.csv',
 '../Dataset/SA13/D05_SA13_R01_2.csv',
 '../Dataset/SA13/D05_SA13_R02_1.csv',
 '../Dataset/SA13/D05_SA13_R02_2.csv',
 '../Dataset/SA13/D05_SA13_R03_1.csv',
 '../Dataset/SA13/D05_SA13_R03_2.csv',
 '../Dataset/SA13/D05_SA13_R04_1.csv',
 '../Dataset/SA13/D05_SA13_R04_2.csv',
 '../Dataset/SA13/D05_SA13_R05_1.csv',
 '../Dataset/SA13/D05_SA13_R05_2.csv',
 '../Dataset/SA13/D06_SA13_R01_1.csv',
 '../Dataset/SA13/D06_SA13_R01_2.csv',
 '../Dataset/SA13/D06_SA13_R02_1.csv',
 '../Dataset/SA13/D06_SA13_R02_2.csv',
 '../Dataset/SA13/D06_SA13_R03_1.csv',
 '../Dataset/SA13/D06_SA13_R03_2.csv',
 '../Dataset/SA13/D06_SA13_R04_1.csv',
 '../Dataset/SA13/D06_SA13_R04_2.csv',
 '../Dataset/SA13/D06_SA13_R05_1.csv',
 '../Dataset/SA13/D06_SA13_R05_2.csv',
 '../Dataset/SA13/D07_SA13_R01.csv',
 '../Dataset/SA13/D07_SA13_R02.csv',
 '../Dataset/SA13/D07_SA13_R03.csv',
 '../Dataset/SA13/D07_SA13_R04.csv',
 '../Dataset/SA13/D07_SA13_R05.csv',
 '../Dataset/SA13/D08_SA13_R01.csv',
 '../Dataset/SA13/D08_SA13_R02.csv',
 '../Dataset/SA13/D08_SA13_R03.csv',
 '../Dataset/SA13/D08_SA13_R04.csv',
 '../Dataset/SA13/D08_SA13_R05.csv',
 '../Dataset/SA13/D09_SA13_R01.csv',
 '../Dataset/SA13/D09_SA13_R02.csv',
 '../Dataset/SA13/D09_SA13_R03.csv',
 '../Dataset/SA13/D09_SA13_R04.csv',
 '../Dataset/SA13/D09_SA13_R05.csv',
 '../Dataset/SA13/D10_SA13_R01.csv',
 '../Dataset/SA13/D10_SA13_R02.csv',
 '../Dataset/SA13/D10_SA13_R03.csv',
 '../Dataset/SA13/D10_SA13_R04.csv',
 '../Dataset/SA13/D10_SA13_R05.csv',
 '../Dataset/SA13/D11_SA13_R01.csv',
 '../Dataset/SA13/D11_SA13_R02.csv',
 '../Dataset/SA13/D11_SA13_R03.csv',
 '../Dataset/SA13/D11_SA13_R04.csv',
 '../Dataset/SA13/D11_SA13_R05.csv',
 '../Dataset/SA13/D12_SA13_R01.csv',
 '../Dataset/SA13/D12_SA13_R02.csv',
 '../Dataset/SA13/D12_SA13_R03.csv',
 '../Dataset/SA13/D12_SA13_R04.csv',
 '../Dataset/SA13/D12_SA13_R05.csv',
 '../Dataset/SA13/D13_SA13_R01.csv',
 '../Dataset/SA13/D13_SA13_R02.csv',
 '../Dataset/SA13/D13_SA13_R03.csv',
 '../Dataset/SA13/D13_SA13_R04.csv',
 '../Dataset/SA13/D13_SA13_R05.csv',
 '../Dataset/SA13/D14_SA13_R01.csv',
 '../Dataset/SA13/D14_SA13_R02.csv',
 '../Dataset/SA13/D14_SA13_R03.csv',
 '../Dataset/SA13/D14_SA13_R04.csv',
 '../Dataset/SA13/D14_SA13_R05.csv',
 '../Dataset/SA13/D15_SA13_R01.csv',
 '../Dataset/SA13/D15_SA13_R02.csv',
 '../Dataset/SA13/D15_SA13_R03.csv',
 '../Dataset/SA13/D15_SA13_R04.csv',
 '../Dataset/SA13/D15_SA13_R05.csv',
 '../Dataset/SA13/D16_SA13_R01.csv',
 '../Dataset/SA13/D16_SA13_R02.csv',
 '../Dataset/SA13/D16_SA13_R03.csv',
 '../Dataset/SA13/D16_SA13_R04.csv',
 '../Dataset/SA13/D16_SA13_R05.csv',
 '../Dataset/SA13/D17_SA13_R01_1.csv',
 '../Dataset/SA13/D17_SA13_R01_2.csv',
 '../Dataset/SA13/D17_SA13_R02_1.csv',
 '../Dataset/SA13/D17_SA13_R02_2.csv',
 '../Dataset/SA13/D17_SA13_R03_1.csv',
 '../Dataset/SA13/D17_SA13_R03_2.csv',
 '../Dataset/SA13/D17_SA13_R04_1.csv',
 '../Dataset/SA13/D17_SA13_R04_2.csv',
 '../Dataset/SA13/D17_SA13_R05_1.csv',
 '../Dataset/SA13/D17_SA13_R05_2.csv',
 '../Dataset/SA13/D18_SA13_R01.csv',
 '../Dataset/SA13/D18_SA13_R02.csv',
 '../Dataset/SA13/D18_SA13_R03.csv',
 '../Dataset/SA13/D18_SA13_R04.csv',
 '../Dataset/SA13/D18_SA13_R05.csv',
 '../Dataset/SA13/D19_SA13_R01.csv',
 '../Dataset/SA13/D19_SA13_R02.csv',
 '../Dataset/SA13/D19_SA13_R03.csv',
 '../Dataset/SA13/D19_SA13_R04.csv',
 '../Dataset/SA13/D19_SA13_R05.csv']

In [219]:
list = []
final_SA13_A = pd.DataFrame(list)

for path in SA13_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA13_A = final_SA13_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA13_A.shape
target_col = row * [0]
final_SA13_A.loc[:,'target'] = target_col

final_SA13_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,253.0,254.0,252.0,254.0,251.0,250.0,248.0,248.0,247.0,248.0,...,250.0,250.0,253.0,252.0,250.0,248.0,245.0,242.0,244.0,0
0,367.0,388.0,412.0,430.0,429.0,423.0,416.0,403.0,390.0,376.0,...,191.0,192.0,193.0,190.0,193.0,186.0,186.0,190.0,196.0,0
0,114.0,114.0,109.0,106.0,121.0,110.0,112.0,114.0,114.0,108.0,...,129.0,122.0,105.0,90.0,68.0,51.0,52.0,65.0,75.0,0
0,255.0,255.0,253.0,254.0,252.0,254.0,250.0,249.0,248.0,246.0,...,254.0,253.0,251.0,252.0,248.0,248.0,247.0,244.0,244.0,0
0,251.0,244.0,243.0,242.0,245.0,244.0,246.0,243.0,244.0,242.0,...,264.0,268.0,274.0,276.0,277.0,279.0,277.0,279.0,276.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,255.0,258.0,256.0,260.0,257.0,256.0,258.0,258.0,260.0,257.0,...,260.0,257.0,257.0,256.0,255.0,258.0,254.0,254.0,254.0,0
0,259.0,261.0,260.0,262.0,262.0,257.0,261.0,260.0,260.0,263.0,...,260.0,262.0,263.0,261.0,262.0,261.0,262.0,260.0,260.0,0
0,262.0,263.0,261.0,259.0,261.0,261.0,261.0,261.0,262.0,260.0,...,259.0,259.0,259.0,262.0,262.0,261.0,258.0,259.0,263.0,0
0,261.0,262.0,260.0,261.0,260.0,257.0,262.0,258.0,259.0,257.0,...,264.0,263.0,261.0,264.0,263.0,267.0,266.0,267.0,265.0,0
0,260.0,259.0,260.0,258.0,260.0,263.0,257.0,262.0,261.0,261.0,...,267.0,268.0,266.0,267.0,265.0,264.0,264.0,265.0,267.0,0

# SA14

In [220]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA14_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA14')
    SA14_A_paths.append(path)

SA14_A_paths

['../Dataset/SA14/D01_SA14_R01.csv',
 '../Dataset/SA14/D02_SA14_R01.csv',
 '../Dataset/SA14/D03_SA14_R01.csv',
 '../Dataset/SA14/D04_SA14_R01.csv',
 '../Dataset/SA14/D05_SA14_R01_1.csv',
 '../Dataset/SA14/D05_SA14_R01_2.csv',
 '../Dataset/SA14/D05_SA14_R02_1.csv',
 '../Dataset/SA14/D05_SA14_R02_2.csv',
 '../Dataset/SA14/D05_SA14_R03_1.csv',
 '../Dataset/SA14/D05_SA14_R03_2.csv',
 '../Dataset/SA14/D05_SA14_R04_1.csv',
 '../Dataset/SA14/D05_SA14_R04_2.csv',
 '../Dataset/SA14/D05_SA14_R05_1.csv',
 '../Dataset/SA14/D05_SA14_R05_2.csv',
 '../Dataset/SA14/D06_SA14_R01_1.csv',
 '../Dataset/SA14/D06_SA14_R01_2.csv',
 '../Dataset/SA14/D06_SA14_R02_1.csv',
 '../Dataset/SA14/D06_SA14_R02_2.csv',
 '../Dataset/SA14/D06_SA14_R03_1.csv',
 '../Dataset/SA14/D06_SA14_R03_2.csv',
 '../Dataset/SA14/D06_SA14_R04_1.csv',
 '../Dataset/SA14/D06_SA14_R04_2.csv',
 '../Dataset/SA14/D06_SA14_R05_1.csv',
 '../Dataset/SA14/D06_SA14_R05_2.csv',
 '../Dataset/SA14/D07_SA14_R01.csv',
 '../Dataset/SA14/D07_SA14_R02.csv',
 '../Dataset/SA14/D07_SA14_R03.csv',
 '../Dataset/SA14/D07_SA14_R04.csv',
 '../Dataset/SA14/D07_SA14_R05.csv',
 '../Dataset/SA14/D08_SA14_R01.csv',
 '../Dataset/SA14/D08_SA14_R02.csv',
 '../Dataset/SA14/D08_SA14_R03.csv',
 '../Dataset/SA14/D08_SA14_R04.csv',
 '../Dataset/SA14/D08_SA14_R05.csv',
 '../Dataset/SA14/D09_SA14_R01.csv',
 '../Dataset/SA14/D09_SA14_R02.csv',
 '../Dataset/SA14/D09_SA14_R03.csv',
 '../Dataset/SA14/D09_SA14_R04.csv',
 '../Dataset/SA14/D09_SA14_R05.csv',
 '../Dataset/SA14/D10_SA14_R01.csv',
 '../Dataset/SA14/D10_SA14_R02.csv',
 '../Dataset/SA14/D10_SA14_R03.csv',
 '../Dataset/SA14/D10_SA14_R04.csv',
 '../Dataset/SA14/D10_SA14_R05.csv',
 '../Dataset/SA14/D11_SA14_R01.csv',
 '../Dataset/SA14/D11_SA14_R02.csv',
 '../Dataset/SA14/D11_SA14_R03.csv',
 '../Dataset/SA14/D11_SA14_R04.csv',
 '../Dataset/SA14/D11_SA14_R05.csv',
 '../Dataset/SA14/D12_SA14_R01.csv',
 '../Dataset/SA14/D12_SA14_R02.csv',
 '../Dataset/SA14/D12_SA14_R03.csv',
 '../Dataset/SA14/D12_SA14_R04.csv',
 '../Dataset/SA14/D12_SA14_R05.csv',
 '../Dataset/SA14/D13_SA14_R01.csv',
 '../Dataset/SA14/D13_SA14_R02.csv',
 '../Dataset/SA14/D13_SA14_R03.csv',
 '../Dataset/SA14/D13_SA14_R04.csv',
 '../Dataset/SA14/D13_SA14_R05.csv',
 '../Dataset/SA14/D14_SA14_R01.csv',
 '../Dataset/SA14/D14_SA14_R02.csv',
 '../Dataset/SA14/D14_SA14_R03.csv',
 '../Dataset/SA14/D14_SA14_R04.csv',
 '../Dataset/SA14/D14_SA14_R05.csv',
 '../Dataset/SA14/D15_SA14_R01.csv',
 '../Dataset/SA14/D15_SA14_R02.csv',
 '../Dataset/SA14/D15_SA14_R03.csv',
 '../Dataset/SA14/D15_SA14_R04.csv',
 '../Dataset/SA14/D15_SA14_R05.csv',
 '../Dataset/SA14/D16_SA14_R01.csv',
 '../Dataset/SA14/D16_SA14_R02.csv',
 '../Dataset/SA14/D16_SA14_R03.csv',
 '../Dataset/SA14/D16_SA14_R04.csv',
 '../Dataset/SA14/D16_SA14_R05.csv',
 '../Dataset/SA14/D17_SA14_R01_1.csv',
 '../Dataset/SA14/D17_SA14_R01_2.csv',
 '../Dataset/SA14/D17_SA14_R02_1.csv',
 '../Dataset/SA14/D17_SA14_R02_2.csv',
 '../Dataset/SA14/D17_SA14_R03_1.csv',
 '../Dataset/SA14/D17_SA14_R03_2.csv',
 '../Dataset/SA14/D17_SA14_R04_1.csv',
 '../Dataset/SA14/D17_SA14_R04_2.csv',
 '../Dataset/SA14/D17_SA14_R05_1.csv',
 '../Dataset/SA14/D17_SA14_R05_2.csv',
 '../Dataset/SA14/D18_SA14_R01.csv',
 '../Dataset/SA14/D18_SA14_R02.csv',
 '../Dataset/SA14/D18_SA14_R03.csv',
 '../Dataset/SA14/D18_SA14_R04.csv',
 '../Dataset/SA14/D18_SA14_R05.csv',
 '../Dataset/SA14/D19_SA14_R01.csv',
 '../Dataset/SA14/D19_SA14_R02.csv',
 '../Dataset/SA14/D19_SA14_R03.csv',
 '../Dataset/SA14/D19_SA14_R04.csv',
 '../Dataset/SA14/D19_SA14_R05.csv']

In [221]:
list = []
final_SA14_A = pd.DataFrame(list)

for path in SA14_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA14_A = final_SA14_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA14_A.shape
target_col = row * [0]
final_SA14_A.loc[:,'target'] = target_col

final_SA14_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,271.0,273.0,273.0,268.0,276.0,274.0,263.0,276.0,264.0,266.0,...,257.0,257.0,253.0,256.0,258.0,261.0,260.0,260.0,257.0,0
0,304.0,314.0,328.0,332.0,333.0,339.0,328.0,317.0,338.0,333.0,...,281.0,271.0,263.0,254.0,247.0,243.0,248.0,255.0,265.0,0
0,48.0,56.0,77.0,81.0,87.0,88.0,110.0,131.0,157.0,195.0,...,329.0,379.0,445.0,519.0,696.0,707.0,690.0,579.0,496.0,0
0,482.0,495.0,508.0,533.0,548.0,554.0,549.0,538.0,532.0,521.0,...,343.0,297.0,263.0,228.0,193.0,160.0,134.0,97.0,62.0,0
0,235.0,236.0,246.0,230.0,237.0,225.0,226.0,214.0,205.0,214.0,...,221.0,218.0,216.0,215.0,212.0,213.0,216.0,220.0,223.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,276.0,275.0,275.0,273.0,276.0,275.0,271.0,272.0,278.0,277.0,...,635.0,554.0,448.0,323.0,207.0,132.0,103.0,141.0,210.0,0
0,275.0,272.0,272.0,275.0,273.0,274.0,271.0,274.0,272.0,277.0,...,276.0,276.0,273.0,272.0,272.0,274.0,274.0,276.0,273.0,0
0,273.0,272.0,275.0,274.0,273.0,277.0,274.0,274.0,273.0,271.0,...,273.0,275.0,271.0,273.0,273.0,272.0,274.0,275.0,272.0,0
0,274.0,276.0,275.0,275.0,273.0,276.0,272.0,273.0,275.0,276.0,...,275.0,274.0,275.0,275.0,275.0,276.0,274.0,274.0,271.0,0
0,273.0,276.0,274.0,275.0,276.0,274.0,276.0,273.0,274.0,272.0,...,279.0,275.0,276.0,273.0,276.0,276.0,276.0,274.0,276.0,0

# SA15

In [222]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA15_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA15')
    SA15_A_paths.append(path)

SA15_A_paths

['../Dataset/SA15/D01_SA15_R01.csv',
 '../Dataset/SA15/D02_SA15_R01.csv',
 '../Dataset/SA15/D03_SA15_R01.csv',
 '../Dataset/SA15/D04_SA15_R01.csv',
 '../Dataset/SA15/D05_SA15_R01_1.csv',
 '../Dataset/SA15/D05_SA15_R01_2.csv',
 '../Dataset/SA15/D05_SA15_R02_1.csv',
 '../Dataset/SA15/D05_SA15_R02_2.csv',
 '../Dataset/SA15/D05_SA15_R03_1.csv',
 '../Dataset/SA15/D05_SA15_R03_2.csv',
 '../Dataset/SA15/D05_SA15_R04_1.csv',
 '../Dataset/SA15/D05_SA15_R04_2.csv',
 '../Dataset/SA15/D05_SA15_R05_1.csv',
 '../Dataset/SA15/D05_SA15_R05_2.csv',
 '../Dataset/SA15/D06_SA15_R01_1.csv',
 '../Dataset/SA15/D06_SA15_R01_2.csv',
 '../Dataset/SA15/D06_SA15_R02_1.csv',
 '../Dataset/SA15/D06_SA15_R02_2.csv',
 '../Dataset/SA15/D06_SA15_R03_1.csv',
 '../Dataset/SA15/D06_SA15_R03_2.csv',
 '../Dataset/SA15/D06_SA15_R04_1.csv',
 '../Dataset/SA15/D06_SA15_R04_2.csv',
 '../Dataset/SA15/D06_SA15_R05_1.csv',
 '../Dataset/SA15/D06_SA15_R05_2.csv',
 '../Dataset/SA15/D07_SA15_R01.csv',
 '../Dataset/SA15/D07_SA15_R02.csv',
 '../Dataset/SA15/D07_SA15_R03.csv',
 '../Dataset/SA15/D07_SA15_R04.csv',
 '../Dataset/SA15/D07_SA15_R05.csv',
 '../Dataset/SA15/D08_SA15_R01.csv',
 '../Dataset/SA15/D08_SA15_R02.csv',
 '../Dataset/SA15/D08_SA15_R03.csv',
 '../Dataset/SA15/D08_SA15_R04.csv',
 '../Dataset/SA15/D08_SA15_R05.csv',
 '../Dataset/SA15/D09_SA15_R01.csv',
 '../Dataset/SA15/D09_SA15_R02.csv',
 '../Dataset/SA15/D09_SA15_R03.csv',
 '../Dataset/SA15/D09_SA15_R04.csv',
 '../Dataset/SA15/D09_SA15_R05.csv',
 '../Dataset/SA15/D10_SA15_R01.csv',
 '../Dataset/SA15/D10_SA15_R02.csv',
 '../Dataset/SA15/D10_SA15_R03.csv',
 '../Dataset/SA15/D10_SA15_R04.csv',
 '../Dataset/SA15/D10_SA15_R05.csv',
 '../Dataset/SA15/D11_SA15_R01.csv',
 '../Dataset/SA15/D11_SA15_R02.csv',
 '../Dataset/SA15/D11_SA15_R03.csv',
 '../Dataset/SA15/D11_SA15_R04.csv',
 '../Dataset/SA15/D11_SA15_R05.csv',
 '../Dataset/SA15/D12_SA15_R01.csv',
 '../Dataset/SA15/D12_SA15_R02.csv',
 '../Dataset/SA15/D12_SA15_R03.csv',
 '../Dataset/SA15/D12_SA15_R04.csv',
 '../Dataset/SA15/D12_SA15_R05.csv',
 '../Dataset/SA15/D13_SA15_R01.csv',
 '../Dataset/SA15/D13_SA15_R02.csv',
 '../Dataset/SA15/D13_SA15_R03.csv',
 '../Dataset/SA15/D13_SA15_R04.csv',
 '../Dataset/SA15/D13_SA15_R05.csv',
 '../Dataset/SA15/D14_SA15_R01.csv',
 '../Dataset/SA15/D14_SA15_R02.csv',
 '../Dataset/SA15/D14_SA15_R03.csv',
 '../Dataset/SA15/D14_SA15_R04.csv',
 '../Dataset/SA15/D14_SA15_R05.csv',
 '../Dataset/SA15/D15_SA15_R01.csv',
 '../Dataset/SA15/D15_SA15_R02.csv',
 '../Dataset/SA15/D15_SA15_R03.csv',
 '../Dataset/SA15/D15_SA15_R04.csv',
 '../Dataset/SA15/D15_SA15_R05.csv',
 '../Dataset/SA15/D16_SA15_R01.csv',
 '../Dataset/SA15/D16_SA15_R02.csv',
 '../Dataset/SA15/D16_SA15_R03.csv',
 '../Dataset/SA15/D16_SA15_R04.csv',
 '../Dataset/SA15/D16_SA15_R05.csv',
 '../Dataset/SA15/D17_SA15_R01_1.csv',
 '../Dataset/SA15/D17_SA15_R01_2.csv',
 '../Dataset/SA15/D17_SA15_R02_1.csv',
 '../Dataset/SA15/D17_SA15_R02_2.csv',
 '../Dataset/SA15/D17_SA15_R03_1.csv',
 '../Dataset/SA15/D17_SA15_R03_2.csv',
 '../Dataset/SA15/D17_SA15_R04_1.csv',
 '../Dataset/SA15/D17_SA15_R04_2.csv',
 '../Dataset/SA15/D17_SA15_R05_1.csv',
 '../Dataset/SA15/D17_SA15_R05_2.csv',
 '../Dataset/SA15/D18_SA15_R01.csv',
 '../Dataset/SA15/D18_SA15_R02.csv',
 '../Dataset/SA15/D18_SA15_R03.csv',
 '../Dataset/SA15/D18_SA15_R04.csv',
 '../Dataset/SA15/D18_SA15_R05.csv',
 '../Dataset/SA15/D19_SA15_R01.csv',
 '../Dataset/SA15/D19_SA15_R02.csv',
 '../Dataset/SA15/D19_SA15_R03.csv',
 '../Dataset/SA15/D19_SA15_R04.csv',
 '../Dataset/SA15/D19_SA15_R05.csv']

In [223]:
list = []
final_SA15_A = pd.DataFrame(list)

for path in SA15_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA15_A = final_SA15_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA15_A.shape
target_col = row * [0]
final_SA15_A.loc[:,'target'] = target_col

final_SA15_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,267.0,262.0,258.0,254.0,253.0,248.0,239.0,235.0,228.0,225.0,...,238.0,242.0,239.0,238.0,241.0,245.0,248.0,246.0,248.0,0
0,231.0,225.0,220.0,208.0,201.0,194.0,187.0,183.0,180.0,181.0,...,391.0,431.0,452.0,461.0,446.0,437.0,418.0,400.0,387.0,0
0,20.0,15.0,25.0,40.0,52.0,65.0,76.0,78.0,71.0,72.0,...,71.0,70.0,66.0,64.0,69.0,73.0,66.0,61.0,61.0,0
0,463.0,511.0,617.0,718.0,775.0,799.0,769.0,786.0,871.0,962.0,...,1048.0,909.0,799.0,724.0,646.0,573.0,515.0,471.0,442.0,0
0,297.0,311.0,311.0,307.0,304.0,299.0,291.0,288.0,289.0,295.0,...,291.0,298.0,306.0,315.0,323.0,332.0,340.0,351.0,365.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,268.0,264.0,266.0,266.0,265.0,265.0,265.0,265.0,267.0,264.0,...,264.0,270.0,267.0,266.0,268.0,267.0,268.0,266.0,269.0,0
0,268.0,265.0,266.0,265.0,269.0,269.0,266.0,269.0,267.0,264.0,...,266.0,267.0,266.0,265.0,265.0,264.0,268.0,268.0,268.0,0
0,265.0,267.0,268.0,266.0,266.0,262.0,268.0,266.0,264.0,266.0,...,266.0,265.0,268.0,271.0,268.0,268.0,267.0,266.0,266.0,0
0,264.0,266.0,265.0,267.0,266.0,269.0,265.0,265.0,267.0,268.0,...,269.0,267.0,266.0,267.0,264.0,266.0,266.0,266.0,266.0,0
0,266.0,265.0,268.0,267.0,264.0,268.0,265.0,266.0,265.0,264.0,...,265.0,267.0,265.0,265.0,269.0,265.0,267.0,265.0,267.0,0

# SA16

In [224]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA16_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA16')
    SA16_A_paths.append(path)

SA16_A_paths

['../Dataset/SA16/D01_SA16_R01.csv',
 '../Dataset/SA16/D02_SA16_R01.csv',
 '../Dataset/SA16/D03_SA16_R01.csv',
 '../Dataset/SA16/D04_SA16_R01.csv',
 '../Dataset/SA16/D05_SA16_R01_1.csv',
 '../Dataset/SA16/D05_SA16_R01_2.csv',
 '../Dataset/SA16/D05_SA16_R02_1.csv',
 '../Dataset/SA16/D05_SA16_R02_2.csv',
 '../Dataset/SA16/D05_SA16_R03_1.csv',
 '../Dataset/SA16/D05_SA16_R03_2.csv',
 '../Dataset/SA16/D05_SA16_R04_1.csv',
 '../Dataset/SA16/D05_SA16_R04_2.csv',
 '../Dataset/SA16/D05_SA16_R05_1.csv',
 '../Dataset/SA16/D05_SA16_R05_2.csv',
 '../Dataset/SA16/D06_SA16_R01_1.csv',
 '../Dataset/SA16/D06_SA16_R01_2.csv',
 '../Dataset/SA16/D06_SA16_R02_1.csv',
 '../Dataset/SA16/D06_SA16_R02_2.csv',
 '../Dataset/SA16/D06_SA16_R03_1.csv',
 '../Dataset/SA16/D06_SA16_R03_2.csv',
 '../Dataset/SA16/D06_SA16_R04_1.csv',
 '../Dataset/SA16/D06_SA16_R04_2.csv',
 '../Dataset/SA16/D06_SA16_R05_1.csv',
 '../Dataset/SA16/D06_SA16_R05_2.csv',
 '../Dataset/SA16/D07_SA16_R01.csv',
 '../Dataset/SA16/D07_SA16_R02.csv',
 '../Dataset/SA16/D07_SA16_R03.csv',
 '../Dataset/SA16/D07_SA16_R04.csv',
 '../Dataset/SA16/D07_SA16_R05.csv',
 '../Dataset/SA16/D08_SA16_R01.csv',
 '../Dataset/SA16/D08_SA16_R02.csv',
 '../Dataset/SA16/D08_SA16_R03.csv',
 '../Dataset/SA16/D08_SA16_R04.csv',
 '../Dataset/SA16/D08_SA16_R05.csv',
 '../Dataset/SA16/D09_SA16_R01.csv',
 '../Dataset/SA16/D09_SA16_R02.csv',
 '../Dataset/SA16/D09_SA16_R03.csv',
 '../Dataset/SA16/D09_SA16_R04.csv',
 '../Dataset/SA16/D09_SA16_R05.csv',
 '../Dataset/SA16/D10_SA16_R01.csv',
 '../Dataset/SA16/D10_SA16_R02.csv',
 '../Dataset/SA16/D10_SA16_R03.csv',
 '../Dataset/SA16/D10_SA16_R04.csv',
 '../Dataset/SA16/D10_SA16_R05.csv',
 '../Dataset/SA16/D11_SA16_R01.csv',
 '../Dataset/SA16/D11_SA16_R02.csv',
 '../Dataset/SA16/D11_SA16_R03.csv',
 '../Dataset/SA16/D11_SA16_R04.csv',
 '../Dataset/SA16/D11_SA16_R05.csv',
 '../Dataset/SA16/D12_SA16_R01.csv',
 '../Dataset/SA16/D12_SA16_R02.csv',
 '../Dataset/SA16/D12_SA16_R03.csv',
 '../Dataset/SA16/D12_SA16_R04.csv',
 '../Dataset/SA16/D12_SA16_R05.csv',
 '../Dataset/SA16/D13_SA16_R01.csv',
 '../Dataset/SA16/D13_SA16_R02.csv',
 '../Dataset/SA16/D13_SA16_R03.csv',
 '../Dataset/SA16/D13_SA16_R04.csv',
 '../Dataset/SA16/D13_SA16_R05.csv',
 '../Dataset/SA16/D14_SA16_R01.csv',
 '../Dataset/SA16/D14_SA16_R02.csv',
 '../Dataset/SA16/D14_SA16_R03.csv',
 '../Dataset/SA16/D14_SA16_R04.csv',
 '../Dataset/SA16/D14_SA16_R05.csv',
 '../Dataset/SA16/D15_SA16_R01.csv',
 '../Dataset/SA16/D15_SA16_R02.csv',
 '../Dataset/SA16/D15_SA16_R03.csv',
 '../Dataset/SA16/D15_SA16_R04.csv',
 '../Dataset/SA16/D15_SA16_R05.csv',
 '../Dataset/SA16/D16_SA16_R01.csv',
 '../Dataset/SA16/D16_SA16_R02.csv',
 '../Dataset/SA16/D16_SA16_R03.csv',
 '../Dataset/SA16/D16_SA16_R04.csv',
 '../Dataset/SA16/D16_SA16_R05.csv',
 '../Dataset/SA16/D17_SA16_R01_1.csv',
 '../Dataset/SA16/D17_SA16_R01_2.csv',
 '../Dataset/SA16/D17_SA16_R02_1.csv',
 '../Dataset/SA16/D17_SA16_R02_2.csv',
 '../Dataset/SA16/D17_SA16_R03_1.csv',
 '../Dataset/SA16/D17_SA16_R03_2.csv',
 '../Dataset/SA16/D17_SA16_R04_1.csv',
 '../Dataset/SA16/D17_SA16_R04_2.csv',
 '../Dataset/SA16/D17_SA16_R05_1.csv',
 '../Dataset/SA16/D17_SA16_R05_2.csv',
 '../Dataset/SA16/D18_SA16_R01.csv',
 '../Dataset/SA16/D18_SA16_R02.csv',
 '../Dataset/SA16/D18_SA16_R03.csv',
 '../Dataset/SA16/D18_SA16_R04.csv',
 '../Dataset/SA16/D18_SA16_R05.csv',
 '../Dataset/SA16/D19_SA16_R01.csv',
 '../Dataset/SA16/D19_SA16_R02.csv',
 '../Dataset/SA16/D19_SA16_R03.csv',
 '../Dataset/SA16/D19_SA16_R04.csv',
 '../Dataset/SA16/D19_SA16_R05.csv']

In [225]:
list = []
final_SA16_A = pd.DataFrame(list)

for path in SA16_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA16_A = final_SA16_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA16_A.shape
target_col = row * [0]
final_SA16_A.loc[:,'target'] = target_col

final_SA16_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,248.0,248.0,250.0,251.0,255.0,258.0,262.0,265.0,269.0,276.0,...,268.0,269.0,266.0,261.0,263.0,263.0,260.0,264.0,267.0,0
0,256.0,252.0,251.0,252.0,253.0,250.0,249.0,250.0,251.0,254.0,...,277.0,280.0,286.0,290.0,297.0,302.0,311.0,313.0,319.0,0
0,259.0,258.0,254.0,254.0,256.0,245.0,264.0,275.0,258.0,257.0,...,267.0,265.0,265.0,264.0,266.0,267.0,266.0,268.0,273.0,0
0,90.0,72.0,55.0,44.0,41.0,38.0,33.0,34.0,37.0,37.0,...,70.0,63.0,59.0,47.0,47.0,45.0,57.0,75.0,101.0,0
0,237.0,232.0,235.0,234.0,238.0,243.0,242.0,246.0,242.0,248.0,...,279.0,274.0,270.0,264.0,261.0,259.0,256.0,256.0,252.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,254.0,253.0,252.0,254.0,258.0,256.0,254.0,253.0,250.0,253.0,...,255.0,252.0,254.0,253.0,251.0,252.0,251.0,256.0,254.0,0
0,259.0,258.0,260.0,256.0,258.0,261.0,256.0,257.0,258.0,255.0,...,260.0,256.0,258.0,257.0,261.0,255.0,255.0,257.0,256.0,0
0,256.0,257.0,253.0,251.0,249.0,255.0,253.0,254.0,254.0,252.0,...,239.0,253.0,253.0,258.0,249.0,260.0,258.0,256.0,256.0,0
0,255.0,255.0,252.0,255.0,253.0,252.0,255.0,253.0,256.0,251.0,...,254.0,255.0,258.0,253.0,260.0,254.0,259.0,257.0,260.0,0
0,257.0,255.0,252.0,254.0,253.0,256.0,253.0,253.0,254.0,254.0,...,253.0,257.0,255.0,257.0,258.0,255.0,260.0,257.0,260.0,0

# SA17

In [226]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA17_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA17')
    SA17_A_paths.append(path)

SA17_A_paths

['../Dataset/SA17/D01_SA17_R01.csv',
 '../Dataset/SA17/D02_SA17_R01.csv',
 '../Dataset/SA17/D03_SA17_R01.csv',
 '../Dataset/SA17/D04_SA17_R01.csv',
 '../Dataset/SA17/D05_SA17_R01_1.csv',
 '../Dataset/SA17/D05_SA17_R01_2.csv',
 '../Dataset/SA17/D05_SA17_R02_1.csv',
 '../Dataset/SA17/D05_SA17_R02_2.csv',
 '../Dataset/SA17/D05_SA17_R03_1.csv',
 '../Dataset/SA17/D05_SA17_R03_2.csv',
 '../Dataset/SA17/D05_SA17_R04_1.csv',
 '../Dataset/SA17/D05_SA17_R04_2.csv',
 '../Dataset/SA17/D05_SA17_R05_1.csv',
 '../Dataset/SA17/D05_SA17_R05_2.csv',
 '../Dataset/SA17/D06_SA17_R01_1.csv',
 '../Dataset/SA17/D06_SA17_R01_2.csv',
 '../Dataset/SA17/D06_SA17_R02_1.csv',
 '../Dataset/SA17/D06_SA17_R02_2.csv',
 '../Dataset/SA17/D06_SA17_R03_1.csv',
 '../Dataset/SA17/D06_SA17_R03_2.csv',
 '../Dataset/SA17/D06_SA17_R04_1.csv',
 '../Dataset/SA17/D06_SA17_R04_2.csv',
 '../Dataset/SA17/D06_SA17_R05_1.csv',
 '../Dataset/SA17/D06_SA17_R05_2.csv',
 '../Dataset/SA17/D07_SA17_R01.csv',
 '../Dataset/SA17/D07_SA17_R02.csv',
 '../Dataset/SA17/D07_SA17_R03.csv',
 '../Dataset/SA17/D07_SA17_R04.csv',
 '../Dataset/SA17/D07_SA17_R05.csv',
 '../Dataset/SA17/D08_SA17_R01.csv',
 '../Dataset/SA17/D08_SA17_R02.csv',
 '../Dataset/SA17/D08_SA17_R03.csv',
 '../Dataset/SA17/D08_SA17_R04.csv',
 '../Dataset/SA17/D08_SA17_R05.csv',
 '../Dataset/SA17/D09_SA17_R01.csv',
 '../Dataset/SA17/D09_SA17_R02.csv',
 '../Dataset/SA17/D09_SA17_R03.csv',
 '../Dataset/SA17/D09_SA17_R04.csv',
 '../Dataset/SA17/D09_SA17_R05.csv',
 '../Dataset/SA17/D10_SA17_R01.csv',
 '../Dataset/SA17/D10_SA17_R02.csv',
 '../Dataset/SA17/D10_SA17_R03.csv',
 '../Dataset/SA17/D10_SA17_R04.csv',
 '../Dataset/SA17/D10_SA17_R05.csv',
 '../Dataset/SA17/D11_SA17_R01.csv',
 '../Dataset/SA17/D11_SA17_R02.csv',
 '../Dataset/SA17/D11_SA17_R03.csv',
 '../Dataset/SA17/D11_SA17_R04.csv',
 '../Dataset/SA17/D11_SA17_R05.csv',
 '../Dataset/SA17/D12_SA17_R01.csv',
 '../Dataset/SA17/D12_SA17_R02.csv',
 '../Dataset/SA17/D12_SA17_R03.csv',
 '../Dataset/SA17/D12_SA17_R04.csv',
 '../Dataset/SA17/D12_SA17_R05.csv',
 '../Dataset/SA17/D13_SA17_R01.csv',
 '../Dataset/SA17/D13_SA17_R02.csv',
 '../Dataset/SA17/D13_SA17_R03.csv',
 '../Dataset/SA17/D13_SA17_R04.csv',
 '../Dataset/SA17/D13_SA17_R05.csv',
 '../Dataset/SA17/D14_SA17_R01.csv',
 '../Dataset/SA17/D14_SA17_R02.csv',
 '../Dataset/SA17/D14_SA17_R03.csv',
 '../Dataset/SA17/D14_SA17_R04.csv',
 '../Dataset/SA17/D14_SA17_R05.csv',
 '../Dataset/SA17/D15_SA17_R01.csv',
 '../Dataset/SA17/D15_SA17_R02.csv',
 '../Dataset/SA17/D15_SA17_R03.csv',
 '../Dataset/SA17/D15_SA17_R04.csv',
 '../Dataset/SA17/D15_SA17_R05.csv',
 '../Dataset/SA17/D16_SA17_R01.csv',
 '../Dataset/SA17/D16_SA17_R02.csv',
 '../Dataset/SA17/D16_SA17_R03.csv',
 '../Dataset/SA17/D16_SA17_R04.csv',
 '../Dataset/SA17/D16_SA17_R05.csv',
 '../Dataset/SA17/D17_SA17_R01_1.csv',
 '../Dataset/SA17/D17_SA17_R01_2.csv',
 '../Dataset/SA17/D17_SA17_R02_1.csv',
 '../Dataset/SA17/D17_SA17_R02_2.csv',
 '../Dataset/SA17/D17_SA17_R03_1.csv',
 '../Dataset/SA17/D17_SA17_R03_2.csv',
 '../Dataset/SA17/D17_SA17_R04_1.csv',
 '../Dataset/SA17/D17_SA17_R04_2.csv',
 '../Dataset/SA17/D17_SA17_R05_1.csv',
 '../Dataset/SA17/D17_SA17_R05_2.csv',
 '../Dataset/SA17/D18_SA17_R01.csv',
 '../Dataset/SA17/D18_SA17_R02.csv',
 '../Dataset/SA17/D18_SA17_R03.csv',
 '../Dataset/SA17/D18_SA17_R04.csv',
 '../Dataset/SA17/D18_SA17_R05.csv',
 '../Dataset/SA17/D19_SA17_R01.csv',
 '../Dataset/SA17/D19_SA17_R02.csv',
 '../Dataset/SA17/D19_SA17_R03.csv',
 '../Dataset/SA17/D19_SA17_R04.csv',
 '../Dataset/SA17/D19_SA17_R05.csv']

In [227]:
list = []
final_SA17_A = pd.DataFrame(list)

for path in SA17_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA17_A = final_SA17_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA17_A.shape
target_col = row * [0]
final_SA17_A.loc[:,'target'] = target_col

final_SA17_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,245.0,246.0,243.0,241.0,242.0,241.0,242.0,242.0,233.0,233.0,...,262.0,261.0,264.0,266.0,265.0,265.0,267.0,269.0,269.0,0
0,244.0,248.0,252.0,254.0,258.0,265.0,255.0,268.0,264.0,267.0,...,258.0,257.0,252.0,252.0,255.0,256.0,258.0,260.0,256.0,0
0,244.0,245.0,243.0,246.0,249.0,253.0,247.0,258.0,249.0,251.0,...,365.0,359.0,348.0,342.0,330.0,325.0,318.0,310.0,313.0,0
0,262.0,260.0,261.0,255.0,255.0,244.0,251.0,246.0,252.0,258.0,...,255.0,257.0,256.0,256.0,254.0,256.0,256.0,255.0,253.0,0
0,258.0,260.0,264.0,263.0,263.0,264.0,260.0,262.0,262.0,262.0,...,254.0,249.0,250.0,250.0,250.0,253.0,256.0,251.0,254.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,262.0,257.0,258.0,255.0,255.0,254.0,253.0,255.0,256.0,254.0,...,257.0,256.0,255.0,255.0,255.0,260.0,258.0,255.0,257.0,0
0,260.0,257.0,259.0,257.0,258.0,255.0,257.0,259.0,255.0,256.0,...,260.0,260.0,262.0,264.0,261.0,261.0,258.0,257.0,255.0,0
0,254.0,258.0,259.0,260.0,265.0,263.0,263.0,266.0,264.0,265.0,...,256.0,260.0,259.0,260.0,257.0,257.0,258.0,258.0,257.0,0
0,259.0,259.0,260.0,258.0,259.0,259.0,257.0,256.0,255.0,256.0,...,259.0,257.0,259.0,257.0,258.0,256.0,261.0,257.0,260.0,0
0,260.0,258.0,258.0,261.0,256.0,258.0,257.0,256.0,254.0,257.0,...,256.0,258.0,254.0,257.0,257.0,255.0,256.0,255.0,258.0,0

# SA18

In [228]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA18_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA18')
    SA18_A_paths.append(path)

SA18_A_paths

['../Dataset/SA18/D01_SA18_R01.csv',
 '../Dataset/SA18/D02_SA18_R01.csv',
 '../Dataset/SA18/D03_SA18_R01.csv',
 '../Dataset/SA18/D04_SA18_R01.csv',
 '../Dataset/SA18/D05_SA18_R01_1.csv',
 '../Dataset/SA18/D05_SA18_R01_2.csv',
 '../Dataset/SA18/D05_SA18_R02_1.csv',
 '../Dataset/SA18/D05_SA18_R02_2.csv',
 '../Dataset/SA18/D05_SA18_R03_1.csv',
 '../Dataset/SA18/D05_SA18_R03_2.csv',
 '../Dataset/SA18/D05_SA18_R04_1.csv',
 '../Dataset/SA18/D05_SA18_R04_2.csv',
 '../Dataset/SA18/D05_SA18_R05_1.csv',
 '../Dataset/SA18/D05_SA18_R05_2.csv',
 '../Dataset/SA18/D06_SA18_R01_1.csv',
 '../Dataset/SA18/D06_SA18_R01_2.csv',
 '../Dataset/SA18/D06_SA18_R02_1.csv',
 '../Dataset/SA18/D06_SA18_R02_2.csv',
 '../Dataset/SA18/D06_SA18_R03_1.csv',
 '../Dataset/SA18/D06_SA18_R03_2.csv',
 '../Dataset/SA18/D06_SA18_R04_1.csv',
 '../Dataset/SA18/D06_SA18_R04_2.csv',
 '../Dataset/SA18/D06_SA18_R05_1.csv',
 '../Dataset/SA18/D06_SA18_R05_2.csv',
 '../Dataset/SA18/D07_SA18_R01.csv',
 '../Dataset/SA18/D07_SA18_R02.csv',
 '../Dataset/SA18/D07_SA18_R03.csv',
 '../Dataset/SA18/D07_SA18_R04.csv',
 '../Dataset/SA18/D07_SA18_R05.csv',
 '../Dataset/SA18/D08_SA18_R01.csv',
 '../Dataset/SA18/D08_SA18_R02.csv',
 '../Dataset/SA18/D08_SA18_R03.csv',
 '../Dataset/SA18/D08_SA18_R04.csv',
 '../Dataset/SA18/D08_SA18_R05.csv',
 '../Dataset/SA18/D09_SA18_R01.csv',
 '../Dataset/SA18/D09_SA18_R02.csv',
 '../Dataset/SA18/D09_SA18_R03.csv',
 '../Dataset/SA18/D09_SA18_R04.csv',
 '../Dataset/SA18/D09_SA18_R05.csv',
 '../Dataset/SA18/D10_SA18_R01.csv',
 '../Dataset/SA18/D10_SA18_R02.csv',
 '../Dataset/SA18/D10_SA18_R03.csv',
 '../Dataset/SA18/D10_SA18_R04.csv',
 '../Dataset/SA18/D10_SA18_R05.csv',
 '../Dataset/SA18/D11_SA18_R01.csv',
 '../Dataset/SA18/D11_SA18_R02.csv',
 '../Dataset/SA18/D11_SA18_R03.csv',
 '../Dataset/SA18/D11_SA18_R04.csv',
 '../Dataset/SA18/D11_SA18_R05.csv',
 '../Dataset/SA18/D12_SA18_R01.csv',
 '../Dataset/SA18/D12_SA18_R02.csv',
 '../Dataset/SA18/D12_SA18_R03.csv',
 '../Dataset/SA18/D12_SA18_R04.csv',
 '../Dataset/SA18/D12_SA18_R05.csv',
 '../Dataset/SA18/D13_SA18_R01.csv',
 '../Dataset/SA18/D13_SA18_R02.csv',
 '../Dataset/SA18/D13_SA18_R03.csv',
 '../Dataset/SA18/D13_SA18_R04.csv',
 '../Dataset/SA18/D13_SA18_R05.csv',
 '../Dataset/SA18/D14_SA18_R01.csv',
 '../Dataset/SA18/D14_SA18_R02.csv',
 '../Dataset/SA18/D14_SA18_R03.csv',
 '../Dataset/SA18/D14_SA18_R04.csv',
 '../Dataset/SA18/D14_SA18_R05.csv',
 '../Dataset/SA18/D15_SA18_R01.csv',
 '../Dataset/SA18/D15_SA18_R02.csv',
 '../Dataset/SA18/D15_SA18_R03.csv',
 '../Dataset/SA18/D15_SA18_R04.csv',
 '../Dataset/SA18/D15_SA18_R05.csv',
 '../Dataset/SA18/D16_SA18_R01.csv',
 '../Dataset/SA18/D16_SA18_R02.csv',
 '../Dataset/SA18/D16_SA18_R03.csv',
 '../Dataset/SA18/D16_SA18_R04.csv',
 '../Dataset/SA18/D16_SA18_R05.csv',
 '../Dataset/SA18/D17_SA18_R01_1.csv',
 '../Dataset/SA18/D17_SA18_R01_2.csv',
 '../Dataset/SA18/D17_SA18_R02_1.csv',
 '../Dataset/SA18/D17_SA18_R02_2.csv',
 '../Dataset/SA18/D17_SA18_R03_1.csv',
 '../Dataset/SA18/D17_SA18_R03_2.csv',
 '../Dataset/SA18/D17_SA18_R04_1.csv',
 '../Dataset/SA18/D17_SA18_R04_2.csv',
 '../Dataset/SA18/D17_SA18_R05_1.csv',
 '../Dataset/SA18/D17_SA18_R05_2.csv',
 '../Dataset/SA18/D18_SA18_R01.csv',
 '../Dataset/SA18/D18_SA18_R02.csv',
 '../Dataset/SA18/D18_SA18_R03.csv',
 '../Dataset/SA18/D18_SA18_R04.csv',
 '../Dataset/SA18/D18_SA18_R05.csv',
 '../Dataset/SA18/D19_SA18_R01.csv',
 '../Dataset/SA18/D19_SA18_R02.csv',
 '../Dataset/SA18/D19_SA18_R03.csv',
 '../Dataset/SA18/D19_SA18_R04.csv',
 '../Dataset/SA18/D19_SA18_R05.csv']

In [229]:
list = []
final_SA18_A = pd.DataFrame(list)

for path in SA18_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA18_A = final_SA18_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA18_A.shape
target_col = row * [0]
final_SA18_A.loc[:,'target'] = target_col

final_SA18_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,257.0,255.0,258.0,255.0,255.0,273.0,245.0,252.0,257.0,255.0,...,254.0,252.0,254.0,252.0,251.0,251.0,244.0,251.0,252.0,0
0,257.0,258.0,259.0,257.0,257.0,263.0,257.0,256.0,253.0,253.0,...,258.0,255.0,250.0,250.0,250.0,249.0,249.0,248.0,246.0,0
0,231.0,233.0,235.0,240.0,242.0,247.0,244.0,255.0,253.0,250.0,...,676.0,668.0,621.0,499.0,392.0,342.0,341.0,388.0,442.0,0
0,192.0,193.0,193.0,187.0,195.0,191.0,191.0,189.0,189.0,187.0,...,299.0,263.0,220.0,174.0,139.0,182.0,126.0,136.0,154.0,0
0,262.0,257.0,251.0,251.0,253.0,255.0,260.0,258.0,259.0,261.0,...,264.0,261.0,260.0,258.0,260.0,258.0,259.0,261.0,257.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,259.0,258.0,255.0,253.0,252.0,254.0,254.0,251.0,257.0,253.0,...,253.0,252.0,252.0,254.0,254.0,253.0,256.0,256.0,256.0,0
0,256.0,257.0,260.0,259.0,261.0,255.0,258.0,257.0,255.0,260.0,...,254.0,257.0,255.0,253.0,253.0,254.0,256.0,256.0,258.0,0
0,257.0,257.0,259.0,257.0,258.0,258.0,257.0,255.0,257.0,256.0,...,262.0,258.0,259.0,258.0,255.0,253.0,256.0,259.0,259.0,0
0,254.0,254.0,252.0,252.0,255.0,252.0,254.0,256.0,256.0,259.0,...,256.0,255.0,257.0,253.0,253.0,252.0,255.0,259.0,253.0,0
0,259.0,257.0,256.0,255.0,253.0,251.0,252.0,253.0,255.0,253.0,...,255.0,256.0,256.0,251.0,252.0,250.0,252.0,253.0,255.0,0

# SA19

In [230]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA19_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA19')
    SA19_A_paths.append(path)

SA19_A_paths

['../Dataset/SA19/D01_SA19_R01.csv',
 '../Dataset/SA19/D02_SA19_R01.csv',
 '../Dataset/SA19/D03_SA19_R01.csv',
 '../Dataset/SA19/D04_SA19_R01.csv',
 '../Dataset/SA19/D05_SA19_R01_1.csv',
 '../Dataset/SA19/D05_SA19_R01_2.csv',
 '../Dataset/SA19/D05_SA19_R02_1.csv',
 '../Dataset/SA19/D05_SA19_R02_2.csv',
 '../Dataset/SA19/D05_SA19_R03_1.csv',
 '../Dataset/SA19/D05_SA19_R03_2.csv',
 '../Dataset/SA19/D05_SA19_R04_1.csv',
 '../Dataset/SA19/D05_SA19_R04_2.csv',
 '../Dataset/SA19/D05_SA19_R05_1.csv',
 '../Dataset/SA19/D05_SA19_R05_2.csv',
 '../Dataset/SA19/D06_SA19_R01_1.csv',
 '../Dataset/SA19/D06_SA19_R01_2.csv',
 '../Dataset/SA19/D06_SA19_R02_1.csv',
 '../Dataset/SA19/D06_SA19_R02_2.csv',
 '../Dataset/SA19/D06_SA19_R03_1.csv',
 '../Dataset/SA19/D06_SA19_R03_2.csv',
 '../Dataset/SA19/D06_SA19_R04_1.csv',
 '../Dataset/SA19/D06_SA19_R04_2.csv',
 '../Dataset/SA19/D06_SA19_R05_1.csv',
 '../Dataset/SA19/D06_SA19_R05_2.csv',
 '../Dataset/SA19/D07_SA19_R01.csv',
 '../Dataset/SA19/D07_SA19_R02.csv',
 '../Dataset/SA19/D07_SA19_R03.csv',
 '../Dataset/SA19/D07_SA19_R04.csv',
 '../Dataset/SA19/D07_SA19_R05.csv',
 '../Dataset/SA19/D08_SA19_R01.csv',
 '../Dataset/SA19/D08_SA19_R02.csv',
 '../Dataset/SA19/D08_SA19_R03.csv',
 '../Dataset/SA19/D08_SA19_R04.csv',
 '../Dataset/SA19/D08_SA19_R05.csv',
 '../Dataset/SA19/D09_SA19_R01.csv',
 '../Dataset/SA19/D09_SA19_R02.csv',
 '../Dataset/SA19/D09_SA19_R03.csv',
 '../Dataset/SA19/D09_SA19_R04.csv',
 '../Dataset/SA19/D09_SA19_R05.csv',
 '../Dataset/SA19/D10_SA19_R01.csv',
 '../Dataset/SA19/D10_SA19_R02.csv',
 '../Dataset/SA19/D10_SA19_R03.csv',
 '../Dataset/SA19/D10_SA19_R04.csv',
 '../Dataset/SA19/D10_SA19_R05.csv',
 '../Dataset/SA19/D11_SA19_R01.csv',
 '../Dataset/SA19/D11_SA19_R02.csv',
 '../Dataset/SA19/D11_SA19_R03.csv',
 '../Dataset/SA19/D11_SA19_R04.csv',
 '../Dataset/SA19/D11_SA19_R05.csv',
 '../Dataset/SA19/D12_SA19_R01.csv',
 '../Dataset/SA19/D12_SA19_R02.csv',
 '../Dataset/SA19/D12_SA19_R03.csv',
 '../Dataset/SA19/D12_SA19_R04.csv',
 '../Dataset/SA19/D12_SA19_R05.csv',
 '../Dataset/SA19/D13_SA19_R01.csv',
 '../Dataset/SA19/D13_SA19_R02.csv',
 '../Dataset/SA19/D13_SA19_R03.csv',
 '../Dataset/SA19/D13_SA19_R04.csv',
 '../Dataset/SA19/D13_SA19_R05.csv',
 '../Dataset/SA19/D14_SA19_R01.csv',
 '../Dataset/SA19/D14_SA19_R02.csv',
 '../Dataset/SA19/D14_SA19_R03.csv',
 '../Dataset/SA19/D14_SA19_R04.csv',
 '../Dataset/SA19/D14_SA19_R05.csv',
 '../Dataset/SA19/D15_SA19_R01.csv',
 '../Dataset/SA19/D15_SA19_R02.csv',
 '../Dataset/SA19/D15_SA19_R03.csv',
 '../Dataset/SA19/D15_SA19_R04.csv',
 '../Dataset/SA19/D15_SA19_R05.csv',
 '../Dataset/SA19/D16_SA19_R01.csv',
 '../Dataset/SA19/D16_SA19_R02.csv',
 '../Dataset/SA19/D16_SA19_R03.csv',
 '../Dataset/SA19/D16_SA19_R04.csv',
 '../Dataset/SA19/D16_SA19_R05.csv',
 '../Dataset/SA19/D17_SA19_R01_1.csv',
 '../Dataset/SA19/D17_SA19_R01_2.csv',
 '../Dataset/SA19/D17_SA19_R02_1.csv',
 '../Dataset/SA19/D17_SA19_R02_2.csv',
 '../Dataset/SA19/D17_SA19_R03_1.csv',
 '../Dataset/SA19/D17_SA19_R03_2.csv',
 '../Dataset/SA19/D17_SA19_R04_1.csv',
 '../Dataset/SA19/D17_SA19_R04_2.csv',
 '../Dataset/SA19/D17_SA19_R05_1.csv',
 '../Dataset/SA19/D17_SA19_R05_2.csv',
 '../Dataset/SA19/D18_SA19_R01.csv',
 '../Dataset/SA19/D18_SA19_R02.csv',
 '../Dataset/SA19/D18_SA19_R03.csv',
 '../Dataset/SA19/D18_SA19_R04.csv',
 '../Dataset/SA19/D18_SA19_R05.csv',
 '../Dataset/SA19/D19_SA19_R01.csv',
 '../Dataset/SA19/D19_SA19_R02.csv',
 '../Dataset/SA19/D19_SA19_R03.csv',
 '../Dataset/SA19/D19_SA19_R04.csv',
 '../Dataset/SA19/D19_SA19_R05.csv']

In [231]:
list = []
final_SA19_A = pd.DataFrame(list)

for path in SA19_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA19_A = final_SA19_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA19_A.shape
target_col = row * [0]
final_SA19_A.loc[:,'target'] = target_col

final_SA19_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,282.0,280.0,279.0,281.0,281.0,274.0,282.0,280.0,283.0,284.0,...,300.0,296.0,293.0,291.0,286.0,285.0,279.0,284.0,280.0,0
0,255.0,258.0,254.0,253.0,253.0,255.0,253.0,256.0,253.0,256.0,...,260.0,260.0,262.0,264.0,263.0,264.0,264.0,262.0,260.0,0
0,248.0,252.0,252.0,253.0,254.0,257.0,259.0,256.0,260.0,262.0,...,137.0,88.0,58.0,39.0,31.0,26.0,35.0,47.0,60.0,0
0,247.0,246.0,245.0,239.0,232.0,229.0,229.0,226.0,222.0,223.0,...,60.0,36.0,42.0,61.0,86.0,99.0,166.0,136.0,171.0,0
0,257.0,259.0,260.0,262.0,260.0,255.0,259.0,259.0,257.0,255.0,...,258.0,260.0,263.0,264.0,263.0,265.0,266.0,265.0,266.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,256.0,262.0,259.0,256.0,254.0,255.0,256.0,258.0,256.0,259.0,...,259.0,252.0,253.0,257.0,256.0,260.0,259.0,258.0,256.0,0
0,260.0,258.0,257.0,257.0,257.0,257.0,257.0,259.0,258.0,254.0,...,260.0,258.0,255.0,256.0,256.0,256.0,258.0,260.0,257.0,0
0,259.0,260.0,262.0,259.0,258.0,259.0,259.0,260.0,261.0,255.0,...,263.0,257.0,258.0,260.0,258.0,258.0,261.0,260.0,259.0,0
0,256.0,258.0,253.0,256.0,255.0,256.0,252.0,253.0,253.0,254.0,...,258.0,260.0,259.0,260.0,263.0,263.0,261.0,261.0,260.0,0
0,262.0,260.0,257.0,259.0,258.0,260.0,257.0,255.0,258.0,257.0,...,254.0,259.0,257.0,254.0,255.0,255.0,256.0,257.0,256.0,0

# SA20

In [232]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA20_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA20')
    SA20_A_paths.append(path)

SA20_A_paths

['../Dataset/SA20/D01_SA20_R01.csv',
 '../Dataset/SA20/D02_SA20_R01.csv',
 '../Dataset/SA20/D03_SA20_R01.csv',
 '../Dataset/SA20/D04_SA20_R01.csv',
 '../Dataset/SA20/D05_SA20_R01_1.csv',
 '../Dataset/SA20/D05_SA20_R01_2.csv',
 '../Dataset/SA20/D05_SA20_R02_1.csv',
 '../Dataset/SA20/D05_SA20_R02_2.csv',
 '../Dataset/SA20/D05_SA20_R03_1.csv',
 '../Dataset/SA20/D05_SA20_R03_2.csv',
 '../Dataset/SA20/D05_SA20_R04_1.csv',
 '../Dataset/SA20/D05_SA20_R04_2.csv',
 '../Dataset/SA20/D05_SA20_R05_1.csv',
 '../Dataset/SA20/D05_SA20_R05_2.csv',
 '../Dataset/SA20/D06_SA20_R01_1.csv',
 '../Dataset/SA20/D06_SA20_R01_2.csv',
 '../Dataset/SA20/D06_SA20_R02_1.csv',
 '../Dataset/SA20/D06_SA20_R02_2.csv',
 '../Dataset/SA20/D06_SA20_R03_1.csv',
 '../Dataset/SA20/D06_SA20_R03_2.csv',
 '../Dataset/SA20/D06_SA20_R04_1.csv',
 '../Dataset/SA20/D06_SA20_R04_2.csv',
 '../Dataset/SA20/D06_SA20_R05_1.csv',
 '../Dataset/SA20/D06_SA20_R05_2.csv',
 '../Dataset/SA20/D07_SA20_R01.csv',
 '../Dataset/SA20/D07_SA20_R02.csv',
 '../Dataset/SA20/D07_SA20_R03.csv',
 '../Dataset/SA20/D07_SA20_R04.csv',
 '../Dataset/SA20/D07_SA20_R05.csv',
 '../Dataset/SA20/D08_SA20_R01.csv',
 '../Dataset/SA20/D08_SA20_R02.csv',
 '../Dataset/SA20/D08_SA20_R03.csv',
 '../Dataset/SA20/D08_SA20_R04.csv',
 '../Dataset/SA20/D08_SA20_R05.csv',
 '../Dataset/SA20/D09_SA20_R01.csv',
 '../Dataset/SA20/D09_SA20_R02.csv',
 '../Dataset/SA20/D09_SA20_R03.csv',
 '../Dataset/SA20/D09_SA20_R04.csv',
 '../Dataset/SA20/D09_SA20_R05.csv',
 '../Dataset/SA20/D10_SA20_R01.csv',
 '../Dataset/SA20/D10_SA20_R02.csv',
 '../Dataset/SA20/D10_SA20_R03.csv',
 '../Dataset/SA20/D10_SA20_R04.csv',
 '../Dataset/SA20/D10_SA20_R05.csv',
 '../Dataset/SA20/D11_SA20_R01.csv',
 '../Dataset/SA20/D11_SA20_R02.csv',
 '../Dataset/SA20/D11_SA20_R03.csv',
 '../Dataset/SA20/D11_SA20_R04.csv',
 '../Dataset/SA20/D11_SA20_R05.csv',
 '../Dataset/SA20/D12_SA20_R01.csv',
 '../Dataset/SA20/D12_SA20_R02.csv',
 '../Dataset/SA20/D12_SA20_R03.csv',
 '../Dataset/SA20/D12_SA20_R04.csv',
 '../Dataset/SA20/D12_SA20_R05.csv',
 '../Dataset/SA20/D13_SA20_R01.csv',
 '../Dataset/SA20/D13_SA20_R02.csv',
 '../Dataset/SA20/D13_SA20_R03.csv',
 '../Dataset/SA20/D13_SA20_R04.csv',
 '../Dataset/SA20/D13_SA20_R05.csv',
 '../Dataset/SA20/D14_SA20_R01.csv',
 '../Dataset/SA20/D14_SA20_R02.csv',
 '../Dataset/SA20/D14_SA20_R03.csv',
 '../Dataset/SA20/D14_SA20_R04.csv',
 '../Dataset/SA20/D14_SA20_R05.csv',
 '../Dataset/SA20/D15_SA20_R01.csv',
 '../Dataset/SA20/D15_SA20_R02.csv',
 '../Dataset/SA20/D15_SA20_R03.csv',
 '../Dataset/SA20/D15_SA20_R04.csv',
 '../Dataset/SA20/D15_SA20_R05.csv',
 '../Dataset/SA20/D16_SA20_R01.csv',
 '../Dataset/SA20/D16_SA20_R02.csv',
 '../Dataset/SA20/D16_SA20_R03.csv',
 '../Dataset/SA20/D16_SA20_R04.csv',
 '../Dataset/SA20/D16_SA20_R05.csv',
 '../Dataset/SA20/D17_SA20_R01_1.csv',
 '../Dataset/SA20/D17_SA20_R01_2.csv',
 '../Dataset/SA20/D17_SA20_R02_1.csv',
 '../Dataset/SA20/D17_SA20_R02_2.csv',
 '../Dataset/SA20/D17_SA20_R03_1.csv',
 '../Dataset/SA20/D17_SA20_R03_2.csv',
 '../Dataset/SA20/D17_SA20_R04_1.csv',
 '../Dataset/SA20/D17_SA20_R04_2.csv',
 '../Dataset/SA20/D17_SA20_R05_1.csv',
 '../Dataset/SA20/D17_SA20_R05_2.csv',
 '../Dataset/SA20/D18_SA20_R01.csv',
 '../Dataset/SA20/D18_SA20_R02.csv',
 '../Dataset/SA20/D18_SA20_R03.csv',
 '../Dataset/SA20/D18_SA20_R04.csv',
 '../Dataset/SA20/D18_SA20_R05.csv',
 '../Dataset/SA20/D19_SA20_R01.csv',
 '../Dataset/SA20/D19_SA20_R02.csv',
 '../Dataset/SA20/D19_SA20_R03.csv',
 '../Dataset/SA20/D19_SA20_R04.csv',
 '../Dataset/SA20/D19_SA20_R05.csv']

In [233]:
list = []
final_SA20_A = pd.DataFrame(list)

for path in SA20_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA20_A = final_SA20_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA20_A.shape
target_col = row * [0]
final_SA20_A.loc[:,'target'] = target_col

final_SA20_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,258.0,266.0,270.0,276.0,280.0,283.0,289.0,284.0,270.0,278.0,...,204.0,203.0,200.0,197.0,197.0,201.0,202.0,205.0,207.0,0
0,186.0,182.0,183.0,190.0,201.0,201.0,217.0,235.0,247.0,259.0,...,209.0,222.0,236.0,249.0,259.0,265.0,274.0,267.0,271.0,0
0,268.0,269.0,265.0,268.0,268.0,268.0,272.0,272.0,272.0,277.0,...,463.0,455.0,435.0,423.0,395.0,378.0,355.0,332.0,316.0,0
0,787.0,691.0,587.0,483.0,443.0,443.0,460.0,472.0,482.0,493.0,...,584.0,528.0,460.0,386.0,306.0,252.0,230.0,231.0,240.0,0
0,257.0,256.0,252.0,258.0,253.0,253.0,254.0,255.0,253.0,254.0,...,254.0,257.0,255.0,256.0,257.0,258.0,256.0,257.0,254.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,253.0,251.0,252.0,250.0,250.0,245.0,251.0,254.0,254.0,248.0,...,251.0,251.0,251.0,252.0,255.0,255.0,256.0,253.0,253.0,0
0,257.0,257.0,255.0,260.0,257.0,257.0,257.0,256.0,253.0,259.0,...,254.0,256.0,258.0,253.0,257.0,255.0,254.0,258.0,257.0,0
0,256.0,252.0,254.0,254.0,252.0,254.0,252.0,253.0,253.0,257.0,...,256.0,254.0,256.0,254.0,255.0,254.0,252.0,254.0,252.0,0
0,253.0,256.0,257.0,259.0,254.0,257.0,257.0,257.0,258.0,260.0,...,257.0,255.0,251.0,256.0,255.0,256.0,257.0,257.0,256.0,0
0,256.0,258.0,258.0,256.0,258.0,255.0,257.0,255.0,258.0,257.0,...,255.0,258.0,255.0,256.0,257.0,256.0,255.0,254.0,258.0,0

# SA21

In [234]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA21_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA21')
    SA21_A_paths.append(path)

SA21_A_paths

['../Dataset/SA21/D01_SA21_R01.csv',
 '../Dataset/SA21/D02_SA21_R01.csv',
 '../Dataset/SA21/D03_SA21_R01.csv',
 '../Dataset/SA21/D04_SA21_R01.csv',
 '../Dataset/SA21/D05_SA21_R01_1.csv',
 '../Dataset/SA21/D05_SA21_R01_2.csv',
 '../Dataset/SA21/D05_SA21_R02_1.csv',
 '../Dataset/SA21/D05_SA21_R02_2.csv',
 '../Dataset/SA21/D05_SA21_R03_1.csv',
 '../Dataset/SA21/D05_SA21_R03_2.csv',
 '../Dataset/SA21/D05_SA21_R04_1.csv',
 '../Dataset/SA21/D05_SA21_R04_2.csv',
 '../Dataset/SA21/D05_SA21_R05_1.csv',
 '../Dataset/SA21/D05_SA21_R05_2.csv',
 '../Dataset/SA21/D06_SA21_R01_1.csv',
 '../Dataset/SA21/D06_SA21_R01_2.csv',
 '../Dataset/SA21/D06_SA21_R02_1.csv',
 '../Dataset/SA21/D06_SA21_R02_2.csv',
 '../Dataset/SA21/D06_SA21_R03_1.csv',
 '../Dataset/SA21/D06_SA21_R03_2.csv',
 '../Dataset/SA21/D06_SA21_R04_1.csv',
 '../Dataset/SA21/D06_SA21_R04_2.csv',
 '../Dataset/SA21/D06_SA21_R05_1.csv',
 '../Dataset/SA21/D06_SA21_R05_2.csv',
 '../Dataset/SA21/D07_SA21_R01.csv',
 '../Dataset/SA21/D07_SA21_R02.csv',
 '../Dataset/SA21/D07_SA21_R03.csv',
 '../Dataset/SA21/D07_SA21_R04.csv',
 '../Dataset/SA21/D07_SA21_R05.csv',
 '../Dataset/SA21/D08_SA21_R01.csv',
 '../Dataset/SA21/D08_SA21_R02.csv',
 '../Dataset/SA21/D08_SA21_R03.csv',
 '../Dataset/SA21/D08_SA21_R04.csv',
 '../Dataset/SA21/D08_SA21_R05.csv',
 '../Dataset/SA21/D09_SA21_R01.csv',
 '../Dataset/SA21/D09_SA21_R02.csv',
 '../Dataset/SA21/D09_SA21_R03.csv',
 '../Dataset/SA21/D09_SA21_R04.csv',
 '../Dataset/SA21/D09_SA21_R05.csv',
 '../Dataset/SA21/D10_SA21_R01.csv',
 '../Dataset/SA21/D10_SA21_R02.csv',
 '../Dataset/SA21/D10_SA21_R03.csv',
 '../Dataset/SA21/D10_SA21_R04.csv',
 '../Dataset/SA21/D10_SA21_R05.csv',
 '../Dataset/SA21/D11_SA21_R01.csv',
 '../Dataset/SA21/D11_SA21_R02.csv',
 '../Dataset/SA21/D11_SA21_R03.csv',
 '../Dataset/SA21/D11_SA21_R04.csv',
 '../Dataset/SA21/D11_SA21_R05.csv',
 '../Dataset/SA21/D12_SA21_R01.csv',
 '../Dataset/SA21/D12_SA21_R02.csv',
 '../Dataset/SA21/D12_SA21_R03.csv',
 '../Dataset/SA21/D12_SA21_R04.csv',
 '../Dataset/SA21/D12_SA21_R05.csv',
 '../Dataset/SA21/D13_SA21_R01.csv',
 '../Dataset/SA21/D13_SA21_R02.csv',
 '../Dataset/SA21/D13_SA21_R03.csv',
 '../Dataset/SA21/D13_SA21_R04.csv',
 '../Dataset/SA21/D13_SA21_R05.csv',
 '../Dataset/SA21/D14_SA21_R01.csv',
 '../Dataset/SA21/D14_SA21_R02.csv',
 '../Dataset/SA21/D14_SA21_R03.csv',
 '../Dataset/SA21/D14_SA21_R04.csv',
 '../Dataset/SA21/D14_SA21_R05.csv',
 '../Dataset/SA21/D15_SA21_R01.csv',
 '../Dataset/SA21/D15_SA21_R02.csv',
 '../Dataset/SA21/D15_SA21_R03.csv',
 '../Dataset/SA21/D15_SA21_R04.csv',
 '../Dataset/SA21/D15_SA21_R05.csv',
 '../Dataset/SA21/D16_SA21_R01.csv',
 '../Dataset/SA21/D16_SA21_R02.csv',
 '../Dataset/SA21/D16_SA21_R03.csv',
 '../Dataset/SA21/D16_SA21_R04.csv',
 '../Dataset/SA21/D16_SA21_R05.csv',
 '../Dataset/SA21/D17_SA21_R01_1.csv',
 '../Dataset/SA21/D17_SA21_R01_2.csv',
 '../Dataset/SA21/D17_SA21_R02_1.csv',
 '../Dataset/SA21/D17_SA21_R02_2.csv',
 '../Dataset/SA21/D17_SA21_R03_1.csv',
 '../Dataset/SA21/D17_SA21_R03_2.csv',
 '../Dataset/SA21/D17_SA21_R04_1.csv',
 '../Dataset/SA21/D17_SA21_R04_2.csv',
 '../Dataset/SA21/D17_SA21_R05_1.csv',
 '../Dataset/SA21/D17_SA21_R05_2.csv',
 '../Dataset/SA21/D18_SA21_R01.csv',
 '../Dataset/SA21/D18_SA21_R02.csv',
 '../Dataset/SA21/D18_SA21_R03.csv',
 '../Dataset/SA21/D18_SA21_R04.csv',
 '../Dataset/SA21/D18_SA21_R05.csv',
 '../Dataset/SA21/D19_SA21_R01.csv',
 '../Dataset/SA21/D19_SA21_R02.csv',
 '../Dataset/SA21/D19_SA21_R03.csv',
 '../Dataset/SA21/D19_SA21_R04.csv',
 '../Dataset/SA21/D19_SA21_R05.csv']

In [235]:
list = []
final_SA21_A = pd.DataFrame(list)

for path in SA21_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA21_A = final_SA21_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA21_A.shape
target_col = row * [0]
final_SA21_A.loc[:,'target'] = target_col

final_SA21_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,263.0,258.0,260.0,259.0,256.0,256.0,252.0,273.0,260.0,259.0,...,295.0,299.0,309.0,312.0,311.0,310.0,302.0,291.0,285.0,0
0,230.0,235.0,237.0,240.0,236.0,240.0,242.0,239.0,236.0,234.0,...,238.0,241.0,244.0,250.0,254.0,259.0,265.0,265.0,273.0,0
0,261.0,258.0,260.0,259.0,255.0,256.0,257.0,256.0,257.0,259.0,...,270.0,268.0,267.0,264.0,257.0,256.0,251.0,252.0,255.0,0
0,261.0,262.0,261.0,260.0,262.0,268.0,262.0,260.0,262.0,260.0,...,284.0,280.0,276.0,269.0,274.0,280.0,285.0,292.0,294.0,0
0,252.0,250.0,248.0,248.0,250.0,248.0,248.0,244.0,251.0,251.0,...,200.0,205.0,202.0,207.0,208.0,208.0,214.0,212.0,217.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,259.0,256.0,258.0,259.0,259.0,257.0,258.0,261.0,261.0,261.0,...,261.0,261.0,257.0,258.0,260.0,258.0,258.0,262.0,262.0,0
0,255.0,258.0,258.0,259.0,259.0,257.0,260.0,261.0,260.0,260.0,...,243.0,267.0,269.0,263.0,259.0,268.0,260.0,262.0,258.0,0
0,255.0,255.0,255.0,254.0,254.0,259.0,256.0,258.0,261.0,261.0,...,262.0,262.0,258.0,257.0,255.0,257.0,257.0,257.0,256.0,0
0,255.0,256.0,255.0,257.0,259.0,259.0,244.0,258.0,252.0,261.0,...,260.0,259.0,257.0,259.0,260.0,260.0,258.0,261.0,260.0,0
0,259.0,258.0,260.0,260.0,260.0,257.0,255.0,258.0,258.0,259.0,...,259.0,261.0,256.0,258.0,259.0,257.0,259.0,258.0,261.0,0

# SA22

In [236]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA22_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA22')
    SA22_A_paths.append(path)

SA22_A_paths

['../Dataset/SA22/D01_SA22_R01.csv',
 '../Dataset/SA22/D02_SA22_R01.csv',
 '../Dataset/SA22/D03_SA22_R01.csv',
 '../Dataset/SA22/D04_SA22_R01.csv',
 '../Dataset/SA22/D05_SA22_R01_1.csv',
 '../Dataset/SA22/D05_SA22_R01_2.csv',
 '../Dataset/SA22/D05_SA22_R02_1.csv',
 '../Dataset/SA22/D05_SA22_R02_2.csv',
 '../Dataset/SA22/D05_SA22_R03_1.csv',
 '../Dataset/SA22/D05_SA22_R03_2.csv',
 '../Dataset/SA22/D05_SA22_R04_1.csv',
 '../Dataset/SA22/D05_SA22_R04_2.csv',
 '../Dataset/SA22/D05_SA22_R05_1.csv',
 '../Dataset/SA22/D05_SA22_R05_2.csv',
 '../Dataset/SA22/D06_SA22_R01_1.csv',
 '../Dataset/SA22/D06_SA22_R01_2.csv',
 '../Dataset/SA22/D06_SA22_R02_1.csv',
 '../Dataset/SA22/D06_SA22_R02_2.csv',
 '../Dataset/SA22/D06_SA22_R03_1.csv',
 '../Dataset/SA22/D06_SA22_R03_2.csv',
 '../Dataset/SA22/D06_SA22_R04_1.csv',
 '../Dataset/SA22/D06_SA22_R04_2.csv',
 '../Dataset/SA22/D06_SA22_R05_1.csv',
 '../Dataset/SA22/D06_SA22_R05_2.csv',
 '../Dataset/SA22/D07_SA22_R01.csv',
 '../Dataset/SA22/D07_SA22_R02.csv',
 '../Dataset/SA22/D07_SA22_R03.csv',
 '../Dataset/SA22/D07_SA22_R04.csv',
 '../Dataset/SA22/D07_SA22_R05.csv',
 '../Dataset/SA22/D08_SA22_R01.csv',
 '../Dataset/SA22/D08_SA22_R02.csv',
 '../Dataset/SA22/D08_SA22_R03.csv',
 '../Dataset/SA22/D08_SA22_R04.csv',
 '../Dataset/SA22/D08_SA22_R05.csv',
 '../Dataset/SA22/D09_SA22_R01.csv',
 '../Dataset/SA22/D09_SA22_R02.csv',
 '../Dataset/SA22/D09_SA22_R03.csv',
 '../Dataset/SA22/D09_SA22_R04.csv',
 '../Dataset/SA22/D09_SA22_R05.csv',
 '../Dataset/SA22/D10_SA22_R01.csv',
 '../Dataset/SA22/D10_SA22_R02.csv',
 '../Dataset/SA22/D10_SA22_R03.csv',
 '../Dataset/SA22/D10_SA22_R04.csv',
 '../Dataset/SA22/D10_SA22_R05.csv',
 '../Dataset/SA22/D11_SA22_R01.csv',
 '../Dataset/SA22/D11_SA22_R02.csv',
 '../Dataset/SA22/D11_SA22_R03.csv',
 '../Dataset/SA22/D11_SA22_R04.csv',
 '../Dataset/SA22/D11_SA22_R05.csv',
 '../Dataset/SA22/D12_SA22_R01.csv',
 '../Dataset/SA22/D12_SA22_R02.csv',
 '../Dataset/SA22/D12_SA22_R03.csv',
 '../Dataset/SA22/D12_SA22_R04.csv',
 '../Dataset/SA22/D12_SA22_R05.csv',
 '../Dataset/SA22/D13_SA22_R01.csv',
 '../Dataset/SA22/D13_SA22_R02.csv',
 '../Dataset/SA22/D13_SA22_R03.csv',
 '../Dataset/SA22/D13_SA22_R04.csv',
 '../Dataset/SA22/D13_SA22_R05.csv',
 '../Dataset/SA22/D14_SA22_R01.csv',
 '../Dataset/SA22/D14_SA22_R02.csv',
 '../Dataset/SA22/D14_SA22_R03.csv',
 '../Dataset/SA22/D14_SA22_R04.csv',
 '../Dataset/SA22/D14_SA22_R05.csv',
 '../Dataset/SA22/D15_SA22_R01.csv',
 '../Dataset/SA22/D15_SA22_R02.csv',
 '../Dataset/SA22/D15_SA22_R03.csv',
 '../Dataset/SA22/D15_SA22_R04.csv',
 '../Dataset/SA22/D15_SA22_R05.csv',
 '../Dataset/SA22/D16_SA22_R01.csv',
 '../Dataset/SA22/D16_SA22_R02.csv',
 '../Dataset/SA22/D16_SA22_R03.csv',
 '../Dataset/SA22/D16_SA22_R04.csv',
 '../Dataset/SA22/D16_SA22_R05.csv',
 '../Dataset/SA22/D17_SA22_R01_1.csv',
 '../Dataset/SA22/D17_SA22_R01_2.csv',
 '../Dataset/SA22/D17_SA22_R02_1.csv',
 '../Dataset/SA22/D17_SA22_R02_2.csv',
 '../Dataset/SA22/D17_SA22_R03_1.csv',
 '../Dataset/SA22/D17_SA22_R03_2.csv',
 '../Dataset/SA22/D17_SA22_R04_1.csv',
 '../Dataset/SA22/D17_SA22_R04_2.csv',
 '../Dataset/SA22/D17_SA22_R05_1.csv',
 '../Dataset/SA22/D17_SA22_R05_2.csv',
 '../Dataset/SA22/D18_SA22_R01.csv',
 '../Dataset/SA22/D18_SA22_R02.csv',
 '../Dataset/SA22/D18_SA22_R03.csv',
 '../Dataset/SA22/D18_SA22_R04.csv',
 '../Dataset/SA22/D18_SA22_R05.csv',
 '../Dataset/SA22/D19_SA22_R01.csv',
 '../Dataset/SA22/D19_SA22_R02.csv',
 '../Dataset/SA22/D19_SA22_R03.csv',
 '../Dataset/SA22/D19_SA22_R04.csv',
 '../Dataset/SA22/D19_SA22_R05.csv']

In [237]:
list = []
final_SA22_A = pd.DataFrame(list)

for path in SA22_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA22_A = final_SA22_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA22_A.shape
target_col = row * [0]
final_SA22_A.loc[:,'target'] = target_col

final_SA22_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,221.0,215.0,214.0,212.0,211.0,205.0,224.0,217.0,217.0,225.0,...,380.0,383.0,389.0,386.0,390.0,387.0,388.0,384.0,383.0,0
0,295.0,288.0,293.0,305.0,329.0,369.0,428.0,471.0,513.0,542.0,...,271.0,248.0,224.0,200.0,177.0,163.0,142.0,121.0,103.0,0
0,257.0,256.0,256.0,257.0,256.0,257.0,257.0,256.0,258.0,256.0,...,217.0,213.0,208.0,207.0,208.0,210.0,211.0,216.0,222.0,0
0,248.0,248.0,248.0,248.0,244.0,258.0,241.0,241.0,242.0,240.0,...,282.0,286.0,294.0,305.0,313.0,322.0,329.0,335.0,340.0,0
0,330.0,339.0,354.0,362.0,378.0,394.0,410.0,425.0,436.0,444.0,...,227.0,210.0,196.0,185.0,184.0,179.0,178.0,183.0,184.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,258.0,260.0,260.0,260.0,259.0,256.0,257.0,259.0,256.0,260.0,...,255.0,256.0,255.0,259.0,258.0,254.0,254.0,257.0,255.0,0
0,256.0,256.0,258.0,259.0,257.0,260.0,258.0,257.0,261.0,260.0,...,256.0,258.0,257.0,259.0,259.0,256.0,255.0,258.0,257.0,0
0,255.0,257.0,259.0,259.0,257.0,256.0,259.0,255.0,254.0,258.0,...,257.0,261.0,261.0,259.0,257.0,261.0,259.0,258.0,259.0,0
0,259.0,257.0,257.0,259.0,258.0,255.0,259.0,258.0,256.0,256.0,...,254.0,256.0,254.0,256.0,257.0,257.0,258.0,254.0,253.0,0
0,259.0,257.0,258.0,260.0,260.0,258.0,258.0,258.0,259.0,260.0,...,256.0,260.0,259.0,259.0,259.0,259.0,261.0,258.0,259.0,0

# SA 23

In [238]:
paths = []

for i in range(1, 20):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SA23_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SA23')
    SA23_A_paths.append(path)

SA23_A_paths

['../Dataset/SA23/D01_SA23_R01.csv',
 '../Dataset/SA23/D02_SA23_R01.csv',
 '../Dataset/SA23/D03_SA23_R01.csv',
 '../Dataset/SA23/D04_SA23_R01.csv',
 '../Dataset/SA23/D05_SA23_R01_1.csv',
 '../Dataset/SA23/D05_SA23_R01_2.csv',
 '../Dataset/SA23/D05_SA23_R02_1.csv',
 '../Dataset/SA23/D05_SA23_R02_2.csv',
 '../Dataset/SA23/D05_SA23_R03_1.csv',
 '../Dataset/SA23/D05_SA23_R03_2.csv',
 '../Dataset/SA23/D05_SA23_R04_1.csv',
 '../Dataset/SA23/D05_SA23_R04_2.csv',
 '../Dataset/SA23/D05_SA23_R05_1.csv',
 '../Dataset/SA23/D05_SA23_R05_2.csv',
 '../Dataset/SA23/D06_SA23_R01_1.csv',
 '../Dataset/SA23/D06_SA23_R01_2.csv',
 '../Dataset/SA23/D06_SA23_R02_1.csv',
 '../Dataset/SA23/D06_SA23_R02_2.csv',
 '../Dataset/SA23/D06_SA23_R03_1.csv',
 '../Dataset/SA23/D06_SA23_R03_2.csv',
 '../Dataset/SA23/D06_SA23_R04_1.csv',
 '../Dataset/SA23/D06_SA23_R04_2.csv',
 '../Dataset/SA23/D06_SA23_R05_1.csv',
 '../Dataset/SA23/D06_SA23_R05_2.csv',
 '../Dataset/SA23/D07_SA23_R01.csv',
 '../Dataset/SA23/D07_SA23_R02.csv',
 '../Dataset/SA23/D07_SA23_R03.csv',
 '../Dataset/SA23/D07_SA23_R04.csv',
 '../Dataset/SA23/D07_SA23_R05.csv',
 '../Dataset/SA23/D08_SA23_R01.csv',
 '../Dataset/SA23/D08_SA23_R02.csv',
 '../Dataset/SA23/D08_SA23_R03.csv',
 '../Dataset/SA23/D08_SA23_R04.csv',
 '../Dataset/SA23/D08_SA23_R05.csv',
 '../Dataset/SA23/D09_SA23_R01.csv',
 '../Dataset/SA23/D09_SA23_R02.csv',
 '../Dataset/SA23/D09_SA23_R03.csv',
 '../Dataset/SA23/D09_SA23_R04.csv',
 '../Dataset/SA23/D09_SA23_R05.csv',
 '../Dataset/SA23/D10_SA23_R01.csv',
 '../Dataset/SA23/D10_SA23_R02.csv',
 '../Dataset/SA23/D10_SA23_R03.csv',
 '../Dataset/SA23/D10_SA23_R04.csv',
 '../Dataset/SA23/D10_SA23_R05.csv',
 '../Dataset/SA23/D11_SA23_R01.csv',
 '../Dataset/SA23/D11_SA23_R02.csv',
 '../Dataset/SA23/D11_SA23_R03.csv',
 '../Dataset/SA23/D11_SA23_R04.csv',
 '../Dataset/SA23/D11_SA23_R05.csv',
 '../Dataset/SA23/D12_SA23_R01.csv',
 '../Dataset/SA23/D12_SA23_R02.csv',
 '../Dataset/SA23/D12_SA23_R03.csv',
 '../Dataset/SA23/D12_SA23_R04.csv',
 '../Dataset/SA23/D12_SA23_R05.csv',
 '../Dataset/SA23/D13_SA23_R01.csv',
 '../Dataset/SA23/D13_SA23_R02.csv',
 '../Dataset/SA23/D13_SA23_R03.csv',
 '../Dataset/SA23/D13_SA23_R04.csv',
 '../Dataset/SA23/D13_SA23_R05.csv',
 '../Dataset/SA23/D14_SA23_R01.csv',
 '../Dataset/SA23/D14_SA23_R02.csv',
 '../Dataset/SA23/D14_SA23_R03.csv',
 '../Dataset/SA23/D14_SA23_R04.csv',
 '../Dataset/SA23/D14_SA23_R05.csv',
 '../Dataset/SA23/D15_SA23_R01.csv',
 '../Dataset/SA23/D15_SA23_R02.csv',
 '../Dataset/SA23/D15_SA23_R03.csv',
 '../Dataset/SA23/D15_SA23_R04.csv',
 '../Dataset/SA23/D15_SA23_R05.csv',
 '../Dataset/SA23/D16_SA23_R01.csv',
 '../Dataset/SA23/D16_SA23_R02.csv',
 '../Dataset/SA23/D16_SA23_R03.csv',
 '../Dataset/SA23/D16_SA23_R04.csv',
 '../Dataset/SA23/D16_SA23_R05.csv',
 '../Dataset/SA23/D17_SA23_R01_1.csv',
 '../Dataset/SA23/D17_SA23_R01_2.csv',
 '../Dataset/SA23/D17_SA23_R02_1.csv',
 '../Dataset/SA23/D17_SA23_R02_2.csv',
 '../Dataset/SA23/D17_SA23_R03_1.csv',
 '../Dataset/SA23/D17_SA23_R03_2.csv',
 '../Dataset/SA23/D17_SA23_R04_1.csv',
 '../Dataset/SA23/D17_SA23_R04_2.csv',
 '../Dataset/SA23/D17_SA23_R05_1.csv',
 '../Dataset/SA23/D17_SA23_R05_2.csv',
 '../Dataset/SA23/D18_SA23_R01.csv',
 '../Dataset/SA23/D18_SA23_R02.csv',
 '../Dataset/SA23/D18_SA23_R03.csv',
 '../Dataset/SA23/D18_SA23_R04.csv',
 '../Dataset/SA23/D18_SA23_R05.csv',
 '../Dataset/SA23/D19_SA23_R01.csv',
 '../Dataset/SA23/D19_SA23_R02.csv',
 '../Dataset/SA23/D19_SA23_R03.csv',
 '../Dataset/SA23/D19_SA23_R04.csv',
 '../Dataset/SA23/D19_SA23_R05.csv']

In [239]:
list = []
final_SA23_A = pd.DataFrame(list)

for path in SA23_A_paths:
    data = pd.read_csv(path, header=None)
    data = data.iloc[:, :3]
    rows, cols = data.shape

    sliced_df = data[0 : 160]
    
    col_1_r = sliced_df[0].to_numpy().astype(int)
    col_2_r = sliced_df[1].to_numpy().astype(int)
    col_3_r = sliced_df[2].to_numpy().astype(int)

    col_1 = col_1_r*col_1_r
    col_2 = col_2_r*col_2_r
    col_3 = col_3_r*col_3_r
    
    C_nine = np.sqrt(col_1 + col_2 + col_3)
    list_C_nine = pd.DataFrame(C_nine).transpose().round()
    final_SA23_A = final_SA23_A.append(list_C_nine)

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SA23_A.shape
target_col = row * [0]
final_SA23_A.loc[:,'target'] = target_col

final_SA23_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,342.0,330.0,317.0,304.0,287.0,268.0,250.0,245.0,220.0,215.0,...,445.0,423.0,384.0,339.0,297.0,255.0,212.0,179.0,149.0,0
0,291.0,274.0,255.0,237.0,221.0,208.0,195.0,192.0,195.0,206.0,...,390.0,374.0,356.0,329.0,302.0,273.0,243.0,212.0,189.0,0
0,293.0,275.0,260.0,244.0,227.0,217.0,204.0,192.0,185.0,182.0,...,552.0,530.0,500.0,469.0,436.0,408.0,381.0,366.0,353.0,0
0,235.0,239.0,236.0,237.0,239.0,240.0,240.0,241.0,239.0,239.0,...,447.0,449.0,462.0,480.0,506.0,533.0,561.0,579.0,594.0,0
0,249.0,248.0,253.0,253.0,256.0,256.0,254.0,253.0,252.0,249.0,...,262.0,255.0,254.0,254.0,254.0,252.0,253.0,252.0,257.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,262.0,261.0,265.0,262.0,262.0,264.0,264.0,265.0,266.0,270.0,...,256.0,257.0,259.0,256.0,257.0,256.0,256.0,256.0,258.0,0
0,255.0,255.0,257.0,252.0,254.0,245.0,256.0,256.0,257.0,257.0,...,256.0,257.0,256.0,255.0,259.0,259.0,258.0,259.0,256.0,0
0,254.0,257.0,258.0,257.0,260.0,254.0,255.0,256.0,256.0,255.0,...,253.0,256.0,255.0,257.0,255.0,259.0,255.0,258.0,256.0,0
0,258.0,254.0,255.0,258.0,256.0,262.0,256.0,256.0,256.0,255.0,...,258.0,256.0,254.0,255.0,254.0,256.0,254.0,258.0,258.0,0
0,257.0,255.0,259.0,260.0,257.0,257.0,258.0,256.0,255.0,259.0,...,256.0,255.0,254.0,259.0,255.0,258.0,256.0,254.0,257.0,0

# SE01

In [240]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE01_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE01')
    SE01_A_paths.append(path)

SE01_A_paths

['../Dataset/SE01/D01_SE01_R01.csv',
 '../Dataset/SE01/D02_SE01_R01.csv',
 '../Dataset/SE01/D03_SE01_R01.csv',
 '../Dataset/SE01/D04_SE01_R01.csv',
 '../Dataset/SE01/D05_SE01_R01_1.csv',
 '../Dataset/SE01/D05_SE01_R01_2.csv',
 '../Dataset/SE01/D05_SE01_R02_1.csv',
 '../Dataset/SE01/D05_SE01_R02_2.csv',
 '../Dataset/SE01/D05_SE01_R03_1.csv',
 '../Dataset/SE01/D05_SE01_R03_2.csv',
 '../Dataset/SE01/D05_SE01_R04_1.csv',
 '../Dataset/SE01/D05_SE01_R04_2.csv',
 '../Dataset/SE01/D05_SE01_R05_1.csv',
 '../Dataset/SE01/D05_SE01_R05_2.csv',
 '../Dataset/SE01/D06_SE01_R01_1.csv',
 '../Dataset/SE01/D06_SE01_R01_2.csv',
 '../Dataset/SE01/D06_SE01_R02_1.csv',
 '../Dataset/SE01/D06_SE01_R02_2.csv',
 '../Dataset/SE01/D06_SE01_R03_1.csv',
 '../Dataset/SE01/D06_SE01_R03_2.csv',
 '../Dataset/SE01/D06_SE01_R04_1.csv',
 '../Dataset/SE01/D06_SE01_R04_2.csv',
 '../Dataset/SE01/D06_SE01_R05_1.csv',
 '../Dataset/SE01/D06_SE01_R05_2.csv',
 '../Dataset/SE01/D07_SE01_R01.csv',
 '../Dataset/SE01/D07_SE01_R02.csv',
 '../Dataset/SE01/D07_SE01_R03.csv',
 '../Dataset/SE01/D07_SE01_R04.csv',
 '../Dataset/SE01/D07_SE01_R05.csv',
 '../Dataset/SE01/D08_SE01_R01.csv',
 '../Dataset/SE01/D08_SE01_R02.csv',
 '../Dataset/SE01/D08_SE01_R03.csv',
 '../Dataset/SE01/D08_SE01_R04.csv',
 '../Dataset/SE01/D08_SE01_R05.csv',
 '../Dataset/SE01/D09_SE01_R01.csv',
 '../Dataset/SE01/D09_SE01_R02.csv',
 '../Dataset/SE01/D09_SE01_R03.csv',
 '../Dataset/SE01/D09_SE01_R04.csv',
 '../Dataset/SE01/D09_SE01_R05.csv',
 '../Dataset/SE01/D10_SE01_R01.csv',
 '../Dataset/SE01/D10_SE01_R02.csv',
 '../Dataset/SE01/D10_SE01_R03.csv',
 '../Dataset/SE01/D10_SE01_R04.csv',
 '../Dataset/SE01/D10_SE01_R05.csv',
 '../Dataset/SE01/D11_SE01_R01.csv',
 '../Dataset/SE01/D11_SE01_R02.csv',
 '../Dataset/SE01/D11_SE01_R03.csv',
 '../Dataset/SE01/D11_SE01_R04.csv',
 '../Dataset/SE01/D11_SE01_R05.csv',
 '../Dataset/SE01/D12_SE01_R01.csv',
 '../Dataset/SE01/D12_SE01_R02.csv',
 '../Dataset/SE01/D12_SE01_R03.csv',
 '../Dataset/SE01/D12_SE01_R04.csv',
 '../Dataset/SE01/D12_SE01_R05.csv',
 '../Dataset/SE01/D13_SE01_R01.csv',
 '../Dataset/SE01/D13_SE01_R02.csv',
 '../Dataset/SE01/D13_SE01_R03.csv',
 '../Dataset/SE01/D13_SE01_R04.csv',
 '../Dataset/SE01/D13_SE01_R05.csv',
 '../Dataset/SE01/D14_SE01_R01.csv',
 '../Dataset/SE01/D14_SE01_R02.csv',
 '../Dataset/SE01/D14_SE01_R03.csv',
 '../Dataset/SE01/D14_SE01_R04.csv',
 '../Dataset/SE01/D14_SE01_R05.csv',
 '../Dataset/SE01/D17_SE01_R01_1.csv',
 '../Dataset/SE01/D17_SE01_R01_2.csv',
 '../Dataset/SE01/D17_SE01_R02_1.csv',
 '../Dataset/SE01/D17_SE01_R02_2.csv',
 '../Dataset/SE01/D17_SE01_R03_1.csv',
 '../Dataset/SE01/D17_SE01_R03_2.csv',
 '../Dataset/SE01/D17_SE01_R04_1.csv',
 '../Dataset/SE01/D17_SE01_R04_2.csv',
 '../Dataset/SE01/D17_SE01_R05_1.csv',
 '../Dataset/SE01/D17_SE01_R05_2.csv',
 '../Dataset/SE01/D16_SE01_R01.csv',
 '../Dataset/SE01/D16_SE01_R02.csv',
 '../Dataset/SE01/D16_SE01_R03.csv',
 '../Dataset/SE01/D16_SE01_R04.csv',
 '../Dataset/SE01/D16_SE01_R05.csv',
 '../Dataset/SE01/D17_SE01_R01.csv',
 '../Dataset/SE01/D17_SE01_R02.csv',
 '../Dataset/SE01/D17_SE01_R03.csv',
 '../Dataset/SE01/D17_SE01_R04.csv',
 '../Dataset/SE01/D17_SE01_R05.csv']

In [241]:
list = []
final_SE01_A = pd.DataFrame(list)

for path in SE01_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE01_A = final_SE01_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE01_A.shape
target_col = row * [0]
final_SE01_A.loc[:,'target'] = target_col

final_SE01_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,234.0,235.0,239.0,241.0,239.0,238.0,237.0,236.0,234.0,229.0,...,227.0,230.0,234.0,234.0,235.0,237.0,236.0,244.0,241.0,0
0,247.0,249.0,247.0,247.0,242.0,247.0,247.0,247.0,249.0,245.0,...,248.0,247.0,250.0,247.0,251.0,245.0,251.0,247.0,248.0,0
0,248.0,249.0,247.0,248.0,245.0,248.0,249.0,250.0,249.0,252.0,...,237.0,241.0,240.0,239.0,242.0,244.0,244.0,248.0,247.0,0
0,249.0,254.0,255.0,254.0,252.0,255.0,252.0,248.0,251.0,250.0,...,271.0,249.0,256.0,299.0,293.0,259.0,255.0,303.0,311.0,0
0,272.0,275.0,277.0,283.0,285.0,289.0,294.0,294.0,297.0,297.0,...,315.0,317.0,316.0,317.0,318.0,312.0,315.0,308.0,310.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,280.0,277.0,279.0,280.0,277.0,283.0,279.0,277.0,277.0,280.0,...,277.0,276.0,278.0,275.0,276.0,272.0,275.0,274.0,274.0,0
0,276.0,278.0,277.0,282.0,274.0,280.0,277.0,277.0,277.0,275.0,...,277.0,275.0,277.0,271.0,277.0,278.0,277.0,273.0,279.0,0
0,278.0,279.0,280.0,276.0,279.0,279.0,281.0,278.0,276.0,277.0,...,275.0,276.0,275.0,278.0,276.0,276.0,279.0,279.0,278.0,0
0,272.0,279.0,278.0,275.0,280.0,277.0,278.0,276.0,277.0,279.0,...,277.0,281.0,277.0,276.0,276.0,277.0,273.0,277.0,277.0,0
0,276.0,281.0,279.0,278.0,277.0,278.0,279.0,278.0,271.0,280.0,...,277.0,276.0,274.0,278.0,277.0,278.0,281.0,277.0,281.0,0

# SE01

In [242]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE02_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE02')
    SE02_A_paths.append(path)

SE02_A_paths

['../Dataset/SE02/D01_SE02_R01.csv',
 '../Dataset/SE02/D02_SE02_R01.csv',
 '../Dataset/SE02/D03_SE02_R01.csv',
 '../Dataset/SE02/D04_SE02_R01.csv',
 '../Dataset/SE02/D05_SE02_R01_1.csv',
 '../Dataset/SE02/D05_SE02_R01_2.csv',
 '../Dataset/SE02/D05_SE02_R02_1.csv',
 '../Dataset/SE02/D05_SE02_R02_2.csv',
 '../Dataset/SE02/D05_SE02_R03_1.csv',
 '../Dataset/SE02/D05_SE02_R03_2.csv',
 '../Dataset/SE02/D05_SE02_R04_1.csv',
 '../Dataset/SE02/D05_SE02_R04_2.csv',
 '../Dataset/SE02/D05_SE02_R05_1.csv',
 '../Dataset/SE02/D05_SE02_R05_2.csv',
 '../Dataset/SE02/D06_SE02_R01_1.csv',
 '../Dataset/SE02/D06_SE02_R01_2.csv',
 '../Dataset/SE02/D06_SE02_R02_1.csv',
 '../Dataset/SE02/D06_SE02_R02_2.csv',
 '../Dataset/SE02/D06_SE02_R03_1.csv',
 '../Dataset/SE02/D06_SE02_R03_2.csv',
 '../Dataset/SE02/D06_SE02_R04_1.csv',
 '../Dataset/SE02/D06_SE02_R04_2.csv',
 '../Dataset/SE02/D06_SE02_R05_1.csv',
 '../Dataset/SE02/D06_SE02_R05_2.csv',
 '../Dataset/SE02/D07_SE02_R01.csv',
 '../Dataset/SE02/D07_SE02_R02.csv',
 '../Dataset/SE02/D07_SE02_R03.csv',
 '../Dataset/SE02/D07_SE02_R04.csv',
 '../Dataset/SE02/D07_SE02_R05.csv',
 '../Dataset/SE02/D08_SE02_R01.csv',
 '../Dataset/SE02/D08_SE02_R02.csv',
 '../Dataset/SE02/D08_SE02_R03.csv',
 '../Dataset/SE02/D08_SE02_R04.csv',
 '../Dataset/SE02/D08_SE02_R05.csv',
 '../Dataset/SE02/D09_SE02_R01.csv',
 '../Dataset/SE02/D09_SE02_R02.csv',
 '../Dataset/SE02/D09_SE02_R03.csv',
 '../Dataset/SE02/D09_SE02_R04.csv',
 '../Dataset/SE02/D09_SE02_R05.csv',
 '../Dataset/SE02/D10_SE02_R01.csv',
 '../Dataset/SE02/D10_SE02_R02.csv',
 '../Dataset/SE02/D10_SE02_R03.csv',
 '../Dataset/SE02/D10_SE02_R04.csv',
 '../Dataset/SE02/D10_SE02_R05.csv',
 '../Dataset/SE02/D11_SE02_R01.csv',
 '../Dataset/SE02/D11_SE02_R02.csv',
 '../Dataset/SE02/D11_SE02_R03.csv',
 '../Dataset/SE02/D11_SE02_R04.csv',
 '../Dataset/SE02/D11_SE02_R05.csv',
 '../Dataset/SE02/D12_SE02_R01.csv',
 '../Dataset/SE02/D12_SE02_R02.csv',
 '../Dataset/SE02/D12_SE02_R03.csv',
 '../Dataset/SE02/D12_SE02_R04.csv',
 '../Dataset/SE02/D12_SE02_R05.csv',
 '../Dataset/SE02/D13_SE02_R01.csv',
 '../Dataset/SE02/D13_SE02_R02.csv',
 '../Dataset/SE02/D13_SE02_R03.csv',
 '../Dataset/SE02/D13_SE02_R04.csv',
 '../Dataset/SE02/D13_SE02_R05.csv',
 '../Dataset/SE02/D14_SE02_R01.csv',
 '../Dataset/SE02/D14_SE02_R02.csv',
 '../Dataset/SE02/D14_SE02_R03.csv',
 '../Dataset/SE02/D14_SE02_R04.csv',
 '../Dataset/SE02/D14_SE02_R05.csv',
 '../Dataset/SE02/D17_SE02_R01_1.csv',
 '../Dataset/SE02/D17_SE02_R01_2.csv',
 '../Dataset/SE02/D17_SE02_R02_1.csv',
 '../Dataset/SE02/D17_SE02_R02_2.csv',
 '../Dataset/SE02/D17_SE02_R03_1.csv',
 '../Dataset/SE02/D17_SE02_R03_2.csv',
 '../Dataset/SE02/D17_SE02_R04_1.csv',
 '../Dataset/SE02/D17_SE02_R04_2.csv',
 '../Dataset/SE02/D17_SE02_R05_1.csv',
 '../Dataset/SE02/D17_SE02_R05_2.csv',
 '../Dataset/SE02/D16_SE02_R01.csv',
 '../Dataset/SE02/D16_SE02_R02.csv',
 '../Dataset/SE02/D16_SE02_R03.csv',
 '../Dataset/SE02/D16_SE02_R04.csv',
 '../Dataset/SE02/D16_SE02_R05.csv',
 '../Dataset/SE02/D17_SE02_R01.csv',
 '../Dataset/SE02/D17_SE02_R02.csv',
 '../Dataset/SE02/D17_SE02_R03.csv',
 '../Dataset/SE02/D17_SE02_R04.csv',
 '../Dataset/SE02/D17_SE02_R05.csv']

In [243]:
list = []
final_SE02_A = pd.DataFrame(list)

for path in SE02_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE02_A = final_SE02_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE02_A.shape
target_col = row * [0]
final_SE02_A.loc[:,'target'] = target_col

final_SE02_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,270.0,270.0,264.0,264.0,258.0,255.0,255.0,254.0,253.0,250.0,...,273.0,273.0,272.0,264.0,260.0,254.0,247.0,242.0,234.0,0
0,195.0,196.0,201.0,207.0,212.0,218.0,224.0,232.0,244.0,253.0,...,412.0,412.0,408.0,387.0,354.0,331.0,297.0,278.0,269.0,0
0,249.0,247.0,248.0,247.0,249.0,247.0,249.0,248.0,249.0,249.0,...,242.0,239.0,241.0,242.0,248.0,252.0,247.0,247.0,251.0,0
0,227.0,228.0,228.0,228.0,230.0,234.0,237.0,234.0,240.0,243.0,...,236.0,241.0,244.0,250.0,251.0,253.0,251.0,257.0,255.0,0
0,388.0,381.0,380.0,377.0,370.0,366.0,356.0,347.0,331.0,319.0,...,345.0,356.0,372.0,387.0,396.0,400.0,399.0,386.0,378.0,0
0,253.0,251.0,248.0,252.0,253.0,257.0,254.0,256.0,260.0,255.0,...,220.0,224.0,225.0,235.0,237.0,242.0,243.0,243.0,245.0,0
0,431.0,460.0,478.0,501.0,509.0,511.0,495.0,476.0,450.0,412.0,...,171.0,165.0,163.0,159.0,164.0,168.0,168.0,171.0,180.0,0
0,247.0,244.0,241.0,244.0,240.0,240.0,243.0,248.0,253.0,253.0,...,237.0,243.0,248.0,258.0,272.0,287.0,303.0,322.0,343.0,0
0,169.0,170.0,172.0,179.0,198.0,213.0,237.0,260.0,274.0,288.0,...,239.0,246.0,257.0,270.0,279.0,289.0,300.0,313.0,324.0,0
0,260.0,258.0,264.0,262.0,262.0,263.0,265.0,264.0,262.0,260.0,...,227.0,230.0,234.0,235.0,233.0,234.0,235.0,235.0,239.0,0
0,211.0,210.0,210.0,217.0,227.0,234.0,240.0,251.0,257.0,258.0,...,208.0,209.0,211.0,213.0,217.0,213.0,216.0,218.0,218.0,0
0,232.0,221.0,211.0,201.0,201.0,193.0,191.0,194.0,193.0,198.0,...,245.0,244.0,247.0,246.0,242.0,245.0,241.0,241.0,242.0,0
0,291.0,311.0,324.0,330.0,338.0,344.0,343.0,347.0,356.0,361.0,...,364.0,370.0,378.0,381.0,381.0,380.0,380.0,371.0,372.0,0
0,249.0,243.0,245.0,242.0,245.0,247.0,244.0,246.0,244.0,249.0,...,249.0,251.0,252.0,250.0,249.0,249.0,253.0,251.0,248.0,0
0,246.0,246.0,246.0,244.0,249.0,252.0,252.0,247.0,252.0,252.0,...,250.0,251.0,247.0,249.0,247.0,250.0,244.0,251.0,250.0,0
0,246.0,248.0,246.0,247.0,249.0,245.0,247.0,250.0,251.0,246.0,...,247.0,249.0,245.0,244.0,250.0,247.0,251.0,249.0,247.0,0
0,245.0,243.0,244.0,246.0,247.0,244.0,245.0,245.0,246.0,248.0,...,244.0,243.0,243.0,246.0,247.0,246.0,243.0,246.0,245.0,0
0,250.0,251.0,246.0,249.0,245.0,250.0,251.0,248.0,253.0,252.0,...,244.0,244.0,245.0,247.0,247.0,245.0,246.0,248.0,247.0,0
0,252.0,247.0,247.0,250.0,250.0,247.0,250.0,247.0,248.0,242.0,...,248.0,247.0,244.0,243.0,244.0,240.0,240.0,244.0,242.0,0
0,244.0,250.0,250.0,253.0,245.0,246.0,245.0,250.0,247.0,244.0,...,247.0,249.0,246.0,249.0,246.0,253.0,251.0,248.0,246.0,0
0,253.0,253.0,245.0,249.0,249.0,251.0,251.0,245.0,252.0,248.0,...,249.0,246.0,247.0,251.0,250.0,244.0,246.0,246.0,246.0,0
0,250.0,248.0,246.0,244.0,249.0,253.0,254.0,249.0,248.0,248.0,...,248.0,247.0,246.0,248.0,246.0,245.0,240.0,250.0,248.0,0
0,250.0,247.0,250.0,246.0,249.0,240.0,245.0,244.0,245.0,246.0,...,248.0,249.0,245.0,246.0,243.0,246.0,247.0,247.0,246.0,0
0,250.0,247.0,245.0,247.0,250.0,253.0,248.0,247.0,253.0,252.0,...,244.0,245.0,249.0,246.0,246.0,246.0,247.0,249.0,249.0,0
0,250.0,247.0,247.0,246.0,245.0,247.0,246.0,251.0,246.0,251.0,...,252.0,251.0,247.0,252.0,252.0,254.0,250.0,253.0,251.0,0
0,252.0,254.0,253.0,251.0,249.0,248.0,251.0,251.0,249.0,243.0,...,249.0,247.0,249.0,258.0,252.0,250.0,250.0,250.0,251.0,0
0,245.0,248.0,252.0,251.0,247.0,250.0,248.0,250.0,248.0,249.0,...,247.0,249.0,246.0,247.0,248.0,247.0,248.0,247.0,249.0,0
0,250.0,251.0,249.0,249.0,246.0,250.0,249.0,246.0,249.0,247.0,...,249.0,252.0,252.0,249.0,251.0,246.0,247.0,250.0,249.0,0
0,245.0,248.0,244.0,248.0,248.0,246.0,246.0,247.0,245.0,248.0,...,248.0,248.0,245.0,248.0,248.0,251.0,247.0,247.0,251.0,0
0,249.0,251.0,241.0,247.0,248.0,251.0,247.0,250.0,244.0,244.0,...,246.0,249.0,252.0,247.0,249.0,246.0,253.0,252.0,248.0,0
0,247.0,249.0,250.0,252.0,251.0,248.0,251.0,251.0,249.0,250.0,...,251.0,248.0,249.0,252.0,247.0,249.0,245.0,249.0,244.0,0
0,247.0,247.0,247.0,248.0,248.0,247.0,247.0,248.0,250.0,248.0,...,251.0,251.0,249.0,247.0,253.0,251.0,246.0,252.0,254.0,0
0,245.0,249.0,249.0,249.0,253.0,247.0,242.0,245.0,246.0,250.0,...,249.0,248.0,248.0,247.0,250.0,251.0,247.0,249.0,248.0,0
0,249.0,251.0,249.0,252.0,252.0,250.0,251.0,252.0,254.0,255.0,...,250.0,253.0,253.0,252.0,249.0,250.0,258.0,254.0,250.0,0
0,247.0,250.0,251.0,245.0,249.0,252.0,252.0,251.0,253.0,251.0,...,252.0,251.0,252.0,252.0,253.0,252.0,258.0,260.0,255.0,0
0,250.0,254.0,255.0,249.0,254.0,252.0,256.0,250.0,250.0,249.0,...,253.0,255.0,255.0,254.0,253.0,253.0,256.0,254.0,254.0,0
0,249.0,253.0,252.0,254.0,255.0,245.0,248.0,256.0,254.0,249.0,...,254.0,256.0,255.0,252.0,253.0,252.0,252.0,252.0,255.0,0
0,252.0,253.0,249.0,249.0,248.0,251.0,251.0,254.0,253.0,251.0,...,251.0,255.0,250.0,251.0,252.0,254.0,253.0,254.0,252.0,0
0,245.0,248.0,247.0,252.0,250.0,242.0,249.0,249.0,243.0,248.0,...,252.0,250.0,251.0,251.0,249.0,250.0,253.0,247.0,247.0,0
0,234.0,237.0,243.0,243.0,246.0,250.0,251.0,253.0,258.0,261.0,...,264.0,266.0,261.0,269.0,262.0,265.0,262.0,260.0,259.0,0
0,251.0,251.0,248.0,251.0,246.0,251.0,248.0,248.0,248.0,249.0,...,249.0,247.0,249.0,248.0,248.0,249.0,249.0,248.0,248.0,0
0,197.0,189.0,179.0,165.0,158.0,152.0,150.0,149.0,151.0,156.0,...,343.0,344.0,338.0,329.0,326.0,322.0,315.0,314.0,312.0,0
0,248.0,248.0,248.0,252.0,248.0,247.0,246.0,247.0,250.0,251.0,...,248.0,248.0,245.0,247.0,246.0,251.0,250.0,248.0,247.0,0
0,230.0,238.0,227.0,226.0,225.0,222.0,222.0,221.0,222.0,221.0,...,267.0,254.0,247.0,231.0,226.0,215.0,202.0,195.0,189.0,0
0,248.0,249.0,254.0,247.0,250.0,243.0,248.0,246.0,246.0,247.0,...,253.0,257.0,257.0,257.0,257.0,258.0,255.0,259.0,260.0,0
0,233.0,235.0,234.0,235.0,238.0,242.0,241.0,247.0,250.0,254.0,...,252.0,255.0,259.0,256.0,258.0,260.0,260.0,256.0,261.0,0
0,246.0,249.0,252.0,249.0,251.0,251.0,254.0,256.0,261.0,259.0,...,247.0,250.0,253.0,257.0,255.0,255.0,257.0,258.0,260.0,0
0,245.0,246.0,248.0,248.0,244.0,247.0,250.0,248.0,255.0,249.0,...,257.0,260.0,256.0,258.0,257.0,258.0,254.0,255.0,254.0,0
0,249.0,254.0,250.0,248.0,253.0,248.0,253.0,252.0,250.0,250.0,...,249.0,248.0,251.0,246.0,251.0,247.0,251.0,246.0,248.0,0
0,249.0,251.0,252.0,248.0,249.0,250.0,249.0,248.0,252.0,251.0,...,245.0,249.0,249.0,249.0,252.0,245.0,248.0,246.0,248.0,0
0,249.0,246.0,254.0,254.0,251.0,251.0,250.0,254.0,256.0,256.0,...,246.0,250.0,246.0,248.0,247.0,248.0,247.0,248.0,249.0,0
0,252.0,248.0,251.0,247.0,246.0,246.0,251.0,247.0,248.0,255.0,...,242.0,242.0,248.0,243.0,246.0,248.0,248.0,248.0,250.0,0
0,245.0,246.0,246.0,246.0,250.0,253.0,248.0,252.0,247.0,249.0,...,248.0,246.0,246.0,245.0,249.0,250.0,250.0,250.0,248.0,0
0,245.0,248.0,247.0,252.0,250.0,242.0,249.0,249.0,243.0,248.0,...,252.0,250.0,251.0,251.0,249.0,250.0,253.0,247.0,247.0,0
0,251.0,251.0,248.0,251.0,246.0,251.0,248.0,248.0,248.0,249.0,...,249.0,247.0,249.0,248.0,248.0,249.0,249.0,248.0,248.0,0
0,248.0,248.0,248.0,252.0,248.0,247.0,246.0,247.0,250.0,251.0,...,248.0,248.0,245.0,247.0,246.0,251.0,250.0,248.0,247.0,0
0,248.0,249.0,254.0,247.0,250.0,243.0,248.0,246.0,246.0,247.0,...,253.0,257.0,257.0,257.0,257.0,258.0,255.0,259.0,260.0,0
0,246.0,249.0,252.0,249.0,251.0,251.0,254.0,256.0,261.0,259.0,...,247.0,250.0,253.0,257.0,255.0,255.0,257.0,258.0,260.0,0

# SE03

In [244]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE03_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE03')
    SE03_A_paths.append(path)

SE03_A_paths

['../Dataset/SE03/D01_SE03_R01.csv',
 '../Dataset/SE03/D02_SE03_R01.csv',
 '../Dataset/SE03/D03_SE03_R01.csv',
 '../Dataset/SE03/D04_SE03_R01.csv',
 '../Dataset/SE03/D05_SE03_R01_1.csv',
 '../Dataset/SE03/D05_SE03_R01_2.csv',
 '../Dataset/SE03/D05_SE03_R02_1.csv',
 '../Dataset/SE03/D05_SE03_R02_2.csv',
 '../Dataset/SE03/D05_SE03_R03_1.csv',
 '../Dataset/SE03/D05_SE03_R03_2.csv',
 '../Dataset/SE03/D05_SE03_R04_1.csv',
 '../Dataset/SE03/D05_SE03_R04_2.csv',
 '../Dataset/SE03/D05_SE03_R05_1.csv',
 '../Dataset/SE03/D05_SE03_R05_2.csv',
 '../Dataset/SE03/D06_SE03_R01_1.csv',
 '../Dataset/SE03/D06_SE03_R01_2.csv',
 '../Dataset/SE03/D06_SE03_R02_1.csv',
 '../Dataset/SE03/D06_SE03_R02_2.csv',
 '../Dataset/SE03/D06_SE03_R03_1.csv',
 '../Dataset/SE03/D06_SE03_R03_2.csv',
 '../Dataset/SE03/D06_SE03_R04_1.csv',
 '../Dataset/SE03/D06_SE03_R04_2.csv',
 '../Dataset/SE03/D06_SE03_R05_1.csv',
 '../Dataset/SE03/D06_SE03_R05_2.csv',
 '../Dataset/SE03/D07_SE03_R01.csv',
 '../Dataset/SE03/D07_SE03_R02.csv',
 '../Dataset/SE03/D07_SE03_R03.csv',
 '../Dataset/SE03/D07_SE03_R04.csv',
 '../Dataset/SE03/D07_SE03_R05.csv',
 '../Dataset/SE03/D08_SE03_R01.csv',
 '../Dataset/SE03/D08_SE03_R02.csv',
 '../Dataset/SE03/D08_SE03_R03.csv',
 '../Dataset/SE03/D08_SE03_R04.csv',
 '../Dataset/SE03/D08_SE03_R05.csv',
 '../Dataset/SE03/D09_SE03_R01.csv',
 '../Dataset/SE03/D09_SE03_R02.csv',
 '../Dataset/SE03/D09_SE03_R03.csv',
 '../Dataset/SE03/D09_SE03_R04.csv',
 '../Dataset/SE03/D09_SE03_R05.csv',
 '../Dataset/SE03/D10_SE03_R01.csv',
 '../Dataset/SE03/D10_SE03_R02.csv',
 '../Dataset/SE03/D10_SE03_R03.csv',
 '../Dataset/SE03/D10_SE03_R04.csv',
 '../Dataset/SE03/D10_SE03_R05.csv',
 '../Dataset/SE03/D11_SE03_R01.csv',
 '../Dataset/SE03/D11_SE03_R02.csv',
 '../Dataset/SE03/D11_SE03_R03.csv',
 '../Dataset/SE03/D11_SE03_R04.csv',
 '../Dataset/SE03/D11_SE03_R05.csv',
 '../Dataset/SE03/D12_SE03_R01.csv',
 '../Dataset/SE03/D12_SE03_R02.csv',
 '../Dataset/SE03/D12_SE03_R03.csv',
 '../Dataset/SE03/D12_SE03_R04.csv',
 '../Dataset/SE03/D12_SE03_R05.csv',
 '../Dataset/SE03/D13_SE03_R01.csv',
 '../Dataset/SE03/D13_SE03_R02.csv',
 '../Dataset/SE03/D13_SE03_R03.csv',
 '../Dataset/SE03/D13_SE03_R04.csv',
 '../Dataset/SE03/D13_SE03_R05.csv',
 '../Dataset/SE03/D14_SE03_R01.csv',
 '../Dataset/SE03/D14_SE03_R02.csv',
 '../Dataset/SE03/D14_SE03_R03.csv',
 '../Dataset/SE03/D14_SE03_R04.csv',
 '../Dataset/SE03/D14_SE03_R05.csv',
 '../Dataset/SE03/D17_SE03_R01_1.csv',
 '../Dataset/SE03/D17_SE03_R01_2.csv',
 '../Dataset/SE03/D17_SE03_R02_1.csv',
 '../Dataset/SE03/D17_SE03_R02_2.csv',
 '../Dataset/SE03/D17_SE03_R03_1.csv',
 '../Dataset/SE03/D17_SE03_R03_2.csv',
 '../Dataset/SE03/D17_SE03_R04_1.csv',
 '../Dataset/SE03/D17_SE03_R04_2.csv',
 '../Dataset/SE03/D17_SE03_R05_1.csv',
 '../Dataset/SE03/D17_SE03_R05_2.csv',
 '../Dataset/SE03/D16_SE03_R01.csv',
 '../Dataset/SE03/D16_SE03_R02.csv',
 '../Dataset/SE03/D16_SE03_R03.csv',
 '../Dataset/SE03/D16_SE03_R04.csv',
 '../Dataset/SE03/D16_SE03_R05.csv',
 '../Dataset/SE03/D17_SE03_R01.csv',
 '../Dataset/SE03/D17_SE03_R02.csv',
 '../Dataset/SE03/D17_SE03_R03.csv',
 '../Dataset/SE03/D17_SE03_R04.csv',
 '../Dataset/SE03/D17_SE03_R05.csv']

In [245]:
list = []
final_SE03_A = pd.DataFrame(list)

for path in SE03_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE03_A = final_SE03_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE03_A.shape
target_col = row * [0]
final_SE03_A.loc[:,'target'] = target_col

final_SE03_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,281.0,280.0,278.0,286.0,291.0,304.0,328.0,344.0,361.0,373.0,...,277.0,272.0,262.0,257.0,247.0,240.0,227.0,213.0,204.0,0
0,249.0,254.0,252.0,252.0,250.0,252.0,252.0,252.0,253.0,254.0,...,390.0,421.0,455.0,487.0,502.0,495.0,470.0,442.0,426.0,0
0,255.0,248.0,253.0,248.0,249.0,247.0,245.0,244.0,241.0,242.0,...,222.0,230.0,239.0,249.0,260.0,273.0,291.0,306.0,321.0,0
0,253.0,248.0,251.0,252.0,252.0,251.0,250.0,252.0,252.0,250.0,...,253.0,252.0,254.0,253.0,251.0,249.0,254.0,254.0,252.0,0
0,316.0,316.0,322.0,327.0,331.0,339.0,340.0,341.0,338.0,338.0,...,326.0,339.0,345.0,359.0,365.0,378.0,385.0,388.0,391.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,257.0,257.0,256.0,254.0,256.0,255.0,254.0,253.0,252.0,256.0,...,251.0,250.0,246.0,248.0,246.0,251.0,247.0,251.0,249.0,0
0,256.0,259.0,259.0,260.0,258.0,261.0,261.0,261.0,260.0,262.0,...,259.0,259.0,258.0,257.0,258.0,260.0,256.0,258.0,259.0,0
0,256.0,254.0,255.0,253.0,250.0,254.0,253.0,249.0,254.0,254.0,...,252.0,248.0,249.0,251.0,250.0,251.0,250.0,252.0,254.0,0
0,257.0,260.0,261.0,259.0,260.0,259.0,258.0,258.0,259.0,255.0,...,263.0,264.0,263.0,264.0,262.0,258.0,262.0,259.0,263.0,0
0,256.0,256.0,257.0,256.0,256.0,258.0,257.0,258.0,256.0,256.0,...,255.0,253.0,259.0,257.0,257.0,247.0,256.0,254.0,258.0,0

# SE04

In [246]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE04_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE04')
    SE04_A_paths.append(path)

SE04_A_paths

['../Dataset/SE04/D01_SE04_R01.csv',
 '../Dataset/SE04/D02_SE04_R01.csv',
 '../Dataset/SE04/D03_SE04_R01.csv',
 '../Dataset/SE04/D04_SE04_R01.csv',
 '../Dataset/SE04/D05_SE04_R01_1.csv',
 '../Dataset/SE04/D05_SE04_R01_2.csv',
 '../Dataset/SE04/D05_SE04_R02_1.csv',
 '../Dataset/SE04/D05_SE04_R02_2.csv',
 '../Dataset/SE04/D05_SE04_R03_1.csv',
 '../Dataset/SE04/D05_SE04_R03_2.csv',
 '../Dataset/SE04/D05_SE04_R04_1.csv',
 '../Dataset/SE04/D05_SE04_R04_2.csv',
 '../Dataset/SE04/D05_SE04_R05_1.csv',
 '../Dataset/SE04/D05_SE04_R05_2.csv',
 '../Dataset/SE04/D06_SE04_R01_1.csv',
 '../Dataset/SE04/D06_SE04_R01_2.csv',
 '../Dataset/SE04/D06_SE04_R02_1.csv',
 '../Dataset/SE04/D06_SE04_R02_2.csv',
 '../Dataset/SE04/D06_SE04_R03_1.csv',
 '../Dataset/SE04/D06_SE04_R03_2.csv',
 '../Dataset/SE04/D06_SE04_R04_1.csv',
 '../Dataset/SE04/D06_SE04_R04_2.csv',
 '../Dataset/SE04/D06_SE04_R05_1.csv',
 '../Dataset/SE04/D06_SE04_R05_2.csv',
 '../Dataset/SE04/D07_SE04_R01.csv',
 '../Dataset/SE04/D07_SE04_R02.csv',
 '../Dataset/SE04/D07_SE04_R03.csv',
 '../Dataset/SE04/D07_SE04_R04.csv',
 '../Dataset/SE04/D07_SE04_R05.csv',
 '../Dataset/SE04/D08_SE04_R01.csv',
 '../Dataset/SE04/D08_SE04_R02.csv',
 '../Dataset/SE04/D08_SE04_R03.csv',
 '../Dataset/SE04/D08_SE04_R04.csv',
 '../Dataset/SE04/D08_SE04_R05.csv',
 '../Dataset/SE04/D09_SE04_R01.csv',
 '../Dataset/SE04/D09_SE04_R02.csv',
 '../Dataset/SE04/D09_SE04_R03.csv',
 '../Dataset/SE04/D09_SE04_R04.csv',
 '../Dataset/SE04/D09_SE04_R05.csv',
 '../Dataset/SE04/D10_SE04_R01.csv',
 '../Dataset/SE04/D10_SE04_R02.csv',
 '../Dataset/SE04/D10_SE04_R03.csv',
 '../Dataset/SE04/D10_SE04_R04.csv',
 '../Dataset/SE04/D10_SE04_R05.csv',
 '../Dataset/SE04/D11_SE04_R01.csv',
 '../Dataset/SE04/D11_SE04_R02.csv',
 '../Dataset/SE04/D11_SE04_R03.csv',
 '../Dataset/SE04/D11_SE04_R04.csv',
 '../Dataset/SE04/D11_SE04_R05.csv',
 '../Dataset/SE04/D12_SE04_R01.csv',
 '../Dataset/SE04/D12_SE04_R02.csv',
 '../Dataset/SE04/D12_SE04_R03.csv',
 '../Dataset/SE04/D12_SE04_R04.csv',
 '../Dataset/SE04/D12_SE04_R05.csv',
 '../Dataset/SE04/D13_SE04_R01.csv',
 '../Dataset/SE04/D13_SE04_R02.csv',
 '../Dataset/SE04/D13_SE04_R03.csv',
 '../Dataset/SE04/D13_SE04_R04.csv',
 '../Dataset/SE04/D13_SE04_R05.csv',
 '../Dataset/SE04/D14_SE04_R01.csv',
 '../Dataset/SE04/D14_SE04_R02.csv',
 '../Dataset/SE04/D14_SE04_R03.csv',
 '../Dataset/SE04/D14_SE04_R04.csv',
 '../Dataset/SE04/D14_SE04_R05.csv',
 '../Dataset/SE04/D17_SE04_R01_1.csv',
 '../Dataset/SE04/D17_SE04_R01_2.csv',
 '../Dataset/SE04/D17_SE04_R02_1.csv',
 '../Dataset/SE04/D17_SE04_R02_2.csv',
 '../Dataset/SE04/D17_SE04_R03_1.csv',
 '../Dataset/SE04/D17_SE04_R03_2.csv',
 '../Dataset/SE04/D17_SE04_R04_1.csv',
 '../Dataset/SE04/D17_SE04_R04_2.csv',
 '../Dataset/SE04/D17_SE04_R05_1.csv',
 '../Dataset/SE04/D17_SE04_R05_2.csv',
 '../Dataset/SE04/D16_SE04_R01.csv',
 '../Dataset/SE04/D16_SE04_R02.csv',
 '../Dataset/SE04/D16_SE04_R03.csv',
 '../Dataset/SE04/D16_SE04_R04.csv',
 '../Dataset/SE04/D16_SE04_R05.csv',
 '../Dataset/SE04/D17_SE04_R01.csv',
 '../Dataset/SE04/D17_SE04_R02.csv',
 '../Dataset/SE04/D17_SE04_R03.csv',
 '../Dataset/SE04/D17_SE04_R04.csv',
 '../Dataset/SE04/D17_SE04_R05.csv']

In [247]:
list = []
final_SE04_A = pd.DataFrame(list)

for path in SE04_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE04_A = final_SE04_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE04_A.shape
target_col = row * [0]
final_SE04_A.loc[:,'target'] = target_col

final_SE04_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,251.0,249.0,251.0,250.0,248.0,247.0,249.0,248.0,246.0,248.0,...,248.0,246.0,245.0,246.0,249.0,250.0,246.0,249.0,249.0,0
0,249.0,246.0,245.0,246.0,244.0,244.0,241.0,236.0,236.0,234.0,...,355.0,340.0,323.0,300.0,277.0,264.0,235.0,211.0,189.0,0
0,248.0,251.0,249.0,247.0,246.0,247.0,249.0,249.0,250.0,252.0,...,244.0,242.0,240.0,237.0,237.0,236.0,232.0,230.0,231.0,0
0,249.0,250.0,245.0,247.0,251.0,248.0,245.0,250.0,251.0,248.0,...,274.0,269.0,266.0,267.0,271.0,274.0,276.0,286.0,287.0,0
0,216.0,212.0,209.0,211.0,213.0,215.0,219.0,223.0,230.0,238.0,...,235.0,230.0,229.0,228.0,230.0,237.0,235.0,240.0,238.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,249.0,248.0,249.0,248.0,248.0,246.0,248.0,248.0,250.0,248.0,...,244.0,249.0,251.0,248.0,246.0,249.0,250.0,251.0,248.0,0
0,248.0,248.0,247.0,247.0,250.0,250.0,250.0,249.0,248.0,250.0,...,251.0,249.0,252.0,252.0,249.0,248.0,249.0,249.0,249.0,0
0,247.0,250.0,250.0,247.0,250.0,249.0,251.0,249.0,249.0,251.0,...,253.0,251.0,258.0,258.0,251.0,248.0,250.0,250.0,250.0,0
0,248.0,249.0,248.0,252.0,249.0,247.0,251.0,249.0,248.0,251.0,...,249.0,251.0,250.0,252.0,252.0,254.0,249.0,253.0,252.0,0
0,247.0,248.0,248.0,254.0,249.0,249.0,250.0,250.0,246.0,248.0,...,249.0,246.0,246.0,248.0,249.0,249.0,246.0,246.0,248.0,0

# SE05

In [248]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE05_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE05')
    SE05_A_paths.append(path)

SE05_A_paths

['../Dataset/SE05/D01_SE05_R01.csv',
 '../Dataset/SE05/D02_SE05_R01.csv',
 '../Dataset/SE05/D03_SE05_R01.csv',
 '../Dataset/SE05/D04_SE05_R01.csv',
 '../Dataset/SE05/D05_SE05_R01_1.csv',
 '../Dataset/SE05/D05_SE05_R01_2.csv',
 '../Dataset/SE05/D05_SE05_R02_1.csv',
 '../Dataset/SE05/D05_SE05_R02_2.csv',
 '../Dataset/SE05/D05_SE05_R03_1.csv',
 '../Dataset/SE05/D05_SE05_R03_2.csv',
 '../Dataset/SE05/D05_SE05_R04_1.csv',
 '../Dataset/SE05/D05_SE05_R04_2.csv',
 '../Dataset/SE05/D05_SE05_R05_1.csv',
 '../Dataset/SE05/D05_SE05_R05_2.csv',
 '../Dataset/SE05/D06_SE05_R01_1.csv',
 '../Dataset/SE05/D06_SE05_R01_2.csv',
 '../Dataset/SE05/D06_SE05_R02_1.csv',
 '../Dataset/SE05/D06_SE05_R02_2.csv',
 '../Dataset/SE05/D06_SE05_R03_1.csv',
 '../Dataset/SE05/D06_SE05_R03_2.csv',
 '../Dataset/SE05/D06_SE05_R04_1.csv',
 '../Dataset/SE05/D06_SE05_R04_2.csv',
 '../Dataset/SE05/D06_SE05_R05_1.csv',
 '../Dataset/SE05/D06_SE05_R05_2.csv',
 '../Dataset/SE05/D07_SE05_R01.csv',
 '../Dataset/SE05/D07_SE05_R02.csv',
 '../Dataset/SE05/D07_SE05_R03.csv',
 '../Dataset/SE05/D07_SE05_R04.csv',
 '../Dataset/SE05/D07_SE05_R05.csv',
 '../Dataset/SE05/D08_SE05_R01.csv',
 '../Dataset/SE05/D08_SE05_R02.csv',
 '../Dataset/SE05/D08_SE05_R03.csv',
 '../Dataset/SE05/D08_SE05_R04.csv',
 '../Dataset/SE05/D08_SE05_R05.csv',
 '../Dataset/SE05/D09_SE05_R01.csv',
 '../Dataset/SE05/D09_SE05_R02.csv',
 '../Dataset/SE05/D09_SE05_R03.csv',
 '../Dataset/SE05/D09_SE05_R04.csv',
 '../Dataset/SE05/D09_SE05_R05.csv',
 '../Dataset/SE05/D10_SE05_R01.csv',
 '../Dataset/SE05/D10_SE05_R02.csv',
 '../Dataset/SE05/D10_SE05_R03.csv',
 '../Dataset/SE05/D10_SE05_R04.csv',
 '../Dataset/SE05/D10_SE05_R05.csv',
 '../Dataset/SE05/D11_SE05_R01.csv',
 '../Dataset/SE05/D11_SE05_R02.csv',
 '../Dataset/SE05/D11_SE05_R03.csv',
 '../Dataset/SE05/D11_SE05_R04.csv',
 '../Dataset/SE05/D11_SE05_R05.csv',
 '../Dataset/SE05/D12_SE05_R01.csv',
 '../Dataset/SE05/D12_SE05_R02.csv',
 '../Dataset/SE05/D12_SE05_R03.csv',
 '../Dataset/SE05/D12_SE05_R04.csv',
 '../Dataset/SE05/D12_SE05_R05.csv',
 '../Dataset/SE05/D13_SE05_R01.csv',
 '../Dataset/SE05/D13_SE05_R02.csv',
 '../Dataset/SE05/D13_SE05_R03.csv',
 '../Dataset/SE05/D13_SE05_R04.csv',
 '../Dataset/SE05/D13_SE05_R05.csv',
 '../Dataset/SE05/D14_SE05_R01.csv',
 '../Dataset/SE05/D14_SE05_R02.csv',
 '../Dataset/SE05/D14_SE05_R03.csv',
 '../Dataset/SE05/D14_SE05_R04.csv',
 '../Dataset/SE05/D14_SE05_R05.csv',
 '../Dataset/SE05/D17_SE05_R01_1.csv',
 '../Dataset/SE05/D17_SE05_R01_2.csv',
 '../Dataset/SE05/D17_SE05_R02_1.csv',
 '../Dataset/SE05/D17_SE05_R02_2.csv',
 '../Dataset/SE05/D17_SE05_R03_1.csv',
 '../Dataset/SE05/D17_SE05_R03_2.csv',
 '../Dataset/SE05/D17_SE05_R04_1.csv',
 '../Dataset/SE05/D17_SE05_R04_2.csv',
 '../Dataset/SE05/D17_SE05_R05_1.csv',
 '../Dataset/SE05/D17_SE05_R05_2.csv',
 '../Dataset/SE05/D16_SE05_R01.csv',
 '../Dataset/SE05/D16_SE05_R02.csv',
 '../Dataset/SE05/D16_SE05_R03.csv',
 '../Dataset/SE05/D16_SE05_R04.csv',
 '../Dataset/SE05/D16_SE05_R05.csv',
 '../Dataset/SE05/D17_SE05_R01.csv',
 '../Dataset/SE05/D17_SE05_R02.csv',
 '../Dataset/SE05/D17_SE05_R03.csv',
 '../Dataset/SE05/D17_SE05_R04.csv',
 '../Dataset/SE05/D17_SE05_R05.csv']

In [249]:
list = []
final_SE05_A = pd.DataFrame(list)

for path in SE05_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE05_A = final_SE05_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE05_A.shape
target_col = row * [0]
final_SE05_A.loc[:,'target'] = target_col

final_SE05_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,255.0,253.0,243.0,247.0,249.0,253.0,252.0,252.0,260.0,256.0,...,274.0,284.0,285.0,292.0,299.0,303.0,307.0,308.0,309.0,0
0,275.0,276.0,279.0,282.0,288.0,295.0,314.0,320.0,330.0,342.0,...,316.0,317.0,316.0,323.0,322.0,339.0,350.0,360.0,367.0,0
0,299.0,297.0,298.0,295.0,292.0,291.0,292.0,291.0,294.0,288.0,...,243.0,244.0,246.0,253.0,257.0,252.0,248.0,245.0,227.0,0
0,287.0,288.0,286.0,287.0,281.0,280.0,276.0,274.0,272.0,270.0,...,265.0,267.0,268.0,266.0,268.0,265.0,270.0,266.0,266.0,0
0,267.0,266.0,267.0,268.0,267.0,266.0,267.0,264.0,258.0,256.0,...,293.0,288.0,279.0,276.0,268.0,262.0,259.0,254.0,247.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,250.0,251.0,248.0,249.0,243.0,241.0,249.0,250.0,246.0,249.0,...,250.0,250.0,250.0,250.0,251.0,247.0,247.0,249.0,248.0,0
0,239.0,243.0,240.0,242.0,244.0,241.0,245.0,241.0,240.0,241.0,...,242.0,245.0,246.0,242.0,244.0,241.0,242.0,241.0,241.0,0
0,243.0,247.0,244.0,244.0,247.0,242.0,247.0,242.0,242.0,243.0,...,243.0,246.0,245.0,244.0,249.0,249.0,249.0,248.0,249.0,0
0,252.0,251.0,253.0,256.0,256.0,256.0,257.0,257.0,254.0,258.0,...,253.0,255.0,253.0,253.0,255.0,254.0,258.0,257.0,257.0,0
0,254.0,257.0,258.0,253.0,251.0,252.0,250.0,253.0,250.0,251.0,...,257.0,254.0,255.0,258.0,255.0,254.0,252.0,250.0,253.0,0

# SE06

In [250]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE06_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE06')
    SE06_A_paths.append(path)

SE06_A_paths

['../Dataset/SE06/D01_SE06_R01.csv',
 '../Dataset/SE06/D02_SE06_R01.csv',
 '../Dataset/SE06/D03_SE06_R01.csv',
 '../Dataset/SE06/D04_SE06_R01.csv',
 '../Dataset/SE06/D05_SE06_R01_1.csv',
 '../Dataset/SE06/D05_SE06_R01_2.csv',
 '../Dataset/SE06/D05_SE06_R02_1.csv',
 '../Dataset/SE06/D05_SE06_R02_2.csv',
 '../Dataset/SE06/D05_SE06_R03_1.csv',
 '../Dataset/SE06/D05_SE06_R03_2.csv',
 '../Dataset/SE06/D05_SE06_R04_1.csv',
 '../Dataset/SE06/D05_SE06_R04_2.csv',
 '../Dataset/SE06/D05_SE06_R05_1.csv',
 '../Dataset/SE06/D05_SE06_R05_2.csv',
 '../Dataset/SE06/D06_SE06_R01_1.csv',
 '../Dataset/SE06/D06_SE06_R01_2.csv',
 '../Dataset/SE06/D06_SE06_R02_1.csv',
 '../Dataset/SE06/D06_SE06_R02_2.csv',
 '../Dataset/SE06/D06_SE06_R03_1.csv',
 '../Dataset/SE06/D06_SE06_R03_2.csv',
 '../Dataset/SE06/D06_SE06_R04_1.csv',
 '../Dataset/SE06/D06_SE06_R04_2.csv',
 '../Dataset/SE06/D06_SE06_R05_1.csv',
 '../Dataset/SE06/D06_SE06_R05_2.csv',
 '../Dataset/SE06/D07_SE06_R01.csv',
 '../Dataset/SE06/D07_SE06_R02.csv',
 '../Dataset/SE06/D07_SE06_R03.csv',
 '../Dataset/SE06/D07_SE06_R04.csv',
 '../Dataset/SE06/D07_SE06_R05.csv',
 '../Dataset/SE06/D08_SE06_R01.csv',
 '../Dataset/SE06/D08_SE06_R02.csv',
 '../Dataset/SE06/D08_SE06_R03.csv',
 '../Dataset/SE06/D08_SE06_R04.csv',
 '../Dataset/SE06/D08_SE06_R05.csv',
 '../Dataset/SE06/D09_SE06_R01.csv',
 '../Dataset/SE06/D09_SE06_R02.csv',
 '../Dataset/SE06/D09_SE06_R03.csv',
 '../Dataset/SE06/D09_SE06_R04.csv',
 '../Dataset/SE06/D09_SE06_R05.csv',
 '../Dataset/SE06/D10_SE06_R01.csv',
 '../Dataset/SE06/D10_SE06_R02.csv',
 '../Dataset/SE06/D10_SE06_R03.csv',
 '../Dataset/SE06/D10_SE06_R04.csv',
 '../Dataset/SE06/D10_SE06_R05.csv',
 '../Dataset/SE06/D11_SE06_R01.csv',
 '../Dataset/SE06/D11_SE06_R02.csv',
 '../Dataset/SE06/D11_SE06_R03.csv',
 '../Dataset/SE06/D11_SE06_R04.csv',
 '../Dataset/SE06/D11_SE06_R05.csv',
 '../Dataset/SE06/D12_SE06_R01.csv',
 '../Dataset/SE06/D12_SE06_R02.csv',
 '../Dataset/SE06/D12_SE06_R03.csv',
 '../Dataset/SE06/D12_SE06_R04.csv',
 '../Dataset/SE06/D12_SE06_R05.csv',
 '../Dataset/SE06/D13_SE06_R01.csv',
 '../Dataset/SE06/D13_SE06_R02.csv',
 '../Dataset/SE06/D13_SE06_R03.csv',
 '../Dataset/SE06/D13_SE06_R04.csv',
 '../Dataset/SE06/D13_SE06_R05.csv',
 '../Dataset/SE06/D14_SE06_R01.csv',
 '../Dataset/SE06/D14_SE06_R02.csv',
 '../Dataset/SE06/D14_SE06_R03.csv',
 '../Dataset/SE06/D14_SE06_R04.csv',
 '../Dataset/SE06/D14_SE06_R05.csv',
 '../Dataset/SE06/D17_SE06_R01_1.csv',
 '../Dataset/SE06/D17_SE06_R01_2.csv',
 '../Dataset/SE06/D17_SE06_R02_1.csv',
 '../Dataset/SE06/D17_SE06_R02_2.csv',
 '../Dataset/SE06/D17_SE06_R03_1.csv',
 '../Dataset/SE06/D17_SE06_R03_2.csv',
 '../Dataset/SE06/D17_SE06_R04_1.csv',
 '../Dataset/SE06/D17_SE06_R04_2.csv',
 '../Dataset/SE06/D17_SE06_R05_1.csv',
 '../Dataset/SE06/D17_SE06_R05_2.csv',
 '../Dataset/SE06/D16_SE06_R01.csv',
 '../Dataset/SE06/D16_SE06_R02.csv',
 '../Dataset/SE06/D16_SE06_R03.csv',
 '../Dataset/SE06/D16_SE06_R04.csv',
 '../Dataset/SE06/D16_SE06_R05.csv',
 '../Dataset/SE06/D17_SE06_R01.csv',
 '../Dataset/SE06/D17_SE06_R02.csv',
 '../Dataset/SE06/D17_SE06_R03.csv',
 '../Dataset/SE06/D17_SE06_R04.csv',
 '../Dataset/SE06/D17_SE06_R05.csv']

In [251]:
list = []
final_SE06_A = pd.DataFrame(list)

for path in SE06_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE06_A = final_SE06_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE06_A.shape
target_col = row * [0]
final_SE06_A.loc[:,'target'] = target_col

final_SE06_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,247.0,248.0,249.0,248.0,249.0,245.0,250.0,246.0,248.0,246.0,...,251.0,245.0,239.0,238.0,238.0,236.0,237.0,235.0,230.0,0
0,246.0,246.0,246.0,248.0,243.0,247.0,245.0,248.0,249.0,244.0,...,246.0,238.0,235.0,229.0,224.0,225.0,227.0,236.0,245.0,0
0,253.0,256.0,256.0,257.0,257.0,263.0,258.0,258.0,259.0,259.0,...,218.0,217.0,215.0,217.0,216.0,217.0,215.0,220.0,221.0,0
0,251.0,247.0,248.0,246.0,249.0,237.0,249.0,246.0,247.0,246.0,...,217.0,219.0,232.0,244.0,259.0,274.0,283.0,299.0,313.0,0
0,230.0,223.0,221.0,219.0,216.0,212.0,210.0,212.0,211.0,216.0,...,181.0,191.0,193.0,196.0,197.0,201.0,207.0,215.0,222.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,244.0,251.0,251.0,250.0,248.0,252.0,248.0,249.0,250.0,251.0,...,249.0,247.0,248.0,250.0,247.0,248.0,240.0,248.0,248.0,0
0,247.0,248.0,251.0,249.0,250.0,253.0,250.0,247.0,247.0,245.0,...,250.0,251.0,248.0,249.0,244.0,249.0,248.0,253.0,248.0,0
0,249.0,249.0,254.0,249.0,250.0,253.0,247.0,246.0,247.0,251.0,...,248.0,249.0,250.0,247.0,248.0,248.0,248.0,247.0,248.0,0
0,248.0,243.0,251.0,251.0,249.0,244.0,248.0,249.0,249.0,247.0,...,258.0,249.0,248.0,244.0,241.0,229.0,235.0,235.0,231.0,0
0,241.0,241.0,240.0,237.0,238.0,243.0,239.0,242.0,242.0,249.0,...,253.0,256.0,259.0,258.0,262.0,267.0,266.0,269.0,269.0,0

# SE07

In [252]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE07_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE07')
    SE07_A_paths.append(path)

SE07_A_paths

['../Dataset/SE07/D01_SE07_R01.csv',
 '../Dataset/SE07/D02_SE07_R01.csv',
 '../Dataset/SE07/D03_SE07_R01.csv',
 '../Dataset/SE07/D04_SE07_R01.csv',
 '../Dataset/SE07/D05_SE07_R01_1.csv',
 '../Dataset/SE07/D05_SE07_R01_2.csv',
 '../Dataset/SE07/D05_SE07_R02_1.csv',
 '../Dataset/SE07/D05_SE07_R02_2.csv',
 '../Dataset/SE07/D05_SE07_R03_1.csv',
 '../Dataset/SE07/D05_SE07_R03_2.csv',
 '../Dataset/SE07/D05_SE07_R04_1.csv',
 '../Dataset/SE07/D05_SE07_R04_2.csv',
 '../Dataset/SE07/D05_SE07_R05_1.csv',
 '../Dataset/SE07/D05_SE07_R05_2.csv',
 '../Dataset/SE07/D06_SE07_R01_1.csv',
 '../Dataset/SE07/D06_SE07_R01_2.csv',
 '../Dataset/SE07/D06_SE07_R02_1.csv',
 '../Dataset/SE07/D06_SE07_R02_2.csv',
 '../Dataset/SE07/D06_SE07_R03_1.csv',
 '../Dataset/SE07/D06_SE07_R03_2.csv',
 '../Dataset/SE07/D06_SE07_R04_1.csv',
 '../Dataset/SE07/D06_SE07_R04_2.csv',
 '../Dataset/SE07/D06_SE07_R05_1.csv',
 '../Dataset/SE07/D06_SE07_R05_2.csv',
 '../Dataset/SE07/D07_SE07_R01.csv',
 '../Dataset/SE07/D07_SE07_R02.csv',
 '../Dataset/SE07/D07_SE07_R03.csv',
 '../Dataset/SE07/D07_SE07_R04.csv',
 '../Dataset/SE07/D07_SE07_R05.csv',
 '../Dataset/SE07/D08_SE07_R01.csv',
 '../Dataset/SE07/D08_SE07_R02.csv',
 '../Dataset/SE07/D08_SE07_R03.csv',
 '../Dataset/SE07/D08_SE07_R04.csv',
 '../Dataset/SE07/D08_SE07_R05.csv',
 '../Dataset/SE07/D09_SE07_R01.csv',
 '../Dataset/SE07/D09_SE07_R02.csv',
 '../Dataset/SE07/D09_SE07_R03.csv',
 '../Dataset/SE07/D09_SE07_R04.csv',
 '../Dataset/SE07/D09_SE07_R05.csv',
 '../Dataset/SE07/D10_SE07_R01.csv',
 '../Dataset/SE07/D10_SE07_R02.csv',
 '../Dataset/SE07/D10_SE07_R03.csv',
 '../Dataset/SE07/D10_SE07_R04.csv',
 '../Dataset/SE07/D10_SE07_R05.csv',
 '../Dataset/SE07/D11_SE07_R01.csv',
 '../Dataset/SE07/D11_SE07_R02.csv',
 '../Dataset/SE07/D11_SE07_R03.csv',
 '../Dataset/SE07/D11_SE07_R04.csv',
 '../Dataset/SE07/D11_SE07_R05.csv',
 '../Dataset/SE07/D12_SE07_R01.csv',
 '../Dataset/SE07/D12_SE07_R02.csv',
 '../Dataset/SE07/D12_SE07_R03.csv',
 '../Dataset/SE07/D12_SE07_R04.csv',
 '../Dataset/SE07/D12_SE07_R05.csv',
 '../Dataset/SE07/D13_SE07_R01.csv',
 '../Dataset/SE07/D13_SE07_R02.csv',
 '../Dataset/SE07/D13_SE07_R03.csv',
 '../Dataset/SE07/D13_SE07_R04.csv',
 '../Dataset/SE07/D13_SE07_R05.csv',
 '../Dataset/SE07/D14_SE07_R01.csv',
 '../Dataset/SE07/D14_SE07_R02.csv',
 '../Dataset/SE07/D14_SE07_R03.csv',
 '../Dataset/SE07/D14_SE07_R04.csv',
 '../Dataset/SE07/D14_SE07_R05.csv',
 '../Dataset/SE07/D17_SE07_R01_1.csv',
 '../Dataset/SE07/D17_SE07_R01_2.csv',
 '../Dataset/SE07/D17_SE07_R02_1.csv',
 '../Dataset/SE07/D17_SE07_R02_2.csv',
 '../Dataset/SE07/D17_SE07_R03_1.csv',
 '../Dataset/SE07/D17_SE07_R03_2.csv',
 '../Dataset/SE07/D17_SE07_R04_1.csv',
 '../Dataset/SE07/D17_SE07_R04_2.csv',
 '../Dataset/SE07/D17_SE07_R05_1.csv',
 '../Dataset/SE07/D17_SE07_R05_2.csv',
 '../Dataset/SE07/D16_SE07_R01.csv',
 '../Dataset/SE07/D16_SE07_R02.csv',
 '../Dataset/SE07/D16_SE07_R03.csv',
 '../Dataset/SE07/D16_SE07_R04.csv',
 '../Dataset/SE07/D16_SE07_R05.csv',
 '../Dataset/SE07/D17_SE07_R01.csv',
 '../Dataset/SE07/D17_SE07_R02.csv',
 '../Dataset/SE07/D17_SE07_R03.csv',
 '../Dataset/SE07/D17_SE07_R04.csv',
 '../Dataset/SE07/D17_SE07_R05.csv']

In [253]:
list = []
final_SE07_A = pd.DataFrame(list)

for path in SE07_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE07_A = final_SE07_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE07_A.shape
target_col = row * [0]
final_SE07_A.loc[:,'target'] = target_col

final_SE07_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,266.0,267.0,266.0,266.0,265.0,265.0,264.0,264.0,268.0,269.0,...,215.0,227.0,241.0,253.0,274.0,296.0,318.0,331.0,342.0,0
0,268.0,270.0,267.0,270.0,268.0,265.0,266.0,269.0,270.0,268.0,...,301.0,303.0,304.0,298.0,293.0,290.0,290.0,281.0,275.0,0
0,268.0,272.0,268.0,271.0,273.0,272.0,265.0,260.0,275.0,271.0,...,272.0,266.0,271.0,268.0,268.0,270.0,271.0,268.0,272.0,0
0,276.0,276.0,273.0,270.0,275.0,270.0,272.0,270.0,273.0,269.0,...,269.0,270.0,265.0,264.0,263.0,260.0,256.0,255.0,254.0,0
0,253.0,259.0,255.0,256.0,257.0,256.0,256.0,254.0,258.0,255.0,...,259.0,258.0,259.0,257.0,256.0,256.0,254.0,254.0,251.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,246.0,245.0,245.0,248.0,246.0,246.0,245.0,246.0,247.0,247.0,...,249.0,249.0,249.0,247.0,245.0,246.0,247.0,246.0,245.0,0
0,241.0,245.0,237.0,238.0,241.0,241.0,238.0,240.0,239.0,238.0,...,238.0,240.0,240.0,238.0,241.0,242.0,239.0,241.0,244.0,0
0,247.0,249.0,245.0,247.0,244.0,246.0,247.0,246.0,247.0,247.0,...,251.0,248.0,248.0,245.0,250.0,249.0,250.0,248.0,248.0,0
0,244.0,240.0,241.0,241.0,241.0,240.0,240.0,238.0,236.0,238.0,...,226.0,228.0,230.0,229.0,231.0,234.0,236.0,237.0,240.0,0
0,247.0,246.0,248.0,246.0,244.0,250.0,247.0,246.0,248.0,248.0,...,246.0,245.0,245.0,247.0,247.0,248.0,248.0,245.0,244.0,0

# SE08

In [254]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE08_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE08')
    SE08_A_paths.append(path)

SE08_A_paths

['../Dataset/SE08/D01_SE08_R01.csv',
 '../Dataset/SE08/D02_SE08_R01.csv',
 '../Dataset/SE08/D03_SE08_R01.csv',
 '../Dataset/SE08/D04_SE08_R01.csv',
 '../Dataset/SE08/D05_SE08_R01_1.csv',
 '../Dataset/SE08/D05_SE08_R01_2.csv',
 '../Dataset/SE08/D05_SE08_R02_1.csv',
 '../Dataset/SE08/D05_SE08_R02_2.csv',
 '../Dataset/SE08/D05_SE08_R03_1.csv',
 '../Dataset/SE08/D05_SE08_R03_2.csv',
 '../Dataset/SE08/D05_SE08_R04_1.csv',
 '../Dataset/SE08/D05_SE08_R04_2.csv',
 '../Dataset/SE08/D05_SE08_R05_1.csv',
 '../Dataset/SE08/D05_SE08_R05_2.csv',
 '../Dataset/SE08/D06_SE08_R01_1.csv',
 '../Dataset/SE08/D06_SE08_R01_2.csv',
 '../Dataset/SE08/D06_SE08_R02_1.csv',
 '../Dataset/SE08/D06_SE08_R02_2.csv',
 '../Dataset/SE08/D06_SE08_R03_1.csv',
 '../Dataset/SE08/D06_SE08_R03_2.csv',
 '../Dataset/SE08/D06_SE08_R04_1.csv',
 '../Dataset/SE08/D06_SE08_R04_2.csv',
 '../Dataset/SE08/D06_SE08_R05_1.csv',
 '../Dataset/SE08/D06_SE08_R05_2.csv',
 '../Dataset/SE08/D07_SE08_R01.csv',
 '../Dataset/SE08/D07_SE08_R02.csv',
 '../Dataset/SE08/D07_SE08_R03.csv',
 '../Dataset/SE08/D07_SE08_R04.csv',
 '../Dataset/SE08/D07_SE08_R05.csv',
 '../Dataset/SE08/D08_SE08_R01.csv',
 '../Dataset/SE08/D08_SE08_R02.csv',
 '../Dataset/SE08/D08_SE08_R03.csv',
 '../Dataset/SE08/D08_SE08_R04.csv',
 '../Dataset/SE08/D08_SE08_R05.csv',
 '../Dataset/SE08/D09_SE08_R01.csv',
 '../Dataset/SE08/D09_SE08_R02.csv',
 '../Dataset/SE08/D09_SE08_R03.csv',
 '../Dataset/SE08/D09_SE08_R04.csv',
 '../Dataset/SE08/D09_SE08_R05.csv',
 '../Dataset/SE08/D10_SE08_R01.csv',
 '../Dataset/SE08/D10_SE08_R02.csv',
 '../Dataset/SE08/D10_SE08_R03.csv',
 '../Dataset/SE08/D10_SE08_R04.csv',
 '../Dataset/SE08/D10_SE08_R05.csv',
 '../Dataset/SE08/D11_SE08_R01.csv',
 '../Dataset/SE08/D11_SE08_R02.csv',
 '../Dataset/SE08/D11_SE08_R03.csv',
 '../Dataset/SE08/D11_SE08_R04.csv',
 '../Dataset/SE08/D11_SE08_R05.csv',
 '../Dataset/SE08/D12_SE08_R01.csv',
 '../Dataset/SE08/D12_SE08_R02.csv',
 '../Dataset/SE08/D12_SE08_R03.csv',
 '../Dataset/SE08/D12_SE08_R04.csv',
 '../Dataset/SE08/D12_SE08_R05.csv',
 '../Dataset/SE08/D13_SE08_R01.csv',
 '../Dataset/SE08/D13_SE08_R02.csv',
 '../Dataset/SE08/D13_SE08_R03.csv',
 '../Dataset/SE08/D13_SE08_R04.csv',
 '../Dataset/SE08/D13_SE08_R05.csv',
 '../Dataset/SE08/D14_SE08_R01.csv',
 '../Dataset/SE08/D14_SE08_R02.csv',
 '../Dataset/SE08/D14_SE08_R03.csv',
 '../Dataset/SE08/D14_SE08_R04.csv',
 '../Dataset/SE08/D14_SE08_R05.csv',
 '../Dataset/SE08/D17_SE08_R01_1.csv',
 '../Dataset/SE08/D17_SE08_R01_2.csv',
 '../Dataset/SE08/D17_SE08_R02_1.csv',
 '../Dataset/SE08/D17_SE08_R02_2.csv',
 '../Dataset/SE08/D17_SE08_R03_1.csv',
 '../Dataset/SE08/D17_SE08_R03_2.csv',
 '../Dataset/SE08/D17_SE08_R04_1.csv',
 '../Dataset/SE08/D17_SE08_R04_2.csv',
 '../Dataset/SE08/D17_SE08_R05_1.csv',
 '../Dataset/SE08/D17_SE08_R05_2.csv',
 '../Dataset/SE08/D16_SE08_R01.csv',
 '../Dataset/SE08/D16_SE08_R02.csv',
 '../Dataset/SE08/D16_SE08_R03.csv',
 '../Dataset/SE08/D16_SE08_R04.csv',
 '../Dataset/SE08/D16_SE08_R05.csv',
 '../Dataset/SE08/D17_SE08_R01.csv',
 '../Dataset/SE08/D17_SE08_R02.csv',
 '../Dataset/SE08/D17_SE08_R03.csv',
 '../Dataset/SE08/D17_SE08_R04.csv',
 '../Dataset/SE08/D17_SE08_R05.csv']

In [255]:
list = []
final_SE08_A = pd.DataFrame(list)

for path in SE08_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE08_A = final_SE08_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE08_A.shape
target_col = row * [0]
final_SE08_A.loc[:,'target'] = target_col

final_SE08_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,260.0,262.0,259.0,258.0,258.0,251.0,260.0,258.0,257.0,258.0,...,253.0,254.0,255.0,254.0,253.0,255.0,254.0,254.0,253.0,0
0,148.0,147.0,156.0,165.0,175.0,185.0,196.0,203.0,210.0,216.0,...,173.0,183.0,192.0,207.0,223.0,238.0,255.0,273.0,283.0,0
0,255.0,255.0,255.0,252.0,258.0,259.0,255.0,255.0,256.0,257.0,...,257.0,258.0,261.0,265.0,267.0,269.0,273.0,275.0,281.0,0
0,258.0,260.0,259.0,258.0,258.0,254.0,258.0,257.0,253.0,252.0,...,251.0,247.0,248.0,243.0,238.0,237.0,236.0,234.0,231.0,0
0,254.0,255.0,254.0,255.0,253.0,255.0,255.0,258.0,257.0,260.0,...,341.0,343.0,343.0,340.0,338.0,344.0,353.0,369.0,379.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,253.0,253.0,255.0,253.0,255.0,254.0,255.0,252.0,254.0,254.0,...,249.0,253.0,248.0,252.0,251.0,251.0,254.0,252.0,250.0,0
0,253.0,252.0,255.0,252.0,252.0,252.0,255.0,256.0,253.0,253.0,...,253.0,251.0,250.0,251.0,250.0,249.0,249.0,250.0,253.0,0
0,250.0,252.0,251.0,250.0,248.0,253.0,252.0,255.0,253.0,253.0,...,254.0,250.0,255.0,252.0,257.0,255.0,252.0,255.0,249.0,0
0,252.0,253.0,255.0,254.0,254.0,254.0,254.0,251.0,252.0,251.0,...,250.0,253.0,250.0,252.0,251.0,254.0,249.0,250.0,250.0,0
0,255.0,256.0,252.0,254.0,256.0,253.0,255.0,253.0,253.0,255.0,...,256.0,255.0,256.0,254.0,256.0,256.0,255.0,253.0,251.0,0

# SE09

In [256]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE09_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE09')
    SE09_A_paths.append(path)

SE09_A_paths

['../Dataset/SE09/D01_SE09_R01.csv',
 '../Dataset/SE09/D02_SE09_R01.csv',
 '../Dataset/SE09/D03_SE09_R01.csv',
 '../Dataset/SE09/D04_SE09_R01.csv',
 '../Dataset/SE09/D05_SE09_R01_1.csv',
 '../Dataset/SE09/D05_SE09_R01_2.csv',
 '../Dataset/SE09/D05_SE09_R02_1.csv',
 '../Dataset/SE09/D05_SE09_R02_2.csv',
 '../Dataset/SE09/D05_SE09_R03_1.csv',
 '../Dataset/SE09/D05_SE09_R03_2.csv',
 '../Dataset/SE09/D05_SE09_R04_1.csv',
 '../Dataset/SE09/D05_SE09_R04_2.csv',
 '../Dataset/SE09/D05_SE09_R05_1.csv',
 '../Dataset/SE09/D05_SE09_R05_2.csv',
 '../Dataset/SE09/D06_SE09_R01_1.csv',
 '../Dataset/SE09/D06_SE09_R01_2.csv',
 '../Dataset/SE09/D06_SE09_R02_1.csv',
 '../Dataset/SE09/D06_SE09_R02_2.csv',
 '../Dataset/SE09/D06_SE09_R03_1.csv',
 '../Dataset/SE09/D06_SE09_R03_2.csv',
 '../Dataset/SE09/D06_SE09_R04_1.csv',
 '../Dataset/SE09/D06_SE09_R04_2.csv',
 '../Dataset/SE09/D06_SE09_R05_1.csv',
 '../Dataset/SE09/D06_SE09_R05_2.csv',
 '../Dataset/SE09/D07_SE09_R01.csv',
 '../Dataset/SE09/D07_SE09_R02.csv',
 '../Dataset/SE09/D07_SE09_R03.csv',
 '../Dataset/SE09/D07_SE09_R04.csv',
 '../Dataset/SE09/D07_SE09_R05.csv',
 '../Dataset/SE09/D08_SE09_R01.csv',
 '../Dataset/SE09/D08_SE09_R02.csv',
 '../Dataset/SE09/D08_SE09_R03.csv',
 '../Dataset/SE09/D08_SE09_R04.csv',
 '../Dataset/SE09/D08_SE09_R05.csv',
 '../Dataset/SE09/D09_SE09_R01.csv',
 '../Dataset/SE09/D09_SE09_R02.csv',
 '../Dataset/SE09/D09_SE09_R03.csv',
 '../Dataset/SE09/D09_SE09_R04.csv',
 '../Dataset/SE09/D09_SE09_R05.csv',
 '../Dataset/SE09/D10_SE09_R01.csv',
 '../Dataset/SE09/D10_SE09_R02.csv',
 '../Dataset/SE09/D10_SE09_R03.csv',
 '../Dataset/SE09/D10_SE09_R04.csv',
 '../Dataset/SE09/D10_SE09_R05.csv',
 '../Dataset/SE09/D11_SE09_R01.csv',
 '../Dataset/SE09/D11_SE09_R02.csv',
 '../Dataset/SE09/D11_SE09_R03.csv',
 '../Dataset/SE09/D11_SE09_R04.csv',
 '../Dataset/SE09/D11_SE09_R05.csv',
 '../Dataset/SE09/D12_SE09_R01.csv',
 '../Dataset/SE09/D12_SE09_R02.csv',
 '../Dataset/SE09/D12_SE09_R03.csv',
 '../Dataset/SE09/D12_SE09_R04.csv',
 '../Dataset/SE09/D12_SE09_R05.csv',
 '../Dataset/SE09/D13_SE09_R01.csv',
 '../Dataset/SE09/D13_SE09_R02.csv',
 '../Dataset/SE09/D13_SE09_R03.csv',
 '../Dataset/SE09/D13_SE09_R04.csv',
 '../Dataset/SE09/D13_SE09_R05.csv',
 '../Dataset/SE09/D14_SE09_R01.csv',
 '../Dataset/SE09/D14_SE09_R02.csv',
 '../Dataset/SE09/D14_SE09_R03.csv',
 '../Dataset/SE09/D14_SE09_R04.csv',
 '../Dataset/SE09/D14_SE09_R05.csv',
 '../Dataset/SE09/D17_SE09_R01_1.csv',
 '../Dataset/SE09/D17_SE09_R01_2.csv',
 '../Dataset/SE09/D17_SE09_R02_1.csv',
 '../Dataset/SE09/D17_SE09_R02_2.csv',
 '../Dataset/SE09/D17_SE09_R03_1.csv',
 '../Dataset/SE09/D17_SE09_R03_2.csv',
 '../Dataset/SE09/D17_SE09_R04_1.csv',
 '../Dataset/SE09/D17_SE09_R04_2.csv',
 '../Dataset/SE09/D17_SE09_R05_1.csv',
 '../Dataset/SE09/D17_SE09_R05_2.csv',
 '../Dataset/SE09/D16_SE09_R01.csv',
 '../Dataset/SE09/D16_SE09_R02.csv',
 '../Dataset/SE09/D16_SE09_R03.csv',
 '../Dataset/SE09/D16_SE09_R04.csv',
 '../Dataset/SE09/D16_SE09_R05.csv',
 '../Dataset/SE09/D17_SE09_R01.csv',
 '../Dataset/SE09/D17_SE09_R02.csv',
 '../Dataset/SE09/D17_SE09_R03.csv',
 '../Dataset/SE09/D17_SE09_R04.csv',
 '../Dataset/SE09/D17_SE09_R05.csv']

In [257]:
list = []
final_SE09_A = pd.DataFrame(list)

for path in SE09_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE09_A = final_SE09_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE09_A.shape
target_col = row * [0]
final_SE09_A.loc[:,'target'] = target_col

final_SE09_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,255.0,252.0,252.0,246.0,251.0,251.0,249.0,248.0,248.0,250.0,...,258.0,258.0,253.0,256.0,255.0,257.0,256.0,257.0,257.0,0
0,259.0,259.0,258.0,258.0,259.0,255.0,257.0,256.0,257.0,258.0,...,256.0,254.0,254.0,254.0,253.0,254.0,253.0,250.0,248.0,0
0,253.0,252.0,255.0,258.0,259.0,261.0,260.0,261.0,262.0,263.0,...,254.0,257.0,260.0,255.0,256.0,258.0,257.0,258.0,260.0,0
0,254.0,254.0,255.0,254.0,249.0,253.0,248.0,252.0,255.0,257.0,...,258.0,256.0,254.0,254.0,255.0,259.0,260.0,261.0,267.0,0
0,256.0,256.0,255.0,259.0,257.0,258.0,255.0,256.0,257.0,257.0,...,263.0,264.0,263.0,261.0,262.0,263.0,261.0,260.0,258.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,254.0,256.0,257.0,259.0,255.0,252.0,257.0,260.0,256.0,260.0,...,258.0,259.0,256.0,259.0,256.0,258.0,257.0,258.0,257.0,0
0,258.0,260.0,260.0,264.0,262.0,263.0,264.0,267.0,266.0,268.0,...,252.0,257.0,254.0,258.0,260.0,259.0,262.0,263.0,263.0,0
0,257.0,256.0,256.0,257.0,259.0,257.0,257.0,258.0,254.0,256.0,...,257.0,255.0,256.0,257.0,260.0,258.0,257.0,257.0,255.0,0
0,257.0,260.0,258.0,259.0,257.0,250.0,258.0,254.0,257.0,257.0,...,257.0,258.0,261.0,259.0,258.0,261.0,258.0,259.0,259.0,0
0,259.0,260.0,259.0,256.0,259.0,254.0,257.0,257.0,259.0,257.0,...,259.0,257.0,257.0,256.0,259.0,254.0,256.0,256.0,254.0,0

# SE10

In [258]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE10_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE10')
    SE10_A_paths.append(path)

SE10_A_paths

['../Dataset/SE10/D01_SE10_R01.csv',
 '../Dataset/SE10/D02_SE10_R01.csv',
 '../Dataset/SE10/D03_SE10_R01.csv',
 '../Dataset/SE10/D04_SE10_R01.csv',
 '../Dataset/SE10/D05_SE10_R01_1.csv',
 '../Dataset/SE10/D05_SE10_R01_2.csv',
 '../Dataset/SE10/D05_SE10_R02_1.csv',
 '../Dataset/SE10/D05_SE10_R02_2.csv',
 '../Dataset/SE10/D05_SE10_R03_1.csv',
 '../Dataset/SE10/D05_SE10_R03_2.csv',
 '../Dataset/SE10/D05_SE10_R04_1.csv',
 '../Dataset/SE10/D05_SE10_R04_2.csv',
 '../Dataset/SE10/D05_SE10_R05_1.csv',
 '../Dataset/SE10/D05_SE10_R05_2.csv',
 '../Dataset/SE10/D06_SE10_R01_1.csv',
 '../Dataset/SE10/D06_SE10_R01_2.csv',
 '../Dataset/SE10/D06_SE10_R02_1.csv',
 '../Dataset/SE10/D06_SE10_R02_2.csv',
 '../Dataset/SE10/D06_SE10_R03_1.csv',
 '../Dataset/SE10/D06_SE10_R03_2.csv',
 '../Dataset/SE10/D06_SE10_R04_1.csv',
 '../Dataset/SE10/D06_SE10_R04_2.csv',
 '../Dataset/SE10/D06_SE10_R05_1.csv',
 '../Dataset/SE10/D06_SE10_R05_2.csv',
 '../Dataset/SE10/D07_SE10_R01.csv',
 '../Dataset/SE10/D07_SE10_R02.csv',
 '../Dataset/SE10/D07_SE10_R03.csv',
 '../Dataset/SE10/D07_SE10_R04.csv',
 '../Dataset/SE10/D07_SE10_R05.csv',
 '../Dataset/SE10/D08_SE10_R01.csv',
 '../Dataset/SE10/D08_SE10_R02.csv',
 '../Dataset/SE10/D08_SE10_R03.csv',
 '../Dataset/SE10/D08_SE10_R04.csv',
 '../Dataset/SE10/D08_SE10_R05.csv',
 '../Dataset/SE10/D09_SE10_R01.csv',
 '../Dataset/SE10/D09_SE10_R02.csv',
 '../Dataset/SE10/D09_SE10_R03.csv',
 '../Dataset/SE10/D09_SE10_R04.csv',
 '../Dataset/SE10/D09_SE10_R05.csv',
 '../Dataset/SE10/D10_SE10_R01.csv',
 '../Dataset/SE10/D10_SE10_R02.csv',
 '../Dataset/SE10/D10_SE10_R03.csv',
 '../Dataset/SE10/D10_SE10_R04.csv',
 '../Dataset/SE10/D10_SE10_R05.csv',
 '../Dataset/SE10/D11_SE10_R01.csv',
 '../Dataset/SE10/D11_SE10_R02.csv',
 '../Dataset/SE10/D11_SE10_R03.csv',
 '../Dataset/SE10/D11_SE10_R04.csv',
 '../Dataset/SE10/D11_SE10_R05.csv',
 '../Dataset/SE10/D12_SE10_R01.csv',
 '../Dataset/SE10/D12_SE10_R02.csv',
 '../Dataset/SE10/D12_SE10_R03.csv',
 '../Dataset/SE10/D12_SE10_R04.csv',
 '../Dataset/SE10/D12_SE10_R05.csv',
 '../Dataset/SE10/D13_SE10_R01.csv',
 '../Dataset/SE10/D13_SE10_R02.csv',
 '../Dataset/SE10/D13_SE10_R03.csv',
 '../Dataset/SE10/D13_SE10_R04.csv',
 '../Dataset/SE10/D13_SE10_R05.csv',
 '../Dataset/SE10/D14_SE10_R01.csv',
 '../Dataset/SE10/D14_SE10_R02.csv',
 '../Dataset/SE10/D14_SE10_R03.csv',
 '../Dataset/SE10/D14_SE10_R04.csv',
 '../Dataset/SE10/D14_SE10_R05.csv',
 '../Dataset/SE10/D17_SE10_R01_1.csv',
 '../Dataset/SE10/D17_SE10_R01_2.csv',
 '../Dataset/SE10/D17_SE10_R02_1.csv',
 '../Dataset/SE10/D17_SE10_R02_2.csv',
 '../Dataset/SE10/D17_SE10_R03_1.csv',
 '../Dataset/SE10/D17_SE10_R03_2.csv',
 '../Dataset/SE10/D17_SE10_R04_1.csv',
 '../Dataset/SE10/D17_SE10_R04_2.csv',
 '../Dataset/SE10/D17_SE10_R05_1.csv',
 '../Dataset/SE10/D17_SE10_R05_2.csv',
 '../Dataset/SE10/D16_SE10_R01.csv',
 '../Dataset/SE10/D16_SE10_R02.csv',
 '../Dataset/SE10/D16_SE10_R03.csv',
 '../Dataset/SE10/D16_SE10_R04.csv',
 '../Dataset/SE10/D16_SE10_R05.csv',
 '../Dataset/SE10/D17_SE10_R01.csv',
 '../Dataset/SE10/D17_SE10_R02.csv',
 '../Dataset/SE10/D17_SE10_R03.csv',
 '../Dataset/SE10/D17_SE10_R04.csv',
 '../Dataset/SE10/D17_SE10_R05.csv']

In [259]:
list = []
final_SE10_A = pd.DataFrame(list)

for path in SE10_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE10_A = final_SE10_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE10_A.shape
target_col = row * [0]
final_SE10_A.loc[:,'target'] = target_col

final_SE10_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,247.0,239.0,238.0,232.0,228.0,222.0,220.0,227.0,233.0,221.0,...,316.0,312.0,308.0,311.0,315.0,325.0,338.0,347.0,365.0,0
0,268.0,264.0,267.0,267.0,266.0,262.0,263.0,263.0,265.0,265.0,...,261.0,261.0,263.0,262.0,262.0,265.0,264.0,262.0,263.0,0
0,260.0,260.0,259.0,263.0,264.0,267.0,265.0,269.0,266.0,270.0,...,293.0,286.0,275.0,273.0,262.0,260.0,252.0,249.0,241.0,0
0,269.0,267.0,264.0,264.0,264.0,264.0,263.0,268.0,265.0,265.0,...,264.0,264.0,264.0,261.0,263.0,262.0,263.0,261.0,264.0,0
0,268.0,267.0,266.0,265.0,266.0,267.0,265.0,265.0,264.0,267.0,...,289.0,290.0,289.0,289.0,291.0,285.0,283.0,284.0,275.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,264.0,267.0,266.0,265.0,267.0,280.0,265.0,268.0,266.0,266.0,...,265.0,266.0,267.0,274.0,266.0,267.0,267.0,264.0,267.0,0
0,265.0,266.0,267.0,264.0,266.0,267.0,268.0,266.0,266.0,270.0,...,265.0,267.0,265.0,266.0,267.0,268.0,265.0,265.0,267.0,0
0,262.0,263.0,265.0,268.0,265.0,259.0,265.0,270.0,266.0,265.0,...,264.0,265.0,264.0,263.0,264.0,267.0,263.0,266.0,267.0,0
0,269.0,267.0,264.0,267.0,264.0,264.0,267.0,264.0,268.0,266.0,...,264.0,267.0,265.0,263.0,268.0,266.0,267.0,266.0,266.0,0
0,265.0,268.0,266.0,264.0,269.0,266.0,266.0,266.0,265.0,268.0,...,263.0,266.0,268.0,269.0,266.0,267.0,267.0,266.0,266.0,0

# SE11

In [260]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE11_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE11')
    SE11_A_paths.append(path)

SE11_A_paths

['../Dataset/SE11/D01_SE11_R01.csv',
 '../Dataset/SE11/D02_SE11_R01.csv',
 '../Dataset/SE11/D03_SE11_R01.csv',
 '../Dataset/SE11/D04_SE11_R01.csv',
 '../Dataset/SE11/D05_SE11_R01_1.csv',
 '../Dataset/SE11/D05_SE11_R01_2.csv',
 '../Dataset/SE11/D05_SE11_R02_1.csv',
 '../Dataset/SE11/D05_SE11_R02_2.csv',
 '../Dataset/SE11/D05_SE11_R03_1.csv',
 '../Dataset/SE11/D05_SE11_R03_2.csv',
 '../Dataset/SE11/D05_SE11_R04_1.csv',
 '../Dataset/SE11/D05_SE11_R04_2.csv',
 '../Dataset/SE11/D05_SE11_R05_1.csv',
 '../Dataset/SE11/D05_SE11_R05_2.csv',
 '../Dataset/SE11/D06_SE11_R01_1.csv',
 '../Dataset/SE11/D06_SE11_R01_2.csv',
 '../Dataset/SE11/D06_SE11_R02_1.csv',
 '../Dataset/SE11/D06_SE11_R02_2.csv',
 '../Dataset/SE11/D06_SE11_R03_1.csv',
 '../Dataset/SE11/D06_SE11_R03_2.csv',
 '../Dataset/SE11/D06_SE11_R04_1.csv',
 '../Dataset/SE11/D06_SE11_R04_2.csv',
 '../Dataset/SE11/D06_SE11_R05_1.csv',
 '../Dataset/SE11/D06_SE11_R05_2.csv',
 '../Dataset/SE11/D07_SE11_R01.csv',
 '../Dataset/SE11/D07_SE11_R02.csv',
 '../Dataset/SE11/D07_SE11_R03.csv',
 '../Dataset/SE11/D07_SE11_R04.csv',
 '../Dataset/SE11/D07_SE11_R05.csv',
 '../Dataset/SE11/D08_SE11_R01.csv',
 '../Dataset/SE11/D08_SE11_R02.csv',
 '../Dataset/SE11/D08_SE11_R03.csv',
 '../Dataset/SE11/D08_SE11_R04.csv',
 '../Dataset/SE11/D08_SE11_R05.csv',
 '../Dataset/SE11/D09_SE11_R01.csv',
 '../Dataset/SE11/D09_SE11_R02.csv',
 '../Dataset/SE11/D09_SE11_R03.csv',
 '../Dataset/SE11/D09_SE11_R04.csv',
 '../Dataset/SE11/D09_SE11_R05.csv',
 '../Dataset/SE11/D10_SE11_R01.csv',
 '../Dataset/SE11/D10_SE11_R02.csv',
 '../Dataset/SE11/D10_SE11_R03.csv',
 '../Dataset/SE11/D10_SE11_R04.csv',
 '../Dataset/SE11/D10_SE11_R05.csv',
 '../Dataset/SE11/D11_SE11_R01.csv',
 '../Dataset/SE11/D11_SE11_R02.csv',
 '../Dataset/SE11/D11_SE11_R03.csv',
 '../Dataset/SE11/D11_SE11_R04.csv',
 '../Dataset/SE11/D11_SE11_R05.csv',
 '../Dataset/SE11/D12_SE11_R01.csv',
 '../Dataset/SE11/D12_SE11_R02.csv',
 '../Dataset/SE11/D12_SE11_R03.csv',
 '../Dataset/SE11/D12_SE11_R04.csv',
 '../Dataset/SE11/D12_SE11_R05.csv',
 '../Dataset/SE11/D13_SE11_R01.csv',
 '../Dataset/SE11/D13_SE11_R02.csv',
 '../Dataset/SE11/D13_SE11_R03.csv',
 '../Dataset/SE11/D13_SE11_R04.csv',
 '../Dataset/SE11/D13_SE11_R05.csv',
 '../Dataset/SE11/D14_SE11_R01.csv',
 '../Dataset/SE11/D14_SE11_R02.csv',
 '../Dataset/SE11/D14_SE11_R03.csv',
 '../Dataset/SE11/D14_SE11_R04.csv',
 '../Dataset/SE11/D14_SE11_R05.csv',
 '../Dataset/SE11/D17_SE11_R01_1.csv',
 '../Dataset/SE11/D17_SE11_R01_2.csv',
 '../Dataset/SE11/D17_SE11_R02_1.csv',
 '../Dataset/SE11/D17_SE11_R02_2.csv',
 '../Dataset/SE11/D17_SE11_R03_1.csv',
 '../Dataset/SE11/D17_SE11_R03_2.csv',
 '../Dataset/SE11/D17_SE11_R04_1.csv',
 '../Dataset/SE11/D17_SE11_R04_2.csv',
 '../Dataset/SE11/D17_SE11_R05_1.csv',
 '../Dataset/SE11/D17_SE11_R05_2.csv',
 '../Dataset/SE11/D16_SE11_R01.csv',
 '../Dataset/SE11/D16_SE11_R02.csv',
 '../Dataset/SE11/D16_SE11_R03.csv',
 '../Dataset/SE11/D16_SE11_R04.csv',
 '../Dataset/SE11/D16_SE11_R05.csv',
 '../Dataset/SE11/D17_SE11_R01.csv',
 '../Dataset/SE11/D17_SE11_R02.csv',
 '../Dataset/SE11/D17_SE11_R03.csv',
 '../Dataset/SE11/D17_SE11_R04.csv',
 '../Dataset/SE11/D17_SE11_R05.csv']

In [261]:
list = []
final_SE11_A = pd.DataFrame(list)

for path in SE11_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE11_A = final_SE11_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE11_A.shape
target_col = row * [0]
final_SE11_A.loc[:,'target'] = target_col

final_SE11_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,251.0,246.0,246.0,244.0,239.0,234.0,240.0,237.0,236.0,231.0,...,231.0,237.0,240.0,247.0,250.0,249.0,253.0,253.0,250.0,0
0,257.0,256.0,258.0,256.0,259.0,260.0,261.0,261.0,261.0,263.0,...,258.0,262.0,269.0,274.0,277.0,276.0,274.0,268.0,264.0,0
0,253.0,253.0,258.0,254.0,256.0,258.0,260.0,259.0,259.0,261.0,...,253.0,258.0,258.0,257.0,254.0,256.0,255.0,250.0,251.0,0
0,256.0,253.0,259.0,257.0,260.0,257.0,257.0,258.0,258.0,254.0,...,264.0,259.0,260.0,260.0,254.0,255.0,258.0,255.0,255.0,0
0,302.0,302.0,293.0,293.0,288.0,285.0,279.0,273.0,267.0,264.0,...,256.0,244.0,240.0,229.0,222.0,213.0,206.0,204.0,201.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,262.0,262.0,262.0,263.0,262.0,257.0,274.0,257.0,261.0,261.0,...,261.0,261.0,262.0,260.0,259.0,260.0,263.0,261.0,261.0,0
0,262.0,262.0,260.0,260.0,262.0,253.0,261.0,260.0,259.0,261.0,...,262.0,262.0,264.0,261.0,261.0,260.0,262.0,264.0,260.0,0
0,262.0,261.0,258.0,260.0,260.0,263.0,261.0,262.0,261.0,262.0,...,261.0,260.0,262.0,263.0,262.0,261.0,262.0,263.0,262.0,0
0,261.0,262.0,259.0,261.0,259.0,258.0,260.0,262.0,263.0,260.0,...,261.0,262.0,264.0,258.0,259.0,263.0,262.0,263.0,262.0,0
0,260.0,261.0,260.0,263.0,261.0,263.0,262.0,261.0,262.0,260.0,...,262.0,260.0,259.0,261.0,261.0,262.0,263.0,260.0,261.0,0

# SE12

In [262]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE12_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE12')
    SE12_A_paths.append(path)

SE12_A_paths

['../Dataset/SE12/D01_SE12_R01.csv',
 '../Dataset/SE12/D02_SE12_R01.csv',
 '../Dataset/SE12/D03_SE12_R01.csv',
 '../Dataset/SE12/D04_SE12_R01.csv',
 '../Dataset/SE12/D05_SE12_R01_1.csv',
 '../Dataset/SE12/D05_SE12_R01_2.csv',
 '../Dataset/SE12/D05_SE12_R02_1.csv',
 '../Dataset/SE12/D05_SE12_R02_2.csv',
 '../Dataset/SE12/D05_SE12_R03_1.csv',
 '../Dataset/SE12/D05_SE12_R03_2.csv',
 '../Dataset/SE12/D05_SE12_R04_1.csv',
 '../Dataset/SE12/D05_SE12_R04_2.csv',
 '../Dataset/SE12/D05_SE12_R05_1.csv',
 '../Dataset/SE12/D05_SE12_R05_2.csv',
 '../Dataset/SE12/D06_SE12_R01_1.csv',
 '../Dataset/SE12/D06_SE12_R01_2.csv',
 '../Dataset/SE12/D06_SE12_R02_1.csv',
 '../Dataset/SE12/D06_SE12_R02_2.csv',
 '../Dataset/SE12/D06_SE12_R03_1.csv',
 '../Dataset/SE12/D06_SE12_R03_2.csv',
 '../Dataset/SE12/D06_SE12_R04_1.csv',
 '../Dataset/SE12/D06_SE12_R04_2.csv',
 '../Dataset/SE12/D06_SE12_R05_1.csv',
 '../Dataset/SE12/D06_SE12_R05_2.csv',
 '../Dataset/SE12/D07_SE12_R01.csv',
 '../Dataset/SE12/D07_SE12_R02.csv',
 '../Dataset/SE12/D07_SE12_R03.csv',
 '../Dataset/SE12/D07_SE12_R04.csv',
 '../Dataset/SE12/D07_SE12_R05.csv',
 '../Dataset/SE12/D08_SE12_R01.csv',
 '../Dataset/SE12/D08_SE12_R02.csv',
 '../Dataset/SE12/D08_SE12_R03.csv',
 '../Dataset/SE12/D08_SE12_R04.csv',
 '../Dataset/SE12/D08_SE12_R05.csv',
 '../Dataset/SE12/D09_SE12_R01.csv',
 '../Dataset/SE12/D09_SE12_R02.csv',
 '../Dataset/SE12/D09_SE12_R03.csv',
 '../Dataset/SE12/D09_SE12_R04.csv',
 '../Dataset/SE12/D09_SE12_R05.csv',
 '../Dataset/SE12/D10_SE12_R01.csv',
 '../Dataset/SE12/D10_SE12_R02.csv',
 '../Dataset/SE12/D10_SE12_R03.csv',
 '../Dataset/SE12/D10_SE12_R04.csv',
 '../Dataset/SE12/D10_SE12_R05.csv',
 '../Dataset/SE12/D11_SE12_R01.csv',
 '../Dataset/SE12/D11_SE12_R02.csv',
 '../Dataset/SE12/D11_SE12_R03.csv',
 '../Dataset/SE12/D11_SE12_R04.csv',
 '../Dataset/SE12/D11_SE12_R05.csv',
 '../Dataset/SE12/D12_SE12_R01.csv',
 '../Dataset/SE12/D12_SE12_R02.csv',
 '../Dataset/SE12/D12_SE12_R03.csv',
 '../Dataset/SE12/D12_SE12_R04.csv',
 '../Dataset/SE12/D12_SE12_R05.csv',
 '../Dataset/SE12/D13_SE12_R01.csv',
 '../Dataset/SE12/D13_SE12_R02.csv',
 '../Dataset/SE12/D13_SE12_R03.csv',
 '../Dataset/SE12/D13_SE12_R04.csv',
 '../Dataset/SE12/D13_SE12_R05.csv',
 '../Dataset/SE12/D14_SE12_R01.csv',
 '../Dataset/SE12/D14_SE12_R02.csv',
 '../Dataset/SE12/D14_SE12_R03.csv',
 '../Dataset/SE12/D14_SE12_R04.csv',
 '../Dataset/SE12/D14_SE12_R05.csv',
 '../Dataset/SE12/D17_SE12_R01_1.csv',
 '../Dataset/SE12/D17_SE12_R01_2.csv',
 '../Dataset/SE12/D17_SE12_R02_1.csv',
 '../Dataset/SE12/D17_SE12_R02_2.csv',
 '../Dataset/SE12/D17_SE12_R03_1.csv',
 '../Dataset/SE12/D17_SE12_R03_2.csv',
 '../Dataset/SE12/D17_SE12_R04_1.csv',
 '../Dataset/SE12/D17_SE12_R04_2.csv',
 '../Dataset/SE12/D17_SE12_R05_1.csv',
 '../Dataset/SE12/D17_SE12_R05_2.csv',
 '../Dataset/SE12/D16_SE12_R01.csv',
 '../Dataset/SE12/D16_SE12_R02.csv',
 '../Dataset/SE12/D16_SE12_R03.csv',
 '../Dataset/SE12/D16_SE12_R04.csv',
 '../Dataset/SE12/D16_SE12_R05.csv',
 '../Dataset/SE12/D17_SE12_R01.csv',
 '../Dataset/SE12/D17_SE12_R02.csv',
 '../Dataset/SE12/D17_SE12_R03.csv',
 '../Dataset/SE12/D17_SE12_R04.csv',
 '../Dataset/SE12/D17_SE12_R05.csv']

In [263]:
list = []
final_SE12_A = pd.DataFrame(list)

for path in SE12_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE12_A = final_SE12_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE12_A.shape
target_col = row * [0]
final_SE12_A.loc[:,'target'] = target_col

final_SE12_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,208.0,215.0,222.0,236.0,240.0,252.0,263.0,269.0,287.0,293.0,...,278.0,285.0,301.0,313.0,325.0,330.0,336.0,340.0,338.0,0
0,368.0,376.0,382.0,384.0,376.0,362.0,345.0,322.0,300.0,280.0,...,77.0,77.0,81.0,79.0,88.0,96.0,104.0,116.0,131.0,0
0,177.0,200.0,229.0,254.0,276.0,279.0,297.0,302.0,314.0,327.0,...,81.0,79.0,83.0,93.0,99.0,111.0,120.0,135.0,175.0,0
0,332.0,330.0,319.0,311.0,297.0,285.0,267.0,261.0,257.0,262.0,...,232.0,218.0,210.0,197.0,197.0,198.0,198.0,188.0,177.0,0
0,237.0,239.0,240.0,239.0,242.0,244.0,247.0,251.0,256.0,260.0,...,213.0,219.0,219.0,223.0,228.0,232.0,235.0,240.0,241.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,260.0,256.0,255.0,259.0,257.0,256.0,258.0,257.0,258.0,260.0,...,257.0,260.0,257.0,259.0,259.0,254.0,257.0,256.0,259.0,0
0,259.0,256.0,259.0,258.0,259.0,264.0,262.0,259.0,258.0,255.0,...,258.0,256.0,257.0,261.0,260.0,257.0,259.0,258.0,257.0,0
0,264.0,263.0,262.0,261.0,259.0,258.0,258.0,257.0,258.0,254.0,...,277.0,278.0,278.0,277.0,277.0,275.0,271.0,267.0,266.0,0
0,261.0,264.0,259.0,260.0,257.0,263.0,261.0,255.0,259.0,258.0,...,261.0,258.0,259.0,259.0,259.0,260.0,256.0,256.0,257.0,0
0,259.0,260.0,257.0,260.0,260.0,261.0,264.0,268.0,265.0,269.0,...,258.0,258.0,260.0,258.0,261.0,261.0,261.0,260.0,260.0,0

# SE13

In [264]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE13_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE13')
    SE13_A_paths.append(path)

SE13_A_paths

['../Dataset/SE13/D01_SE13_R01.csv',
 '../Dataset/SE13/D02_SE13_R01.csv',
 '../Dataset/SE13/D03_SE13_R01.csv',
 '../Dataset/SE13/D04_SE13_R01.csv',
 '../Dataset/SE13/D05_SE13_R01_1.csv',
 '../Dataset/SE13/D05_SE13_R01_2.csv',
 '../Dataset/SE13/D05_SE13_R02_1.csv',
 '../Dataset/SE13/D05_SE13_R02_2.csv',
 '../Dataset/SE13/D05_SE13_R03_1.csv',
 '../Dataset/SE13/D05_SE13_R03_2.csv',
 '../Dataset/SE13/D05_SE13_R04_1.csv',
 '../Dataset/SE13/D05_SE13_R04_2.csv',
 '../Dataset/SE13/D05_SE13_R05_1.csv',
 '../Dataset/SE13/D05_SE13_R05_2.csv',
 '../Dataset/SE13/D06_SE13_R01_1.csv',
 '../Dataset/SE13/D06_SE13_R01_2.csv',
 '../Dataset/SE13/D06_SE13_R02_1.csv',
 '../Dataset/SE13/D06_SE13_R02_2.csv',
 '../Dataset/SE13/D06_SE13_R03_1.csv',
 '../Dataset/SE13/D06_SE13_R03_2.csv',
 '../Dataset/SE13/D06_SE13_R04_1.csv',
 '../Dataset/SE13/D06_SE13_R04_2.csv',
 '../Dataset/SE13/D06_SE13_R05_1.csv',
 '../Dataset/SE13/D06_SE13_R05_2.csv',
 '../Dataset/SE13/D07_SE13_R01.csv',
 '../Dataset/SE13/D07_SE13_R02.csv',
 '../Dataset/SE13/D07_SE13_R03.csv',
 '../Dataset/SE13/D07_SE13_R04.csv',
 '../Dataset/SE13/D07_SE13_R05.csv',
 '../Dataset/SE13/D08_SE13_R01.csv',
 '../Dataset/SE13/D08_SE13_R02.csv',
 '../Dataset/SE13/D08_SE13_R03.csv',
 '../Dataset/SE13/D08_SE13_R04.csv',
 '../Dataset/SE13/D08_SE13_R05.csv',
 '../Dataset/SE13/D09_SE13_R01.csv',
 '../Dataset/SE13/D09_SE13_R02.csv',
 '../Dataset/SE13/D09_SE13_R03.csv',
 '../Dataset/SE13/D09_SE13_R04.csv',
 '../Dataset/SE13/D09_SE13_R05.csv',
 '../Dataset/SE13/D10_SE13_R01.csv',
 '../Dataset/SE13/D10_SE13_R02.csv',
 '../Dataset/SE13/D10_SE13_R03.csv',
 '../Dataset/SE13/D10_SE13_R04.csv',
 '../Dataset/SE13/D10_SE13_R05.csv',
 '../Dataset/SE13/D11_SE13_R01.csv',
 '../Dataset/SE13/D11_SE13_R02.csv',
 '../Dataset/SE13/D11_SE13_R03.csv',
 '../Dataset/SE13/D11_SE13_R04.csv',
 '../Dataset/SE13/D11_SE13_R05.csv',
 '../Dataset/SE13/D12_SE13_R01.csv',
 '../Dataset/SE13/D12_SE13_R02.csv',
 '../Dataset/SE13/D12_SE13_R03.csv',
 '../Dataset/SE13/D12_SE13_R04.csv',
 '../Dataset/SE13/D12_SE13_R05.csv',
 '../Dataset/SE13/D13_SE13_R01.csv',
 '../Dataset/SE13/D13_SE13_R02.csv',
 '../Dataset/SE13/D13_SE13_R03.csv',
 '../Dataset/SE13/D13_SE13_R04.csv',
 '../Dataset/SE13/D13_SE13_R05.csv',
 '../Dataset/SE13/D14_SE13_R01.csv',
 '../Dataset/SE13/D14_SE13_R02.csv',
 '../Dataset/SE13/D14_SE13_R03.csv',
 '../Dataset/SE13/D14_SE13_R04.csv',
 '../Dataset/SE13/D14_SE13_R05.csv',
 '../Dataset/SE13/D17_SE13_R01_1.csv',
 '../Dataset/SE13/D17_SE13_R01_2.csv',
 '../Dataset/SE13/D17_SE13_R02_1.csv',
 '../Dataset/SE13/D17_SE13_R02_2.csv',
 '../Dataset/SE13/D17_SE13_R03_1.csv',
 '../Dataset/SE13/D17_SE13_R03_2.csv',
 '../Dataset/SE13/D17_SE13_R04_1.csv',
 '../Dataset/SE13/D17_SE13_R04_2.csv',
 '../Dataset/SE13/D17_SE13_R05_1.csv',
 '../Dataset/SE13/D17_SE13_R05_2.csv',
 '../Dataset/SE13/D16_SE13_R01.csv',
 '../Dataset/SE13/D16_SE13_R02.csv',
 '../Dataset/SE13/D16_SE13_R03.csv',
 '../Dataset/SE13/D16_SE13_R04.csv',
 '../Dataset/SE13/D16_SE13_R05.csv',
 '../Dataset/SE13/D17_SE13_R01.csv',
 '../Dataset/SE13/D17_SE13_R02.csv',
 '../Dataset/SE13/D17_SE13_R03.csv',
 '../Dataset/SE13/D17_SE13_R04.csv',
 '../Dataset/SE13/D17_SE13_R05.csv']

In [265]:
list = []
final_SE13_A = pd.DataFrame(list)

for path in SE13_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE13_A = final_SE13_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE13_A.shape
target_col = row * [0]
final_SE13_A.loc[:,'target'] = target_col

final_SE13_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,289.0,293.0,295.0,297.0,301.0,302.0,300.0,302.0,301.0,310.0,...,261.0,261.0,258.0,255.0,260.0,261.0,256.0,256.0,256.0,0
0,298.0,306.0,308.0,307.0,310.0,310.0,307.0,311.0,314.0,319.0,...,410.0,406.0,400.0,386.0,370.0,355.0,335.0,326.0,314.0,0
0,273.0,267.0,258.0,252.0,243.0,235.0,226.0,220.0,211.0,208.0,...,363.0,394.0,424.0,453.0,470.0,485.0,482.0,466.0,459.0,0
0,478.0,586.0,661.0,696.0,702.0,696.0,675.0,651.0,612.0,572.0,...,439.0,460.0,500.0,622.0,737.0,785.0,754.0,685.0,633.0,0
0,255.0,256.0,255.0,255.0,255.0,256.0,255.0,253.0,254.0,256.0,...,200.0,197.0,196.0,196.0,195.0,198.0,194.0,196.0,191.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,264.0,266.0,266.0,266.0,266.0,272.0,266.0,268.0,267.0,265.0,...,256.0,256.0,256.0,255.0,261.0,259.0,259.0,256.0,258.0,0
0,259.0,257.0,258.0,258.0,257.0,265.0,257.0,257.0,257.0,257.0,...,257.0,256.0,258.0,259.0,259.0,257.0,259.0,257.0,260.0,0
0,259.0,259.0,260.0,260.0,258.0,258.0,258.0,257.0,257.0,255.0,...,258.0,255.0,259.0,258.0,258.0,260.0,253.0,259.0,255.0,0
0,259.0,258.0,258.0,258.0,257.0,255.0,256.0,258.0,257.0,256.0,...,255.0,256.0,258.0,259.0,259.0,258.0,257.0,257.0,259.0,0
0,258.0,258.0,258.0,259.0,259.0,259.0,258.0,258.0,257.0,262.0,...,258.0,261.0,259.0,261.0,258.0,257.0,257.0,256.0,257.0,0

# SE14

In [266]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE14_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE14')
    SE14_A_paths.append(path)

SE14_A_paths

['../Dataset/SE14/D01_SE14_R01.csv',
 '../Dataset/SE14/D02_SE14_R01.csv',
 '../Dataset/SE14/D03_SE14_R01.csv',
 '../Dataset/SE14/D04_SE14_R01.csv',
 '../Dataset/SE14/D05_SE14_R01_1.csv',
 '../Dataset/SE14/D05_SE14_R01_2.csv',
 '../Dataset/SE14/D05_SE14_R02_1.csv',
 '../Dataset/SE14/D05_SE14_R02_2.csv',
 '../Dataset/SE14/D05_SE14_R03_1.csv',
 '../Dataset/SE14/D05_SE14_R03_2.csv',
 '../Dataset/SE14/D05_SE14_R04_1.csv',
 '../Dataset/SE14/D05_SE14_R04_2.csv',
 '../Dataset/SE14/D05_SE14_R05_1.csv',
 '../Dataset/SE14/D05_SE14_R05_2.csv',
 '../Dataset/SE14/D06_SE14_R01_1.csv',
 '../Dataset/SE14/D06_SE14_R01_2.csv',
 '../Dataset/SE14/D06_SE14_R02_1.csv',
 '../Dataset/SE14/D06_SE14_R02_2.csv',
 '../Dataset/SE14/D06_SE14_R03_1.csv',
 '../Dataset/SE14/D06_SE14_R03_2.csv',
 '../Dataset/SE14/D06_SE14_R04_1.csv',
 '../Dataset/SE14/D06_SE14_R04_2.csv',
 '../Dataset/SE14/D06_SE14_R05_1.csv',
 '../Dataset/SE14/D06_SE14_R05_2.csv',
 '../Dataset/SE14/D07_SE14_R01.csv',
 '../Dataset/SE14/D07_SE14_R02.csv',
 '../Dataset/SE14/D07_SE14_R03.csv',
 '../Dataset/SE14/D07_SE14_R04.csv',
 '../Dataset/SE14/D07_SE14_R05.csv',
 '../Dataset/SE14/D08_SE14_R01.csv',
 '../Dataset/SE14/D08_SE14_R02.csv',
 '../Dataset/SE14/D08_SE14_R03.csv',
 '../Dataset/SE14/D08_SE14_R04.csv',
 '../Dataset/SE14/D08_SE14_R05.csv',
 '../Dataset/SE14/D09_SE14_R01.csv',
 '../Dataset/SE14/D09_SE14_R02.csv',
 '../Dataset/SE14/D09_SE14_R03.csv',
 '../Dataset/SE14/D09_SE14_R04.csv',
 '../Dataset/SE14/D09_SE14_R05.csv',
 '../Dataset/SE14/D10_SE14_R01.csv',
 '../Dataset/SE14/D10_SE14_R02.csv',
 '../Dataset/SE14/D10_SE14_R03.csv',
 '../Dataset/SE14/D10_SE14_R04.csv',
 '../Dataset/SE14/D10_SE14_R05.csv',
 '../Dataset/SE14/D11_SE14_R01.csv',
 '../Dataset/SE14/D11_SE14_R02.csv',
 '../Dataset/SE14/D11_SE14_R03.csv',
 '../Dataset/SE14/D11_SE14_R04.csv',
 '../Dataset/SE14/D11_SE14_R05.csv',
 '../Dataset/SE14/D12_SE14_R01.csv',
 '../Dataset/SE14/D12_SE14_R02.csv',
 '../Dataset/SE14/D12_SE14_R03.csv',
 '../Dataset/SE14/D12_SE14_R04.csv',
 '../Dataset/SE14/D12_SE14_R05.csv',
 '../Dataset/SE14/D13_SE14_R01.csv',
 '../Dataset/SE14/D13_SE14_R02.csv',
 '../Dataset/SE14/D13_SE14_R03.csv',
 '../Dataset/SE14/D13_SE14_R04.csv',
 '../Dataset/SE14/D13_SE14_R05.csv',
 '../Dataset/SE14/D14_SE14_R01.csv',
 '../Dataset/SE14/D14_SE14_R02.csv',
 '../Dataset/SE14/D14_SE14_R03.csv',
 '../Dataset/SE14/D14_SE14_R04.csv',
 '../Dataset/SE14/D14_SE14_R05.csv',
 '../Dataset/SE14/D17_SE14_R01_1.csv',
 '../Dataset/SE14/D17_SE14_R01_2.csv',
 '../Dataset/SE14/D17_SE14_R02_1.csv',
 '../Dataset/SE14/D17_SE14_R02_2.csv',
 '../Dataset/SE14/D17_SE14_R03_1.csv',
 '../Dataset/SE14/D17_SE14_R03_2.csv',
 '../Dataset/SE14/D17_SE14_R04_1.csv',
 '../Dataset/SE14/D17_SE14_R04_2.csv',
 '../Dataset/SE14/D17_SE14_R05_1.csv',
 '../Dataset/SE14/D17_SE14_R05_2.csv',
 '../Dataset/SE14/D16_SE14_R01.csv',
 '../Dataset/SE14/D16_SE14_R02.csv',
 '../Dataset/SE14/D16_SE14_R03.csv',
 '../Dataset/SE14/D16_SE14_R04.csv',
 '../Dataset/SE14/D16_SE14_R05.csv',
 '../Dataset/SE14/D17_SE14_R01.csv',
 '../Dataset/SE14/D17_SE14_R02.csv',
 '../Dataset/SE14/D17_SE14_R03.csv',
 '../Dataset/SE14/D17_SE14_R04.csv',
 '../Dataset/SE14/D17_SE14_R05.csv']

In [267]:
list = []
final_SE14_A = pd.DataFrame(list)

for path in SE14_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE14_A = final_SE14_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE14_A.shape
target_col = row * [0]
final_SE14_A.loc[:,'target'] = target_col

final_SE14_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,272.0,266.0,263.0,261.0,260.0,258.0,247.0,256.0,250.0,231.0,...,247.0,244.0,248.0,247.0,243.0,246.0,244.0,246.0,245.0,0
0,258.0,258.0,260.0,260.0,261.0,262.0,259.0,260.0,257.0,260.0,...,242.0,239.0,241.0,239.0,237.0,238.0,241.0,239.0,245.0,0
0,257.0,258.0,258.0,258.0,254.0,260.0,266.0,261.0,251.0,258.0,...,256.0,262.0,254.0,264.0,254.0,262.0,265.0,263.0,259.0,0
0,256.0,257.0,258.0,257.0,258.0,255.0,257.0,255.0,256.0,255.0,...,246.0,250.0,248.0,248.0,250.0,253.0,257.0,259.0,257.0,0
0,297.0,291.0,297.0,306.0,313.0,305.0,312.0,308.0,301.0,301.0,...,299.0,315.0,328.0,346.0,360.0,380.0,393.0,402.0,412.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,258.0,259.0,259.0,258.0,259.0,259.0,259.0,259.0,259.0,258.0,...,257.0,260.0,256.0,261.0,259.0,261.0,261.0,261.0,260.0,0
0,260.0,257.0,260.0,261.0,259.0,250.0,261.0,258.0,258.0,263.0,...,256.0,258.0,259.0,256.0,255.0,257.0,256.0,256.0,255.0,0
0,259.0,260.0,260.0,260.0,256.0,257.0,261.0,259.0,258.0,261.0,...,260.0,261.0,260.0,261.0,261.0,261.0,258.0,259.0,259.0,0
0,257.0,257.0,258.0,258.0,256.0,261.0,257.0,259.0,256.0,258.0,...,259.0,259.0,260.0,259.0,260.0,260.0,259.0,259.0,259.0,0
0,260.0,260.0,262.0,261.0,267.0,264.0,266.0,265.0,264.0,264.0,...,258.0,260.0,259.0,260.0,257.0,259.0,259.0,259.0,259.0,0

# SE15

In [268]:
paths = []

for i in range(1, 18):
    root, file = os.path.split("../Dataset/SA01/D01_SA01_R01.csv")
    if i < 10:
        file = file[:2] + str(i) + file[3:]
        tmp = os.path.join(root, file)
        paths.append(tmp)
        if i > 4:
            for j in range(2, 6):
                file_new = file[:-5] + str(j) + file[-4:]
                tmp = os.path.join(root, file_new)
                paths.append(tmp)
    if i >= 10:
        file = file[:1] + str(i) + file[3:]
        for j in range(1, 6):
            file = file[:-5] + str(j) + file[-4:]
            tmp = os.path.join(root, file)
            paths.append(tmp)

paths[4:14] = ['../Dataset/SA01/D05_SA01_R01_1.csv',
                '../Dataset/SA01/D05_SA01_R01_2.csv',
                '../Dataset/SA01/D05_SA01_R02_1.csv',
                '../Dataset/SA01/D05_SA01_R02_2.csv',
                '../Dataset/SA01/D05_SA01_R03_1.csv',
                '../Dataset/SA01/D05_SA01_R03_2.csv',
                '../Dataset/SA01/D05_SA01_R04_1.csv',
                '../Dataset/SA01/D05_SA01_R04_2.csv',
                '../Dataset/SA01/D05_SA01_R05_1.csv',
                '../Dataset/SA01/D05_SA01_R05_2.csv',
                '../Dataset/SA01/D06_SA01_R01_1.csv',
                '../Dataset/SA01/D06_SA01_R01_2.csv',
                '../Dataset/SA01/D06_SA01_R02_1.csv',
                '../Dataset/SA01/D06_SA01_R02_2.csv',
                '../Dataset/SA01/D06_SA01_R03_1.csv',
                '../Dataset/SA01/D06_SA01_R03_2.csv',
                '../Dataset/SA01/D06_SA01_R04_1.csv',
                '../Dataset/SA01/D06_SA01_R04_2.csv',
                '../Dataset/SA01/D06_SA01_R05_1.csv',
                '../Dataset/SA01/D06_SA01_R05_2.csv']

paths[-15:-10] = ['../Dataset/SA01/D17_SA01_R01_1.csv',
                 '../Dataset/SA01/D17_SA01_R01_2.csv',
                 '../Dataset/SA01/D17_SA01_R02_1.csv',
                 '../Dataset/SA01/D17_SA01_R02_2.csv',
                 '../Dataset/SA01/D17_SA01_R03_1.csv',
                 '../Dataset/SA01/D17_SA01_R03_2.csv',
                 '../Dataset/SA01/D17_SA01_R04_1.csv',
                 '../Dataset/SA01/D17_SA01_R04_2.csv',
                 '../Dataset/SA01/D17_SA01_R05_1.csv',
                 '../Dataset/SA01/D17_SA01_R05_2.csv']

SE15_A_paths = []

for path in paths:
    path = path.replace('SA01', 'SE15')
    SE15_A_paths.append(path)

SE15_A_paths

['../Dataset/SE15/D01_SE15_R01.csv',
 '../Dataset/SE15/D02_SE15_R01.csv',
 '../Dataset/SE15/D03_SE15_R01.csv',
 '../Dataset/SE15/D04_SE15_R01.csv',
 '../Dataset/SE15/D05_SE15_R01_1.csv',
 '../Dataset/SE15/D05_SE15_R01_2.csv',
 '../Dataset/SE15/D05_SE15_R02_1.csv',
 '../Dataset/SE15/D05_SE15_R02_2.csv',
 '../Dataset/SE15/D05_SE15_R03_1.csv',
 '../Dataset/SE15/D05_SE15_R03_2.csv',
 '../Dataset/SE15/D05_SE15_R04_1.csv',
 '../Dataset/SE15/D05_SE15_R04_2.csv',
 '../Dataset/SE15/D05_SE15_R05_1.csv',
 '../Dataset/SE15/D05_SE15_R05_2.csv',
 '../Dataset/SE15/D06_SE15_R01_1.csv',
 '../Dataset/SE15/D06_SE15_R01_2.csv',
 '../Dataset/SE15/D06_SE15_R02_1.csv',
 '../Dataset/SE15/D06_SE15_R02_2.csv',
 '../Dataset/SE15/D06_SE15_R03_1.csv',
 '../Dataset/SE15/D06_SE15_R03_2.csv',
 '../Dataset/SE15/D06_SE15_R04_1.csv',
 '../Dataset/SE15/D06_SE15_R04_2.csv',
 '../Dataset/SE15/D06_SE15_R05_1.csv',
 '../Dataset/SE15/D06_SE15_R05_2.csv',
 '../Dataset/SE15/D07_SE15_R01.csv',
 '../Dataset/SE15/D07_SE15_R02.csv',
 '../Dataset/SE15/D07_SE15_R03.csv',
 '../Dataset/SE15/D07_SE15_R04.csv',
 '../Dataset/SE15/D07_SE15_R05.csv',
 '../Dataset/SE15/D08_SE15_R01.csv',
 '../Dataset/SE15/D08_SE15_R02.csv',
 '../Dataset/SE15/D08_SE15_R03.csv',
 '../Dataset/SE15/D08_SE15_R04.csv',
 '../Dataset/SE15/D08_SE15_R05.csv',
 '../Dataset/SE15/D09_SE15_R01.csv',
 '../Dataset/SE15/D09_SE15_R02.csv',
 '../Dataset/SE15/D09_SE15_R03.csv',
 '../Dataset/SE15/D09_SE15_R04.csv',
 '../Dataset/SE15/D09_SE15_R05.csv',
 '../Dataset/SE15/D10_SE15_R01.csv',
 '../Dataset/SE15/D10_SE15_R02.csv',
 '../Dataset/SE15/D10_SE15_R03.csv',
 '../Dataset/SE15/D10_SE15_R04.csv',
 '../Dataset/SE15/D10_SE15_R05.csv',
 '../Dataset/SE15/D11_SE15_R01.csv',
 '../Dataset/SE15/D11_SE15_R02.csv',
 '../Dataset/SE15/D11_SE15_R03.csv',
 '../Dataset/SE15/D11_SE15_R04.csv',
 '../Dataset/SE15/D11_SE15_R05.csv',
 '../Dataset/SE15/D12_SE15_R01.csv',
 '../Dataset/SE15/D12_SE15_R02.csv',
 '../Dataset/SE15/D12_SE15_R03.csv',
 '../Dataset/SE15/D12_SE15_R04.csv',
 '../Dataset/SE15/D12_SE15_R05.csv',
 '../Dataset/SE15/D13_SE15_R01.csv',
 '../Dataset/SE15/D13_SE15_R02.csv',
 '../Dataset/SE15/D13_SE15_R03.csv',
 '../Dataset/SE15/D13_SE15_R04.csv',
 '../Dataset/SE15/D13_SE15_R05.csv',
 '../Dataset/SE15/D14_SE15_R01.csv',
 '../Dataset/SE15/D14_SE15_R02.csv',
 '../Dataset/SE15/D14_SE15_R03.csv',
 '../Dataset/SE15/D14_SE15_R04.csv',
 '../Dataset/SE15/D14_SE15_R05.csv',
 '../Dataset/SE15/D17_SE15_R01_1.csv',
 '../Dataset/SE15/D17_SE15_R01_2.csv',
 '../Dataset/SE15/D17_SE15_R02_1.csv',
 '../Dataset/SE15/D17_SE15_R02_2.csv',
 '../Dataset/SE15/D17_SE15_R03_1.csv',
 '../Dataset/SE15/D17_SE15_R03_2.csv',
 '../Dataset/SE15/D17_SE15_R04_1.csv',
 '../Dataset/SE15/D17_SE15_R04_2.csv',
 '../Dataset/SE15/D17_SE15_R05_1.csv',
 '../Dataset/SE15/D17_SE15_R05_2.csv',
 '../Dataset/SE15/D16_SE15_R01.csv',
 '../Dataset/SE15/D16_SE15_R02.csv',
 '../Dataset/SE15/D16_SE15_R03.csv',
 '../Dataset/SE15/D16_SE15_R04.csv',
 '../Dataset/SE15/D16_SE15_R05.csv',
 '../Dataset/SE15/D17_SE15_R01.csv',
 '../Dataset/SE15/D17_SE15_R02.csv',
 '../Dataset/SE15/D17_SE15_R03.csv',
 '../Dataset/SE15/D17_SE15_R04.csv',
 '../Dataset/SE15/D17_SE15_R05.csv']

In [269]:
list = []
final_SE15_A = pd.DataFrame(list)

for path in SE15_A_paths:
    try:
        data = pd.read_csv(path, header=None)
        data = data.iloc[:, :3]
        rows, cols = data.shape

        sliced_df = data[0 : 160]
        
        col_1_r = sliced_df[0].to_numpy().astype(int)
        col_2_r = sliced_df[1].to_numpy().astype(int)
        col_3_r = sliced_df[2].to_numpy().astype(int)

        col_1 = col_1_r*col_1_r
        col_2 = col_2_r*col_2_r
        col_3 = col_3_r*col_3_r
        
        C_nine = np.sqrt(col_1 + col_2 + col_3)
        list_C_nine = pd.DataFrame(C_nine).transpose().round()
        final_SE15_A = final_SE15_A.append(list_C_nine)
    except:
        pass

# pd.set_option('display.max_row', 500)
# pd.set_option('display.max_columns', 100)

row, col = final_SE15_A.shape
target_col = row * [0]
final_SE15_A.loc[:,'target'] = target_col

final_SE15_A

,0,1,2,3,4,5,6,7,8,9,...,151,152,153,154,155,156,157,158,159,target
0,263.0,253.0,250.0,243.0,236.0,230.0,225.0,223.0,220.0,218.0,...,194.0,196.0,199.0,198.0,201.0,206.0,207.0,209.0,212.0,0
0,344.0,342.0,335.0,326.0,318.0,307.0,299.0,291.0,287.0,277.0,...,141.0,147.0,153.0,161.0,167.0,179.0,185.0,193.0,198.0,0
0,312.0,339.0,341.0,334.0,336.0,343.0,360.0,374.0,392.0,411.0,...,474.0,511.0,543.0,578.0,596.0,612.0,603.0,581.0,548.0,0
0,262.0,261.0,263.0,261.0,260.0,260.0,260.0,258.0,259.0,256.0,...,280.0,274.0,267.0,255.0,254.0,245.0,241.0,239.0,238.0,0
0,257.0,256.0,258.0,253.0,254.0,256.0,257.0,257.0,260.0,258.0,...,259.0,257.0,263.0,259.0,260.0,258.0,262.0,262.0,258.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,257.0,256.0,257.0,256.0,258.0,253.0,254.0,250.0,255.0,260.0,...,260.0,259.0,257.0,256.0,257.0,258.0,257.0,260.0,255.0,0
0,257.0,257.0,258.0,257.0,257.0,251.0,245.0,267.0,263.0,249.0,...,255.0,255.0,260.0,256.0,256.0,257.0,256.0,254.0,256.0,0
0,258.0,257.0,258.0,257.0,258.0,253.0,257.0,258.0,257.0,255.0,...,257.0,258.0,258.0,256.0,260.0,259.0,254.0,256.0,258.0,0
0,259.0,257.0,258.0,257.0,257.0,254.0,260.0,255.0,255.0,259.0,...,258.0,258.0,260.0,257.0,256.0,257.0,256.0,258.0,258.0,0
0,257.0,260.0,257.0,256.0,260.0,257.0,255.0,256.0,255.0,253.0,...,258.0,258.0,260.0,256.0,257.0,260.0,257.0,259.0,260.0,0

# ADL 데이터 붙이기

In [270]:
file_list = [final_SA01_A, final_SA02_A, final_SA03_A, final_SA04_A, final_SA05_A,
             final_SA06_A, final_SA07_A, final_SA08_A, final_SA09_A, final_SA10_A,
             final_SA11_A, final_SA12_A, final_SA13_A, final_SA14_A, final_SA15_A,
             final_SA16_A, final_SA17_A, final_SA18_A, final_SA19_A, final_SA20_A,
             final_SA21_A, final_SA22_A, final_SA23_A,
             final_SE01_A, final_SE02_A, final_SE03_A, final_SE04_A, final_SE05_A,
             final_SE06_A, final_SE07_A, final_SE08_A, final_SE09_A, final_SE10_A,
             final_SE11_A, final_SE12_A, final_SE13_A, final_SE14_A, final_SE15_A]

result = pd.concat(file_list)
result.to_csv('202111171539_ADL.csv', index=False)